import {DeliveryStatus} from '@prisma/client';import {describe,expect,it} from 'vitest';import {parseDeliveryListSearchParams,setDeliveryListParams} from '../delivery-list';
const now=new Date('2026-10-08T12:00:00Z');
describe('delivery workbench URL contract',()=>{
 it('uses safe defaults and omits them from the canonical URL',()=>{const parsed=parseDeliveryListSearchParams({},now);expect(parsed.query).toMatchObject({page:1,pageSize:50,sort:'priority',direction:'desc'});expect(parsed.canonical.toString()).toBe('');expect(parsed.needsRedirect).toBe(false);});
 it('canonicalizes invalid, unknown, conflicting, and capped values',()=>{const parsed=parseDeliveryListSearchParams({page:'0',pageSize:'500',sort:'drop',direction:'up',group:'needs_action',status:DeliveryStatus.DELIVERED,unknown:'x'},now);expect(parsed.query).toMatchObject({page:1,pageSize:100,sort:'priority',direction:'desc',workflowGroup:'needs_action',status:undefined});expect(parsed.canonical.toString()).toBe('group=needs_action&pageSize=100');expect(parsed.needsRedirect).toBe(true);});
 it('ignores malformed/incomplete dates and trims bounded filters',()=>{const parsed=parseDeliveryListSearchParams({startDate:'invalid',q:'  SJ-01  ',customer:' customer '},now);expect(parsed.query.search).toBe('SJ-01');expect(parsed.query.customerId).toBe('customer');expect(parsed.canonical.toString()).toBe('q=SJ-01&customer=customer');});
 it('keeps a valid ISO range and raw status when no group is selected',()=>{const parsed=parseDeliveryListSearchParams({startDate:'2026-10-01T00:00:00.000Z',endDate:'2026-10-31T23:59:59.999Z',status:'SHIPPED'},now);expect(parsed.query.status).toBe(DeliveryStatus.SHIPPED);expect(parsed.canonical.get('status')).toBe('SHIPPED');});
 it('resets page for filter changes but preserves it for page navigation',()=>{const current=new URLSearchParams('q=old&page=4');expect(setDeliveryListParams(current,{q:'new'}).toString()).toBe('q=new');expect(setDeliveryListParams(current,{page:'5'},false).toString()).toBe('q=old&page=5');});
});
