import { prisma } from '@/lib/prisma';
import { Prisma, StockMovement, JournalStatus } from '@prisma/client';
import { createJournalEntry } from './journals-service';

type StockMovementWithProduct = Prisma.StockMovementGetPayload<{
    include: { productVariant: { include: { product: true } } }
}>;

export async function recordInventoryMovement(
    movement: StockMovement & { productVariant?: StockMovementWithProduct['productVariant'] },
    tx?: Prisma.TransactionClient
) {
    const db = tx || prisma;

    const productVariant = movement.productVariant ?? await db.productVariant.findUnique({
        where: { id: movement.productVariantId },
        include: { product: true }
    });

    if (!productVariant) return;

    const date = movement.createdAt || new Date();
    const cost = Number(productVariant.standardCost || productVariant.price || 0);
    const totalAmount = Number(movement.quantity) * cost;

    if (totalAmount === 0) return;

    const productType = productVariant.product.productType;

    const getInventoryAccount = (pType: string) => {
        switch (pType) {
            case 'RAW_MATERIAL': return '12100'; // Virgin Resin (Parent)
            case 'FINISHED_GOOD': return '12500';
            case 'WIP': return '12400';
            case 'SCRAP': return '12300';
            case 'INTERMEDIATE': return '12400';
            case 'PACKAGING': return '12600';
            default: return '12100';
        }
    };

    const lines = [];

    if (movement.type === 'PURCHASE' || movement.goodsReceiptId) {
        const invAccount = productVariant.product.inventoryAccountId || getInventoryAccount(productType);
        lines.push(
            { accountId: (await getAccountId(invAccount)), debit: totalAmount, credit: 0, description: `GR: ${productVariant.name}` },
            { accountId: (await getAccountId('21110')), debit: 0, credit: totalAmount, description: `AP Accrual: ${productVariant.name}` }
        );
    }

    else if (movement.type === 'OUT' && movement.salesOrderId) {
        const invAccount = productVariant.product.inventoryAccountId || getInventoryAccount(productType);
        const cogsAccount = productVariant.product.cogsAccountId || '50000';
        lines.push(
            { accountId: (await getAccountId(cogsAccount)), debit: totalAmount, credit: 0, description: `COGS: ${productVariant.name}` },
            { accountId: (await getAccountId(invAccount)), debit: 0, credit: totalAmount, description: `Shipment: ${productVariant.name}` }
        );
    }

    else if (movement.type === 'OUT' && !movement.salesOrderId) {
        const creditAccount = productVariant.product.inventoryAccountId || getInventoryAccount(productType);
        const wipAccount = productVariant.product.wipAccountId || '12400';
        lines.push(
            { accountId: (await getAccountId(wipAccount)), debit: totalAmount, credit: 0, description: `Production Issue: ${productVariant.name}` },
            { accountId: (await getAccountId(creditAccount)), debit: 0, credit: totalAmount, description: `Material Consumed` }
        );
    }

    else if (movement.type === 'IN' && !movement.goodsReceiptId) {
        const debitAccount = productVariant.product.inventoryAccountId || getInventoryAccount(productType);
        const wipAccount = productVariant.product.wipAccountId || '12400';
        lines.push(
            { accountId: (await getAccountId(debitAccount)), debit: totalAmount, credit: 0, description: `Production Output: ${productVariant.name}` },
            { accountId: (await getAccountId(wipAccount)), debit: 0, credit: totalAmount, description: `WIP Relief` }
        );
    }

    else if (movement.type === 'ADJUSTMENT') {
        const invAccount = getInventoryAccount(productType);
        const absAmt = Math.abs(totalAmount);

        if (Number(movement.quantity) > 0) {
            lines.push(
                { accountId: (await getAccountId(invAccount)), debit: absAmt, credit: 0, description: `Stock Adj (In)` },
                { accountId: (await getAccountId('81100')), debit: 0, credit: absAmt, description: `Adj Gain` }
            );
        } else {
            lines.push(
                { accountId: (await getAccountId('91100')), debit: absAmt, credit: 0, description: `Adj Loss` },
                { accountId: (await getAccountId(invAccount)), debit: 0, credit: absAmt, description: `Stock Adj (Out)` }
            );
        }
    }

    if (lines.length > 0) {
        await createJournalEntry({
            entryDate: date,
            description: `Auto: ${movement.type} - ${productVariant.name}`,
            reference: movement.reference || movement.id,
            referenceType: movement.type === 'PURCHASE' ? 'GOODS_RECEIPT' : (movement.type === 'ADJUSTMENT' ? 'STOCK_ADJUSTMENT' : 'MANUAL_ENTRY'),
            referenceId: movement.id,
            isAutoGenerated: true,
            status: JournalStatus.POSTED,
            lines,
            createdById: movement.createdById ?? undefined
        }, tx);
    }
}

const accountCache = new Map<string, string>();

async function getAccountId(code: string): Promise<string> {
    if (accountCache.has(code)) return accountCache.get(code)!;

    const acc = await prisma.account.findUnique({ where: { code } });
    if (!acc) throw new Error(`GL Account code ${code} not found during auto-journal.`);

    accountCache.set(code, acc.id);
    return acc.id;
}
