import { prisma } from "@/lib/core/prisma";
import { Prisma } from "@prisma/client";
import { getClosingBalances } from "./reports-service";
import { resolveAccount } from "./account-resolver";
import { createJournalEntry } from "./journal-posting";

export async function createClosingJournalEntry(
  periodId: string,
  userId: string,
  tx?: Prisma.TransactionClient,
) {
  const db = tx || prisma;

  const period = await db.fiscalPeriod.findUnique({ where: { id: periodId } });
  if (!period) throw new Error("Period not found");

  const reference = `CLOSING-${period.name.replace(/\s+/g, "-")}`;

  // 1. Re-close capability: Delete existing closing entry if it exists
  const existing = await db.journalEntry.findFirst({
    where: { reference },
  });

  if (existing) {
    // We delete to keep it clean.
    await db.journalLine.deleteMany({ where: { journalEntryId: existing.id } });
    await db.journalEntry.delete({ where: { id: existing.id } });
  }

  const balances = await getClosingBalances(period.startDate, period.endDate);
  if (balances.length === 0) return null;

  let totalNetIncome = 0;
  const lines = balances.map((b) => {
    const isRevenue = b.type === "REVENUE";
    const amount = Math.abs(b.netBalance);

    totalNetIncome += isRevenue ? b.netBalance : -b.netBalance;

    return {
      accountId: b.id,
      debit: isRevenue ? amount : 0,
      credit: isRevenue ? 0 : amount,
      description: `Closing Entry for ${period.name}`,
    };
  });

  const resolvedEarnings = await resolveAccount("current-year-earnings");
  const earningsAccount = await db.account.findUnique({
    where: { id: resolvedEarnings.id },
  });
  if (!earningsAccount)
    throw new Error("Current Year Earnings account not found in COA");

  lines.push({
    accountId: earningsAccount.id,
    debit: totalNetIncome < 0 ? Math.abs(totalNetIncome) : 0,
    credit: totalNetIncome > 0 ? Math.abs(totalNetIncome) : 0,
    description: `Net Income Transfer for ${period.name}`,
  });

  return await createJournalEntry(
    {
      entryDate: period.endDate,
      description: `Closing Entries for ${period.name}`,
      reference,
      referenceType: "MANUAL_ENTRY",
      status: "POSTED",
      isAutoGenerated: true,
      createdById: userId,
      lines,
    },
    tx,
  );
}

/**
 * Transfers Year-End accumulated balance from Current Year Earnings (33000)
 * to Retained Earnings (32000)
 */
export async function createYearEndClosingEntry(
  year: number,
  userId: string,
  tx?: Prisma.TransactionClient,
) {
  const db = tx || prisma;
  const reference = `YEAREND-${year}`;

  // 1. Re-close check
  const existing = await db.journalEntry.findFirst({ where: { reference } });
  if (existing) {
    await db.journalLine.deleteMany({ where: { journalEntryId: existing.id } });
    await db.journalEntry.delete({ where: { id: existing.id } });
  }

  // 2. Get Balance of Current Year Earnings (33000)
  const resolvedEarnings = await resolveAccount("current-year-earnings");
  const earningsAccount = await db.account.findUnique({
    where: { id: resolvedEarnings.id },
  });
  if (!earningsAccount)
    throw new Error("Current Year Earnings account not found");

  const resolvedRetained = await resolveAccount("retained-earnings");
  const retainedEarningsAccount = await db.account.findUnique({
    where: { id: resolvedRetained.id },
  });
  if (!retainedEarningsAccount)
    throw new Error("Retained Earnings account not found");

  // Calculate sum of all journal lines for 33000 in this year
  const journalLines = await db.journalLine.findMany({
    where: {
      accountId: earningsAccount.id,
      journalEntry: {
        entryDate: {
          gte: new Date(year, 0, 1),
          lte: new Date(year, 11, 31, 23, 59, 59),
        },
        status: "POSTED",
      },
    },
  });

  const totalDebit = journalLines.reduce((sum, l) => sum + Number(l.debit), 0);
  const totalCredit = journalLines.reduce(
    (sum, l) => sum + Number(l.credit),
    0,
  );
  const balance = totalCredit - totalDebit; // Credit Normal

  if (Math.abs(balance) < 0.01) {
    throw new Error(
      `No balance in Current Year Earnings (33000) for year ${year} to transfer.`,
    );
  }

  // 3. Create Transfer Entry
  const closingLines = [
    {
      accountId: earningsAccount.id,
      debit: balance > 0 ? balance : 0,
      credit: balance < 0 ? Math.abs(balance) : 0,
      description: `Year-End Transfer of Earnings to Retained Earnings - ${year}`,
    },
    {
      accountId: retainedEarningsAccount.id,
      debit: balance < 0 ? Math.abs(balance) : 0,
      credit: balance > 0 ? balance : 0,
      description: `Transferred from Current Year Earnings - ${year}`,
    },
  ];

  return await createJournalEntry(
    {
      entryDate: new Date(year, 11, 31, 23, 59, 59),
      description: `Year-End Closing Entry ${year}`,
      reference,
      referenceType: "MANUAL_ENTRY",
      status: "POSTED",
      isAutoGenerated: true,
      createdById: userId,
      lines: closingLines,
    },
    tx,
  );
}
