import { prisma } from "@/lib/core/prisma";
import { JournalStatus, Prisma, ReferenceType } from "@prisma/client";
import type { CreateJournalEntryInput } from "./types";
import { isPeriodOpen } from "@/services/accounting/periods-service";

export async function createJournalEntry(
  input: CreateJournalEntryInput,
  tx?: Prisma.TransactionClient,
) {
  const { lines } = input;

  const totalDebit = lines.reduce((sum, line) => sum + Number(line.debit), 0);
  const totalCredit = lines.reduce((sum, line) => sum + Number(line.credit), 0);

  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new Error(
      `Journal Entry is not balanced. Debit: ${totalDebit}, Credit: ${totalCredit}`,
    );
  }

  // Validation: Prevent manual entries to Control Accounts (AR & Inventory)
  if (!input.isAutoGenerated && input.referenceType === "MANUAL_ENTRY") {
    const db = tx || prisma;
    const accountIds = lines.map((l) => l.accountId);
    const controlAccounts = await db.account.findMany({
      where: {
        id: { in: accountIds },
        OR: [
          { code: { startsWith: "112" } }, // Accounts Receivable
          { code: { startsWith: "113" } }, // Inventory
        ],
      },
    });

    if (controlAccounts.length > 0) {
      const codes = controlAccounts.map((a) => a.code).join(", ");
      throw new Error(
        `Manual journal entry is forbidden for Control Accounts: ${codes}. Please use the Receive Payment, Bill Payment, or Inventory modules instead to ensure data consistency.`,
      );
    }
  }

  const isOpen = await isPeriodOpen(input.entryDate);
  if (!isOpen) {
    throw new Error("Cannot create journal entry in a closed fiscal period.");
  }

  const maxRetries = 3;
  let lastError: unknown;

  for (let i = 0; i < maxRetries; i++) {
    try {
      const executeInTx = async (db: Prisma.TransactionClient) => {
        const entryNumber = await generateEntryNumber(input.entryDate, db);

        return await db.journalEntry.create({
          data: {
            entryNumber,
            entryDate: input.entryDate,
            description: input.description,
            reference: input.reference,
            referenceType: input.referenceType,
            referenceId: input.referenceId,
            status: input.status || JournalStatus.DRAFT,
            isAutoGenerated: input.isAutoGenerated || false,
            createdById: input.createdById,
            lines: {
              create: lines.map((line) => ({
                accountId: line.accountId,
                debit: line.debit,
                credit: line.credit,
                description: line.description,
              })),
            },
          },
          include: {
            lines: {
              include: { account: true },
            },
          },
        });
      };

      if (tx) {
        return await executeInTx(tx);
      } else {
        return await prisma.$transaction(
          async (innerTx) => {
            return await executeInTx(innerTx);
          },
          {
            isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
          },
        );
      }
    } catch (error) {
      lastError = error;
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === "P2002"
      ) {
        const target = (error.meta?.target as string[]) || [];
        if (target.includes("entryNumber") && !tx) {
          console.warn(
            `[JournalService] entryNumber collision detected, retrying... (${i + 1}/${maxRetries})`,
          );
          await new Promise((resolve) => setTimeout(resolve, 50 * (i + 1)));
          continue;
        }
      }
      throw error;
    }
  }

  throw lastError;
}

export async function postJournal(
  id: string,
  userId?: string,
  tx?: Prisma.TransactionClient,
) {
  const db = tx || prisma;
  const journal = await db.journalEntry.findUnique({
    where: { id },
    include: { lines: true },
  });

  if (!journal) throw new Error("Journal not found");
  if (journal.status !== "DRAFT")
    throw new Error("Only DRAFT journals can be posted");

  const isOpen = await isPeriodOpen(journal.entryDate, tx);
  if (!isOpen) {
    throw new Error("Cannot post journal entry to a closed fiscal period.");
  }

  const updatedJournal = await db.journalEntry.update({
    where: { id },
    data: {
      status: "POSTED",
      approvedById: userId,
      approvedAt: new Date(),
    },
  });

  // Cascade status update to the source document if applicable
  if (journal.referenceType === "PURCHASE_INVOICE" && journal.referenceId) {
    await db.purchaseInvoice.updateMany({
      where: { id: journal.referenceId, status: "DRAFT" },
      data: { status: "UNPAID" },
    });
  } else if (journal.referenceType === "SALES_INVOICE" && journal.referenceId) {
    await db.invoice.updateMany({
      where: { id: journal.referenceId, status: "DRAFT" },
      data: { status: "UNPAID" },
    });
  }

  return updatedJournal;
}

export async function postBulkJournals(ids: string[], userId?: string) {
  const journals = await prisma.journalEntry.findMany({
    where: { id: { in: ids }, status: "DRAFT" },
  });

  for (const journal of journals) {
    const isOpen = await isPeriodOpen(journal.entryDate);
    if (!isOpen) {
      throw new Error(
        `Cannot post journal ${journal.entryNumber} to a closed fiscal period.`,
      );
    }
  }

  const res = await prisma.journalEntry.updateMany({
    where: {
      id: { in: ids },
      status: "DRAFT",
    },
    data: {
      status: "POSTED",
      approvedById: userId,
      approvedAt: new Date(),
    },
  });

  const purchaseInvoiceIds = journals
    .filter((j) => j.referenceType === "PURCHASE_INVOICE" && j.referenceId)
    .map((j) => j.referenceId as string);

  const salesInvoiceIds = journals
    .filter((j) => j.referenceType === "SALES_INVOICE" && j.referenceId)
    .map((j) => j.referenceId as string);

  if (purchaseInvoiceIds.length > 0) {
    await prisma.purchaseInvoice.updateMany({
      where: { id: { in: purchaseInvoiceIds }, status: "DRAFT" },
      data: { status: "UNPAID" },
    });
  }

  if (salesInvoiceIds.length > 0) {
    await prisma.invoice.updateMany({
      where: { id: { in: salesInvoiceIds }, status: "DRAFT" },
      data: { status: "UNPAID" },
    });
  }

  return res;
}

export async function voidJournal(id: string, userId?: string) {
  const journal = await prisma.journalEntry.findUnique({ where: { id } });

  if (!journal) throw new Error("Journal not found");
  if (journal.status !== "POSTED")
    throw new Error("Only POSTED journals can be voided");
  if (journal.isAutoGenerated)
    throw new Error(
      "Cannot directly void an auto-generated journal entry. Please void the associated source document instead.",
    );

  const isOpen = await isPeriodOpen(journal.entryDate);
  if (!isOpen) {
    throw new Error("Cannot void journal entry in a closed fiscal period.");
  }

  return await prisma.journalEntry.update({
    where: { id },
    data: {
      status: "VOIDED",
      approvedById: userId,
      approvedAt: new Date(),
    },
  });
}

export async function reverseJournal(id: string, userId?: string) {
  const original = await prisma.journalEntry.findUnique({
    where: { id },
    include: { lines: true },
  });

  if (!original) throw new Error("Journal not found");
  if (original.status !== "POSTED")
    throw new Error("Only POSTED journals can be reversed");
  if (original.isAutoGenerated)
    throw new Error(
      "Cannot directly reverse an auto-generated journal entry. Please reverse the associated source document instead.",
    );

  const isOpen = await isPeriodOpen(original.entryDate);
  if (!isOpen) {
    throw new Error("Cannot reverse journal entry in a closed fiscal period.");
  }

  const reversalLines = original.lines.map((l) => ({
    accountId: l.accountId,
    debit: Number(l.credit),
    credit: Number(l.debit),
    description: `Reversal of ${original.entryNumber}: ${l.description || ""} `,
  }));

  return await createJournalEntry({
    entryDate: new Date(),
    description: `Reversal of ${original.description} `,
    reference: original.entryNumber,
    referenceType: "MANUAL_ENTRY",
    createdById: userId,
    lines: reversalLines,
  });
}

export async function createBulkJournalEntries(
  data: CreateJournalEntryInput[],
) {
  const maxRetries = 3;
  let lastError: unknown;

  for (let i = 0; i < maxRetries; i++) {
    try {
      return await prisma.$transaction(
        async (tx) => {
          const results = [];
          for (const entry of data) {
            const totalDebit = entry.lines.reduce(
              (sum, l) => sum + (Number(l.debit) || 0),
              0,
            );
            const totalCredit = entry.lines.reduce(
              (sum, l) => sum + (Number(l.credit) || 0),
              0,
            );
            if (Math.abs(totalDebit - totalCredit) > 0.01) {
              throw new Error(
                `Unbalanced journal for reference ${entry.reference}`,
              );
            }

            const isOpen = await isPeriodOpen(entry.entryDate, tx);
            if (!isOpen) {
              throw new Error(
                `Cannot create journal entry in a closed fiscal period for reference ${entry.reference}`,
              );
            }

            const entryNumber = await generateEntryNumber(entry.entryDate, tx);

            const je = await tx.journalEntry.create({
              data: {
                entryNumber,
                entryDate: entry.entryDate,
                description: entry.description,
                reference: entry.reference,
                referenceType: entry.referenceType as ReferenceType,
                createdById: entry.createdById,
                isAutoGenerated: entry.isAutoGenerated,
                status: entry.status || JournalStatus.DRAFT,
                lines: {
                  create: entry.lines.map((l) => ({
                    accountId: l.accountId,
                    debit: l.debit,
                    credit: l.credit,
                    description: l.description,
                    currency: "IDR",
                    exchangeRate: 1,
                  })),
                },
              },
            });
            results.push(je);
          }
          return results;
        },
        {
          isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
        },
      );
    } catch (error) {
      lastError = error;
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        (error.code === "P2002" ||
          error.code === "P2034" ||
          error.message.includes("serialization failure"))
      ) {
        console.warn(
          `[JournalService] Bulk collision or serialization error, retrying... (${i + 1}/${maxRetries})`,
        );
        await new Promise((resolve) => setTimeout(resolve, 100 * (i + 1)));
        continue;
      }
      throw error;
    }
  }
  throw lastError;
}

async function generateEntryNumber(
  date: Date,
  tx?: Prisma.TransactionClient,
): Promise<string> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = (tx || prisma) as any;
  const year = date.getFullYear();
  const key = `JOURNAL_ENTRY_${year}`;

  const fastForwardSequence = async (targetValue: number) => {
    console.warn(
      `[JournalService] Fast-forwarding sequence ${key} to ${targetValue + 1} (was behind actual entries)`,
    );
    await db.systemSequence.update({
      where: { key },
      data: { value: BigInt(targetValue + 1) },
    });
    return targetValue;
  };

  const parseEntryNumber = (entryNumber: string): number => {
    const parts = entryNumber.split("-");
    const lastPart = parts[parts.length - 1].trim();
    return parseInt(lastPart, 10);
  };

  const findMaxEntryNumber = async (): Promise<number> => {
    const latestEntry = await (tx || prisma).journalEntry.findFirst({
      where: {
        entryDate: {
          gte: new Date(year, 0, 1),
          lt: new Date(year + 1, 0, 1),
        },
      },
      orderBy: { entryNumber: "desc" },
    });

    if (latestEntry?.entryNumber) {
      const num = parseEntryNumber(latestEntry.entryNumber);
      if (!isNaN(num)) return num;
    }
    return 0;
  };

  try {
    const sequence = await db.systemSequence.update({
      where: { key },
      data: { value: { increment: 1 } },
    });
    const currentVal = Number(sequence.value) - 1;
    const candidate = `JE - ${year} -${currentVal.toString().padStart(5, "0")}`;

    const existing = await (tx || prisma).journalEntry.findUnique({
      where: { entryNumber: candidate },
      select: { id: true },
    });

    if (existing) {
      const maxNum = await findMaxEntryNumber();
      const nextVal = await fastForwardSequence(maxNum);
      return `JE - ${year} -${nextVal.toString().padStart(5, "0")}`;
    }

    return candidate;
  } catch (error) {
    if (
      error instanceof Prisma.PrismaClientKnownRequestError &&
      error.code === "P2025"
    ) {
      const maxNum = await findMaxEntryNumber();
      const startValue = maxNum + 1;

      const sequence = await db.systemSequence.upsert({
        where: { key },
        update: { value: { increment: 1 } },
        create: { key, value: BigInt(startValue + 1) },
      });
      const currentVal = Number(sequence.value) - 1;
      return `JE - ${year} -${currentVal.toString().padStart(5, "0")}`;
    }
    throw error;
  }
}
