import { prisma } from "@/lib/core/prisma";
import { JournalStatus, Prisma } from "@prisma/client";
import type { CreateJournalEntryInput } from "./types";
import type { DetailJournalDirection } from "@/lib/config/detail-journal-templates";
import { isPeriodOpen } from "@/services/accounting/periods-service";
import { NotFoundError, BusinessRuleError } from "@/lib/errors/errors";
import { toBusinessDateString } from "@/lib/utils/timezone";

export async function createJournalEntry(
  input: CreateJournalEntryInput,
  tx?: Prisma.TransactionClient,
) {
  const { lines } = input;

  const totalDebit = lines.reduce((sum, line) => sum + Number(line.debit), 0);
  const totalCredit = lines.reduce((sum, line) => sum + Number(line.credit), 0);

  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new BusinessRuleError(
      `Journal Entry is not balanced. Debit: ${totalDebit}, Credit: ${totalCredit}`,
      { totalDebit, totalCredit, difference: Math.abs(totalDebit - totalCredit) },
      "UNBALANCED_JOURNAL",
    );
  }

  // Validation: Prevent manual entries to Control Accounts (AR & Inventory)
  if (!input.isAutoGenerated && input.referenceType === "MANUAL_ENTRY") {
    const db = tx || prisma;
    const accountIds = lines.map((l) => l.accountId);
    const controlAccounts = await db.account.findMany({
      where: {
        id: { in: accountIds },
        OR: [
          { code: { startsWith: "112" } }, // Accounts Receivable
          { code: { startsWith: "113" } }, // Inventory
        ],
      },
    });

    if (controlAccounts.length > 0) {
      const codes = controlAccounts.map((a: {code: string}) => a.code).join(", ");
      throw new BusinessRuleError(
        `Manual journal entry is forbidden for Control Accounts: ${codes}. Please use the Receive Payment, Bill Payment, or Inventory modules instead to ensure data consistency.`,
        { controlAccountCodes: codes, accountIds },
      );
    }
  }

  const isOpen = await isPeriodOpen(input.entryDate);
  if (!isOpen) {
    throw new BusinessRuleError(
      "Cannot create journal entry in a closed fiscal period.",
      { entryDate: input.entryDate },
      "FISCAL_PERIOD_CLOSED",
    );
  }

  const maxRetries = 3;
  let lastError: unknown;

  for (let i = 0; i < maxRetries; i++) {
    try {
      const executeInTx = async (db: Prisma.TransactionClient) => {
        const entryNumber = await generateEntryNumber(input.entryDate, db);

        return await db.journalEntry.create({
          data: {
            entryNumber,
            entryDate: input.entryDate,
            description: input.description,
            reference: input.reference,
            referenceType: input.referenceType,
            referenceId: input.referenceId,
            status: input.status || JournalStatus.DRAFT,
            isAutoGenerated: input.isAutoGenerated || false,
            createdById: input.createdById,
            lines: {
              create: lines.map((line) => ({
                accountId: line.accountId,
                debit: line.debit,
                credit: line.credit,
                description: line.description,
              })),
            },
          },
          include: {
            lines: {
              include: { account: true },
            },
          },
        });
      };

      if (tx) {
        return await executeInTx(tx);
      } else {
        return await prisma.$transaction(
          async (innerTx) => {
            return await executeInTx(innerTx);
          },
          {
            isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
          },
        );
      }
    } catch (error) {
      lastError = error;
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === "P2002"
      ) {
        const target = (error.meta?.target as string[]) || [];
        if (target.includes("entryNumber") && !tx) {
          console.warn(
            `[JournalService] entryNumber collision detected, retrying... (${i + 1}/${maxRetries})`,
          );
          await new Promise((resolve) => setTimeout(resolve, 50 * (i + 1)));
          continue;
        }
      }
      throw error;
    }
  }

  throw lastError;
}

export async function postJournal(
  id: string,
  userId?: string,
  tx?: Prisma.TransactionClient,
) {
  const db = tx || prisma;
  const journal = await db.journalEntry.findUnique({
    where: { id },
    include: { lines: true },
  });

  if (!journal) throw new NotFoundError("Journal", id);
  if (journal.status !== "DRAFT")
    throw new BusinessRuleError(
      "Only DRAFT journals can be posted",
      { journalId: id, currentStatus: journal.status },
      "INVALID_STATUS_TRANSITION",
    );

  const isOpen = await isPeriodOpen(journal.entryDate, tx);
  if (!isOpen) {
    throw new BusinessRuleError(
      "Cannot post journal entry to a closed fiscal period.",
      { journalId: id, entryDate: journal.entryDate },
      "FISCAL_PERIOD_CLOSED",
    );
  }

  const updatedJournal = await db.journalEntry.update({
    where: { id },
    data: {
      status: "POSTED",
      approvedById: userId,
      approvedAt: new Date(),
    },
  });

  // Cascade status update to the source document if applicable
  if (journal.referenceType === "PURCHASE_INVOICE" && journal.referenceId) {
    await db.purchaseInvoice.updateMany({
      where: { id: journal.referenceId, status: "DRAFT" },
      data: { status: "UNPAID" },
    });
  } else if (journal.referenceType === "SALES_INVOICE" && journal.referenceId) {
    await db.invoice.updateMany({
      where: { id: journal.referenceId, status: "DRAFT" },
      data: { status: "UNPAID" },
    });
  }

  return updatedJournal;
}

export async function postBulkJournals(ids: string[], userId?: string) {
  const journals = await prisma.journalEntry.findMany({
    where: { id: { in: ids }, status: "DRAFT" },
  });

  for (const journal of journals) {
    const isOpen = await isPeriodOpen(journal.entryDate);
    if (!isOpen) {
      throw new BusinessRuleError(
        `Cannot post journal ${journal.entryNumber} to a closed fiscal period.`,
        { journalId: journal.id, entryNumber: journal.entryNumber, entryDate: journal.entryDate },
        "FISCAL_PERIOD_CLOSED",
      );
    }
  }

  const res = await prisma.journalEntry.updateMany({
    where: {
      id: { in: ids },
      status: "DRAFT",
    },
    data: {
      status: "POSTED",
      approvedById: userId,
      approvedAt: new Date(),
    },
  });

  const purchaseInvoiceIds = journals
    .filter((j) => j.referenceType === "PURCHASE_INVOICE" && j.referenceId)
    .map((j) => j.referenceId as string);

  const salesInvoiceIds = journals
    .filter((j) => j.referenceType === "SALES_INVOICE" && j.referenceId)
    .map((j) => j.referenceId as string);

  if (purchaseInvoiceIds.length > 0) {
    await prisma.purchaseInvoice.updateMany({
      where: { id: { in: purchaseInvoiceIds }, status: "DRAFT" },
      data: { status: "UNPAID" },
    });
  }

  if (salesInvoiceIds.length > 0) {
    await prisma.invoice.updateMany({
      where: { id: { in: salesInvoiceIds }, status: "DRAFT" },
      data: { status: "UNPAID" },
    });
  }

  return res;
}

export async function reverseJournal(
  id: string,
  userId?: string,
  reason?: string,
) {
  const reversedById = userId || "system";
  const journal = await prisma.journalEntry.findUnique({
    where: { id },
    include: { lines: true },
  });

  if (!journal) throw new NotFoundError("Journal", id);
  if (journal.status !== "POSTED")
    throw new BusinessRuleError(
      "Only POSTED journals can be reversed",
      { journalId: id, currentStatus: journal.status },
      "INVALID_STATUS_TRANSITION",
    );
  if (journal.isAutoGenerated)
    throw new BusinessRuleError(
      "Cannot directly reverse an auto-generated journal",
      { journalId: id, isAutoGenerated: true },
    );

  const isOpen = await isPeriodOpen(new Date());
  if (!isOpen) {
    throw new BusinessRuleError(
      "Cannot reverse journal in a closed fiscal period.",
      { journalId: id },
      "FISCAL_PERIOD_CLOSED",
    );
  }

  const entryNumber = await generateEntryNumber(new Date());

  const reversal = await prisma.journalEntry.create({
    data: {
      entryNumber,
      entryDate: new Date(),
      description: `REVERSAL of ${journal.entryNumber}: ${reason || journal.description}`,
      reference: journal.entryNumber,
      referenceType: "MANUAL_ENTRY",
      status: "POSTED",
      isAutoGenerated: false,
      createdById: reversedById,
      approvedById: reversedById,
      approvedAt: new Date(),
      lines: {
        create: journal.lines.map((line) => ({
          accountId: line.accountId,
          debit: line.credit, // Swap debit/credit
          credit: line.debit,
          description: `Reversal: ${line.description}`,
        })),
      },
    },
    include: {
      lines: { include: { account: true } },
    },
  });

  await prisma.journalEntry.update({
    where: { id },
    data: { status: "VOIDED" },
  });

  return reversal;
}

export async function voidJournal(
  id: string,
  userId?: string,
  reason?: string,
) {
  const voidedById = userId || "system";
  const journal = await prisma.journalEntry.findUnique({
    where: { id },
    include: { lines: true },
  });

  if (!journal) throw new NotFoundError("Journal", id);
  if (journal.status !== "POSTED")
    throw new BusinessRuleError(
      "Only POSTED journals can be voided",
      { journalId: id, currentStatus: journal.status },
      "INVALID_STATUS_TRANSITION",
    );
  if (journal.isAutoGenerated)
    throw new BusinessRuleError(
      "Cannot directly void an auto-generated journal",
      { journalId: id, isAutoGenerated: true },
    );

  const isOpen = await isPeriodOpen(new Date());
  if (!isOpen) {
    throw new BusinessRuleError(
      "Cannot void journal in a closed fiscal period.",
      { journalId: id },
      "FISCAL_PERIOD_CLOSED",
    );
  }

  // Create reversal entry
  const entryNumber = await generateEntryNumber(new Date());

  await prisma.journalEntry.create({
    data: {
      entryNumber,
      entryDate: new Date(),
      description: `VOID of ${journal.entryNumber}: ${reason || journal.description}`,
      reference: journal.entryNumber,
      referenceType: "MANUAL_ENTRY",
      status: "POSTED",
      isAutoGenerated: false,
      createdById: voidedById,
      approvedById: voidedById,
      approvedAt: new Date(),
      lines: {
        create: journal.lines.map((line) => ({
          accountId: line.accountId,
          debit: line.credit, // Swap debit/credit
          credit: line.debit,
          description: `Void: ${line.description}`,
        })),
      },
    },
  });

  // Mark original as VOIDED
  const voidedJournal = await prisma.journalEntry.update({
    where: { id },
    data: { 
      status: "VOIDED",
      approvedById: voidedById,
      approvedAt: new Date(),
    },
  });

  return voidedJournal;
}

export async function createBulkJournalEntries(
  entries: CreateJournalEntryInput[],
  tx?: Prisma.TransactionClient,
) {
  const maxRetries = 3;
  const results = [];
  
  for (const entry of entries) {
    // Validate balance before creating
    const totalDebit = entry.lines.reduce((sum, line) => sum + Number(line.debit), 0);
    const totalCredit = entry.lines.reduce((sum, line) => sum + Number(line.credit), 0);
    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      throw new BusinessRuleError(
        `Unbalanced journal for reference ${entry.reference || 'UNKNOWN'}`,
        { totalDebit, totalCredit, reference: entry.reference || 'UNKNOWN' },
        "UNBALANCED_JOURNAL",
      );
    }
    
    // Validate period is open
    const isOpen = await isPeriodOpen(entry.entryDate);
    if (!isOpen) {
      throw new BusinessRuleError(
        `Cannot create journal entry in a closed fiscal period for reference ${entry.reference || 'UNKNOWN'}`,
        { reference: entry.reference || 'UNKNOWN', entryDate: entry.entryDate },
        "FISCAL_PERIOD_CLOSED",
      );
    }
    
    // Retry logic for serialization errors
    let lastError: unknown;
    for (let attempt = 0; attempt < maxRetries; attempt++) {
      try {
        const result = await createJournalEntry(entry, tx);
        results.push(result);
        break;
      } catch (error) {
        lastError = error;
        if (
          error instanceof Prisma.PrismaClientKnownRequestError &&
          (error.code === "P2002" || error.code === "P2034")
        ) {
          console.warn(
            `[BulkJournal] Serialization error, retrying... (${attempt + 1}/${maxRetries})`,
          );
          await new Promise((resolve) => setTimeout(resolve, 50 * (attempt + 1)));
          continue;
        }
        throw error;
      }
    }
    if (lastError && results.length <= entries.indexOf(entry)) {
      throw lastError;
    }
  }
  return results;
}

export async function updateDraftJournal(
  id: string,
  input: {
    entryDate: Date;
    description: string;
    reference?: string;
    lines: { accountId: string; debit: number; credit: number; description?: string }[];
  },
  _userId?: string,
) {
  // 1. Load existing journal
  const existing = await prisma.journalEntry.findUnique({
    where: { id },
    include: { lines: true },
  });

  if (!existing) throw new NotFoundError("Journal", id);

  // 2. Guard: must be DRAFT
  if (existing.status !== JournalStatus.DRAFT) {
    throw new BusinessRuleError(
      "Hanya jurnal DRAFT yang bisa diedit",
      { journalId: id, currentStatus: existing.status },
      "INVALID_STATUS_TRANSITION",
    );
  }

  // 3. Guard: not auto-generated
  if (existing.isAutoGenerated) {
    throw new BusinessRuleError(
      "Jurnal otomatis tidak bisa diedit. Ubah dokumen sumber.",
      { journalId: id, isAutoGenerated: true },
    );
  }

  // 4. Balance check
  const { lines } = input;
  const totalDebit = lines.reduce((sum, line) => sum + Number(line.debit), 0);
  const totalCredit = lines.reduce((sum, line) => sum + Number(line.credit), 0);

  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new BusinessRuleError(
      `Journal Entry is not balanced. Debit: ${totalDebit}, Credit: ${totalCredit}`,
      { totalDebit, totalCredit, difference: Math.abs(totalDebit - totalCredit), journalId: id },
      "UNBALANCED_JOURNAL",
    );
  }

  // 5. Control account check (same as create)
  const accountIds = lines.map((l) => l.accountId);
  const controlAccounts = await prisma.account.findMany({
    where: {
      id: { in: accountIds },
      OR: [
        { code: { startsWith: "112" } }, // Accounts Receivable
        { code: { startsWith: "113" } }, // Inventory
      ],
    },
  });

  if (controlAccounts.length > 0) {
    const codes = controlAccounts.map((a) => a.code).join(", ");
    throw new BusinessRuleError(
      `Manual journal entry is forbidden for Control Accounts: ${codes}. Please use the Receive Payment, Bill Payment, or Inventory modules instead to ensure data consistency.`,
      { controlAccountCodes: codes, accountIds, journalId: id },
    );
  }

  // 6. Period open check
  const isOpen = await isPeriodOpen(input.entryDate);
  if (!isOpen) {
    throw new BusinessRuleError(
      "Periode fiskal sudah ditutup",
      { journalId: id, entryDate: input.entryDate },
      "FISCAL_PERIOD_CLOSED",
    );
  }

  // 7. Atomic update: header + line replace
  return await prisma.$transaction(
    async (tx) => {
      // Update header (entryNumber, status, isAutoGenerated, createdById are NOT touched)
      await tx.journalEntry.update({
        where: { id },
        data: {
          entryDate: input.entryDate,
          description: input.description,
          reference: input.reference,
        },
      });

      // Delete all existing lines
      await tx.journalLine.deleteMany({
        where: { journalEntryId: id },
      });

      // Create new lines
      await tx.journalLine.createMany({
        data: lines.map((line) => ({
          journalEntryId: id,
          accountId: line.accountId,
          debit: line.debit,
          credit: line.credit,
          description: line.description,
        })),
      });

      // Return updated journal
      return await tx.journalEntry.findUnique({
        where: { id },
        include: {
          lines: { include: { account: true } },
        },
      });
    },
    { isolationLevel: Prisma.TransactionIsolationLevel.Serializable },
  );
}

/**
 * Allocate the next journal entry number for a calendar year.
 *
 * SystemSequence.value is the next number to assign. Allocation always
 * increments first, then uses value-1. When the sequence has drifted behind
 * real JournalEntry rows (imports/repairs), we floor the sequence to max+1
 * and increment again so the claimed number is consumed — never returned
 * without advancing past it. Returning max+1 without a claim caused the
 * next journal in the same transaction (e.g. multi-material backflush) to
 * re-allocate the same entryNumber and hit P2002.
 */
async function generateEntryNumber(
  date: Date,
  tx?: Prisma.TransactionClient,
  _retryCount = 0,
): Promise<string> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = (tx || prisma) as any;
  // Use WIB calendar year to match the user's intended date, not UTC
  const dateStr = toBusinessDateString(date); // "YYYY-MM-DD" in WIB
  const year = parseInt(dateStr.split('-')[0], 10);
  const key = `JOURNAL_ENTRY_${year}`;
  const MAX_RETRIES = 5;

  const formatEntryNumber = (n: number) =>
    `JE - ${year} -${n.toString().padStart(5, "0")}`;

  const findMaxEntryNumber = async (): Promise<number> => {
    // Numeric suffix only — string order is wrong ("00033" > "00104").
    // Do not filter by entryDate: entryNumber is globally unique, so max
    // must include every JE - {year} -* row regardless of date.
    const result = await (tx || prisma).$queryRaw<
      { max_num: number | bigint | null }[]
    >`
      SELECT MAX(CAST(TRIM(SPLIT_PART("entryNumber", '-', 3)) AS INTEGER)) as max_num
      FROM "JournalEntry"
      WHERE "entryNumber" LIKE ${`JE - ${year} -%`}
    `;
    const raw = result[0]?.max_num;
    return raw == null ? 0 : Number(raw);
  };

  const claimNext = async (): Promise<number> => {
    const sequence = await db.systemSequence.update({
      where: { key },
      data: { value: { increment: 1 } },
    });
    return Number(sequence.value) - 1;
  };

  /** Floor sequence to at least nextFree, then claim via increment. */
  const resyncAndClaim = async (maxNum: number): Promise<number> => {
    const nextFree = maxNum + 1;
    console.warn(
      `[JournalService] Fast-forwarding sequence ${key} to ${nextFree} (was behind actual entries)`,
    );
    // value = next free candidate (not yet claimed)
    await db.systemSequence.update({
      where: { key },
      data: { value: BigInt(nextFree) },
    });
    // increment claims nextFree; value becomes nextFree+1
    return claimNext();
  };

  try {
    let currentVal = await claimNext();
    let candidate = formatEntryNumber(currentVal);

    const existing = await (tx || prisma).journalEntry.findUnique({
      where: { entryNumber: candidate },
      select: { id: true },
    });

    if (!existing) {
      return candidate;
    }

    // Sequence behind real data — resync and claim a free number.
    for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
      const maxNum = await findMaxEntryNumber();
      currentVal = await resyncAndClaim(maxNum);
      candidate = formatEntryNumber(currentVal);

      const stillTaken = await (tx || prisma).journalEntry.findUnique({
        where: { entryNumber: candidate },
        select: { id: true },
      });
      if (!stillTaken) {
        return candidate;
      }

      // Rare race / same-tx sibling: bump floor past this candidate and retry.
      console.warn(
        `[JournalService] entryNumber ${candidate} still taken after resync, retrying (${attempt + 1}/${MAX_RETRIES})`,
      );
      await db.systemSequence.update({
        where: { key },
        data: { value: BigInt(currentVal + 1) },
      });
    }

    throw new BusinessRuleError(
      `Failed to allocate unique journal entryNumber after ${MAX_RETRIES} attempts (year ${year})`,
      { year, maxRetries: MAX_RETRIES },
      "ENTRY_NUMBER_ALLOCATION_FAILED",
    );
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      if (error.code === "P2002" && _retryCount < MAX_RETRIES) {
        console.warn(
          `[JournalService] entryNumber collision, retrying (${_retryCount + 1}/${MAX_RETRIES})`,
        );
        return generateEntryNumber(date, tx, _retryCount + 1);
      }
      if (error.code === "P2025") {
        // Sequence row missing — create from max and claim.
        const maxNum = await findMaxEntryNumber();
        const startValue = maxNum + 1;
        const sequence = await db.systemSequence.upsert({
          where: { key },
          update: { value: { increment: 1 } },
          // create with startValue+1 so value-1 after "virtual claim" semantics
          // matches startValue when we use the upserted value-1 path below
          create: { key, value: BigInt(startValue + 1) },
        });
        const currentVal = Number(sequence.value) - 1;
        return formatEntryNumber(currentVal);
      }
    }
    throw error;
  }
}

// ---------------------------------------------------------------------------
// Direct Labor Journal — compact 2-line GL + detail table
// ---------------------------------------------------------------------------

export type DirectLaborInput = {
  entryDate: Date;
  description: string;
  reference?: string;
  debitAccountId: string;
  creditAccountId: string;
  details: { description: string; amount: number }[];
};

/**
 * Build the 2 journal lines from detail rows.
 * Debit: total to debitAccountId, Credit: total to creditAccountId.
 */
export function buildDirectLaborLines(data: DirectLaborInput) {
  const total = data.details.reduce((sum, d) => sum + Number(d.amount), 0);
  return [
    {
      accountId: data.debitAccountId,
      debit: total,
      credit: 0,
      description: data.description,
    },
    {
      accountId: data.creditAccountId,
      debit: 0,
      credit: total,
      description: `Pembayaran ${data.description}`,
    },
  ];
}

/**
 * Create a Direct Labor journal — thin wrapper around generic createDetailJournal.
 */
export async function createDirectLaborJournal(
  input: DirectLaborInput,
  createdById?: string,
) {
  return createDetailJournal(
    {
      type: "DIRECT_LABOR",
      entryDate: input.entryDate,
      description: input.description,
      reference: input.reference,
      primaryAccountId: input.debitAccountId,
      counterAccountId: input.creditAccountId,
      direction: "OUTFLOW",
      details: input.details,
    },
    createdById,
  );
}

/**
 * Update a DRAFT Direct Labor journal — thin wrapper around generic updateDetailJournal.
 */
export async function updateDirectLaborJournal(
  id: string,
  input: DirectLaborInput,
  _userId?: string,
) {
  return updateDetailJournal(
    id,
    {
      type: "DIRECT_LABOR",
      entryDate: input.entryDate,
      description: input.description,
      reference: input.reference,
      primaryAccountId: input.debitAccountId,
      counterAccountId: input.creditAccountId,
      direction: "OUTFLOW",
      details: input.details,
    },
    _userId,
  );
}

// ---------------------------------------------------------------------------
// Generic Detail Journal — template-driven 2-line GL + detail table
// ---------------------------------------------------------------------------

export type DetailJournalInput = {
  type: string;
  entryDate: Date;
  description: string;
  reference?: string;
  primaryAccountId: string;
  counterAccountId: string;
  direction: DetailJournalDirection;
  details: { description: string; amount: number }[];
};

/**
 * Build 2 balanced GL lines from detail rows, respecting direction.
 *
 * OUTFLOW: Debit primary, Credit counter
 * INFLOW:  Debit counter, Credit primary
 */
export function buildDetailJournalLines(data: DetailJournalInput) {
  const total = data.details.reduce((sum, d) => sum + Number(d.amount), 0);

  if (data.direction === 'OUTFLOW') {
    return [
      {
        accountId: data.primaryAccountId,
        debit: total,
        credit: 0,
        description: data.description,
      },
      {
        accountId: data.counterAccountId,
        debit: 0,
        credit: total,
        description: data.description,
      },
    ];
  }

  // INFLOW
  return [
    {
      accountId: data.counterAccountId,
      debit: total,
      credit: 0,
      description: data.description,
    },
    {
      accountId: data.primaryAccountId,
      debit: 0,
      credit: total,
      description: data.description,
    },
  ];
}

/**
 * Create a detail journal: 2 GL lines + JournalEntryDetail rows (atomic).
 * Generic version that works for all templates (BTKL, Piutang, BPJS).
 */
export async function createDetailJournal(
  input: DetailJournalInput,
  createdById?: string,
) {
  const lines = buildDetailJournalLines(input);

  // Validate balance
  const totalDebit = lines.reduce((s, l) => s + l.debit, 0);
  const totalCredit = lines.reduce((s, l) => s + l.credit, 0);
  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new BusinessRuleError(
      `Journal Entry is not balanced. Debit: ${totalDebit}, Credit: ${totalCredit}`,
      { totalDebit, totalCredit },
      "UNBALANCED_JOURNAL",
    );
  }

  // Control account guard — prevent AR / Inventory accounts
  const accountIds = lines.map((l) => l.accountId);
  const controlAccounts = await prisma.account.findMany({
    where: {
      id: { in: accountIds },
      OR: [
        { code: { startsWith: "112" } }, // Accounts Receivable
        { code: { startsWith: "113" } }, // Inventory
      ],
    },
  });

  if (controlAccounts.length > 0) {
    const codes = controlAccounts
      .map((a: { code: string }) => a.code)
      .join(", ");
    throw new BusinessRuleError(
      `Manual journal entry is forbidden for Control Accounts: ${codes}. Please use the Receive Payment, Bill Payment, or Inventory modules instead to ensure data consistency.`,
      { controlAccountCodes: codes, accountIds },
    );
  }

  // Period check
  const isOpen = await isPeriodOpen(input.entryDate);
  if (!isOpen) {
    throw new BusinessRuleError(
      "Cannot create journal entry in a closed fiscal period.",
      { entryDate: input.entryDate },
      "FISCAL_PERIOD_CLOSED",
    );
  }

  const maxRetries = 3;
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      return await prisma.$transaction(
        async (tx) => {
          const entryNumber = await generateEntryNumber(input.entryDate, tx);

          const entry = await tx.journalEntry.create({
            data: {
              entryNumber,
              entryDate: input.entryDate,
              description: input.description,
              reference: input.reference ?? "",
              referenceType: "MANUAL_ENTRY",
              status: JournalStatus.DRAFT,
              isAutoGenerated: false,
              createdById,
              lines: {
                create: lines.map((l) => ({
                  accountId: l.accountId,
                  debit: l.debit,
                  credit: l.credit,
                  description: l.description,
                })),
              },
              details: {
                create: input.details.map((d, idx) => ({
                  type: input.type,
                  description: d.description,
                  amount: d.amount,
                  sortOrder: idx,
                })),
              },
            },
            include: {
              lines: { include: { account: true } },
              details: { orderBy: { sortOrder: "asc" } },
            },
          });

          return entry;
        },
        { isolationLevel: Prisma.TransactionIsolationLevel.Serializable },
      );
    } catch (error) {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === "P2002" &&
        attempt < maxRetries - 1
      ) {
        continue;
      }
      throw error;
    }
  }

  throw new BusinessRuleError(
    `Failed to allocate unique journal entryNumber after ${maxRetries} attempts`,
    {},
    "ENTRY_NUMBER_ALLOCATION_FAILED",
  );
}

/**
 * Update a DRAFT detail journal: replace lines + details atomically.
 * Generic version that works for all templates.
 */
export async function updateDetailJournal(
  id: string,
  input: DetailJournalInput,
  _userId?: string,
) {
  // 1. Load existing
  const existing = await prisma.journalEntry.findUnique({
    where: { id },
    include: { lines: true, details: true },
  });

  if (!existing) throw new NotFoundError("Journal", id);

  // 2. Guard: must be DRAFT
  if (existing.status !== JournalStatus.DRAFT) {
    throw new BusinessRuleError(
      "Hanya jurnal DRAFT yang bisa diedit",
      { journalId: id, currentStatus: existing.status },
      "INVALID_STATUS_TRANSITION",
    );
  }

  // 3. Guard: not auto-generated
  if (existing.isAutoGenerated) {
    throw new BusinessRuleError(
      "Jurnal otomatis tidak bisa diedit. Ubah dokumen sumber.",
      { journalId: id, isAutoGenerated: true },
    );
  }

  // 4. Balance check
  const lines = buildDetailJournalLines(input);
  const totalDebit = lines.reduce((s, l) => s + l.debit, 0);
  const totalCredit = lines.reduce((s, l) => s + l.credit, 0);

  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new BusinessRuleError(
      `Journal Entry is not balanced. Debit: ${totalDebit}, Credit: ${totalCredit}`,
      { totalDebit, totalCredit, journalId: id },
      "UNBALANCED_JOURNAL",
    );
  }

  // 5. Control account check
  const accountIds = lines.map((l) => l.accountId);
  const controlAccounts = await prisma.account.findMany({
    where: {
      id: { in: accountIds },
      OR: [
        { code: { startsWith: "112" } },
        { code: { startsWith: "113" } },
      ],
    },
  });

  if (controlAccounts.length > 0) {
    const codes = controlAccounts.map((a) => a.code).join(", ");
    throw new BusinessRuleError(
      `Manual journal entry is forbidden for Control Accounts: ${codes}.`,
      { controlAccountCodes: codes, accountIds, journalId: id },
    );
  }

  // 6. Period open check
  const isOpen = await isPeriodOpen(input.entryDate);
  if (!isOpen) {
    throw new BusinessRuleError(
      "Periode fiskal sudah ditutup",
      { journalId: id, entryDate: input.entryDate },
      "FISCAL_PERIOD_CLOSED",
    );
  }

  // 7. Atomic update
  return await prisma.$transaction(
    async (tx) => {
      // Update header
      await tx.journalEntry.update({
        where: { id },
        data: {
          entryDate: input.entryDate,
          description: input.description,
          reference: input.reference,
        },
      });

      // Replace GL lines
      await tx.journalLine.deleteMany({ where: { journalEntryId: id } });
      await tx.journalLine.createMany({
        data: lines.map((l) => ({
          journalEntryId: id,
          accountId: l.accountId,
          debit: l.debit,
          credit: l.credit,
          description: l.description,
        })),
      });

      // Replace details
      await tx.journalEntryDetail.deleteMany({
        where: { journalEntryId: id },
      });
      await tx.journalEntryDetail.createMany({
        data: input.details.map((d, idx) => ({
          journalEntryId: id,
          type: input.type,
          description: d.description,
          amount: d.amount,
          sortOrder: idx,
        })),
      });

      // Return updated journal
      return await tx.journalEntry.findUnique({
        where: { id },
        include: {
          lines: { include: { account: true } },
          details: { orderBy: { sortOrder: "asc" } },
        },
      });
    },
    { isolationLevel: Prisma.TransactionIsolationLevel.Serializable },
  );
}
