import { Prisma, type StockMovement } from '@prisma/client';
import { BusinessRuleError } from '@/lib/errors/errors';
import { logActivity } from '@/lib/tools/audit';
import { generateEntryNumber } from './journal-posting';
import { requireOpenJournalPeriod } from '@/services/finance/sales-recognition-service';

type SourceJournal = Prisma.JournalEntryGetPayload<{ include: { lines: true } }>;

function validatePair(original: StockMovement, reversal: StockMovement) {
    if (
        original.type !== 'OUT' || reversal.type !== 'IN' ||
        !original.salesOrderId || reversal.salesOrderId !== original.salesOrderId ||
        original.id === reversal.id || original.reference?.startsWith('VOID:') ||
        original.productVariantId !== reversal.productVariantId ||
        !original.fromLocationId || original.toLocationId !== null ||
        reversal.toLocationId !== original.fromLocationId || reversal.fromLocationId !== null ||
        original.goodsReceiptId || reversal.goodsReceiptId ||
        original.productionOrderId || reversal.productionOrderId ||
        !original.quantity.isFinite() || !original.quantity.gt(0) ||
        !reversal.quantity.equals(original.quantity)
    ) {
        throw new BusinessRuleError('Pasangan mutasi pembalik pengiriman tidak valid.',
            { originalMovementId: original.id, reversalMovementId: reversal.id }, 'INVALID_SHIPMENT_REVERSAL');
    }
}

async function loadSource(
    original: StockMovement,
    tx: Prisma.TransactionClient,
    offBalanceSheet: boolean,
) {
    // Lock the financial source before reading its immutable posting vector.
    await tx.$queryRaw`SELECT id FROM "JournalEntry" WHERE "referenceId" = ${original.id} ORDER BY id FOR UPDATE`;
    const journals = await tx.journalEntry.findMany({
        where: { referenceId: original.id, status: { not: 'VOIDED' } },
        include: { lines: true },
    });
    if (journals.length === 0 && (original.cost?.equals(0) || offBalanceSheet)) return null;
    const journal = journals[0];
    if (journals.length !== 1 || journal.status !== 'POSTED' || !journal.isAutoGenerated ||
        journal.referenceType !== 'MANUAL_ENTRY' || journal.referenceId !== original.id) {
        throw new BusinessRuleError(
            'Jurnal asli pengiriman hilang atau ambigu. Minta finance memeriksa sumber sebelum membatalkan pengiriman.',
            { originalMovementId: original.id }, 'SHIPMENT_JOURNAL_UNRESOLVED',
        );
    }
    return journal;
}

function inverseLines(journal: SourceJournal) {
    const invalid = journal.lines.length < 2 || journal.lines.some(l =>
        !l.debit.isFinite() || !l.credit.isFinite() || l.debit.lt(0) || l.credit.lt(0) ||
        !l.currency.trim() || !l.exchangeRate.isFinite() || !l.exchangeRate.gt(0),
    );
    const debit = journal.lines.reduce((sum, l) => sum.add(l.debit), new Prisma.Decimal(0));
    const credit = journal.lines.reduce((sum, l) => sum.add(l.credit), new Prisma.Decimal(0));
    if (invalid || !debit.gt(0) || !debit.equals(credit)) {
        throw new BusinessRuleError('Nilai jurnal asli pengiriman tidak valid atau tidak seimbang.',
            { originalJournalId: journal.id }, 'INVALID_SHIPMENT_JOURNAL');
    }
    return journal.lines.map(l => ({
        accountId: l.accountId,
        debit: l.credit,
        credit: l.debit,
        currency: l.currency,
        exchangeRate: l.exchangeRate,
        description: `Reversal ${journal.entryNumber}: ${l.description ?? ''}`,
    }));
}

async function createInverse(
    source: SourceJournal,
    reversal: StockMovement,
    userId: string,
    tx: Prisma.TransactionClient,
) {
    const lines = inverseLines(source);
    const entryNumber = await generateEntryNumber(reversal.createdAt, tx);
    // Direct nested create preserves Decimal + currency/rate; the legacy general
    // createJournalEntry input currently only supports numeric IDR lines.
    return tx.journalEntry.create({ data: {
        entryNumber, entryDate: reversal.createdAt,
        description: `Shipment reversal of ${source.entryNumber}`,
        reference: reversal.reference ?? reversal.id,
        referenceType: 'MANUAL_ENTRY', referenceId: reversal.id,
        status: 'POSTED', isAutoGenerated: true,
        createdById: userId, approvedById: userId, approvedAt: new Date(),
        lines: { create: lines },
    } });
}

/** Caller owns the transaction and serializes cancellations on the delivery row. */
export async function recordShipmentReversal(
    original: StockMovement,
    reversal: StockMovement,
    userId: string,
    tx: Prisma.TransactionClient,
    options: { offBalanceSheet?: boolean } = {},
) {
    validatePair(original, reversal);
    await requireOpenJournalPeriod(tx, reversal.createdAt);
    const existing = await tx.journalEntry.findFirst({
        where: { referenceId: reversal.id, status: { not: 'VOIDED' } }, select: { id: true },
    });
    if (existing) {
        throw new BusinessRuleError('Jurnal pembalik pengiriman sudah ada.',
            { reversalMovementId: reversal.id }, 'ALREADY_REVERSED');
    }
    const source = await loadSource(original, tx, options.offBalanceSheet === true);
    if (!source) return null;
    const journal = await createInverse(source, reversal, userId, tx);
    await logActivity({
        userId, action: 'REVERSE_SHIPMENT_JOURNAL', entityType: 'JournalEntry', entityId: journal.id,
        details: `Exact inverse of ${source.entryNumber}; historical accounts, amounts and currency preserved.`,
        changes: { originalJournalId: source.id, originalMovementId: original.id, reversalMovementId: reversal.id },
        tx,
    });
    return journal;
}
