import { ReferenceType } from '@prisma/client';

export type CreateJournalEntryInput = {
    entryDate: Date;
    description: string;
    reference: string;
    referenceType?: ReferenceType;
    referenceId?: string;
    lines: {
        accountId: string;
        debit: number;
        credit: number;
        description?: string;
    }[];
    createdById?: string;
    isAutoGenerated?: boolean;
};
