import { randomUUID } from 'node:crypto';
import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('@/lib/core/prisma', async () => {
    const { PrismaClient } = await import('@prisma/client');
    const connection = process.env.BILL_SYNC_TEST_DATABASE_URL;
    if (!connection) return { prisma: undefined };
    const url = new URL(connection);
    if (url.hostname !== '127.0.0.1' || url.pathname !== '/polyflow_bill_sync_test') {
        throw new Error('Bill integration tests require disposable localhost polyflow_bill_sync_test');
    }
    return { prisma: new PrismaClient({ datasources: { db: { url: connection } } }) };
});
vi.mock('@/services/accounting/account-resolver', () => ({ resolveAccount: vi.fn() }));

import { prisma as db } from '@/lib/core/prisma';
import { resolveAccount } from '@/services/accounting/account-resolver';
import { createDraftBillFromPo } from '../invoices-service';

const date = new Date('2026-09-01T07:00:00Z');
const actor = 'bill-test-actor';
const control = ['accounts-payable', 'gr-clearing', 'vat-input'] as const;

async function seed() {
    const identity = await db.$queryRaw<{ db: string }[]>`SELECT current_database() db`;
    expect(identity[0].db).toBe('polyflow_bill_sync_test');
    await db.$executeRaw`TRUNCATE "AuditLog", "JournalLine", "JournalEntry", "Payment", "PurchaseInvoice", "GoodsReceiptItem", "GoodsReceipt", "PurchaseOrderItem", "PurchaseOrder", "Supplier", "ProductVariant", "Product", "Location", "Account", "FiscalPeriod", "SystemSequence", "User" CASCADE`;
    await db.user.create({ data: { id: actor, email: 'bill-test@example.invalid', password: randomUUID(), role: 'FINANCE' } });
    await db.account.createMany({ data: control.map((id, n) => ({ id, code: `test-${n}`, name: id, type: 'LIABILITY' as const, category: 'CURRENT_LIABILITY' as const })) });
    await db.fiscalPeriod.create({ data: { year: 2026, month: 9, name: 'Test September', startDate: date, endDate: new Date('2026-09-30T16:59:59Z'), status: 'OPEN' } });
    await db.systemSequence.create({ data: { key: 'JOURNAL_ENTRY_2026', value: 100 } });
    await db.supplier.create({ data: { id: 'supplier', name: 'Test supplier' } });
    await db.location.create({ data: { id: 'location', name: 'Test location', slug: 'test-location' } });
    await db.product.create({ data: { id: 'product', name: 'Test product', productType: 'RAW_MATERIAL' } });
    await db.productVariant.create({ data: { id: 'variant', productId: 'product', name: 'Test variant', skuCode: 'BILL-TEST', primaryUnit: 'KG' } });
    await db.purchaseOrder.create({ data: { id: 'po', orderNumber: 'PO-TEST', supplierId: 'supplier', status: 'PARTIAL_RECEIVED', totalAmount: 44400, taxAmount: 4400,
        items: { create: { id: 'po-item', productVariantId: 'variant', quantity: 4, unitPrice: 10000, subtotal: 40000, taxPercent: 11, ppnMode: 'EXCLUDE', receivedQty: 4 } } } });
    await db.goodsReceipt.create({ data: { id: 'gr', receiptNumber: 'GR-TEST', purchaseOrderId: 'po', locationId: 'location', receivedDate: date,
        items: { create: { id: 'gr-item', purchaseOrderItemId: 'po-item', productVariantId: 'variant', receivedQty: 4, unitCost: 10000 } } } });
    await db.purchaseInvoice.create({ data: { id: 'bill', invoiceNumber: 'BILL-TEST', purchaseOrderId: 'po', invoiceDate: date, status: 'UNPAID', totalAmount: 11100 } });
    await db.journalEntry.create({ data: { id: 'original', entryNumber: 'TEST-ORIGINAL', entryDate: date, description: 'Initial bill', reference: 'BILL-TEST', referenceType: 'PURCHASE_INVOICE', referenceId: 'bill', status: 'POSTED', isAutoGenerated: true,
        lines: { create: [{ accountId: control[0], credit: 11100 }, { accountId: control[1], debit: 10000 }, { accountId: control[2], debit: 1100 }] } } });
}

async function balances() {
    const lines = await db.journalLine.findMany({ where: { journalEntry: { referenceId: 'bill', referenceType: 'PURCHASE_INVOICE', status: 'POSTED' } } });
    return Object.fromEntries(control.map(id => [id, lines.filter(l => l.accountId === id).reduce((sum, l) => sum + Number(l.credit) - Number(l.debit), 0)]));
}

// Opt-in, independent of DATABASE_URL. No application/tenant DB may be used.
describe.skipIf(!process.env.BILL_SYNC_TEST_DATABASE_URL)('purchase bill sync on isolated PostgreSQL', () => {
    beforeEach(async () => {
        vi.mocked(resolveAccount).mockImplementation(async role => ({ id: role, code: role, name: role }));
        await seed();
    });
    afterAll(async () => { await db.$disconnect(); });

    it('GR resync preserves posted original and aligns AP, clearing and VAT', async () => {
        await createDraftBillFromPo('po', actor);
        expect(await balances()).toEqual({ 'accounts-payable': 44400, 'gr-clearing': -40000, 'vat-input': -4400 });
        expect(Number((await db.purchaseInvoice.findUniqueOrThrow({ where: { id: 'bill' } })).totalAmount)).toBe(44400);
        expect((await db.journalEntry.findUniqueOrThrow({ where: { id: 'original' }, include: { lines: true } })).lines.map(l => Number(l.debit) + Number(l.credit)).sort((a, b) => a - b)).toEqual([1100, 10000, 11100]);
        expect(await db.auditLog.count({ where: { entityId: 'bill' } })).toBeGreaterThan(0);
    });

    it('allocates unique bill numbers for concurrent receipts on different POs', async () => {
        await db.journalEntry.delete({ where: { id: 'original' } });
        await db.purchaseInvoice.delete({ where: { id: 'bill' } });
        await db.purchaseOrder.create({ data: { id: 'po-2', orderNumber: 'PO-SECOND', supplierId: 'supplier', status: 'RECEIVED', totalAmount: 44400, taxAmount: 4400 } });
        await Promise.all([createDraftBillFromPo('po', actor), createDraftBillFromPo('po-2', actor)]);
        const bills = await db.purchaseInvoice.findMany();
        expect(bills).toHaveLength(2);
        expect(new Set(bills.map(b => b.invoiceNumber)).size).toBe(2);
    });

    it('repeat and concurrent resync do not duplicate the correction', async () => {
        await Promise.all([createDraftBillFromPo('po', actor), createDraftBillFromPo('po', actor)]);
        const count = await db.journalEntry.count();
        await createDraftBillFromPo('po', actor);
        expect(await db.journalEntry.count()).toBe(count);
        expect(await balances()).toEqual({ 'accounts-payable': 44400, 'gr-clearing': -40000, 'vat-input': -4400 });
    });

    it('decreasing receipts and removing the final receipt reduce the same control balances', async () => {
        await createDraftBillFromPo('po', actor);
        await db.goodsReceiptItem.update({ where: { id: 'gr-item' }, data: { receivedQty: 0.5 } });
        await createDraftBillFromPo('po', actor);
        expect(await balances()).toEqual({ 'accounts-payable': 5550, 'gr-clearing': -5000, 'vat-input': -550 });
        await db.goodsReceipt.delete({ where: { id: 'gr' } });
        await createDraftBillFromPo('po', actor);
        expect(await balances()).toEqual({ 'accounts-payable': 0, 'gr-clearing': 0, 'vat-input': 0 });
        expect(Number((await db.purchaseInvoice.findUniqueOrThrow({ where: { id: 'bill' } })).totalAmount)).toBe(0);
    });

    it('closed source period rejects resync without changing bill, journal or audit', async () => {
        await db.fiscalPeriod.updateMany({ data: { status: 'CLOSED' } });
        await expect(createDraftBillFromPo('po', actor)).rejects.toThrow();
        expect(Number((await db.purchaseInvoice.findUniqueOrThrow({ where: { id: 'bill' } })).totalAmount)).toBe(11100);
        expect(await db.journalEntry.count()).toBe(1);
        expect(await db.auditLog.count()).toBe(0);
    });

    it('a real foreign-key failure rolls back every financial write', async () => {
        await expect(createDraftBillFromPo('po', 'missing-actor')).rejects.toThrow();
        expect(Number((await db.purchaseInvoice.findUniqueOrThrow({ where: { id: 'bill' } })).totalAmount)).toBe(11100);
        expect(await db.journalEntry.count()).toBe(1);
        expect(await db.auditLog.count()).toBe(0);
    });

    it('keeps a paid bill immutable and creates just one supplementary draft', async () => {
        await db.purchaseInvoice.update({ where: { id: 'bill' }, data: { status: 'PARTIAL', paidAmount: 1000 } });
        await createDraftBillFromPo('po', actor);
        const bills = await db.purchaseInvoice.findMany({ orderBy: { createdAt: 'asc' } });
        expect(bills).toHaveLength(2);
        expect(Number(bills[0].totalAmount)).toBe(11100);
        expect(bills[1].status).toBe('DRAFT');
        expect(Number(bills[1].totalAmount)).toBe(33300);
        await createDraftBillFromPo('po', actor);
        expect(await db.purchaseInvoice.count()).toBe(2);
        expect((await balances())['accounts-payable']).toBe(11100);
    });

    it('requires explicit correction if reduced GR would rewrite a paid bill', async () => {
        await db.purchaseInvoice.update({ where: { id: 'bill' }, data: { status: 'PARTIAL', paidAmount: 1000 } });
        await db.goodsReceiptItem.update({ where: { id: 'gr-item' }, data: { receivedQty: 0.5 } });
        await expect(createDraftBillFromPo('po', actor)).rejects.toThrow();
        expect(Number((await db.purchaseInvoice.findUniqueOrThrow({ where: { id: 'bill' } })).totalAmount)).toBe(11100);
    });

    it('forms a missing journal at the new amount in the same operation', async () => {
        await db.journalEntry.delete({ where: { id: 'original' } });
        await createDraftBillFromPo('po', actor);
        expect(await balances()).toEqual({ 'accounts-payable': 44400, 'gr-clearing': -40000, 'vat-input': -4400 });
    });
});
