import { getJournalById } from '@/actions/finance/journal';
import { getChartOfAccounts } from '@/actions/finance/accounting';
import { notFound, redirect } from 'next/navigation';
import ManualJournalForm from '@/components/finance/accounting/manual-journal-form';
import DetailJournalForm from '@/components/finance/accounting/detail-journal-form';
import {
    DETAIL_JOURNAL_TEMPLATES,
    type DetailJournalTemplateKey,
} from '@/lib/config/detail-journal-templates';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

interface EditJournalPageProps {
    params: Promise<{ id: string }>;
}

type JournalEntryData = NonNullable<
    Extract<
        Awaited<ReturnType<typeof getJournalById>>,
        { success: true }
    >['data']
>;
type JournalGlLine = JournalEntryData['lines'][number];
type JournalDetailRow = JournalEntryData['details'][number];

export default async function EditJournalPage({
    params,
}: EditJournalPageProps) {
    const { id } = await params;

    // Load journal
    const journalRes = await getJournalById(id);
    const journal: JournalEntryData | null =
        journalRes.success && journalRes.data ? journalRes.data : null;

    if (!journal) {
        notFound();
    }

    // Guard: only DRAFT non-auto journals can be edited
    if (journal.status !== 'DRAFT' || journal.isAutoGenerated) {
        redirect(`/finance/journals/${id}`);
    }

    // Load COA
    const accountsRes = await getChartOfAccounts();
    const accounts =
        accountsRes.success && accountsRes.data ? accountsRes.data : [];

    const hasDetails = journal.details && journal.details.length > 0;
    const detailType = hasDetails ? journal.details[0].type : null;
    const isKnownTemplate =
        detailType && detailType in DETAIL_JOURNAL_TEMPLATES;

    if (isKnownTemplate) {
        const template =
            DETAIL_JOURNAL_TEMPLATES[detailType as DetailJournalTemplateKey];

        // Infer direction by matching journal lines against template primaryCodes.
        const debitLine = journal.lines.find(
            (l: JournalGlLine) => Number(l.debit) > 0,
        );
        const creditLine = journal.lines.find(
            (l: JournalGlLine) => Number(l.credit) > 0,
        );

        // Resolve account codes from the two GL lines
        const debitAccount = debitLine
            ? accounts.find((a: { id: string }) => a.id === debitLine.accountId)
            : null;
        const creditAccount = creditLine
            ? accounts.find(
                  (a: { id: string }) => a.id === creditLine.accountId,
              )
            : null;

        const primaryCodes = template.primaryAccountCodes;

        // Direction: if debit-line account matches primary codes → OUTFLOW
        //            if credit-line account matches primary codes → INFLOW
        //            fallback: template.defaultDirection
        let direction: 'OUTFLOW' | 'INFLOW' = template.defaultDirection;
        if (debitAccount && primaryCodes.includes(debitAccount.code)) {
            direction = 'OUTFLOW';
        } else if (creditAccount && primaryCodes.includes(creditAccount.code)) {
            direction = 'INFLOW';
        }

        const defaultValues = {
            type: detailType as DetailJournalTemplateKey,
            entryDate: new Date(journal.entryDate),
            description: journal.description,
            reference: journal.reference || '',
            primaryAccountId:
                direction === 'OUTFLOW'
                    ? debitLine?.accountId || ''
                    : creditLine?.accountId || '',
            counterAccountId:
                direction === 'OUTFLOW'
                    ? creditLine?.accountId || ''
                    : debitLine?.accountId || '',
            direction,
            templateKey: detailType,
            details: journal.details.map((d: JournalDetailRow) => ({
                description: d.description,
                amount: Number(d.amount),
            })),
        };

        return (
            <div className="space-y-6">
                <div className="flex items-center gap-4">
                    <Link href={`/finance/journals/${id}`}>
                        <Button variant="outline" size="icon">
                            <ArrowLeft className="h-4 w-4" />
                        </Button>
                    </Link>
                    <div className="flex items-center gap-3">
                        <div>
                            <h1 className="text-2xl font-bold tracking-tight">
                                Edit Journal Entry #{journal.entryNumber}
                            </h1>
                            <p className="text-muted-foreground">
                                Ubah detail jurnal {template.label} sebelum
                                posting
                            </p>
                        </div>
                        <Badge variant="secondary">{journal.status}</Badge>
                    </div>
                </div>

                <DetailJournalForm
                    accounts={accounts}
                    mode="edit"
                    journalId={id}
                    defaultValues={defaultValues}
                />
            </div>
        );
    }

    // Default: render manual journal form
    const defaultValues = {
        entryDate: new Date(journal.entryDate),
        description: journal.description,
        reference: journal.reference || '',
        lines: journal.lines.map((line: JournalGlLine) => ({
            accountId: line.accountId,
            description: line.description || '',
            debit: Number(line.debit),
            credit: Number(line.credit),
        })),
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center gap-4">
                <Link href={`/finance/journals/${id}`}>
                    <Button variant="outline" size="icon">
                        <ArrowLeft className="h-4 w-4" />
                    </Button>
                </Link>
                <div className="flex items-center gap-3">
                    <div>
                        <h1 className="text-2xl font-bold tracking-tight">
                            Edit Journal Entry #{journal.entryNumber}
                        </h1>
                        <p className="text-muted-foreground">
                            Ubah detail jurnal sebelum posting
                        </p>
                    </div>
                    <Badge variant="secondary">{journal.status}</Badge>
                </div>
            </div>

            <ManualJournalForm
                accounts={accounts}
                mode="edit"
                journalId={id}
                defaultValues={defaultValues}
            />
        </div>
    );
}
