import { getJournalById } from '@/actions/finance/journal';
import { getChartOfAccounts } from '@/actions/finance/accounting';
import { notFound, redirect } from 'next/navigation';
import ManualJournalForm from '@/components/finance/accounting/manual-journal-form';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

interface EditJournalPageProps {
    params: Promise<{ id: string }>;
}

export default async function EditJournalPage({ params }: EditJournalPageProps) {
    const { id } = await params;

    // Load journal
    const journalRes = await getJournalById(id);
    const journal = journalRes.success && journalRes.data ? journalRes.data : null;

    if (!journal) {
        notFound();
    }

    // Guard: only DRAFT non-auto journals can be edited
    if (journal.status !== 'DRAFT' || journal.isAutoGenerated) {
        redirect(`/finance/journals/${id}`);
    }

    // Load COA
    const accountsRes = await getChartOfAccounts();
    const accounts = accountsRes.success && accountsRes.data ? accountsRes.data : [];

    // Prepare default values for the form
    const defaultValues = {
        entryDate: new Date(journal.entryDate),
        description: journal.description,
        reference: journal.reference || '',
        lines: journal.lines.map((line) => ({
            accountId: line.accountId,
            description: line.description || '',
            debit: Number(line.debit),
            credit: Number(line.credit),
        })),
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center gap-4">
                <Link href={`/finance/journals/${id}`}>
                    <Button variant="outline" size="icon">
                        <ArrowLeft className="h-4 w-4" />
                    </Button>
                </Link>
                <div className="flex items-center gap-3">
                    <div>
                        <h1 className="text-2xl font-bold tracking-tight">
                            Edit Journal Entry #{journal.entryNumber}
                        </h1>
                        <p className="text-muted-foreground">
                            Ubah detail jurnal sebelum posting
                        </p>
                    </div>
                    <Badge variant="secondary">{journal.status}</Badge>
                </div>
            </div>

            <ManualJournalForm
                accounts={accounts}
                mode="edit"
                journalId={id}
                defaultValues={defaultValues}
            />
        </div>
    );
}
