'use server';

import { manualJournalSchema, ManualJournalValues } from "@/lib/schemas/journal";
import { AccountingService } from "@/services/accounting-service";
import { ReferenceType, JournalStatus } from "@prisma/client";
import { requireAuth } from "@/lib/auth-checks";
import { revalidatePath } from "next/cache";
// ... (rest is same)

export async function createBulkJournals(entries: {
    entryDate: Date;
    description: string;
    reference: string;
    lines: { accountId: string; debit: number; credit: number; description: string }[]
}[]) {
    const session = await requireAuth();

    try {
        await AccountingService.createBulkJournalEntries(
            entries.map(e => ({
                ...e,
                referenceType: ReferenceType.MANUAL_ENTRY,
                createdById: session.user.id,
                isAutoGenerated: false
            }))
        );
        return { success: true, count: entries.length };
    } catch (error) {
        return { success: false, error: error instanceof Error ? error.message : "Bulk import failed" };
    }
}

export async function createManualJournal(data: ManualJournalValues) {
    const session = await requireAuth();

    // Validate Input
    const validation = manualJournalSchema.safeParse(data);
    if (!validation.success) {
        return { success: false, error: validation.error.issues[0].message };
    }

    try {
        await AccountingService.createJournalEntry({
            entryDate: data.entryDate,
            description: data.description,
            reference: data.reference ?? "",
            referenceType: ReferenceType.MANUAL_ENTRY,
            createdById: session.user.id,
            isAutoGenerated: false,
            lines: data.lines.map(l => ({
                accountId: l.accountId,
                debit: l.debit,
                credit: l.credit,
                description: l.description || data.description
            }))
        });

        return { success: true };
    } catch (error) {
        return { success: false, error: error instanceof Error ? error.message : "Failed to create journal" };
    }
}


export async function getJournals(params?: { startDate?: Date, endDate?: Date, status?: JournalStatus, reference?: string }) {
    await requireAuth();
    // Pass plain objects if needed, but Date is fine in Server Components usually,
    // though passing from Client might need conversion.
    // For now assuming Server Component usage mostly.
    return await AccountingService.getJournals(params);
}

export async function getJournalById(id: string) {
    await requireAuth();
    return await AccountingService.getJournalById(id);
}

export async function postJournal(id: string) {
    const session = await requireAuth();
    try {
        await AccountingService.postJournal(id, session.user.id);
        revalidatePath('/dashboard/accounting/journals');
        revalidatePath(`/dashboard/accounting/journals/${id}`);
        return { success: true };
    } catch (error) {
        return { success: false, error: error instanceof Error ? error.message : "Failed to post journal" };
    }
}

export async function voidJournal(id: string) {
    const session = await requireAuth();
    try {
        await AccountingService.voidJournal(id, session.user.id);
        revalidatePath('/dashboard/accounting/journals');
        revalidatePath(`/dashboard/accounting/journals/${id}`);
        return { success: true };
    } catch (error) {
        return { success: false, error: error instanceof Error ? error.message : "Failed to void journal" };
    }
}

export async function reverseJournal(id: string) {
    const session = await requireAuth();
    try {
        await AccountingService.reverseJournal(id, session.user.id);
        revalidatePath('/dashboard/accounting/journals');
        return { success: true };
    } catch (error) {
        return { success: false, error: error instanceof Error ? error.message : "Failed to reverse journal" };
    }
}
