/**
 * Reclassification Script: Move balances from misrouted 12xxx accounts to correct 113xx accounts
 *
 * Reclassifications:
 * 1. 12500 (Persediaan BJ Pack/Kresek) → 11330 (Finished Goods)
 * 2. 12310 (Persediaan Recycle Regrind) → 11310 (Raw Materials)
 * 3. 12400 (Persediaan WIP Roll Jumbo)  → 11320 (Work-in-Progress)
 *
 * After reclassification, deactivate the 12xxx inventory accounts.
 */
import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

async function getBalance(code: string, db: Prisma.TransactionClient | typeof prisma): Promise<{ id: string; name: string; balance: number }> {
    const account = await db.account.findUnique({
        where: { code },
        include: {
            journalLines: {
                where: { journalEntry: { status: 'POSTED' } },
                select: { debit: true, credit: true }
            }
        }
    });
    if (!account) throw new Error(`Account ${code} not found`);
    const balance = account.journalLines.reduce((s, l) => s + (Number(l.debit) - Number(l.credit)), 0);
    return { id: account.id, name: account.name, balance };
}

async function getAccountId(code: string, db: Prisma.TransactionClient | typeof prisma): Promise<string> {
    const acc = await db.account.findUnique({ where: { code } });
    if (!acc) throw new Error(`Account ${code} not found`);
    return acc.id;
}

async function generateEntryNumber(date: Date, db: Prisma.TransactionClient): Promise<string> {
    const year = date.getFullYear();
    const key = `JOURNAL_ENTRY_${year}`;
    try {
        const seq = await (db as any).systemSequence.update({
            where: { key },
            data: { value: { increment: 1 } }
        });
        const val = Number(seq.value) - 1;
        return `JE - ${year} -${val.toString().padStart(5, '0')}`;
    } catch {
        const latest = await prisma.journalEntry.findFirst({
            where: { entryDate: { gte: new Date(year, 0, 1), lt: new Date(year + 1, 0, 1) } },
            orderBy: { entryNumber: 'desc' }
        });
        let startValue = 1;
        if (latest?.entryNumber) {
            const parts = latest.entryNumber.split('-');
            const lastNum = parseInt(parts[parts.length - 1].trim(), 10);
            if (!isNaN(lastNum)) startValue = lastNum + 1;
        }
        const seq = await (db as any).systemSequence.upsert({
            where: { key },
            update: { value: { increment: 1 } },
            create: { key, value: BigInt(startValue + 1) }
        });
        const val = Number(seq.value) - 1;
        return `JE - ${year} -${val.toString().padStart(5, '0')}`;
    }
}

async function main() {
    console.log('=== Reclassification: 12xxx Inventory Accounts → 113xx ===\n');

    // 1. Check balances before
    const before12500 = await getBalance('12500', prisma);
    const before12310 = await getBalance('12310', prisma);
    const before12400 = await getBalance('12400', prisma);

    console.log('Current balances (BEFORE):');
    console.log(`  12500 ${before12500.name}: Rp ${before12500.balance.toLocaleString()}`);
    console.log(`  12310 ${before12310.name}: Rp ${before12310.balance.toLocaleString()}`);
    console.log(`  12400 ${before12400.name}: Rp ${before12400.balance.toLocaleString()}\n`);

    const reclassifications = [
        { from: '12500', to: '11330', balance: before12500.balance, label: 'Reclassify FG: 12500 → 11330' },
        { from: '12310', to: '11310', balance: before12310.balance, label: 'Reclassify RM: 12310 → 11310' },
        { from: '12400', to: '11320', balance: before12400.balance, label: 'Reclassify WIP: 12400 → 11320' },
    ];

    const entryDate = new Date('2026-02-19');

    for (const item of reclassifications) {
        if (Math.abs(item.balance) < 0.01) {
            console.log(`  SKIP: ${item.label} — balance is zero`);
            continue;
        }

        await prisma.$transaction(async (tx) => {
            const fromId = await getAccountId(item.from, tx);
            const toId = await getAccountId(item.to, tx);
            const entryNumber = await generateEntryNumber(entryDate, tx);

            await tx.journalEntry.create({
                data: {
                    entryNumber,
                    entryDate,
                    description: item.label,
                    reference: `RECLASS-${item.from}-TO-${item.to}`,
                    referenceType: 'MANUAL_ENTRY',
                    isAutoGenerated: false,
                    status: 'POSTED',
                    lines: {
                        create: [
                            {
                                accountId: toId,
                                debit: item.balance > 0 ? item.balance : 0,
                                credit: item.balance < 0 ? Math.abs(item.balance) : 0,
                                description: `Reclassification from ${item.from}: ${item.label}`
                            },
                            {
                                accountId: fromId,
                                debit: item.balance < 0 ? Math.abs(item.balance) : 0,
                                credit: item.balance > 0 ? item.balance : 0,
                                description: `Reclassification to ${item.to}: ${item.label}`
                            }
                        ]
                    }
                }
            });
        }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });

        console.log(`  ✅ ${item.label}: Rp ${item.balance.toLocaleString()} dipindahkan`);
    }

    // 3. Deactivate empty 12xxx inventory accounts
    const toDeactivate = ['12500', '12400', '12310', '12210', '12220', '12600', '12610', '12620', '12130'];
    console.log('\n--- Deactivating 12xxx inventory accounts ---');
    for (const code of toDeactivate) {
        const acc = await prisma.account.findUnique({ where: { code } });
        if (!acc) { console.log(`  SKIP: ${code} not found`); continue; }

        // Only deactivate if balance is now zero
        const bal = await getBalance(code, prisma);
        if (Math.abs(bal.balance) > 0.01) {
            console.log(`  SKIP: ${code} still has non-zero balance: Rp ${bal.balance.toLocaleString()}`);
            continue;
        }

        await prisma.account.update({
            where: { code },
            data: { isActive: false }
        });
        console.log(`  ✅ Deactivated: ${code} (${acc.name})`);
    }

    // 4. Verify final balances
    console.log('\n--- Final Balances (AFTER) ---');
    for (const code of ['11310', '11320', '11330', '12310', '12400', '12500']) {
        try {
            const b = await getBalance(code, prisma);
            console.log(`  ${code} ${b.name}: Rp ${b.balance.toLocaleString()}`);
        } catch {
            console.log(`  ${code}: not found`);
        }
    }

    await prisma.$disconnect();
    console.log('\n✅ Reclassification complete!');
}

main().catch(e => {
    console.error(e);
    process.exit(1);
});
