import { randomBytes } from 'node:crypto';
import { Prisma, type PrismaClient } from '@prisma/client';
import { guardedClient } from '../../finance/__tests__/finance-dry-run-postgres-fixture';

export function reversalTestClient() {
    return guardedClient(process.env.REVERSAL_TEST_DATABASE_URL, 'polyflow_reversal_test');
}
export const shippedAt = new Date('2026-08-18T06:00:00Z');
export const shipmentReference = 'Shipment for SO-FIXTURE via DO-FIXTURE';

export async function seedShipment(db: PrismaClient) {
    const [identity] = await db.$queryRaw<{ name: string }[]>`SELECT current_database() name`;
    if (identity.name !== 'polyflow_reversal_test') throw new Error('Disposable reversal database required');
    await db.$executeRaw`TRUNCATE "Account", "Product", "Location", "User", "SalesOrder", "FiscalPeriod", "SystemSequence" CASCADE`;
    await db.user.create({ data: { id: 'actor', email: 'reversal@example.invalid', password: randomBytes(24).toString('hex'), role: 'ADMIN' } });
    await db.account.createMany({ data: [
        { id: 'original-stock', code: 'STOCK', name: 'Original inventory', type: 'ASSET', category: 'CURRENT_ASSET' },
        { id: 'original-cogs', code: 'COGS', name: 'Original cost', type: 'EXPENSE', category: 'COGS' },
        { id: 'current-stock', code: 'NEW-STOCK', name: 'Current inventory mapping', type: 'ASSET', category: 'CURRENT_ASSET' },
        { id: 'current-cogs', code: 'NEW-COGS', name: 'Current cost mapping', type: 'EXPENSE', category: 'COGS' },
        { id: 'wip', code: 'WIP', name: 'WIP', type: 'ASSET', category: 'CURRENT_ASSET' },
    ] });
    await db.product.create({ data: { id: 'product', name: 'Synthetic finished item', productType: 'FINISHED_GOOD',
        inventoryAccountId: 'current-stock', cogsAccountId: 'current-cogs', wipAccountId: 'wip' } });
    await db.productVariant.create({ data: { id: 'variant', productId: 'product', name: 'Synthetic variant', skuCode: 'REV-FIXTURE', primaryUnit: 'KG', standardCost: 99999 } });
    await db.location.create({ data: { id: 'warehouse', name: 'Fixture warehouse', slug: 'reversal-fixture' } });
    await db.inventory.create({ data: { id: 'inventory', locationId: 'warehouse', productVariantId: 'variant', quantity: 10, averageCost: 100 } });
    await db.salesOrder.create({ data: { id: 'order', orderNumber: 'SO-FIXTURE', status: 'SHIPPED', totalAmount: 1000,
        items: { create: { id: 'order-line', productVariantId: 'variant', quantity: '37.5', deliveredQty: '37.5', unitPrice: 10, subtotal: 375 } } } });
    await db.deliveryOrder.create({ data: { id: 'delivery', orderNumber: 'DO-FIXTURE', salesOrderId: 'order',
        sourceLocationId: 'warehouse', status: 'SHIPPED', stockCommittedAt: shippedAt,
        items: { create: { id: 'delivery-line', productVariantId: 'variant', quantity: '37.5' } } } });
    await db.stockMovement.create({ data: { id: 'original-move', type: 'OUT', productVariantId: 'variant',
        fromLocationId: 'warehouse', quantity: '37.5', cost: null, reference: shipmentReference,
        salesOrderId: 'order', createdAt: shippedAt } });
    await db.invoice.create({ data: { id: 'invoice', invoiceNumber: 'INV-FIXTURE', salesOrderId: 'order', invoiceDate: shippedAt, status: 'DRAFT', totalAmount: 1000 } });
    await db.stockReservation.create({ data: { id: 'reservation', productVariantId: 'variant', locationId: 'warehouse',
        quantity: '37.5', reservedFor: 'SALES_ORDER', referenceId: 'order', status: 'FULFILLED' } });
    const now = new Date();
    const currentWib = new Date(now.getTime() + 7 * 60 * 60 * 1000);
    const periods = [{ year: 2026, month: 8 }, { year: currentWib.getUTCFullYear(), month: currentWib.getUTCMonth() + 1 }];
    for (const p of periods.filter((p, i) => periods.findIndex(x => x.year === p.year && x.month === p.month) === i)) {
        await db.fiscalPeriod.create({ data: { ...p, name: `Fixture ${p.year}-${p.month}`, status: 'OPEN',
            startDate: new Date(Date.UTC(p.year, p.month - 1, 1)), endDate: new Date(Date.UTC(p.year, p.month, 1)) } });
    }
    await db.systemSequence.create({ data: { key: `JOURNAL_ENTRY_${currentWib.getUTCFullYear()}`, value: BigInt(1) } });
    await db.journalEntry.create({ data: { id: 'source-journal', entryNumber: 'SOURCE-FIXTURE', entryDate: shippedAt,
        description: 'Historical shipment valuation', reference: shipmentReference, referenceType: 'MANUAL_ENTRY',
        referenceId: 'original-move', status: 'POSTED', isAutoGenerated: true,
        lines: { create: [
            { id: 'cogs-line', accountId: 'original-cogs', debit: new Prisma.Decimal('420.45'), credit: 0 },
            { id: 'stock-line', accountId: 'original-stock', debit: 0, credit: new Prisma.Decimal('420.45') },
        ] } } });
}
