import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { Prisma } from '@prisma/client';

vi.mock('@/lib/core/prisma', async () => {
    const { reversalTestClient } = await import('./shipment-reversal-postgres-fixture');
    const client = reversalTestClient();
    return { prisma: client, getTenantDbFromContext: () => client };
});
import { prisma as db } from '@/lib/core/prisma';
import { reverseDeliveryShipment } from '../delivery-reversal-service';
import { seedShipment } from './shipment-reversal-postgres-fixture';
import { databaseFingerprint } from '../../finance/__tests__/finance-dry-run-postgres-fixture';

const reverse = () => reverseDeliveryShipment('delivery', 'actor', 'Synthetic cancellation before delivery');
async function source() {
    return db.journalEntry.findUniqueOrThrow({ where: { id: 'source-journal' }, include: { lines: { orderBy: { id: 'asc' } } } });
}
async function assertNeutral() {
    const balances = await db.journalLine.groupBy({ by: ['accountId'], _sum: { debit: true, credit: true } });
    expect(balances.length).toBe(2);
    for (const b of balances) expect(b._sum.debit?.minus(b._sum.credit ?? 0).isZero()).toBe(true);
    expect(await db.journalLine.count({ where: { accountId: { in: ['wip', 'current-stock', 'current-cogs'] } } })).toBe(0);
}

describe.skipIf(!process.env.REVERSAL_TEST_DATABASE_URL)('shipment cancellation workflow on isolated PostgreSQL', () => {
    beforeEach(async () => { await seedShipment(db); });
    afterAll(async () => { await db?.$disconnect(); });

    it('reverses the complete workflow at original cost/accounts when current mapping and cost differ', async () => {
        const before = await source();
        expect(await reverse()).toEqual({ success: true, reversedLines: 1 });
        expect(await source()).toEqual(before);
        await assertNeutral();
        expect((await db.inventory.findUniqueOrThrow({ where: { id: 'inventory' } })).quantity.toString()).toBe('47.5');
        expect(await db.deliveryOrder.findUnique({ where: { id: 'delivery' } })).toMatchObject({ status: 'CANCELLED', stockCommittedAt: null });
        expect(await db.invoice.findUnique({ where: { id: 'invoice' } })).toMatchObject({ status: 'CANCELLED' });
        expect(await db.salesOrder.findUnique({ where: { id: 'order' } })).toMatchObject({ status: 'READY_TO_SHIP' });
        expect((await db.salesOrderItem.findUniqueOrThrow({ where: { id: 'order-line' } })).deliveredQty.toString()).toBe('0');
        expect(await db.stockReservation.findUnique({ where: { id: 'reservation' } })).toMatchObject({ status: 'ACTIVE' });
        const returned = await db.stockMovement.findFirstOrThrow({ where: { type: 'IN' } });
        const journal = await db.journalEntry.findFirstOrThrow({ where: { referenceId: returned.id } });
        expect(journal).toMatchObject({ status: 'POSTED', isAutoGenerated: true, createdById: 'actor' });
        expect(await db.auditLog.count({ where: { action: 'REVERSE_SHIPMENT_JOURNAL', entityId: journal.id } })).toBe(1);
        expect(await db.auditLog.count({ where: { action: 'REVERSE_DELIVERY_SHIPMENT' } })).toBe(1);
    });

    it('rejects a partial movement set with the full database fingerprint unchanged', async () => {
        await db.productVariant.create({ data: {
            id: 'variant-2', productId: 'product', name: 'Second variant',
            skuCode: 'REV-SECOND', primaryUnit: 'KG',
        } });
        await db.salesOrderItem.create({ data: {
            id: 'order-line-2', salesOrderId: 'order', productVariantId: 'variant-2',
            quantity: 20, deliveredQty: 20, unitPrice: 10, subtotal: 200,
        } });
        await db.deliveryOrderItem.create({ data: {
            deliveryOrderId: 'delivery', productVariantId: 'variant-2', quantity: 20,
        } });
        const before = await databaseFingerprint(db);
        await expect(reverse()).rejects.toThrow(/mutasi.*pengiriman/i);
        expect(await databaseFingerprint(db)).toEqual(before);
    });

    it.each(['wrong quantity', 'wrong location', 'wrong direction'])('keeps the database unchanged for %s', async kind => {
        if (kind === 'wrong quantity') await db.stockMovement.update({ where: { id: 'original-move' }, data: { quantity: '37.4999' } });
        if (kind === 'wrong direction') await db.stockMovement.update({ where: { id: 'original-move' }, data: { type: 'IN' } });
        if (kind === 'wrong location') {
            await db.location.create({ data: { id: 'other-warehouse', name: 'Other warehouse', slug: 'other-reversal-fixture' } });
            await db.stockMovement.update({ where: { id: 'original-move' }, data: { fromLocationId: 'other-warehouse' } });
        }
        const before = await databaseFingerprint(db);
        await expect(reverse()).rejects.toThrow(/mutasi.*pengiriman/i);
        expect(await databaseFingerprint(db)).toEqual(before);
    });

    it('aggregates repeated SKU rows without losing delivered quantity or original journal value', async () => {
        await db.deliveryOrderItem.update({ where: { id: 'delivery-line' }, data: { quantity: '12.1' } });
        await db.deliveryOrderItem.create({ data: { deliveryOrderId: 'delivery', productVariantId: 'variant', quantity: '25.4' } });
        await db.stockMovement.update({ where: { id: 'original-move' }, data: { quantity: '12.1' } });
        await db.stockMovement.create({ data: {
            id: 'second-move', type: 'OUT', productVariantId: 'variant', fromLocationId: 'warehouse',
            quantity: '25.4', salesOrderId: 'order', reference: 'Shipment for SO-FIXTURE via DO-FIXTURE',
        } });
        await db.journalEntry.create({ data: {
            entryNumber: 'SECOND-SOURCE', entryDate: new Date(), description: 'Second source',
            referenceType: 'MANUAL_ENTRY', referenceId: 'second-move', status: 'POSTED', isAutoGenerated: true,
            lines: { create: [
                { accountId: 'original-cogs', debit: '100.10', credit: 0 },
                { accountId: 'original-stock', debit: 0, credit: '100.10' },
            ] },
        } });
        expect(await reverse()).toEqual({ success: true, reversedLines: 2 });
        expect((await db.salesOrderItem.findUniqueOrThrow({ where: { id: 'order-line' } })).deliveredQty.toString()).toBe('0');
        expect((await db.inventory.findUniqueOrThrow({ where: { id: 'inventory' } })).quantity.toString()).toBe('47.5');
        await assertNeutral();
        expect(await db.journalEntry.count()).toBe(4);
    });

    it.each(['extra variant', 'extra IN', 'ambiguous SO'])('rejects %s with no database changes', async kind => {
        if (kind === 'ambiguous SO') {
            await db.salesOrderItem.create({ data: {
                salesOrderId: 'order', productVariantId: 'variant', quantity: 10,
                deliveredQty: 0, unitPrice: 10, subtotal: 100,
            } });
        } else {
            await db.productVariant.create({ data: {
                id: 'extra-variant', productId: 'product', name: 'Extra variant',
                skuCode: 'REV-EXTRA', primaryUnit: 'KG',
            } });
            await db.stockMovement.create({ data: {
                type: kind === 'extra IN' ? 'IN' : 'OUT', productVariantId: 'extra-variant',
                fromLocationId: 'warehouse', quantity: 1, cost: 0, salesOrderId: 'order',
                reference: 'Shipment for SO-FIXTURE via DO-FIXTURE',
            } });
        }
        const before = await databaseFingerprint(db);
        await expect(reverse()).rejects.toThrow(/mutasi.*pengiriman|atribusi.*ambigu/i);
        expect(await databaseFingerprint(db)).toEqual(before);
    });

    it('preserves source currency and rate in real persisted reversal lines', async () => {
        await db.journalLine.updateMany({ where: { journalEntryId: 'source-journal' }, data: { currency: 'USD', exchangeRate: new Prisma.Decimal('16234.567891') } });
        await reverse();
        const journal = await db.journalEntry.findFirstOrThrow({ where: { id: { not: 'source-journal' } }, include: { lines: true } });
        expect(journal.lines.every(l => l.currency === 'USD' && l.exchangeRate.equals('16234.567891'))).toBe(true);
        await assertNeutral();
    });

    it('serializes concurrent requests so inventory and journals are reversed once', async () => {
        const outcomes = await Promise.allSettled([reverse(), reverse()]);
        expect(outcomes.filter(r => r.status === 'fulfilled')).toHaveLength(1);
        expect(outcomes.filter(r => r.status === 'rejected')).toHaveLength(1);
        expect(await db.stockMovement.count()).toBe(2);
        expect(await db.journalEntry.count()).toBe(2);
        expect((await db.inventory.findUniqueOrThrow({ where: { id: 'inventory' } })).quantity.toString()).toBe('47.5');
        await assertNeutral();
    });

    it('does not cancel an invoice when a concurrent payment commits first', async () => {
        await db.invoice.update({ where: { id: 'invoice' }, data: { status: 'UNPAID' } });
        const { cancellation } = await db.$transaction(async tx => {
            await tx.$queryRaw`SELECT id FROM "Invoice" WHERE id = 'invoice' FOR UPDATE`;
            await tx.payment.create({ data: { paymentNumber: 'PAY-RACE', paymentDate: new Date(),
                invoiceId: 'invoice', method: 'Cash', amount: 1000 } });
            await tx.invoice.update({ where: { id: 'invoice' }, data: { status: 'PAID', paidAmount: 1000 } });
            const cancellation = reverse().then(
                value => ({ status: 'fulfilled' as const, value }),
                reason => ({ status: 'rejected' as const, reason }),
            );
            await vi.waitFor(async () => {
                const [state] = await db.$queryRaw<{ blocked: number }[]>`SELECT count(*)::int blocked FROM pg_stat_activity
                    WHERE datname = current_database() AND wait_event_type = 'Lock' AND query LIKE '%Invoice%'`;
                expect(state.blocked).toBeGreaterThan(0);
            }, { timeout: 3000, interval: 20 });
            return { cancellation };
        });
        expect((await cancellation).status).toBe('rejected');
        expect(await db.invoice.findUnique({ where: { id: 'invoice' } })).toMatchObject({ status: 'PAID' });
        expect(await db.deliveryOrder.findUnique({ where: { id: 'delivery' } })).toMatchObject({ status: 'SHIPPED' });
        expect(await db.stockMovement.count()).toBe(1);
        expect((await db.inventory.findUniqueOrThrow({ where: { id: 'inventory' } })).quantity.toString()).toBe('10');
    });

    it.each(['source', 'posting'])('waits for concurrent %s-period closing before cancelling', async periodKind => {
        const wib = new Date(Date.now() + 7 * 60 * 60 * 1000);
        const period = periodKind === 'source' ? { year: 2026, month: 8 }
            : { year: wib.getUTCFullYear(), month: wib.getUTCMonth() + 1 };
        const { cancellation } = await db.$transaction(async tx => {
            await tx.fiscalPeriod.updateMany({ where: period, data: { status: 'CLOSED' } });
            const settled = vi.fn();
            const cancellation = reverse().then(
                value => ({ status: 'fulfilled' as const, value }),
                reason => ({ status: 'rejected' as const, reason }),
            ).finally(settled);
            await vi.waitFor(async () => {
                const [state] = await db.$queryRaw<{ blocked: number }[]>`SELECT count(*)::int blocked FROM pg_stat_activity
                    WHERE datname = current_database() AND wait_event_type = 'Lock' AND query LIKE '%FiscalPeriod%'`;
                expect(settled.mock.calls.length > 0 || state.blocked > 0).toBe(true);
            }, { timeout: 3000, interval: 20 });
            return { cancellation };
        });
        expect((await cancellation).status).toBe('rejected');
        expect(await db.stockMovement.count()).toBe(1);
        expect(await db.deliveryOrder.findUnique({ where: { id: 'delivery' } })).toMatchObject({ status: 'SHIPPED' });
    });

    it('rejects replay without any further database changes', async () => {
        await reverse();
        const before = await databaseFingerprint(db);
        await expect(reverse()).rejects.toThrow(/SHIPPED/);
        expect(await databaseFingerprint(db)).toEqual(before);
    });

    it.each(['missing', 'ambiguous', 'draft'])('rolls back stock and movement creation for %s accounting source', async kind => {
        if (kind === 'missing') await db.journalEntry.delete({ where: { id: 'source-journal' } });
        if (kind === 'draft') await db.journalEntry.update({ where: { id: 'source-journal' }, data: { status: 'DRAFT' } });
        if (kind === 'ambiguous') await db.journalEntry.create({ data: {
            entryNumber: 'DUPLICATE-SOURCE', entryDate: new Date(), description: 'Ambiguous fixture',
            referenceType: 'MANUAL_ENTRY', referenceId: 'original-move', isAutoGenerated: true, status: 'POSTED',
        } });
        const before = await databaseFingerprint(db);
        await expect(reverse()).rejects.toThrow(/jurnal asli/i);
        expect(await databaseFingerprint(db)).toEqual(before);
    });

    it('rolls back the entire workflow when the journal audit INSERT fails', async () => {
        await db.$executeRaw`CREATE FUNCTION reversal_test_fail_audit() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                IF NEW.action = 'REVERSE_SHIPMENT_JOURNAL' THEN RAISE EXCEPTION 'TEST_AUDIT_FAILURE'; END IF;
                RETURN NEW;
            END $$`;
        await db.$executeRaw`CREATE TRIGGER reversal_test_audit_guard BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION reversal_test_fail_audit()`;
        try {
            const before = await databaseFingerprint(db);
            await expect(reverse()).rejects.toThrow(/TEST_AUDIT_FAILURE/);
            expect(await databaseFingerprint(db)).toEqual(before);
        } finally {
            await db.$executeRaw`DROP TRIGGER reversal_test_audit_guard ON "AuditLog"`;
            await db.$executeRaw`DROP FUNCTION reversal_test_fail_audit()`;
        }
    });

    it('allows explicit zero-cost source without inventing a current-price journal', async () => {
        await db.journalEntry.delete({ where: { id: 'source-journal' } });
        await db.stockMovement.update({ where: { id: 'original-move' }, data: { cost: 0 } });
        await reverse();
        expect(await db.journalEntry.count()).toBe(0);
        expect((await db.inventory.findUniqueOrThrow({ where: { id: 'inventory' } })).quantity.toString()).toBe('47.5');
    });

    it('allows explicit off-balance maklon without inventing owned-inventory accounting', async () => {
        await db.journalEntry.delete({ where: { id: 'source-journal' } });
        await db.salesOrder.update({ where: { id: 'order' }, data: { orderType: 'MAKLON_JASA' } });
        await reverse();
        expect(await db.journalEntry.count()).toBe(0);
        expect(await db.deliveryOrder.findUnique({ where: { id: 'delivery' } })).toMatchObject({ status: 'CANCELLED' });
    });

    it('rolls back cancellation when the current posting period is CLOSED', async () => {
        await db.fiscalPeriod.updateMany({ data: { status: 'CLOSED' } });
        const before = await databaseFingerprint(db);
        await expect(reverse()).rejects.toThrow(/CLOSED|periode/i);
        expect(await databaseFingerprint(db)).toEqual(before);
    });
});
