import {afterAll,beforeEach,describe,expect,it} from 'vitest';
import {DeliveryStatus,PrismaClient} from '@prisma/client';
import {queryDeliveryOrdersPage} from '../deliveries';
import {returnTestClient,verifyReturnTestDatabase} from '@/services/finance/__tests__/return-credit-postgres-fixture';
const connection=process.env.RETURN_CREDIT_TEST_DATABASE_URL;const db=connection?returnTestClient(connection):null;const otherUrl=connection?new URL(connection):null;if(otherUrl)otherUrl.pathname='/polyflow_return_credit_tenant_test';const other=otherUrl?returnTestClient(otherUrl.toString()):null;
async function seed(client:PrismaClient,prefix:string){await verifyReturnTestDatabase(client);await client.$executeRaw`TRUNCATE "DeliveryOrderItem", "DeliveryOrder", "SalesOrderItem", "SalesOrder", "Customer", "Location", "User" CASCADE`;await client.user.create({data:{id:prefix+'-user',email:prefix+'@example.invalid',password:'synthetic-only',role:'SALES'}});await client.customer.create({data:{id:prefix+'-customer',name:prefix+' Customer'}});await client.location.create({data:{id:prefix+'-location',name:prefix+' Warehouse',slug:prefix+'-warehouse'}});await client.salesOrder.create({data:{id:prefix+'-order',orderNumber:prefix+'-SO',customerId:prefix+'-customer',sourceLocationId:prefix+'-location',status:'CONFIRMED'}});const statuses=Object.values(DeliveryStatus);await client.deliveryOrder.createMany({data:Array.from({length:51},(_,i)=>({id:prefix+'-do-'+i,orderNumber:prefix+'-SJ-'+String(i).padStart(3,'0'),salesOrderId:prefix+'-order',sourceLocationId:prefix+'-location',createdById:prefix+'-user',deliveryDate:new Date(i<2?'2026-08-01T00:00:00Z':'2026-10-'+String((i%28)+1).padStart(2,'0')+'T00:00:00Z'),status:i<2?(i===0?'PENDING':'LOADING'):statuses[i%statuses.length]}))});}
const query={startDate:new Date('2026-10-01T00:00:00Z'),endDate:new Date('2026-10-31T23:59:59Z'),page:1,pageSize:25,sort:'orderNumber' as const,direction:'asc' as const};
describe.skipIf(!db)('delivery list PostgreSQL contract',()=>{beforeEach(async()=>{await Promise.all([seed(db!,'tenant-a'),seed(other!,'tenant-b')])});afterAll(async()=>{await Promise.all([db?.$disconnect(),other?.$disconnect()])});
 it('keeps open drafts outside range and rows/total/counts consistent without N+1 queries',async()=>{const queries:string[]=[];const result=await queryDeliveryOrdersPage(db!,query,name=>queries.push(name));expect(queries.sort()).toEqual(['counts','customers','items','locations','total']);expect(result.meta).toMatchObject({page:1,pageSize:25,totalPages:3});expect(result.meta.total).toBe(51);expect(result.items).toHaveLength(25);expect(result.statusCounts.PENDING).toBeGreaterThan(0);expect(result.statusCounts.LOADING).toBeGreaterThan(0);expect(result.items.some(r=>r.id==='tenant-a-do-0')).toBe(true);expect(Object.values(result.statusCounts).reduce((a,b)=>a+b,0)).toBe(51);});
 it('paginates a stable sort without missing or duplicate rows',async()=>{const pages=[] as string[];for(const page of [1,2,3]){const result=await queryDeliveryOrdersPage(db!,{...query,page});pages.push(...result.items.map(row=>row.id));}expect(new Set(pages).size).toBe(51);expect(pages).toHaveLength(51);});
 it('isolates results by the supplied tenant client',async()=>{const [a,b]=await Promise.all([queryDeliveryOrdersPage(db!,query),queryDeliveryOrdersPage(other!,query)]);expect(a.items.every(row=>row.id.startsWith('tenant-a-'))).toBe(true);expect(b.items.every(row=>row.id.startsWith('tenant-b-'))).toBe(true);});
});
