"use server";

import { withTenant } from "@/lib/core/tenant";
import {
  manualJournalSchema,
  ManualJournalValues,
  directLaborJournalSchema,
  DirectLaborJournalValues,
  detailJournalSchema,
  DetailJournalValues,
} from "@/lib/schemas/journal";
import { AccountingService } from "@/services/accounting/accounting-service";
import { ReferenceType, JournalStatus } from "@prisma/client";
import { requireAuth } from "@/lib/tools/auth-checks";
import { revalidatePath } from "next/cache";
import { hasAnyRole } from "@/lib/auth/roles";
import { logActivity } from "@/lib/tools/audit";
import {
  safeAction,
  BusinessRuleError,
  ValidationError,
} from "@/lib/errors/errors";

export const createBulkJournals = withTenant(async function createBulkJournals(
  entries: {
    entryDate: Date;
    description: string;
    reference: string;
    lines: {
      accountId: string;
      debit: number;
      credit: number;
      description: string;
    }[];
  }[],
) {
  return safeAction(async () => {
    const session = await requireAuth();

    try {
      await AccountingService.createBulkJournalEntries(
        entries.map((e) => ({
          ...e,
          referenceType: ReferenceType.MANUAL_ENTRY,
          createdById: session.user.id,
          isAutoGenerated: false,
        })),
      );
      return { count: entries.length };
    } catch (error) {
      throw new BusinessRuleError(
        error instanceof Error ? error.message : "Bulk import failed",
      );
    }
  });
});

export const createManualJournal = withTenant(
  async function createManualJournal(
    data: ManualJournalValues,
    post: boolean = false,
  ) {
    return safeAction(async () => {
      const session = await requireAuth();

      // Validate Input
      const validation = manualJournalSchema.safeParse(data);
      if (!validation.success) {
        throw new ValidationError(validation.error.issues[0].message);
      }

      try {
        const result = await AccountingService.createJournalEntry({
          entryDate: data.entryDate,
          description: data.description,
          reference: data.reference ?? "",
          referenceType: ReferenceType.MANUAL_ENTRY,
          createdById: session.user.id,
          isAutoGenerated: false,
          lines: data.lines.map((l) => ({
            accountId: l.accountId,
            debit: l.debit,
            credit: l.credit,
            description: l.description || data.description,
          })),
        });

        if (post && result.id) {
          await AccountingService.postJournal(result.id, session.user.id);
        }

        await logActivity({
          userId: session.user.id,
          action: post ? "CREATE_AND_POST_JOURNAL" : "CREATE_JOURNAL",
          entityType: "JournalEntry",
          entityId: result.id,
          details: `Created manual journal ${result.entryNumber}`,
        });

        revalidatePath("/finance/journals");
        revalidatePath("/finance/reports/balance-sheet");
        revalidatePath("/finance/reports/trial-balance");

        return {
          message: `Journal entry created ${post ? "and posted " : ""}successfully`,
        };
      } catch (error) {
        throw new BusinessRuleError(
          error instanceof Error ? error.message : "Failed to create journal",
        );
      }
    });
  },
);

export const getJournals = withTenant(async function getJournals(params?: {
  startDate?: Date;
  endDate?: Date;
  status?: JournalStatus;
  reference?: string;
  page?: number;
  limit?: number;
}) {
  return safeAction(async () => {
    await requireAuth();
    return await AccountingService.getJournals(params);
  });
});

export const getJournalById = withTenant(async function getJournalById(
  id: string,
) {
  return safeAction(async () => {
    await requireAuth();
    return await AccountingService.getJournalById(id);
  });
});

export const postJournal = withTenant(async function postJournal(id: string) {
  return safeAction(async () => {
    const session = await requireAuth();
    try {
      await AccountingService.postJournal(id, session.user.id);

      await logActivity({
        userId: session.user.id,
        action: "POST_JOURNAL",
        entityType: "JournalEntry",
        entityId: id,
        details: `Posted journal entry`,
      });

      revalidatePath("/finance/journals");
      revalidatePath(`/finance/journals/${id}`);
      return { message: "Journal posted successfully" };
    } catch (error) {
      throw new BusinessRuleError(
        error instanceof Error ? error.message : "Failed to post journal",
      );
    }
  });
});

export const voidJournal = withTenant(async function voidJournal(id: string) {
  return safeAction(async () => {
    const session = await requireAuth();
    if (!hasAnyRole(session.user, ["ADMIN", "FINANCE"])) {
      throw new BusinessRuleError(
        "Only ADMIN or FINANCE roles can void journal entries",
      );
    }
    try {
      await AccountingService.voidJournal(id, session.user.id);

      await logActivity({
        userId: session.user.id,
        action: "VOID_JOURNAL",
        entityType: "JournalEntry",
        entityId: id,
        details: `Voided journal entry`,
      });

      revalidatePath("/finance/journals");
      revalidatePath(`/finance/journals/${id}`);
      return { message: "Journal voided successfully" };
    } catch (error) {
      throw new BusinessRuleError(
        error instanceof Error ? error.message : "Failed to void journal",
      );
    }
  });
});

export const reverseJournal = withTenant(async function reverseJournal(
  id: string,
) {
  return safeAction(async () => {
    const session = await requireAuth();
    if (!hasAnyRole(session.user, ["ADMIN", "FINANCE"])) {
      throw new BusinessRuleError(
        "Only ADMIN or FINANCE roles can reverse journal entries",
      );
    }
    try {
      await AccountingService.reverseJournal(id, session.user.id);

      await logActivity({
        userId: session.user.id,
        action: "REVERSE_JOURNAL",
        entityType: "JournalEntry",
        entityId: id,
        details: `Reversed journal entry`,
      });

      revalidatePath("/finance/journals");
      return { message: "Journal reversed successfully" };
    } catch (error) {
      throw new BusinessRuleError(
        error instanceof Error ? error.message : "Failed to reverse journal",
      );
    }
  });
});

export const updateManualJournal = withTenant(
  async function updateManualJournal(
    id: string,
    data: ManualJournalValues,
    post: boolean = false,
  ) {
    return safeAction(async () => {
      const session = await requireAuth();

      // Validate Input
      const validation = manualJournalSchema.safeParse(data);
      if (!validation.success) {
        throw new ValidationError(validation.error.issues[0].message);
      }

      try {
        const result = await AccountingService.updateDraftJournal(
          id,
          {
            entryDate: data.entryDate,
            description: data.description,
            reference: data.reference ?? "",
            lines: data.lines.map((l) => ({
              accountId: l.accountId,
              debit: l.debit,
              credit: l.credit,
              description: l.description || data.description,
            })),
          },
          session.user.id,
        );

        if (post && result?.id) {
          await AccountingService.postJournal(result.id, session.user.id);
        }

        await logActivity({
          userId: session.user.id,
          action: post ? "UPDATE_AND_POST_JOURNAL" : "UPDATE_DRAFT_JOURNAL",
          entityType: "JournalEntry",
          entityId: id,
          details: `Updated draft journal ${result?.entryNumber}`,
        });

        revalidatePath("/finance/journals");
        revalidatePath(`/finance/journals/${id}`);
        revalidatePath("/finance/reports/balance-sheet");
        revalidatePath("/finance/reports/trial-balance");

        return {
          message: `Journal entry updated ${post ? "and posted " : ""}successfully`,
        };
      } catch (error) {
        throw new BusinessRuleError(
          error instanceof Error ? error.message : "Failed to update journal",
        );
      }
    });
  },
);

// --- Direct Labor Journal Actions ---

export const createDirectLaborJournalAction = withTenant(
  async function createDirectLaborJournalAction(
    data: DirectLaborJournalValues,
    post: boolean = false,
  ) {
    return safeAction(async () => {
      const session = await requireAuth();

      // Validate Input
      const validation = directLaborJournalSchema.safeParse(data);
      if (!validation.success) {
        throw new ValidationError(validation.error.issues[0].message);
      }

      try {
        const result = await AccountingService.createDirectLaborJournal(
          {
            entryDate: data.entryDate,
            description: data.description,
            reference: data.reference ?? "",
            debitAccountId: data.debitAccountId,
            creditAccountId: data.creditAccountId,
            details: data.details,
          },
          session.user.id,
        );

        if (post && result?.id) {
          await AccountingService.postJournal(result.id, session.user.id);
        }

        await logActivity({
          userId: session.user.id,
          action: post
            ? "CREATE_AND_POST_DIRECT_LABOR_JOURNAL"
            : "CREATE_DIRECT_LABOR_JOURNAL",
          entityType: "JournalEntry",
          entityId: result?.id ?? "",
          details: `Created direct labor journal ${result?.entryNumber}`,
        });

        revalidatePath("/finance/journals");
        revalidatePath("/finance/reports/balance-sheet");
        revalidatePath("/finance/reports/trial-balance");

        return {
          message: `Direct labor journal ${post ? "created and posted" : "saved as draft"} successfully`,
          id: result?.id,
        };
      } catch (error) {
        throw new BusinessRuleError(
          error instanceof Error
            ? error.message
            : "Failed to create direct labor journal",
        );
      }
    });
  },
);

export const updateDirectLaborJournalAction = withTenant(
  async function updateDirectLaborJournalAction(
    id: string,
    data: DirectLaborJournalValues,
    post: boolean = false,
  ) {
    return safeAction(async () => {
      const session = await requireAuth();

      // Validate Input
      const validation = directLaborJournalSchema.safeParse(data);
      if (!validation.success) {
        throw new ValidationError(validation.error.issues[0].message);
      }

      try {
        const result = await AccountingService.updateDirectLaborJournal(
          id,
          {
            entryDate: data.entryDate,
            description: data.description,
            reference: data.reference ?? "",
            debitAccountId: data.debitAccountId,
            creditAccountId: data.creditAccountId,
            details: data.details,
          },
          session.user.id,
        );

        if (post && result?.id) {
          await AccountingService.postJournal(result.id, session.user.id);
        }

        await logActivity({
          userId: session.user.id,
          action: post
            ? "UPDATE_AND_POST_DIRECT_LABOR_JOURNAL"
            : "UPDATE_DIRECT_LABOR_JOURNAL",
          entityType: "JournalEntry",
          entityId: id,
          details: `Updated direct labor journal ${result?.entryNumber}`,
        });

        revalidatePath("/finance/journals");
        revalidatePath(`/finance/journals/${id}`);
        revalidatePath("/finance/reports/balance-sheet");
        revalidatePath("/finance/reports/trial-balance");

        return {
          message: `Direct labor journal ${post ? "updated and posted" : "updated"} successfully`,
        };
      } catch (error) {
        throw new BusinessRuleError(
          error instanceof Error
            ? error.message
            : "Failed to update direct labor journal",
        );
      }
    });
  },
);

// --- Generic Detail Journal Actions (template-driven) ---

export const createDetailJournalAction = withTenant(
  async function createDetailJournalAction(
    data: DetailJournalValues,
    post: boolean = false,
  ) {
    return safeAction(async () => {
      const session = await requireAuth();

      // Validate Input
      const validation = detailJournalSchema.safeParse(data);
      if (!validation.success) {
        throw new ValidationError(validation.error.issues[0].message);
      }

      try {
        const result = await AccountingService.createDetailJournal(
          {
            type: data.type,
            entryDate: data.entryDate,
            description: data.description,
            reference: data.reference ?? "",
            primaryAccountId: data.primaryAccountId,
            counterAccountId: data.counterAccountId,
            direction: data.direction,
            details: data.details,
          },
          session.user.id,
        );

        if (post && result?.id) {
          await AccountingService.postJournal(result.id, session.user.id);
        }

        await logActivity({
          userId: session.user.id,
          action: post
            ? "CREATE_AND_POST_DETAIL_JOURNAL"
            : "CREATE_DETAIL_JOURNAL",
          entityType: "JournalEntry",
          entityId: result?.id ?? "",
          details: `Created detail journal (${data.type}) ${result?.entryNumber}`,
        });

        revalidatePath("/finance/journals");
        revalidatePath("/finance/reports/balance-sheet");
        revalidatePath("/finance/reports/trial-balance");

        return {
          message: `Jurnal detail ${post ? "created and posted" : "saved as draft"} successfully`,
          id: result?.id,
        };
      } catch (error) {
        throw new BusinessRuleError(
          error instanceof Error
            ? error.message
            : "Failed to create detail journal",
        );
      }
    });
  },
);

export const updateDetailJournalAction = withTenant(
  async function updateDetailJournalAction(
    id: string,
    data: DetailJournalValues,
    post: boolean = false,
  ) {
    return safeAction(async () => {
      const session = await requireAuth();

      // Validate Input
      const validation = detailJournalSchema.safeParse(data);
      if (!validation.success) {
        throw new ValidationError(validation.error.issues[0].message);
      }

      try {
        const result = await AccountingService.updateDetailJournal(
          id,
          {
            type: data.type,
            entryDate: data.entryDate,
            description: data.description,
            reference: data.reference ?? "",
            primaryAccountId: data.primaryAccountId,
            counterAccountId: data.counterAccountId,
            direction: data.direction,
            details: data.details,
          },
          session.user.id,
        );

        if (post && result?.id) {
          await AccountingService.postJournal(result.id, session.user.id);
        }

        await logActivity({
          userId: session.user.id,
          action: post
            ? "UPDATE_AND_POST_DETAIL_JOURNAL"
            : "UPDATE_DETAIL_JOURNAL",
          entityType: "JournalEntry",
          entityId: id,
          details: `Updated detail journal (${data.type}) ${result?.entryNumber}`,
        });

        revalidatePath("/finance/journals");
        revalidatePath(`/finance/journals/${id}`);
        revalidatePath("/finance/reports/balance-sheet");
        revalidatePath("/finance/reports/trial-balance");

        return {
          message: `Jurnal detail ${post ? "updated and posted" : "updated"} successfully`,
        };
      } catch (error) {
        throw new BusinessRuleError(
          error instanceof Error
            ? error.message
            : "Failed to update detail journal",
        );
      }
    });
  },
);

export const closePeriod = withTenant(async function closePeriod(
  periodEndDate: Date,
) {
  return safeAction(async () => {
    const session = await requireAuth();
    if (!hasAnyRole(session.user, ["ADMIN", "FINANCE"])) {
      throw new BusinessRuleError(
        "Only ADMIN or FINANCE roles can close fiscal periods",
      );
    }
    try {
      const result = await AccountingService.closePeriod(
        periodEndDate,
        session.user.id,
      );

      await logActivity({
        userId: session.user.id,
        action: "CLOSE_PERIOD",
        entityType: "JournalEntry",
        entityId: result.entryNumber,
        details: `Closed period ${result.period}: Revenue ${result.totalRevenue}, Expenses ${result.totalExpense}, Net Income ${result.netIncome}`,
      });

      revalidatePath("/finance/reports/balance-sheet");
      revalidatePath("/finance/reports/income-statement");
      revalidatePath("/finance/journals");

      return result;
    } catch (error) {
      throw new BusinessRuleError(
        error instanceof Error ? error.message : "Failed to close period",
      );
    }
  });
});
