import {
    AccountCategory,
    AccountType,
    InvoiceStatus,
    JournalStatus,
    Prisma,
    PurchaseInvoiceStatus,
    PurchaseOrderStatus,
    ReferenceType,
    SalesOrderStatus,
    SalesOrderType,
} from '@prisma/client';

import { prisma } from '@/lib/core/prisma';
import { BusinessRuleError } from '@/lib/errors/errors';
import { AccountingService } from '@/services/accounting/accounting-service';

import {
    AP_ACCOUNT_CODE,
    AR_ACCOUNT_CODE,
    CreateOpeningBalanceInput,
    OPENING_BALANCE_ACCOUNT_CODE,
    UnifiedMakeOpeningBalanceInput,
} from './opening-balance-types';

export async function assertNoDuplicateOpeningBalanceEntries(data: UnifiedMakeOpeningBalanceInput) {
    for (const entry of data.arEntries) {
        const [existingInvoice, existingSO] = await Promise.all([
            prisma.invoice.findFirst({ where: { invoiceNumber: entry.invoiceNumber } }),
            prisma.salesOrder.findFirst({ where: { orderNumber: `SO-OPEN-${entry.invoiceNumber}` } })
        ]);

        if (existingInvoice || existingSO) {
            throw new BusinessRuleError(`Customer Invoice #${entry.invoiceNumber} (or its placeholder SO) already exists. Please delete the previous entry or use a different number.`);
        }
    }

    for (const entry of data.apEntries) {
        const [existingBill, existingPO] = await Promise.all([
            prisma.purchaseInvoice.findFirst({ where: { invoiceNumber: entry.invoiceNumber } }),
            prisma.purchaseOrder.findFirst({ where: { orderNumber: `PO-OPEN-${entry.invoiceNumber}` } })
        ]);

        if (existingBill || existingPO) {
            throw new BusinessRuleError(`Supplier Bill #${entry.invoiceNumber} (or its placeholder PO) already exists. Please delete the previous entry or use a different number.`);
        }
    }
}

export async function ensureOpeningBalanceEquityAccount(db: Prisma.TransactionClient | typeof prisma) {
    const existingAccount = await db.account.findUnique({ where: { code: OPENING_BALANCE_ACCOUNT_CODE } });
    if (existingAccount) return existingAccount;

    if ('$transaction' in db) {
        return db.account.create({
            data: {
                code: OPENING_BALANCE_ACCOUNT_CODE,
                name: 'Opening Balance Equity',
                type: AccountType.EQUITY,
                category: AccountCategory.CAPITAL,
                description: 'System account for initial balance setup'
            }
        });
    }

    return db.account.upsert({
        where: { code: OPENING_BALANCE_ACCOUNT_CODE },
        update: {},
        create: {
            code: OPENING_BALANCE_ACCOUNT_CODE,
            name: 'Opening Balance Equity',
            type: AccountType.EQUITY,
            category: AccountCategory.CAPITAL,
            description: 'System account for initial balance setup'
        }
    });
}

export async function getSubLedgerAccountOrThrow(
    db: Prisma.TransactionClient | typeof prisma,
    type: 'AR' | 'AP'
) {
    const code = type === 'AR' ? AR_ACCOUNT_CODE : AP_ACCOUNT_CODE;
    const account = await db.account.findUnique({ where: { code } });
    if (!account) throw new Error(`${type} Account ${code} not found.`);
    return account;
}

export async function createAROpeningBalance(
    data: CreateOpeningBalanceInput,
    userId: string,
    equityAccountId: string,
    arAccountId: string,
    tx?: Prisma.TransactionClient
) {
    const db = tx || prisma;

    const salesOrder = await db.salesOrder.create({
        data: {
            orderNumber: `SO-OPEN-${data.invoiceNumber}`,
            customerId: data.entityId,
            orderDate: data.date,
            status: SalesOrderStatus.DELIVERED,
            orderType: SalesOrderType.MAKE_TO_STOCK,
            totalAmount: data.amount,
            notes: 'Opening Balance Entry',
            createdById: userId,
        }
    });

    const invoice = await db.invoice.create({
        data: {
            invoiceNumber: data.invoiceNumber,
            salesOrderId: salesOrder.id,
            invoiceDate: data.date,
            dueDate: data.dueDate,
            status: InvoiceStatus.UNPAID,
            totalAmount: data.amount,
            notes: data.notes || 'Opening Balance Transfer',
            termOfPaymentDays: 0,
        }
    });

    await AccountingService.createJournalEntry({
        entryDate: data.date,
        description: `Opening Balance AR - Inv #${data.invoiceNumber}`,
        reference: data.invoiceNumber,
        referenceType: ReferenceType.SALES_INVOICE,
        referenceId: invoice.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        createdById: userId,
        lines: [
            {
                accountId: arAccountId,
                debit: data.amount,
                credit: 0,
                description: 'Opening Balance Receivable'
            },
            {
                accountId: equityAccountId,
                debit: 0,
                credit: data.amount,
                description: 'Opening Equity Offset'
            }
        ]
    }, db);

    return invoice;
}

export async function createAPOpeningBalance(
    data: CreateOpeningBalanceInput,
    userId: string,
    equityAccountId: string,
    apAccountId: string,
    tx?: Prisma.TransactionClient
) {
    const db = tx || prisma;

    const purchaseOrder = await db.purchaseOrder.create({
        data: {
            orderNumber: `PO-OPEN-${data.invoiceNumber}`,
            supplierId: data.entityId,
            orderDate: data.date,
            status: PurchaseOrderStatus.RECEIVED,
            totalAmount: data.amount,
            notes: 'Opening Balance Entry',
            createdById: userId,
        }
    });

    const invoice = await db.purchaseInvoice.create({
        data: {
            invoiceNumber: data.invoiceNumber,
            purchaseOrderId: purchaseOrder.id,
            invoiceDate: data.date,
            dueDate: data.dueDate,
            status: PurchaseInvoiceStatus.UNPAID,
            totalAmount: data.amount,
            notes: data.notes || 'Opening Balance Transfer',
        }
    });

    await AccountingService.createJournalEntry({
        entryDate: data.date,
        description: `Opening Balance AP - Inv #${data.invoiceNumber}`,
        reference: data.invoiceNumber,
        referenceType: ReferenceType.PURCHASE_INVOICE,
        referenceId: invoice.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        createdById: userId,
        lines: [
            {
                accountId: equityAccountId,
                debit: data.amount,
                credit: 0,
                description: 'Opening Equity Offset'
            },
            {
                accountId: apAccountId,
                debit: 0,
                credit: data.amount,
                description: 'Opening Balance Payable'
            }
        ]
    }, db);

    return invoice;
}

export async function postGeneralOpeningBalanceJournal(
    data: UnifiedMakeOpeningBalanceInput,
    equityAccountId: string,
    userId: string,
    tx: Prisma.TransactionClient
) {
    const nonZeroLines = data.generalLines.filter(line => line.debit > 0 || line.credit > 0);
    const generalDebit = data.generalLines.reduce((sum, line) => sum + line.debit, 0);
    const generalCredit = data.generalLines.reduce((sum, line) => sum + line.credit, 0);
    const generalOffset = generalDebit - generalCredit;

    if (nonZeroLines.length === 0 && Math.abs(generalOffset) <= 0.01) {
        return;
    }

    const journalLines = nonZeroLines.map(line => ({
        accountId: line.accountId,
        debit: line.debit,
        credit: line.credit,
        description: 'Opening Balance'
    }));

    if (Math.abs(generalOffset) > 0.01) {
        journalLines.push({
            accountId: equityAccountId,
            debit: generalOffset < 0 ? Math.abs(generalOffset) : 0,
            credit: generalOffset > 0 ? generalOffset : 0,
            description: 'Opening Balance Equity (General Offset)'
        });
    }

    const journal = await AccountingService.createJournalEntry({
        entryDate: data.date,
        description: `General Opening Balance - ${data.date.toISOString().split('T')[0]}`,
        reference: 'OPENING-GEN',
        referenceType: ReferenceType.MANUAL_ENTRY,
        isAutoGenerated: true,
        createdById: userId,
        lines: journalLines,
    }, tx);

    await AccountingService.postJournal(journal.id, userId, tx);
}