'use server';

import { prisma } from '@/lib/prisma';
import { requireAuth } from '@/lib/auth-checks';
import { AccountingService } from '@/services/accounting-service';
import { InvoiceStatus, PurchaseInvoiceStatus, ReferenceType, AccountType, AccountCategory, SalesOrderType, SalesOrderStatus, PurchaseOrderStatus } from '@prisma/client';
import { revalidatePath } from 'next/cache';

const OPENING_BALANCE_ACCOUNT_CODE = '30000';
const AR_ACCOUNT_CODE = '11210';
const AP_ACCOUNT_CODE = '21110';

interface CreateOpeningBalanceInput {
    type: 'AR' | 'AP'; // AR = Piutang (Customer), AP = Hutang (Supplier)
    entityId: string; // CustomerId or SupplierId
    invoiceNumber: string;
    date: Date;
    dueDate: Date;
    amount: number;
    notes?: string;
}

export async function createOpeningBalance(data: CreateOpeningBalanceInput) {
    const session = await requireAuth();

    try {
        // 1. Ensure "Opening Balance Equity" account exists
        let equityAccount = await prisma.account.findUnique({ where: { code: OPENING_BALANCE_ACCOUNT_CODE } });
        if (!equityAccount) {
            equityAccount = await prisma.account.create({
                data: {
                    code: OPENING_BALANCE_ACCOUNT_CODE,
                    name: 'Opening Balance Equity',
                    type: AccountType.EQUITY,
                    category: AccountCategory.CAPITAL,
                    description: 'System account for initial balance setup'
                }
            });
        }

        // 2. Get AR/AP Account
        const subLedgerAccountCode = data.type === 'AR' ? AR_ACCOUNT_CODE : AP_ACCOUNT_CODE;
        const subLedgerAccount = await prisma.account.findUnique({ where: { code: subLedgerAccountCode } });
        if (!subLedgerAccount) throw new Error(`Sub-ledger account ${subLedgerAccountCode} not found.`);

        // 3. Create Record
        if (data.type === 'AR') {
            await createAROpeningBalance(data, session.user.id, equityAccount.id, subLedgerAccount.id);
        } else {
            await createAPOpeningBalance(data, session.user.id, equityAccount.id, subLedgerAccount.id);
        }

        revalidatePath('/finance');
        return { success: true };
    } catch (error) {
        console.error('Opening Balance Error:', error);
        return { success: false, error: error instanceof Error ? error.message : 'Failed to create opening balance' };
    }
}

async function createAROpeningBalance(data: CreateOpeningBalanceInput, userId: string, equityAccountId: string, arAccountId: string) {
    // 3a. Create Dummy Sales Order (Use transaction to ensure atomicity if needed, but keeping simple for now)
    const salesOrder = await prisma.salesOrder.create({
        data: {
            orderNumber: `SO-OPEN-${data.invoiceNumber}`,
            customerId: data.entityId,
            orderDate: data.date,
            status: SalesOrderStatus.DELIVERED, // Mark as delivered so it doesn't show up in pending lists
            orderType: SalesOrderType.MAKE_TO_STOCK, // Generic
            totalAmount: data.amount,
            notes: 'Opening Balance Entry',
            createdById: userId,
            // Create a dummy item to satisfy constraints if necessary, or leave empty if schema allows
            // items: { create: [] } 
        }
    });

    // 3b. Create Invoice
    const invoice = await prisma.invoice.create({
        data: {
            invoiceNumber: data.invoiceNumber, // Keep original external invoice number
            salesOrderId: salesOrder.id,
            invoiceDate: data.date,
            dueDate: data.dueDate,
            status: InvoiceStatus.UNPAID,
            totalAmount: data.amount,
            notes: data.notes || 'Opening Balance Transfer',
            termOfPaymentDays: 0, // already calculated manually
        }
    });

    // 3c. Create Journal Entry (Override Auto-Journal)
    // Dr AR, Cr Opening Balance Equity
    await AccountingService.createJournalEntry({
        entryDate: data.date,
        description: `Opening Balance AR - Inv #${data.invoiceNumber}`,
        reference: data.invoiceNumber,
        referenceType: ReferenceType.SALES_INVOICE,
        referenceId: invoice.id,
        isAutoGenerated: true, // System generated but manual logic
        createdById: userId,
        lines: [
            {
                accountId: arAccountId,
                debit: data.amount,
                credit: 0,
                description: `Opening Balance Receivable`
            },
            {
                accountId: equityAccountId,
                debit: 0,
                credit: data.amount,
                description: `Opening Equity Offset`
            }
        ]
    });
}

async function createAPOpeningBalance(data: CreateOpeningBalanceInput, userId: string, equityAccountId: string, apAccountId: string) {
    // 3a. Create Dummy Purchase Order
    const purchaseOrder = await prisma.purchaseOrder.create({
        data: {
            orderNumber: `PO-OPEN-${data.invoiceNumber}`,
            supplierId: data.entityId,
            orderDate: data.date,
            status: PurchaseOrderStatus.RECEIVED,
            totalAmount: data.amount,
            notes: 'Opening Balance Entry',
            createdById: userId,
        }
    });

    // 3b. Create Purchase Invoice
    const invoice = await prisma.purchaseInvoice.create({
        data: {
            invoiceNumber: data.invoiceNumber,
            purchaseOrderId: purchaseOrder.id,
            invoiceDate: data.date,
            dueDate: data.dueDate,
            status: PurchaseInvoiceStatus.UNPAID,
            totalAmount: data.amount,
            notes: data.notes || 'Opening Balance Transfer',
        }
    });

    // 3c. Create Journal Entry
    // Dr Opening Balance Equity, Cr AP
    await AccountingService.createJournalEntry({
        entryDate: data.date,
        description: `Opening Balance AP - Inv #${data.invoiceNumber}`,
        reference: data.invoiceNumber,
        referenceType: ReferenceType.PURCHASE_INVOICE,
        referenceId: invoice.id,
        isAutoGenerated: true,
        createdById: userId,
        lines: [
            {
                accountId: equityAccountId,
                debit: data.amount,
                credit: 0,
                description: `Opening Equity Offset`
            },
            {
                accountId: apAccountId,
                debit: 0,
                credit: data.amount,
                description: `Opening Balance Payable`
            }
        ]
    });
}
