import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("@/lib/core/prisma", () => ({
  prisma: {
    salesReturn: { findUnique: vi.fn() },
    purchaseReturn: { findUnique: vi.fn() },
  },
}));

vi.mock("@/services/accounting/accounting-service", () => ({
  AccountingService: {
    createJournalEntry: vi.fn().mockResolvedValue({ id: "je-1" }),
  },
}));

vi.mock("@/services/finance/auto-journal-shared", () => ({
  getAccountByRole: vi.fn(),
}));

import { prisma } from "@/lib/core/prisma";
import { AccountingService } from "@/services/accounting/accounting-service";
import { getAccountByRole } from "@/services/finance/auto-journal-shared";
import {
  handleSalesReturnReceived,
  handlePurchaseReturnShipped,
} from "@/services/finance/auto-journal-return-handlers";

const mockAccount = (id: string) => ({ id, code: "11100", name: "Test" });

/** Create a Prisma Decimal-like mock that works with Number() and .toNumber() */
function dec(value: number) {
  return {
    toNumber: () => value,
    [Symbol.toPrimitive]: () => value,
  };
}

describe("auto-journal-return-handlers", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("handleSalesReturnReceived", () => {
    it("returns early when sales return not found", async () => {
      vi.mocked(prisma.salesReturn.findUnique).mockResolvedValue(null);

      await handleSalesReturnReceived("ret-1");

      expect(AccountingService.createJournalEntry).not.toHaveBeenCalled();
    });

    it("returns early when totalAmount is null", async () => {
      vi.mocked(prisma.salesReturn.findUnique).mockResolvedValue({
        id: "ret-1",
        totalAmount: null,
        items: [],
        customer: {},
      } as never);

      await handleSalesReturnReceived("ret-1");

      expect(AccountingService.createJournalEntry).not.toHaveBeenCalled();
    });

    it("creates journal entry for sales return without good items", async () => {
      vi.mocked(prisma.salesReturn.findUnique).mockResolvedValue({
        id: "ret-1",
        returnNumber: "SR-001",
        returnDate: new Date("2026-01-15"),
        totalAmount: dec(500),
        items: [
          {
            condition: "DAMAGED",
            returnedQty: dec(10),
            unitPrice: dec(50),
          },
        ],
        customer: { name: "Customer A" },
      } as never);
      vi.mocked(getAccountByRole).mockImplementation(
        async (role: string) => mockAccount(`acc-${role}`) as never,
      );

      await handleSalesReturnReceived("ret-1");

      expect(AccountingService.createJournalEntry).toHaveBeenCalledTimes(1);
      const call = vi.mocked(AccountingService.createJournalEntry).mock
        .calls[0][0] as Record<string, unknown>;
      expect(call.isAutoGenerated).toBe(true);
      expect(call.status).toBe("POSTED");
      expect((call.lines as unknown[]).length).toBe(2);
    });

    it("adds restock lines for GOOD condition items", async () => {
      vi.mocked(prisma.salesReturn.findUnique).mockResolvedValue({
        id: "ret-2",
        returnNumber: "SR-002",
        returnDate: new Date("2026-01-15"),
        totalAmount: dec(1000),
        items: [
          {
            condition: "GOOD",
            returnedQty: dec(10),
            unitPrice: dec(100),
          },
        ],
        customer: { name: "Customer B" },
      } as never);
      vi.mocked(getAccountByRole).mockImplementation(
        async (role: string) => mockAccount(`acc-${role}`) as never,
      );

      await handleSalesReturnReceived("ret-2");

      const call = vi.mocked(AccountingService.createJournalEntry).mock
        .calls[0][0] as Record<string, unknown>;
      expect((call.lines as unknown[]).length).toBe(4);
    });
  });

  describe("handlePurchaseReturnShipped", () => {
    it("returns early when purchase return not found", async () => {
      vi.mocked(prisma.purchaseReturn.findUnique).mockResolvedValue(null);

      await handlePurchaseReturnShipped("ret-1");

      expect(AccountingService.createJournalEntry).not.toHaveBeenCalled();
    });

    it("returns early when totalAmount is null", async () => {
      vi.mocked(prisma.purchaseReturn.findUnique).mockResolvedValue({
        id: "ret-1",
        totalAmount: null,
        items: [],
        supplier: {},
      } as never);

      await handlePurchaseReturnShipped("ret-1");

      expect(AccountingService.createJournalEntry).not.toHaveBeenCalled();
    });

    it("creates journal entry for purchase return", async () => {
      vi.mocked(prisma.purchaseReturn.findUnique).mockResolvedValue({
        id: "ret-3",
        returnNumber: "PR-001",
        returnDate: new Date("2026-01-15"),
        totalAmount: dec(750),
        items: [],
        supplier: { name: "Supplier A" },
      } as never);
      vi.mocked(getAccountByRole).mockImplementation(
        async (role: string) => mockAccount(`acc-${role}`) as never,
      );

      await handlePurchaseReturnShipped("ret-3");

      expect(AccountingService.createJournalEntry).toHaveBeenCalledTimes(1);
      const call = vi.mocked(AccountingService.createJournalEntry).mock
        .calls[0][0] as Record<string, unknown>;
      expect(call.isAutoGenerated).toBe(true);
      expect(call.status).toBe("POSTED");
      expect((call.lines as unknown[]).length).toBe(2);
    });
  });
});
