import { PrismaClient } from '@prisma/client';

export function barterTestClient(connection: string | undefined, database: string) {
    if (!connection) throw new Error('Explicit BARTER_TEST_DATABASE_URL required');
    const url = new URL(connection);
    if (!['postgres:', 'postgresql:'].includes(url.protocol) || url.hostname !== '127.0.0.1' || !url.port ||
        url.pathname !== `/${database}` || !['polyflow_barter_test', 'polyflow_barter_test_2'].includes(database) ||
        [...url.searchParams.keys()].some(k => !['connection_limit', 'application_name'].includes(k))) {
        throw new Error('Only explicitly ported disposable localhost barter databases are allowed');
    }
    return new PrismaClient({ datasources: { db: { url: connection } } });
}
export async function verifyDisposable(db: PrismaClient, database: string) {
    const [identity] = await db.$queryRaw<{ name: string; recovery: boolean }[]>`SELECT current_database() name, pg_is_in_recovery() recovery`;
    if (identity.name !== database || identity.recovery) throw new Error('Wrong disposable database identity');
    const marker = await db.$queryRaw<{ purpose: string }[]>`SELECT purpose FROM "BarterDisposableMarker"`;
    if (marker.length !== 1 || marker[0].purpose !== 'barter-integration-disposable') throw new Error('Disposable marker missing');
}
export const actor = 'barter-test-actor';
export const date = new Date('2026-09-09T00:00:00+07:00');
export async function resetFixture(db: PrismaClient, database: string) {
    await verifyDisposable(db, database);
    await db.$executeRaw`TRUNCATE "BarterSettlement", "BarterPartner", "AuditLog", "JournalLine", "JournalEntry", "Payment", "Invoice", "PurchaseInvoice", "SalesOrder", "PurchaseOrder", "Customer", "Supplier", "Account", "FiscalPeriod", "SystemSequence", "User" CASCADE`;
    await db.user.create({ data: { id: actor, email: 'barter@example.invalid', password: 'test-only', role: 'FINANCE' } });
    await db.customer.create({ data: { id: 'customer', name: 'Fixture Partner' } });
    await db.supplier.create({ data: { id: 'supplier', name: 'Fixture Partner' } });
    await db.barterPartner.create({ data: { id: 'partner', customerId: 'customer', supplierId: 'supplier', isActive: true, createdById: actor, updatedById: actor } });
    await db.account.createMany({ data: [
        { id: 'ar', code: '11210', name: 'AR', type: 'ASSET', category: 'CURRENT_ASSET' },
        { id: 'ap', code: '21100', name: 'AP', type: 'LIABILITY', category: 'CURRENT_LIABILITY' },
        { id: 'cash', code: '11100', name: 'Cash', type: 'ASSET', category: 'CURRENT_ASSET', isCashAccount: true },
        { id: 'revenue', code: '41100', name: 'Revenue', type: 'REVENUE', category: 'OPERATING_REVENUE' },
    ] });
    await db.fiscalPeriod.create({ data: { name: 'September', year: 2026, month: 9, status: 'OPEN', startDate: new Date('2026-09-01'), endDate: new Date('2026-09-30') } });
    await db.systemSequence.create({ data: { key: 'JOURNAL_ENTRY_2026', value: 100 } });
    await db.salesOrder.create({ data: { id: 'so', orderNumber: 'SO-TEST', customerId: 'customer', totalAmount: 600 } });
    await db.purchaseOrder.create({ data: { id: 'po', orderNumber: 'PO-TEST', supplierId: 'supplier', totalAmount: 1000 } });
    await db.invoice.create({ data: { id: 'ar-invoice', invoiceNumber: 'AR-TEST', salesOrderId: 'so', totalAmount: 600, status: 'UNPAID', invoiceDate: date } });
    await db.purchaseInvoice.create({ data: { id: 'ap-invoice', invoiceNumber: 'AP-TEST', purchaseOrderId: 'po', totalAmount: 1000, status: 'UNPAID', invoiceDate: date } });
    for (const side of ['ar', 'ap']) await db.journalEntry.create({ data: {
        id: `${side}-journal`, entryNumber: `${side}-journal`, entryDate: date, description: 'Fixture recognition',
        referenceType: side === 'ar' ? 'SALES_INVOICE' : 'PURCHASE_INVOICE', referenceId: `${side}-invoice`, status: side === 'ar' ? 'DRAFT' : 'POSTED', isAutoGenerated: true,
        lines: { create: side === 'ar' ? [{ accountId: 'ar', debit: 600, credit: 0 }, { accountId: 'revenue', debit: 0, credit: 600 }] : [{ accountId: 'revenue', debit: 1000, credit: 0 }, { accountId: 'ap', debit: 0, credit: 1000 }] },
    } });
}
