import { randomUUID } from 'node:crypto';
import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { returnTestClient, resetReturnFixture, actor, date } from './return-credit-postgres-fixture';
vi.mock('@/services/accounting/account-resolver', () => ({ resolveAccount: async(role: string) => ({id: role==='customer-credit'?'liability':role==='accounts-receivable'?'ar':role==='vat-output'?'vat':'return'}) }));
import { tenantContext } from '@/lib/core/prisma';
import { issueCustomerCredit } from '../customer-credit-issue-service';
import { applyCustomerCredit, reverseCustomerCreditApplication, reverseCustomerCreditNote } from '../customer-credit-application-service';
import { approveCustomerCreditLink, revokeCustomerCreditLink } from '../customer-credit-link-service';
import { getCustomerCreditDetail, getCustomerCreditTargets, getCustomerCredits, searchCreditCustomers } from '../customer-credit-query-service';
import { RekapDagangService } from '../rekap-dagang-service';
const db=process.env.RETURN_CREDIT_TEST_DATABASE_URL?returnTestClient(process.env.RETURN_CREDIT_TEST_DATABASE_URL):null;
// Match the application's 15s interactive transaction budget; remote contract tests add RTT.
if (db) {
 const transaction=db.$transaction.bind(db);
 db.$transaction=((callback: Parameters<typeof transaction>[0], options: object={})=>transaction(callback,{timeout:15000,...options})) as typeof db.$transaction;
}
const run=<T>(fn:()=>Promise<T>)=>tenantContext.run(db!,fn);
const issueInput={returnId:'return-1',invoiceId:'invoice',totalAmount:'222',taxAmount:'22',reason:'Synthetic accepted damaged goods',evidence:'Synthetic original invoice and receipt evidence',postingDate:date,confirmed:true};
const issue=()=>run(()=>issueCustomerCredit(issueInput,actor));
const apply=(noteId:string,amount='100',balance='222',remaining='100')=>run(()=>applyCustomerCredit({noteId,invoiceId:'target',totalAmount:amount,expectedBalance:balance,expectedInvoiceBalance:remaining,postingDate:date,reason:'Synthetic credit allocation',confirmed:true,idempotencyKey:randomUUID()},actor));
const reversal=(id:string)=>({id,reversalDate:date,reason:'Synthetic correction requested',confirmed:true});
describe.skipIf(!db)('customer credit on isolated PostgreSQL',()=>{
 beforeEach(async()=>{
  await resetReturnFixture(db!);
  await db!.account.create({data:{id:'liability',code:'21999',name:'Customer Credit Liability',type:'LIABILITY',category:'CURRENT_LIABILITY'}});
  await db!.invoice.update({where:{id:'invoice'},data:{paidAmount:1110,status:'PAID'}});
  await db!.payment.create({data:{paymentNumber:'SYNTHETIC-PAID',invoiceId:'invoice',amount:1110,paymentDate:date,method:'Cash'}});
  await db!.salesOrder.create({data:{id:'target-order',orderNumber:'SO-TARGET',customerId:'customer',status:'DELIVERED'}});
  await db!.invoice.create({data:{id:'target',invoiceNumber:'INV-TARGET',salesOrderId:'target-order',totalAmount:100,status:'UNPAID',invoiceDate:date}});
  await db!.journalEntry.create({data:{id:'target-source',entryNumber:'TARGET-SOURCE',entryDate:date,description:'Synthetic target invoice',referenceType:'SALES_INVOICE',referenceId:'target',status:'POSTED',isAutoGenerated:true,lines:{create:[{accountId:'ar',debit:100,credit:0},{accountId:'revenue',debit:0,credit:100}]}}});
 });
 afterAll(async()=>{await db?.$disconnect();});
 it('issues liability, applies partially, preserves source payment/stock and reports target AR only',async()=>{
  const n=await issue();expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).remainingAmount.toString()).toBe('0');
  await apply(n.id);const target=await db!.invoice.findUniqueOrThrow({where:{id:'target'}});expect(target.status).toBe('PAID');expect(target.paidAmount.toString()).toBe('0');expect(target.creditedAmount.toString()).toBe('100');
  expect((await run(()=>getCustomerCreditDetail(n.id))).remaining).toBe('122.00');
  expect((await run(()=>getCustomerCredits({search:'Synthetic'}))).rows[0].remaining).toBe('122.00');
  expect((await run(()=>searchCreditCustomers('Synthetic'))).length).toBeGreaterThan(0);expect(await db!.payment.count()).toBe(1);expect(await db!.stockMovement.count()).toBe(1);
  const report=await run(()=>RekapDagangService.getPiutangRecap({from:'2026-09-01',to:'2026-09-30'}));expect(report.totals.closingBalance).toBe(0);
  expect(await db!.auditLog.count({where:{action:{in:['ISSUE_CUSTOMER_CREDIT','APPLY_CUSTOMER_CREDIT']}}})).toBe(2);
 });
 it('retries issuance exactly, rejects different amounts and excludes legacy credits',async()=>{
  const n=await issue();expect((await issue()).id).toBe(n.id);
  await expect(run(()=>issueCustomerCredit({...issueInput,totalAmount:'200'},actor))).rejects.toThrow(/berbeda/);
  await expect(db!.salesReturnCredit.create({data:{salesReturnId:'return-1',createdById:actor}})).rejects.toThrow(/consumed/);
 });
 it('blocks unpaid source, missing receipt, wrong source, bad tax and future date',async()=>{
  await db!.invoice.update({where:{id:'invoice'},data:{paidAmount:0,status:'UNPAID'}});await expect(issue()).rejects.toThrow(/dibayar penuh/);
  await db!.invoice.update({where:{id:'invoice'},data:{paidAmount:1110,status:'PAID'}});
  await expect(run(()=>issueCustomerCredit({...issueInput,invoiceId:'target'},actor))).rejects.toThrow(/sumber/);
  await expect(run(()=>issueCustomerCredit({...issueInput,taxAmount:'223'},actor))).rejects.toThrow();
  await expect(run(()=>issueCustomerCredit({...issueInput,taxAmount:'111'},actor))).rejects.toThrow(/netto/);
  await expect(run(()=>issueCustomerCredit({...issueInput,postingDate:new Date('2099-01-01')},actor))).rejects.toThrow(/Tanggal/);
  await db!.salesReturn.update({where:{id:'return-1'},data:{status:'DRAFT'}});await expect(issue()).rejects.toThrow(/Penerimaan/);
 });
 it('requires tenant, rejects stale/overdraw/source invoice and does not create journals',async()=>{
  await expect(issueCustomerCredit(issueInput,actor)).rejects.toThrow(/tenant/);const n=await issue();
  await expect(apply(n.id,'101')).rejects.toThrow(/melebihi/);await expect(apply(n.id,'10','221')).rejects.toThrow(/berubah/);
  await expect(apply(n.id,'0')).rejects.toThrow(/positif/);
  expect(await db!.customerCreditApplication.count()).toBe(0);
 });
 it('serializes concurrent usage and exact retries',async()=>{
  const n=await issue();const command={noteId:n.id,invoiceId:'target',totalAmount:'100',expectedBalance:'222',expectedInvoiceBalance:'100',postingDate:date,reason:'Synthetic credit allocation',confirmed:true,idempotencyKey:randomUUID()};
  const results=await Promise.all([run(()=>applyCustomerCredit(command,actor)),run(()=>applyCustomerCredit(command,actor))]);expect(results[0].applicationId).toBe(results[1].applicationId);expect(await db!.customerCreditApplication.count()).toBe(1);
  await expect(run(()=>applyCustomerCredit({...command,totalAmount:'99'},actor))).rejects.toThrow(/Instruksi/);
 });
 it('blocks foreign customer, allows explicit pair and prevents future use after revoke',async()=>{
  const n=await issue();await db!.customer.create({data:{id:'duplicate',name:'Synthetic second master'}});await db!.salesOrder.update({where:{id:'target-order'},data:{customerId:'duplicate'}});
  await expect(apply(n.id)).rejects.toThrow(/Customer berbeda/);expect((await run(()=>getCustomerCreditTargets({noteId:n.id}))).rows).toHaveLength(0);
  const link=await run(()=>approveCustomerCreditLink({fromCustomerId:'customer',toCustomerId:'duplicate',reason:'Synthetic confirmed same owner',evidence:'Synthetic identity verification',confirmed:true},actor));
  expect((await run(()=>getCustomerCreditTargets({noteId:n.id}))).rows).toHaveLength(1);
  const a=await apply(n.id,'10');await run(()=>revokeCustomerCreditLink({id:link.id,reason:'Synthetic approval withdrawn',confirmed:true},actor));
  await expect(apply(n.id,'10','212','90')).rejects.toThrow(/Customer berbeda/);
  await run(()=>reverseCustomerCreditApplication(reversal(a.applicationId),actor));expect((await run(()=>getCustomerCreditDetail(n.id))).remaining).toBe('222.00');
 });
 it('compensates usage and note, preserves historical records and disallows reposting',async()=>{
  const n=await issue(),a=await apply(n.id);await expect(run(()=>reverseCustomerCreditNote(reversal(n.id),actor))).rejects.toThrow(/seluruh/);
  await run(()=>reverseCustomerCreditApplication(reversal(a.applicationId),actor));await run(()=>reverseCustomerCreditApplication(reversal(a.applicationId),actor));
  expect((await db!.invoice.findUniqueOrThrow({where:{id:'target'}})).remainingAmount.toString()).toBe('100');
  await run(()=>reverseCustomerCreditNote(reversal(n.id),actor));await run(()=>reverseCustomerCreditNote(reversal(n.id),actor));
  expect((await run(()=>getCustomerCreditDetail(n.id))).remaining).toBe('0.00');expect(await db!.customerCreditApplication.count()).toBe(1);await expect(issue()).rejects.toThrow();
 });
 it('protects source payment and identities, ledger cache, journal history and deletes',async()=>{
  const n=await issue(),a=await apply(n.id);const row=await db!.customerCreditNote.findUniqueOrThrow({where:{id:n.id}});
  await expect(db!.invoice.update({where:{id:'invoice'},data:{paidAmount:0}})).rejects.toThrow(/source/);
  await expect(db!.invoice.update({where:{id:'target'},data:{creditedAmount:0}})).rejects.toThrow(/ledger/);
  await expect(db!.customerCreditNote.delete({where:{id:n.id}})).rejects.toThrow(/deleted/);
  await expect(db!.customerCreditApplication.update({where:{id:a.applicationId},data:{totalAmount:10}})).rejects.toThrow(/immutable/);
  await expect(db!.journalEntry.update({where:{id:row.journalId},data:{description:'Changed'}})).rejects.toThrow(/immutable/);
 });
 it('rolls back on audit failure and closed period',async()=>{
  await db!.$executeRawUnsafe(`CREATE FUNCTION reject_wallet_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='ISSUE_CUSTOMER_CREDIT' THEN RAISE EXCEPTION 'wallet audit failed'; END IF; RETURN NEW; END $$`);
  await db!.$executeRawUnsafe('CREATE TRIGGER reject_wallet_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION reject_wallet_audit()');
  try{await expect(issue()).rejects.toThrow(/audit failed/);expect(await db!.customerCreditNote.count()).toBe(0);}finally{await db!.$executeRawUnsafe('DROP TRIGGER reject_wallet_audit ON "AuditLog"');await db!.$executeRawUnsafe('DROP FUNCTION reject_wallet_audit()');}
  await db!.fiscalPeriod.updateMany({data:{status:'CLOSED'}});await expect(issue()).rejects.toThrow(/Periode/);
 });
 it('isolates tenant clients even with identical IDs and rejects unknown note IDs',async()=>{
  const n=await issue();
  const url=new URL(process.env.RETURN_CREDIT_TEST_DATABASE_URL!);url.pathname='/polyflow_return_credit_tenant_test';
  const other=returnTestClient(url.toString());
  try { await resetReturnFixture(other); await expect(tenantContext.run(other,()=>getCustomerCreditDetail(n.id))).rejects.toThrow(); expect(await other.customerCreditNote.count()).toBe(0); } finally { await other.$disconnect(); }
 });
 it('rolls back an application when its audit fails',async()=>{
  const n=await issue();
  await db!.$executeRawUnsafe(`CREATE FUNCTION reject_application_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='APPLY_CUSTOMER_CREDIT' THEN RAISE EXCEPTION 'application audit failed'; END IF; RETURN NEW; END $$`);
  await db!.$executeRawUnsafe('CREATE TRIGGER reject_application_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION reject_application_audit()');
  try { await expect(apply(n.id)).rejects.toThrow(/audit failed/);expect(await db!.customerCreditApplication.count()).toBe(0);expect((await db!.invoice.findUniqueOrThrow({where:{id:'target'}})).remainingAmount.toString()).toBe('100'); } finally { await db!.$executeRawUnsafe('DROP TRIGGER reject_application_audit ON "AuditLog"');await db!.$executeRawUnsafe('DROP FUNCTION reject_application_audit()'); }
 });
 it('rejects a second note that exceeds source tax capacity',async()=>{
  await issue();await db!.salesReturn.create({data:{id:'second-return',returnNumber:'SR-SYNTHETIC-SECOND',salesOrderId:'order',customerId:'customer',returnLocationId:'location',status:'COMPLETED',returnDate:date,items:{create:{id:'second-item',productVariantId:'variant',returnedQty:1,unitPrice:100,receipt:{create:{sourceMovementId:'credit-source-movement',quantity:1,restockValue:0,receivedAt:date,createdById:actor}}}}}});
  await expect(run(()=>issueCustomerCredit({...issueInput,returnId:'second-return',totalAmount:'1000',taxAmount:'100'},actor))).rejects.toThrow(/netto/);
 });
});
