import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { actor, date, resetReturnFixture } from './return-credit-postgres-fixture';
vi.mock('@/services/accounting/account-resolver', () => ({ resolveAccount: async (role: string) => ({ id: role === 'accounts-receivable' ? 'ar' : role === 'vat-output' ? 'vat' : 'revenue' }) }));
vi.mock('@/services/accounting/tenant-revenue-rule-service', () => ({ loadActiveTenantRevenueRules: async () => [] }));
import { tenantContext } from '@/lib/core/prisma';
import { getPriceAdjustmentSource } from '../invoice-price-source';
import { postInvoicePriceAdjustment, reverseInvoicePriceAdjustment } from '../invoice-price-adjustment-service';

// Explicit URL + both disposable markers are mandatory before any fixture write.
const url = process.env.PRICE_ADJUSTMENT_TEST_DATABASE_URL;
function client(connection: string) {
    const u = new URL(connection);
    if (!['postgres:', 'postgresql:'].includes(u.protocol) || u.hostname !== '127.0.0.1' || u.port !== '55469' || u.pathname !== '/polyflow_return_credit_scope_test' || u.search)
        throw new Error('Only disposable localhost price-adjustment DB allowed');
    return new PrismaClient({ datasources: { db: { url: connection } } });
}
const db = url ? client(url) : null;
const source = () => tenantContext.run(db!, () => db!.$transaction(tx => getPriceAdjustmentSource(tx, 'multi-invoice')));
const reverse = (id: string) => tenantContext.run(db!, () => reverseInvoicePriceAdjustment({ adjustmentId: id, reversalDate: date, reason: 'Synthetic reversal' }, actor));
async function command(index: number, price = '90') {
    const s = await source();
    return { invoiceId: 'multi-invoice', sourceItemId: `multi-item-${index}`, quantity: '1', newNetUnitPrice: price, sourceFingerprint: s.fingerprint, expectedRemaining: s.invoice.remainingAmount.toString(), postingDate: date, reason: 'Synthetic multi-account price change', idempotencyKey: randomUUID(), confirmed: true };
}
const post = (data: unknown) => tenantContext.run(db!, () => postInvoicePriceAdjustment(data, actor));

describe.skipIf(!db)('multi-account invoice prices on disposable PostgreSQL', () => {
    beforeEach(async () => {
        const markers = await db!.$queryRaw<{ purpose: string }[]>`SELECT purpose FROM "PriceAdjustmentDisposableMarker"`;
        if (markers.length !== 1 || markers[0].purpose !== 'price-adjustment-synthetic-only') throw new Error('Price marker required');
        await resetReturnFixture(db!, false);
        await db!.account.createMany({ data: ['a', 'b'].map(id => ({ id: `revenue-${id}`, code: `4-SYN-${id}`, name: `Synthetic revenue ${id}`, type: 'REVENUE', category: 'OPERATING_REVENUE' })) });
        for (let i = 0; i < 7; i++) await db!.productVariant.create({ data: { id: `multi-variant-${i}`, productId: 'product', name: `Synthetic item ${i + 1}`, skuCode: `MULTI-${i}`, primaryUnit: 'PCS', revenueAccountId: i < 2 ? 'revenue-a' : 'revenue-b' } });
        await db!.salesOrder.create({ data: { id: 'multi-order', orderNumber: 'SO-MULTI-SYN', customerId: 'customer', status: 'DELIVERED', totalAmount: 700, items: { create: Array.from({ length: 7 }, (_, i) => ({ id: `multi-item-${i}`, productVariantId: `multi-variant-${i}`, quantity: 1, deliveredQty: 1, unitPrice: 100, subtotal: 100 })) } } });
        await db!.invoice.create({ data: { id: 'multi-invoice', invoiceNumber: 'INV-MULTI-SYN', salesOrderId: 'multi-order', totalAmount: 700, status: 'UNPAID', invoiceDate: date } });
        await db!.journalEntry.create({ data: { id: 'multi-journal', entryNumber: 'JE-MULTI-SYN', entryDate: date, description: 'Synthetic multi-account invoice', referenceType: 'SALES_INVOICE', referenceId: 'multi-invoice', status: 'POSTED', isAutoGenerated: true, lines: { create: [{ accountId: 'ar', debit: 700, credit: 0 }, { accountId: 'revenue-a', debit: 0, credit: 200 }, { accountId: 'revenue-b', debit: 0, credit: 500 }] } } });
        await db!.invoiceReturnBasisLine.createMany({ data: Array.from({ length: 7 }, (_, i) => ({ id: `multi-basis-${i}`, invoiceId: 'multi-invoice', sourceItemId: `multi-item-${i}`, productVariantId: `multi-variant-${i}`, quantity: 1, netAmount: 100, taxAmount: 0, discountAmount: 0, sourceJournalId: 'multi-journal', sourceEvidence: { version: 1, capturedAtInvoiceCreation: true } })) });
    });
    afterAll(async () => { await db?.$disconnect(); });
    it('returns seven options, posts both item accounts, reverses stored accounts and preserves source/stock/payments', async () => {
        const original = await source(); expect(original.items).toHaveLength(7);
        const before = { invoice: await db!.invoice.findUniqueOrThrow({ where: { id: 'multi-invoice' } }), journal: await db!.journalLine.findMany({ where: { journalEntryId: 'multi-journal' }, orderBy: { id: 'asc' } }), basis: await db!.invoiceReturnBasisLine.findMany({ where: { invoiceId: 'multi-invoice' }, orderBy: { id: 'asc' } }), stock: await db!.stockMovement.findMany(), payments: await db!.payment.findMany() };
        const first = await post(await command(0)); const second = await post(await command(2, '120'));
        for (const [row, account, debit, credit] of [[first, 'revenue-a', '10', '0'], [second, 'revenue-b', '0', '20']] as const) {
            const lines = await db!.journalLine.findMany({ where: { journalEntryId: row.journalId } });
            expect(lines).toHaveLength(2);
            const revenue = lines.find(l => l.accountId === account)!;
            expect([revenue.debit.toString(), revenue.credit.toString()]).toEqual([debit, credit]);
        }
        // Reversal must not re-resolve the changed product mapping.
        await db!.productVariant.update({ where: { id: 'multi-variant-0' }, data: { revenueAccountId: 'revenue-b' } });
        const reversed = await reverse(first.id);
        const revLines = await db!.journalLine.findMany({ where: { journalEntryId: reversed.reversalJournalId! } });
        expect(revLines.find(l => l.accountId === 'revenue-a')!.credit.toString()).toBe('10');
        expect((await source()).items[0].revenueAccountId).toBe('revenue-a');
        const after = await db!.invoice.findUniqueOrThrow({ where: { id: 'multi-invoice' } });
        expect(after.totalAmount).toEqual(before.invoice.totalAmount); expect(after.paidAmount).toEqual(before.invoice.paidAmount); expect(after.commercialSnapshot).toEqual(before.invoice.commercialSnapshot);
        expect(after.priceAdjustmentAmount.toString()).toBe('20'); expect(after.remainingAmount.toString()).toBe('720');
        expect(await db!.journalLine.findMany({ where: { journalEntryId: 'multi-journal' }, orderBy: { id: 'asc' } })).toEqual(before.journal);
        expect(await db!.invoiceReturnBasisLine.findMany({ where: { invoiceId: 'multi-invoice' }, orderBy: { id: 'asc' } })).toEqual(before.basis);
        expect(await db!.stockMovement.findMany()).toEqual(before.stock); expect(await db!.payment.findMany()).toEqual(before.payments);
        expect(await db!.auditLog.count({ where: { entityId: 'multi-invoice', action: { in: ['POST_INVOICE_PRICE_ADJUSTMENT', 'REVERSE_INVOICE_PRICE_ADJUSTMENT'] } } })).toBe(3);
    });
    it('rejects a stale equal-total mapping swap before writes and rejects journal mismatch', async () => {
        const input = await command(0);
        await db!.productVariant.update({ where: { id: 'multi-variant-0' }, data: { revenueAccountId: 'revenue-b' } });
        await db!.productVariant.update({ where: { id: 'multi-variant-2' }, data: { revenueAccountId: 'revenue-a' } });
        await expect(post(input)).rejects.toThrow(/berubah/);
        expect(await db!.invoicePriceAdjustment.count()).toBe(0);
        await db!.productVariant.update({ where: { id: 'multi-variant-2' }, data: { revenueAccountId: 'revenue-b' } });
        await expect(source()).rejects.toThrow(/pemetaan/);
    });
    it('fails closed on inactive item accounts and accepts ordinary default-role invoice', async () => {
        await db!.account.update({ where: { id: 'revenue-a' }, data: { isActive: false } });
        await expect(source()).rejects.toThrow();
        const normal = await tenantContext.run(db!, () => db!.$transaction(tx => getPriceAdjustmentSource(tx, 'invoice')));
        expect(normal.items[0].revenueAccountId).toBe('revenue');
    });
});
