import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import { actor, returnTestClient, verifyReturnTestDatabase } from './return-credit-postgres-fixture';
import { correctSalesInvoiceDate, type CorrectionDb } from '../../../../scripts/correct-sales-invoice-date';

vi.mock('node:crypto', () => ({ randomUUID: () => 'correction-id' }));
const connection = process.env.RETURN_CREDIT_TEST_DATABASE_URL;
const db = connection ? returnTestClient(connection) : null;
const OLD_DATE = new Date('2026-09-25T17:00:00.000Z');
const OLD_DUE = new Date('2026-09-26T17:00:00.000Z');
const NEW_DATE = new Date('2026-10-05T17:00:00.000Z');

async function seed() {
    await verifyReturnTestDatabase(db!);
    await db!.$executeRawUnsafe('TRUNCATE "SalesReturnCreditAllocation", "SalesReturnCredit", "InvoiceReturnBasisLine", "AuditLog", "JournalLine", "JournalEntry", "Payment", "InvoiceDateCorrection", "Invoice", "SalesOrder", "ProductVariant", "Product", "Location", "Customer", "Account", "FiscalPeriod", "SystemSequence", "User" CASCADE');
    await db!.user.create({ data: { id: actor, email: 'correction@example.invalid', password: 'fixture', role: 'FINANCE' } });
    await db!.customer.create({ data: { id: 'customer-correction', name: 'Synthetic Correction' } });
    await db!.product.create({ data: { id: 'product-correction', name: 'Synthetic Product', productType: 'FINISHED_GOOD' } });
    await db!.productVariant.create({ data: { id: 'variant-correction', productId: 'product-correction', name: 'Synthetic Variant', skuCode: 'CORRECTION-TEST', primaryUnit: 'KG' } });
    await db!.account.createMany({ data: [
        { id: 'ar-correction', code: '11211', name: 'AR Correction', type: 'ASSET', category: 'CURRENT_ASSET' },
        { id: 'revenue-correction', code: '41101', name: 'Revenue Correction', type: 'REVENUE', category: 'OPERATING_REVENUE' },
    ] });
    await db!.fiscalPeriod.createMany({ data: [
        { id: 'period-september-correction', name: 'September', year: 2026, month: 9, status: 'OPEN', startDate: new Date('2026-09-01'), endDate: new Date('2026-09-30') },
        { id: 'period-october-correction', name: 'October', year: 2026, month: 10, status: 'OPEN', startDate: new Date('2026-10-01'), endDate: new Date('2026-10-31') },
    ] });
    await db!.salesOrder.create({ data: {
        id: 'order-correction', orderNumber: 'SO-CORRECTION', customerId: 'customer-correction',
        status: 'SHIPPED', totalAmount: 1000,
        items: { create: { id: 'item-correction', productVariantId: 'variant-correction', quantity: 1, deliveredQty: 1, unitPrice: 1000, subtotal: 1000 } },
    } });
    await db!.invoice.create({ data: {
        id: 'invoice-correction', invoiceNumber: '1/INV/X/2026', salesOrderId: 'order-correction',
        invoiceDate: OLD_DATE, dueDate: OLD_DUE, termOfPaymentDays: 1,
        status: 'UNPAID', totalAmount: 1000, roundingAmount: 0,
    } });
    await db!.journalEntry.create({ data: {
        id: 'journal-correction', entryNumber: 'JE-CORRECTION', entryDate: OLD_DATE,
        description: 'Sales Invoice #1/INV/X/2026', reference: '1/INV/X/2026',
        referenceType: 'SALES_INVOICE', referenceId: 'invoice-correction', status: 'POSTED',
        isAutoGenerated: true,
        lines: { create: [
            { accountId: 'ar-correction', debit: 1000, credit: 0 },
            { accountId: 'revenue-correction', debit: 0, credit: 1000 },
        ] },
    } });
    await db!.invoiceReturnBasisLine.create({ data: {
        id: 'basis-correction', invoiceId: 'invoice-correction', sourceItemId: 'item-correction',
        productVariantId: 'variant-correction', quantity: 1, netAmount: 1000,
        taxAmount: 0, discountAmount: 0, sourceJournalId: 'journal-correction',
        sourceEvidence: { version: 1, capturedAtInvoiceCreation: true },
    } });
}

describe.skipIf(!db)('audited invoice date correction on disposable PostgreSQL', () => {
    beforeAll(seed);
    afterAll(async () => db?.$disconnect());

    it('keeps the return basis and amounts while synchronizing invoice and journal dates', async () => {
        const result = await correctSalesInvoiceDate(db as unknown as CorrectionDb, {
            invoiceId: 'invoice-correction', expectedInvoiceNumber: '1/INV/X/2026',
            expectedSalesOrderNumber: 'SO-CORRECTION', expectedCurrentDate: '2026-09-26',
            newDate: '2026-10-06', expectedStatus: 'UNPAID', expectedTotal: 1000,
            expectedPaid: 0, renumber: false, execute: true, actorUserId: actor,
        });
        expect(result.changed).toBe(true);
        const invoice = await db!.invoice.findUniqueOrThrow({ where: { id: 'invoice-correction' } });
        const journal = await db!.journalEntry.findUniqueOrThrow({ where: { id: 'journal-correction' } });
        expect(invoice.invoiceDate).toEqual(NEW_DATE);
        expect(invoice.dueDate).toEqual(new Date('2026-10-06T17:00:00.000Z'));
        expect(invoice.totalAmount.toString()).toBe('1000');
        expect(journal.entryDate).toEqual(NEW_DATE);
        expect(await db!.invoiceReturnBasisLine.count({ where: { invoiceId: invoice.id } })).toBe(1);
        expect(await db!.invoiceDateCorrection.count({ where: { invoiceId: invoice.id } })).toBe(1);
        expect(await db!.auditLog.count({ where: { action: 'CORRECT_SALES_INVOICE_DATE' } })).toBe(1);
    });

    it('is idempotent after the audited correction', async () => {
        const result = await correctSalesInvoiceDate(db as unknown as CorrectionDb, {
            invoiceId: 'invoice-correction', expectedInvoiceNumber: '1/INV/X/2026',
            expectedSalesOrderNumber: 'SO-CORRECTION', expectedCurrentDate: '2026-09-26',
            newDate: '2026-10-06', expectedStatus: 'UNPAID', expectedTotal: 1000,
            expectedPaid: 0, renumber: false, execute: true, actorUserId: actor,
        });
        expect(result.changed).toBe(false);
        expect(await db!.invoiceDateCorrection.count()).toBe(1);
        expect(await db!.auditLog.count({ where: { action: 'CORRECT_SALES_INVOICE_DATE' } })).toBe(1);
    });
});
