import { Prisma } from '@prisma/client';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { getPriceAdjustmentSource } from '../invoice-price-source';

const mocks = vi.hoisted(() => ({ rules: vi.fn(), tenant: vi.fn() }));
vi.mock('@/services/accounting/account-resolver', () => ({
    resolveAccount: async (role: string) => ({ id: ({ 'accounts-receivable': 'ar', 'vat-output': 'vat', 'sales-revenue': 'default', 'sales-rounding-income': 'rounding' } as Record<string, string>)[role] }),
}));
vi.mock('@/lib/core/prisma', () => ({ getTenantIdFromContext: mocks.tenant }));
vi.mock('@/services/accounting/tenant-revenue-rule-service', () => ({ loadActiveTenantRevenueRules: mocks.rules }));
const d = (v: Prisma.Decimal.Value) => new Prisma.Decimal(v);

function fixture(multi = true) {
    const accounts = ['ar', 'vat', 'default', 'a', 'b', 'rounding'].map(id => ({ id, code: id, name: id, isActive: true, type: id === 'ar' ? 'ASSET' : id === 'vat' ? 'LIABILITY' : 'REVENUE' }));
    const items = Array.from({ length: 7 }, (_, index) => ({
        id: `item-${index}`, productVariantId: `variant-${index}`, quantity: d(10), deliveredQty: d(10), unitPrice: d(10), subtotal: d(100), taxAmount: d(0), discountPercent: d(0), taxPercent: d(0), ppnMode: 'EXCLUDE',
        productVariant: { name: `Synthetic item ${index + 1}`, skuCode: `SYN-${index}`, primaryUnit: 'PCS', revenueAccountId: multi ? index < 2 ? 'a' : 'b' : null as string | null, product: { id: 'product', name: 'Synthetic product', revenueAccountId: null as string | null } },
    }));
    const invoice = {
        id: 'invoice', invoiceNumber: 'SYNTHETIC', salesOrderId: 'order', status: 'UNPAID', totalAmount: d(700), paidAmount: d(0), creditedAmount: d(0), priceAdjustmentAmount: d(0), roundingAmount: d(0), commercialSnapshot: null as unknown,
        salesOrder: { customerId: 'customer', items, shippingCost: d(0), deliveryOrders: [] },
        returnBasisLines: items.map(i => ({ id: `basis-${i.id}`, sourceItemId: i.id, productVariantId: i.productVariantId, quantity: d(10), netAmount: d(100), taxAmount: d(0), sourceJournalId: 'journal', sourceEvidence: { version: 1, capturedAtInvoiceCreation: true } })),
    };
    const line = (accountId: string, debit: number, credit: number) => ({ accountId, debit: d(debit), credit: d(credit), currency: 'IDR', exchangeRate: d(1) });
    const journal = { id: 'journal', status: 'POSTED', isAutoGenerated: true, lines: [line('ar', 700, 0), ...(multi ? [line('a', 0, 200), line('b', 0, 500)] : [line('default', 0, 700)])] };
    const existing: { id: string; sourceJournalId: string; sourceItemId: string; status: string; sourceEvidence: unknown }[] = [];
    const tx = {
        invoice: { findUnique: vi.fn(async () => invoice), count: vi.fn(async () => 1) },
        journalEntry: { findMany: vi.fn(async () => [journal]) },
        invoicePriceAdjustment: { findMany: vi.fn(async () => existing) },
        salesReturnCreditAllocation: { findMany: vi.fn(async () => []) },
        account: {
            findUnique: vi.fn(async ({ where }: { where: { id?: string; code?: string } }) => accounts.find(a => where.id ? a.id === where.id : a.code === where.code) ?? null),
            count: vi.fn(async ({ where }: { where: { id: { in: string[] }; type?: string } }) => accounts.filter(a => where.id.in.includes(a.id) && a.isActive && (!where.type || a.type === where.type)).length),
        },
    };
    return { invoice, journal, existing, accounts, line, read: () => getPriceAdjustmentSource(tx as unknown as Prisma.TransactionClient, 'invoice') };
}

beforeEach(() => { vi.clearAllMocks(); mocks.rules.mockResolvedValue([]); mocks.tenant.mockReturnValue('synthetic-tenant'); });
describe('invoice price source revenue attribution', () => {
    it('returns all seven immutable invoice items and their exact revenue accounts', async () => {
        const f = fixture(); const source = await f.read();
        expect(source.items).toHaveLength(7);
        expect(source.items.map(i => i.revenueAccountId)).toEqual(['a', 'a', 'b', 'b', 'b', 'b', 'b']);
        expect(source.originalLines.map(i => i.revenueAccountId)).toEqual(source.items.map(i => i.revenueAccountId));
        expect(mocks.rules).toHaveBeenCalledWith('synthetic-tenant');
    });
    it('accepts the default role when the resolver has no override or rule', async () => {
        expect((await fixture(false).read()).items.every(i => i.revenueAccountId === 'default')).toBe(true);
    });
    it('uses product overrides and tenant rules with the same precedence as issuance', async () => {
        const f = fixture();
        f.invoice.salesOrder.items.forEach((i, index) => { i.productVariant.revenueAccountId = null; i.productVariant.product.revenueAccountId = index < 2 ? 'a' : null; });
        mocks.rules.mockResolvedValue([{ matchType: 'SKU_PREFIX', matchValue: 'SYN-', accountCode: 'b', priority: 0 }]);
        expect((await f.read()).items.map(i => i.revenueAccountId)).toEqual(['a', 'a', 'b', 'b', 'b', 'b', 'b']);
    });
    it('rejects changed mapping or missing rule rather than sending everything to default', async () => {
        const f = fixture(); f.invoice.salesOrder.items[0].productVariant.revenueAccountId = null;
        await expect(f.read()).rejects.toThrow(/pemetaan/);
    });
    it('changes fingerprint for a mapping swap even when aggregate journal totals stay equal', async () => {
        const f = fixture(); const before = await f.read();
        f.invoice.salesOrder.items[0].productVariant.revenueAccountId = 'b';
        f.invoice.salesOrder.items[2].productVariant.revenueAccountId = 'a';
        expect((await f.read()).fingerprint).not.toBe(before.fingerprint);
    });
    it.each(['a', 'default', 'ar', 'vat'])('rejects inactive account %s', async id => {
        const f = fixture(id === 'default' ? false : true); f.accounts.find(a => a.id === id)!.isActive = false;
        await expect(f.read()).rejects.toThrow();
    });
    it('validates the dedicated rounding account as active', async () => {
        const f = fixture(); f.invoice.totalAmount = d(705); f.invoice.roundingAmount = d(5);
        f.journal.lines[0].debit = d(705); f.journal.lines.push(f.line('rounding', 0, 5));
        expect((await f.read()).items).toHaveLength(7);
        f.accounts.find(a => a.id === 'rounding')!.isActive = false;
        await expect(f.read()).rejects.toThrow(/tidak aktif/);
    });
    it('keeps legacy current-SO reconstruction available only when it matches the original journal', async () => {
        const f = fixture(false); f.invoice.returnBasisLines = [];
        expect((await f.read()).sourceLabel).toContain('SO saat ini');
        f.invoice.salesOrder.items[0].unitPrice = d(999);
        await expect(f.read()).rejects.toThrow();
    });
    it('rejects a non-revenue item account even when the journal matches', async () => {
        const f = fixture(); f.accounts.find(a => a.id === 'a')!.type = 'EXPENSE';
        await expect(f.read()).rejects.toThrow(/akun|Akun/);
    });
    it.each(['currency', 'exchangeRate', 'status', 'amount', 'extra', 'offset'])('rejects journal mismatch: %s', async kind => {
        const f = fixture();
        if (kind === 'currency') f.journal.lines[0].currency = 'USD';
        if (kind === 'exchangeRate') f.journal.lines[0].exchangeRate = d(2);
        if (kind === 'status') f.journal.status = 'DRAFT';
        if (kind === 'amount') { f.journal.lines[1].credit = d(201); f.journal.lines[2].credit = d(499); }
        if (kind === 'extra') f.journal.lines.push(f.line('rounding', 1, 0), f.line('default', 0, 1));
        if (kind === 'offset') f.journal.lines.push(f.line('a', 1, 0), f.line('a', 0, 1));
        await expect(f.read()).rejects.toThrow(/Jurnal/);
    });
    it('retains reviewed accounts even after reversal and an equal-value master mapping swap', async () => {
        const f = fixture(); const before = await f.read();
        f.existing.push({ id: 'prior', sourceJournalId: 'journal', sourceItemId: 'item-0', status: 'REVERSED', sourceEvidence: { version: 1, originalLines: before.originalLines } });
        f.invoice.salesOrder.items[0].productVariant.revenueAccountId = 'b'; f.invoice.salesOrder.items[2].productVariant.revenueAccountId = 'a';
        expect((await f.read()).items.map(i => i.revenueAccountId)).toEqual(before.items.map(i => i.revenueAccountId));
    });
    it('retains default-only v1 historical evidence without reinterpreting it using new product mapping', async () => {
        const f = fixture(false); const before = await f.read();
        f.existing.push({ id: 'prior', sourceJournalId: 'journal', sourceItemId: 'item-0', status: 'REVERSED', sourceEvidence: { version: 1, originalLines: before.originalLines.map(({ revenueAccountId: _account, ...line }) => line) } });
        f.invoice.returnBasisLines = [];
        f.invoice.salesOrder.items.forEach(i => { i.productVariant.revenueAccountId = 'a'; i.unitPrice = d(999); });
        expect((await f.read()).items.every(i => i.revenueAccountId === 'default' && i.netAmount === '100.00')).toBe(true);
    });
    it('uses immutable commercial snapshot metadata instead of changed product mappings', async () => {
        const f = fixture();
        f.invoice.commercialSnapshot = {
            version: 1, basis: 'DELIVERED', orderNumber: 'SYNTHETIC', customer: null,
            shippingAmount: '0.00', discountAmount: '0.00', taxAmount: '0.00', commercialTotal: '700.00',
            items: f.invoice.salesOrder.items.map(i => ({
                sourceItemId: i.id, productVariantId: i.productVariantId,
                name: i.productVariant.name, skuCode: i.productVariant.skuCode, unit: 'PCS',
                quantity: 10, unitPrice: '10.00', discountPercent: 0, taxPercent: 0, ppnMode: 'EXCLUDE',
                discountAmount: '0.00', netAmount: '100.00', taxAmount: '0.00', totalAmount: '100.00',
                enteredUnit: 'PCS', conversionFactor: 1, enteredQuantity: 10, enteredUnitPrice: '10.00',
                revenueAccountId: i.productVariant.revenueAccountId, product: { ...i.productVariant.product },
            })),
        };
        f.invoice.salesOrder.items.forEach(i => { i.productVariant.revenueAccountId = 'default'; });
        expect((await f.read()).items.map(i => i.revenueAccountId)).toEqual(['a', 'a', 'b', 'b', 'b', 'b', 'b']);
        f.invoice.returnBasisLines[0].quantity = d(9);
        await expect(f.read()).rejects.toThrow(/snapshot komersial/);
    });
    it('rejects conflicting attribution across historical approvals', async () => {
        const f = fixture(); const before = await f.read();
        f.existing.push({ id: 'prior', sourceJournalId: 'journal', sourceItemId: 'item-0', status: 'REVERSED', sourceEvidence: { version: 1, originalLines: before.originalLines } });
        const swapped = before.originalLines.map(l => ({ ...l }));
        swapped[0].revenueAccountId = 'b'; swapped[2].revenueAccountId = 'a';
        f.existing.push({ id: 'other', sourceJournalId: 'journal', sourceItemId: 'item-1', status: 'REVERSED', sourceEvidence: { version: 1, originalLines: swapped } });
        await expect(f.read()).rejects.toThrow(/antar penyesuaian/);
    });
    it('rechecks historical item account activity even though current mapping has changed', async () => {
        const f = fixture(); const before = await f.read();
        f.existing.push({ id: 'prior', sourceJournalId: 'journal', sourceItemId: 'item-0', status: 'REVERSED', sourceEvidence: { version: 1, originalLines: before.originalLines } });
        f.accounts.find(a => a.id === 'a')!.isActive = false;
        await expect(f.read()).rejects.toThrow(/tidak aktif/);
    });
    it.each(['journal', 'version', 'quantity', 'partial-account', 'conflict'])('rejects invalid historical evidence: %s', async kind => {
        const f = fixture(); const before = await f.read();
        const originalLines = before.originalLines.map(l => ({ ...l }));
        if (kind === 'quantity') originalLines[0].quantity = 'NaN';
        if (kind === 'partial-account') delete (originalLines[0] as { revenueAccountId?: string }).revenueAccountId;
        if (kind === 'conflict') originalLines[0].netAmount = '99.00';
        f.existing.push({ id: 'prior', sourceJournalId: kind === 'journal' ? 'other' : 'journal', sourceItemId: 'item-0', status: 'REVERSED', sourceEvidence: { version: kind === 'version' ? 99 : 1, originalLines } });
        await expect(f.read()).rejects.toThrow(/Bukti/);
    });
});
