import { randomUUID } from 'node:crypto';
import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { actor, date, resetReturnFixture, returnTestClient } from './return-credit-postgres-fixture';
vi.mock('@/services/accounting/account-resolver', () => ({ resolveAccount: async (role: string) => ({ id: role === 'vat-output' ? 'vat' : role === 'sales-return' ? 'return' : 'ar' }) }));
import { tenantContext } from '@/lib/core/prisma';
import { getQuickReturnOrderItems, getQuickReturnOrders, postQuickSalesReturn, previewQuickSalesReturn } from '../quick-sales-return-service';
const db = process.env.RETURN_CREDIT_TEST_DATABASE_URL ? returnTestClient(process.env.RETURN_CREDIT_TEST_DATABASE_URL) : null;
const selection = { salesOrderId: 'order', items: [{ productVariantId: 'variant', quantity: '2' }] };
const preview = () => tenantContext.run(db!, () => previewQuickSalesReturn(selection));
const post = (input: unknown) => tenantContext.run(db!, () => postQuickSalesReturn(input, actor));
async function command() { return { selection, requestId: randomUUID(), fingerprint: (await preview()).fingerprint, confirmed: true }; }
async function setup() {
    await resetReturnFixture(db!, false);
    await db!.salesReturn.delete({ where: { id: 'return-1' } });
    await db!.stockMovement.update({ where: { id: 'credit-source-movement' }, data: { createdAt: date, cost: 60 } });
    await db!.journalEntry.create({ data: { id: 'shipment-journal', entryNumber: 'SHIP-JE', entryDate: date,
        description: 'Synthetic shipment cost', referenceType: 'MANUAL_ENTRY', referenceId: 'credit-source-movement', status: 'POSTED', isAutoGenerated: true,
        lines: { create: [{ accountId: 'cogs', debit: 600, credit: 0 }, { accountId: 'inventory', debit: 0, credit: 600 }] },
    } });
    // Posting uses today's business day, not a client-controlled date.
    const now = new Date();
    await db!.fiscalPeriod.updateMany({ data: { year: now.getFullYear(), month: now.getMonth() + 1,
        startDate: new Date(now.getFullYear(), now.getMonth(), 1), endDate: new Date(now.getFullYear(), now.getMonth() + 1, 0) } });
}
describe.skipIf(!db)('one-step return — real PostgreSQL receipt, ledger and rollback', () => {
    beforeEach(setup);
    afterAll(async () => { await db?.$disconnect(); });
    it('quotes with no writes, receives at historical cost and reduces the exact SO invoice atomically', async () => {
        const quote = await preview();
        expect(quote).toMatchObject({ totalAmount: '222.00', remaining: '1110.00', remainingAfter: '888.00', locationName: 'Synthetic Returns' });
        expect(await db!.salesReturn.count()).toBe(0);
        const result = await post({ selection, requestId: randomUUID(), fingerprint: quote.fingerprint, confirmed: true });
        const returned = await db!.salesReturn.findUniqueOrThrow({ where: { id: result.id }, include: { credit: true, items: { include: { receipt: true } } } });
        expect(returned.status).toBe('COMPLETED'); expect(returned.credit?.status).toBe('POSTED');
        expect(returned.items[0].receipt?.restockValue.toString()).toBe('120');
        const stock = await db!.inventory.findFirstOrThrow();
        expect(stock.quantity.toString()).toBe('2'); expect(stock.averageCost?.toString()).toBe('60');
        const invoice = await db!.invoice.findUniqueOrThrow({ where: { id: 'invoice' } });
        expect(invoice.remainingAmount.toString()).toBe('888'); expect(invoice.totalAmount.toString()).toBe('1110');
        expect(invoice.paidAmount.toString()).toBe('0'); expect(await db!.payment.count()).toBe(0);
        expect(await db!.auditLog.count({ where: { entityId: result.id } })).toBeGreaterThanOrEqual(4);
    });
    it('same request concurrently/retried returns one document, one receipt and one credit', async () => {
        const input = await command();
        const results = await Promise.all([post(input), post(input)]);
        expect(results[0].id).toBe(results[1].id); expect(await post(input)).toEqual(results[0]);
        expect(await db!.salesReturn.count()).toBe(1); expect(await db!.salesReturnReceiptLine.count()).toBe(1);
        expect(await db!.salesReturnCredit.count()).toBe(1);
        expect((await db!.inventory.findFirstOrThrow()).quantity.toString()).toBe('2');
        await expect(post({ ...input, selection: { ...selection, items: [{ productVariantId: 'variant', quantity: '3' }] } })).rejects.toThrow(/berbeda/);
    });
    it('competing different requests cannot consume a stale quote twice', async () => {
        const input = await command();
        const results = await Promise.allSettled([post(input), post({ ...input, requestId: randomUUID() })]);
        expect(results.filter(result => result.status === 'fulfilled')).toHaveLength(1);
        expect(await db!.salesReturnCredit.count()).toBe(1);
        expect((await db!.inventory.findFirstOrThrow()).quantity.toString()).toBe('2');
    });
    it('supports a matching legacy SO proposal without manufacturing historical snapshots', async () => {
        await db!.invoice.update({ where: { id: 'invoice' }, data: { status: 'DRAFT' } });
        await db!.invoiceReturnBasisLine.deleteMany();
        await db!.invoice.update({ where: { id: 'invoice' }, data: { status: 'UNPAID' } });
        expect((await preview()).source).toBe('SO_REVIEW'); await post(await command());
        expect(await db!.invoiceReturnBasisLine.count()).toBe(0);
        expect((await db!.invoice.findUniqueOrThrow({ where: { id: 'invoice' } })).remainingAmount.toString()).toBe('888');
    });
    it.each(['missing-cost', 'closed-period', 'unknown-destination-value', 'legacy-receipt'])('rolls back all writes on %s', async failure => {
        const input = await command();
        if (failure === 'missing-cost') await db!.journalEntry.delete({ where: { id: 'shipment-journal' } });
        if (failure === 'closed-period') await db!.fiscalPeriod.updateMany({ data: { status: 'CLOSED' } });
        if (failure === 'unknown-destination-value') await db!.inventory.create({ data: { locationId: 'location', productVariantId: 'variant', quantity: 3, averageCost: null } });
        if (failure === 'legacy-receipt') await db!.salesReturn.create({ data: { id: 'legacy', returnNumber: 'SR-LEGACY', salesOrderId: 'order', customerId: 'customer', returnLocationId: 'location', status: 'RECEIVED',
            items: { create: { productVariantId: 'variant', returnedQty: 1, unitPrice: 100 } } } });
        await expect(post(input)).rejects.toThrow();
        expect(await db!.salesReturn.count({ where: { id: input.requestId } })).toBe(0);
        expect(await db!.salesReturnCredit.count()).toBe(0); expect(await db!.salesReturnReceiptLine.count()).toBe(0);
        expect((await db!.invoice.findUniqueOrThrow({ where: { id: 'invoice' } })).remainingAmount.toString()).toBe('1110');
        expect(await db!.stockMovement.count({ where: { type: 'RETURN_IN' } })).toBe(0);
    });
    it('rolls back stock, credit and all audits when the LAST audit fails', async () => {
        const input = await command();
        await db!.$executeRawUnsafe(`CREATE FUNCTION reject_quick_return_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='COMPLETE_SALES_RETURN' THEN RAISE EXCEPTION 'final audit failed'; END IF; RETURN NEW; END $$`);
        await db!.$executeRawUnsafe(`CREATE TRIGGER reject_quick_return_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION reject_quick_return_audit()`);
        try {
            await expect(post(input)).rejects.toThrow('final audit failed');
            expect(await db!.salesReturn.count()).toBe(0); expect(await db!.salesReturnCredit.count()).toBe(0);
            expect(await db!.inventory.count()).toBe(0); expect(await db!.salesReturnReceiptLine.count()).toBe(0);
            expect(await db!.auditLog.count()).toBe(0);
            expect((await db!.invoice.findUniqueOrThrow({ where: { id: 'invoice' } })).remainingAmount.toString()).toBe('1110');
        } finally {
            await db!.$executeRawUnsafe('DROP TRIGGER reject_quick_return_audit ON "AuditLog"');
            await db!.$executeRawUnsafe('DROP FUNCTION reject_quick_return_audit()');
        }
    });
    it('rejects stale price/source, paid balances, phantom payments, and over-quantity without writes', async () => {
        const input = await command();
        await db!.salesOrderItem.update({ where: { id: 'source-item' }, data: { unitPrice: 126 } });
        await expect(post(input)).rejects.toThrow(/berubah/);
        await db!.invoice.update({ where: { id: 'invoice' }, data: { paidAmount: 1 } });
        await expect(preview()).rejects.toThrow(/pembayaran/);
        await db!.invoice.update({ where: { id: 'invoice' }, data: { paidAmount: 1110, status: 'PAID' } });
        await expect(preview()).rejects.toThrow(/lunas/);
        await expect(tenantContext.run(db!, () => previewQuickSalesReturn({ ...selection, items: [{ productVariantId: 'variant', quantity: '11' }] }))).rejects.toThrow(/melebihi/);
        expect(await db!.salesReturn.count()).toBe(0);
    });
    it('does not infer a shipment or use customer-owned inventory', async () => {
        await db!.stockMovement.create({ data: { type: 'OUT', salesOrderId: 'order', productVariantId: 'variant', fromLocationId: 'location', quantity: 1 } });
        await expect(preview()).rejects.toThrow(/lebih dari satu/);
        await db!.stockMovement.deleteMany({ where: { id: { not: 'credit-source-movement' } } });
        await db!.location.update({ where: { id: 'location' }, data: { locationType: 'CUSTOMER_OWNED' } });
        await expect(preview()).rejects.toThrow(/internal/);
    });
    it('scopes lookups and rejects missing tenant and missing order/invalid confirmation', async () => {
        expect(await tenantContext.run(db!, () => getQuickReturnOrders('SO-RETURN'))).toEqual([{ id: 'order', orderNumber: 'SO-RETURN-TEST' }]);
        expect(await tenantContext.run(db!, () => getQuickReturnOrderItems('order'))).toHaveLength(1);
        await expect(tenantContext.run(db!, () => getQuickReturnOrderItems('foreign'))).rejects.toThrow();
        await expect(previewQuickSalesReturn(selection)).rejects.toThrow(/tenant/);
        await expect(post({ ...(await command()), confirmed: false })).rejects.toThrow();
        expect(await db!.salesReturn.count()).toBe(0);
    });
});
