import { PrismaClient } from '@prisma/client';

const allowed = ['polyflow_return_credit_scope_test', 'polyflow_return_credit_tenant_test', 'polyflow_return_receipt_scope_test'];
export function returnTestClient(connection: string | undefined) {
    if (!connection) throw new Error('Explicit RETURN_CREDIT_TEST_DATABASE_URL required');
    const url = new URL(connection);
    if (!['postgres:', 'postgresql:'].includes(url.protocol) || url.hostname !== '127.0.0.1' || url.port !== '55439' ||
        !allowed.includes(url.pathname.slice(1)) || [...url.searchParams.keys()].some(key => !['connection_limit','application_name'].includes(key))) {
        throw new Error('Only isolated localhost:55439 return-credit test databases allowed');
    }
    return new PrismaClient({ datasources: { db: { url: connection } } });
}
export async function verifyReturnTestDatabase(db: PrismaClient) {
    const [identity] = await db.$queryRaw<{ name: string; recovery: boolean }[]>`SELECT current_database() name, pg_is_in_recovery() recovery`;
    if (!allowed.includes(identity.name) || identity.recovery) throw new Error('Wrong disposable database identity');
    const markers = await db.$queryRaw<{ purpose: string }[]>`SELECT purpose FROM "ReturnCreditDisposableMarker"`;
    if (markers.length !== 1 || markers[0].purpose !== 'return-credit-synthetic-only') throw new Error('Disposable marker required');
}
export const actor = 'return-test-actor';
export const date = new Date('2026-09-18T00:00:00+07:00');
export async function resetReturnFixture(db: PrismaClient, withReceiptEvidence = true, returnedQuantity = 2) {
    await verifyReturnTestDatabase(db);
    await db.$executeRaw`TRUNCATE "BarterSettlement", "BarterPartner", "PurchaseInvoice", "PurchaseOrder", "Supplier", "SalesReturnCreditAllocation", "SalesReturnCredit", "InvoiceReturnBasisLine", "SalesReturnItem", "SalesReturn", "AuditLog", "JournalLine", "JournalEntry", "Payment", "Invoice", "SalesOrder", "ProductVariant", "Product", "Location", "Customer", "Account", "FiscalPeriod", "SystemSequence", "User" CASCADE`;
    await db.user.create({data:{id:actor,email:'return-test@example.invalid',password:'fixture-not-a-real-account',role:'FINANCE'}});
    await db.customer.create({data:{id:'customer',name:'Synthetic Customer'}});
    await db.location.create({data:{id:'location',name:'Synthetic Returns',slug:'return-test'}});
    await db.product.create({data:{id:'product',name:'Synthetic Product',productType:'FINISHED_GOOD'}});
    await db.productVariant.create({data:{id:'variant',productId:'product',name:'Synthetic Variant',skuCode:'RETURN-TEST',primaryUnit:'KG'}});
    await db.account.createMany({data:[
        {id:'ar',code:'11210',name:'AR',type:'ASSET',category:'CURRENT_ASSET'},
        {id:'revenue',code:'41100',name:'Revenue',type:'REVENUE',category:'OPERATING_REVENUE'},
        {id:'return',code:'41900',name:'Sales Return',type:'REVENUE',category:'OPERATING_REVENUE'},
        {id:'vat',code:'21310',name:'VAT Output',type:'LIABILITY',category:'CURRENT_LIABILITY'},
        {id:'inventory',code:'11300',name:'Inventory',type:'ASSET',category:'CURRENT_ASSET'},
        {id:'cogs',code:'51100',name:'COGS',type:'EXPENSE',category:'COGS'},
    ]});
    await db.fiscalPeriod.create({data:{name:'September',year:2026,month:9,status:'OPEN',startDate:new Date('2026-09-01'),endDate:new Date('2026-09-30')}});
    await db.systemSequence.create({data:{key:'JOURNAL_ENTRY_2026',value:100}});
    await db.salesOrder.create({data:{id:'order',orderNumber:'SO-RETURN-TEST',customerId:'customer',status:'DELIVERED',totalAmount:1110,items:{create:{id:'source-item',productVariantId:'variant',quantity:10,deliveredQty:10,unitPrice:125,subtotal:1110,taxAmount:110,discountPercent:20,taxPercent:11}}}});
    await db.invoice.create({data:{id:'invoice',invoiceNumber:'INV-RETURN-TEST',salesOrderId:'order',totalAmount:1110,status:'UNPAID',invoiceDate:date}});
    await db.journalEntry.create({data:{id:'source-journal',entryNumber:'SOURCE-JE',entryDate:date,description:'Synthetic invoice',referenceType:'SALES_INVOICE',referenceId:'invoice',status:'POSTED',isAutoGenerated:true,lines:{create:[{accountId:'ar',debit:1110,credit:0},{accountId:'revenue',debit:0,credit:1000},{accountId:'vat',debit:0,credit:110}]}}});
    await db.invoiceReturnBasisLine.create({data:{id:'basis',invoiceId:'invoice',sourceItemId:'source-item',productVariantId:'variant',quantity:10,netAmount:1000,taxAmount:110,discountAmount:250,sourceJournalId:'source-journal',sourceEvidence:{version:1,capturedAtInvoiceCreation:true}}});
    await db.stockMovement.create({data:{id:'credit-source-movement',type:'OUT',salesOrderId:'order',productVariantId:'variant',fromLocationId:'location',quantity:10,reference:'Synthetic credit source'}});
    await createReturn(db,'return-1',returnedQuantity,withReceiptEvidence);
}
export async function createReturn(db: PrismaClient, id: string, qty: number, withReceiptEvidence = true) {
    return db.salesReturn.create({data:{id,returnNumber:`SR-${id}`,salesOrderId:'order',customerId:'customer',returnLocationId:'location',status:'RECEIVED',returnDate:date,totalAmount:qty*999,createdById:actor,items:{create:{id:`${id}-item`,productVariantId:'variant',returnedQty:qty,unitPrice:999,condition:'GOOD',...(withReceiptEvidence?{receipt:{create:{sourceMovementId:'credit-source-movement',quantity:qty,restockValue:0,receivedAt:date,createdById:actor}}}:{})}}}});
}
