import { randomUUID } from 'node:crypto';
import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('@/lib/core/prisma', async () => {
    const { PrismaClient } = await import('@prisma/client');
    const connection = process.env.TEST_DATABASE_URL;
    if (!connection) return { prisma: undefined };
    const url = new URL(connection);
    if (url.hostname !== '127.0.0.1' || url.pathname !== '/polyflow_recognition_test') {
        throw new Error('Integration tests require a disposable localhost polyflow_recognition_test database');
    }
    return { prisma: new PrismaClient({ datasources: { db: { url: connection } } }) };
});
vi.mock('@/services/accounting/account-resolver', () => ({ resolveAccount: vi.fn() }));
vi.mock('@/services/settings/app-settings-service', () => ({ getPaymentBanksSetting: vi.fn().mockResolvedValue([]) }));
import { prisma as db } from '@/lib/core/prisma';
import { resolveAccount } from '@/services/accounting/account-resolver';
import { recordCustomerPaymentInTransaction } from '../customer-payment-service';
import { updateInvoiceStatus } from '../invoice-lifecycle-service';
import { collectFinanceJournalIssues } from '../journal-health-service';

const august = new Date('2026-08-19T00:00:00Z');
const paymentDate = new Date('2026-08-20T00:00:00Z');
const actor = 'recognition-test-actor';
const roleAccount = (role: string) => ({ id: role === 'accounts-receivable' ? 'ar' : 'cash', code: role === 'accounts-receivable' ? '11210' : '11100', name: role });
const pay = (amount: number, number: string, date = paymentDate) => db.$transaction(tx => recordCustomerPaymentInTransaction(tx, {
    invoiceId: 'invoice', amount, method: 'Cash', paymentDate: date,
}, number, actor));

// Opt-in only: never connect to the application's configured tenant database.
describe.skipIf(!process.env.TEST_DATABASE_URL)('sales recognition on isolated PostgreSQL', () => {
    beforeEach(async () => {
        vi.mocked(resolveAccount).mockImplementation(async role => roleAccount(role));
        const identity = await db.$queryRaw<{ db: string }[]>`SELECT current_database() db`;
        expect(identity[0].db).toBe('polyflow_recognition_test');
        await db.$executeRaw`TRUNCATE "AuditLog", "JournalLine", "JournalEntry", "Payment", "Invoice", "SalesOrder", "Account", "FiscalPeriod", "SystemSequence", "User" CASCADE`;
        await db.user.create({ data: { id: actor, email: 'finance@example.invalid', password: randomUUID(), role: 'FINANCE' } });
        await db.account.createMany({ data: [
            { id: 'ar', code: '11210', name: 'AR', type: 'ASSET', category: 'CURRENT_ASSET' },
            { id: 'cash', code: '11100', name: 'Cash', type: 'ASSET', category: 'CURRENT_ASSET' },
            { id: 'revenue', code: '41100', name: 'Revenue', type: 'REVENUE', category: 'OPERATING_REVENUE' },
        ] });
        await db.fiscalPeriod.createMany({ data: [8, 9].map(month => ({
            name: `Period ${month}`, year: 2026, month, status: 'OPEN' as const,
            startDate: new Date(Date.UTC(2026, month - 1, 1)), endDate: new Date(Date.UTC(2026, month, 0)),
        })) });
        await db.systemSequence.create({ data: { key: 'JOURNAL_ENTRY_2026', value: 100 } });
        await db.salesOrder.create({ data: { id: 'order', orderNumber: 'SO-TEST', status: 'DELIVERED', totalAmount: 100 } });
        await db.invoice.create({ data: { id: 'invoice', invoiceNumber: 'INV-TEST', salesOrderId: 'order', status: 'DRAFT', totalAmount: 100, invoiceDate: august } });
        await db.journalEntry.create({ data: {
            id: 'sales-journal', entryNumber: 'TEST-SALES', entryDate: august, description: 'Test sales', reference: 'INV-TEST',
            referenceType: 'SALES_INVOICE', referenceId: 'invoice', status: 'DRAFT', isAutoGenerated: true,
            lines: { create: [{ accountId: 'ar', debit: 100, credit: 0 }, { accountId: 'revenue', debit: 0, credit: 100 }] },
        } });
    });
    afterAll(async () => { await db.$disconnect(); });

    it('confirmation -> partial payment -> paid keeps one revenue journal and settles AR', async () => {
        await updateInvoiceStatus({ id: 'invoice', status: 'UNPAID' }, actor);
        await pay(40, 'PAY-1');
        expect((await db.invoice.findUniqueOrThrow({ where: { id: 'invoice' } })).status).toBe('PARTIAL');
        await pay(60, 'PAY-2');
        const invoice = await db.invoice.findUniqueOrThrow({ where: { id: 'invoice' } });
        expect(invoice.status).toBe('PAID');
        expect(Number(invoice.paidAmount)).toBe(100);
        expect(await db.journalEntry.count({ where: { referenceType: 'SALES_INVOICE' } })).toBe(1);
        expect(await db.journalEntry.count({ where: { status: 'POSTED' } })).toBe(3);
        const ar = await db.journalLine.aggregate({ where: { accountId: 'ar', journalEntry: { status: 'POSTED' } }, _sum: { debit: true, credit: true } });
        expect(Number(ar._sum.debit) - Number(ar._sum.credit)).toBe(0);
        const revenue = await db.journalLine.aggregate({ where: { accountId: 'revenue', journalEntry: { status: 'POSTED' } }, _sum: { credit: true } });
        expect(Number(revenue._sum.credit)).toBe(100);
        expect(await db.auditLog.count({ where: { action: 'POST_SALES_INVOICE_JOURNAL' } })).toBe(1);
        const health = await collectFinanceJournalIssues(db);
        expect(health.salesInvoicesUnposted).toEqual([]);
        expect(health.salesPaymentsMissing).toEqual([]);
    });

    it('surfaces the draft-journal anomaly and clears it only after recognition', async () => {
        await db.invoice.update({ where: { id: 'invoice' }, data: { status: 'UNPAID' } });
        expect((await collectFinanceJournalIssues(db)).salesInvoicesUnposted.map(i => i.id)).toEqual(['invoice']);
        await pay(100, 'PAY-1');
        expect((await collectFinanceJournalIssues(db)).salesInvoicesUnposted).toEqual([]);
    });

    it('rolls back every financial write when the receipt account is invalid', async () => {
        vi.mocked(resolveAccount).mockImplementation(async role => role === 'accounts-receivable' ? roleAccount(role) : { id: 'missing-account', code: 'NONE', name: 'Missing' });
        await expect(pay(100, 'PAY-FAIL')).rejects.toThrow();
        expect((await db.invoice.findUniqueOrThrow({ where: { id: 'invoice' } })).status).toBe('DRAFT');
        expect((await db.journalEntry.findUniqueOrThrow({ where: { id: 'sales-journal' } })).status).toBe('DRAFT');
        expect(await db.payment.count()).toBe(0);
        expect(await db.auditLog.count()).toBe(0);
    });

    it('blocks closed-period recognition but allows current payment of already posted old revenue', async () => {
        await db.fiscalPeriod.update({ where: { year_month: { year: 2026, month: 8 } }, data: { status: 'CLOSED' } });
        await expect(pay(100, 'PAY-BLOCKED', new Date('2026-09-07'))).rejects.toMatchObject({ code: 'FISCAL_PERIOD_CLOSED' });
        expect(await db.payment.count()).toBe(0);
        await db.journalEntry.update({ where: { id: 'sales-journal' }, data: { status: 'POSTED' } });
        await db.invoice.update({ where: { id: 'invoice' }, data: { status: 'UNPAID' } });
        await pay(100, 'PAY-CURRENT', new Date('2026-09-07'));
        expect(await db.payment.count()).toBe(1);
        expect((await db.journalEntry.findUniqueOrThrow({ where: { id: 'sales-journal' } })).entryDate).toEqual(august);
    });

    it('serializes concurrent payments so they cannot overpay the invoice', async () => {
        const outcomes = await Promise.allSettled([pay(80, 'PAY-A'), pay(80, 'PAY-B')]);
        expect(outcomes.filter(o => o.status === 'fulfilled')).toHaveLength(1);
        expect(outcomes.filter(o => o.status === 'rejected')).toHaveLength(1);
        expect(Number((await db.invoice.findUniqueOrThrow({ where: { id: 'invoice' } })).paidAmount)).toBe(80);
        expect(await db.payment.count()).toBe(1);
        expect(await db.journalEntry.count({ where: { referenceType: 'SALES_PAYMENT' } })).toBe(1);
    });
});
