import { Prisma } from '@prisma/client';
import { describe, expect, it } from 'vitest';
import { allocateHistoricalReturnCost } from '../sales-return-cost-basis';
const D=(s:string|number)=>new Prisma.Decimal(s);
const source={ movement:{id:'movement',type:'OUT',salesOrderId:'order',productVariantId:'variant',quantity:D(3)}, journal:{id:'source',status:'POSTED',referenceType:'MANUAL_ENTRY',referenceId:'movement',isAutoGenerated:true,lines:[{accountId:'cogs',debit:D(100),credit:D(0),currency:'IDR',exchangeRate:D(1)},{accountId:'inventory',debit:D(0),credit:D(100),currency:'IDR',exchangeRate:D(1)}]} };
describe('historical return HPP',()=>{
 it('reverses original GL accounts and exact cumulative amount, not selling price',()=>{
  const result=allocateHistoricalReturnCost(source,'1','1','GOOD');
  expect(result.amount.toFixed(2)).toBe('33.34');
  expect(result.lines.map(l=>[l.accountId,l.debit.toFixed(2),l.credit.toFixed(2)])).toEqual([['cogs','0.00','33.34'],['inventory','33.34','0.00']]);
 });
 it('does not restock saleable inventory or reverse COGS for damaged goods',()=>{
  expect(allocateHistoricalReturnCost(source,'0','1','DAMAGED')).toMatchObject({lines:[],restock:false});
 });
 it('rejects missing/voided/unbalanced/foreign movement historical evidence',()=>{
  expect(()=>allocateHistoricalReturnCost({...source,journal:null},'0','1','GOOD')).toThrow();
  expect(()=>allocateHistoricalReturnCost({...source,journal:{...source.journal,status:'VOIDED'}},'0','1','GOOD')).toThrow();
  expect(()=>allocateHistoricalReturnCost({...source,journal:{...source.journal,referenceId:'other'}},'0','1','GOOD')).toThrow();
  expect(()=>allocateHistoricalReturnCost({...source,journal:{...source.journal,lines:source.journal.lines.slice(0,1)}},'0','1','GOOD')).toThrow();
 });
 it('rejects over-return before valuation, including DAMAGED',()=>{
  expect(()=>allocateHistoricalReturnCost(source,'2','2','GOOD')).toThrow();
  expect(()=>allocateHistoricalReturnCost(source,'2','2','DAMAGED')).toThrow();
 });
 it('requires IDR at historical rate one rather than implicitly converting',()=>{
  expect(()=>allocateHistoricalReturnCost({...source,journal:{...source.journal,lines:source.journal.lines.map(l=>({...l,currency:'USD'}))}},'0','1','GOOD')).toThrow();
 });
});
