import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { Prisma } from '@prisma/client';
import { actor, createReturn, date, resetReturnFixture, returnTestClient } from './return-credit-postgres-fixture';

vi.mock('@/services/accounting/account-resolver', () => ({resolveAccount: async (role:string) => ({id:role==='sales-return'?'return':role==='vat-output'?'vat':role==='petty-cash'?'cash':role==='accounts-payable'?'ap':'ar'})}));
import { postReturnCredit, postReturnCreditInTransaction } from '../sales-return-credit-service';
import { reverseReturnCreditInTransaction } from '../sales-return-credit-reversal-service';
import { BarterSettlementService } from '../barter-settlement-service';
import { positiveSalesReceivableWhere } from '../sales-receivable-query';
vi.mock('@/services/settings/app-settings-service', () => ({ getPaymentBanksSetting: async () => [] }));
import { tenantContext } from '@/lib/core/prisma';
import { recordCustomerPaymentInTransaction } from '../customer-payment-service';
import { deleteCustomerPaymentInTransaction } from '../customer-payment-delete-service';
import { updateInvoiceStatus } from '../invoice-lifecycle-service';
const url = process.env.RETURN_CREDIT_TEST_DATABASE_URL;
const db = url ? returnTestClient(url) : null;
const post = (id='return-1', invoiceId='invoice', basisLineId='basis') => db!.$transaction(tx => postReturnCreditInTransaction(tx, {returnId:id,invoiceId,postingDate:date,lines:[{returnItemId:`${id}-item`,basisLineId}]},actor));

describe.skipIf(!db)('return credits on disposable PostgreSQL', () => {
    beforeEach(async()=> { await resetReturnFixture(db!); });
    afterAll(async()=>{ await db?.$disconnect(); });
    it('posts original net/tax atomically and leaves gross, paid, stock and cash untouched',async()=>{
        const result=await post();
        expect(result.status).toBe('POSTED');
        const invoice=await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}});
        expect(invoice.creditedAmount.toString()).toBe('222');
        expect(invoice.totalAmount.toString()).toBe('1110');
        expect(invoice.paidAmount.toString()).toBe('0');
        expect(await db!.payment.count()).toBe(0);
        expect(await db!.stockMovement.count()).toBe(1);
        const journal=await db!.journalEntry.findUniqueOrThrow({where:{id:result.journalId!},include:{lines:true}});
        expect(journal.lines.find(l=>l.accountId==='ar')?.credit.toString()).toBe('222');
        expect(journal.lines.find(l=>l.accountId==='vat')?.debit.toString()).toBe('22');
        expect(journal.lines.find(l=>l.accountId==='return')?.debit.toString()).toBe('200');
        expect(await db!.auditLog.count({where:{action:'POST_SALES_RETURN_CREDIT'}})).toBe(1);
    });
    it('allocates one return item across explicitly selected invoices without first-invoice or FIFO inference',async()=>{
        await db!.invoice.update({where:{id:'invoice'},data:{status:'DRAFT'}});
        await db!.invoice.update({where:{id:'invoice'},data:{totalAmount:111}});
        await db!.invoiceReturnBasisLine.update({where:{id:'basis'},data:{quantity:1,netAmount:100,taxAmount:11,discountAmount:25}});
        await db!.journalLine.updateMany({where:{journalEntryId:'source-journal',accountId:'ar'},data:{debit:111}});
        await db!.journalLine.updateMany({where:{journalEntryId:'source-journal',accountId:'revenue'},data:{credit:100}});
        await db!.journalLine.updateMany({where:{journalEntryId:'source-journal',accountId:'vat'},data:{credit:11}});
        await db!.invoice.create({data:{id:'invoice-2',invoiceNumber:'SECOND',salesOrderId:'order',totalAmount:999,status:'UNPAID',invoiceDate:date}});
        await db!.journalEntry.create({data:{id:'source-2',entryNumber:'SOURCE-2',entryDate:date,description:'Synthetic second invoice',referenceType:'SALES_INVOICE',referenceId:'invoice-2',status:'POSTED',isAutoGenerated:true,lines:{create:[{accountId:'ar',debit:999,credit:0},{accountId:'revenue',debit:0,credit:900},{accountId:'vat',debit:0,credit:99}]}}});
        await db!.invoiceReturnBasisLine.create({data:{id:'basis-2',invoiceId:'invoice-2',sourceItemId:'source-item',productVariantId:'variant',quantity:9,netAmount:900,taxAmount:99,discountAmount:225,sourceJournalId:'source-2',sourceEvidence:{version:1,capturedAtInvoiceCreation:true}}});
        await db!.invoice.update({where:{id:'invoice'},data:{status:'UNPAID'}});
        const input={returnId:'return-1',postingDate:date,lines:[{returnItemId:'return-1-item',basisLineId:'basis-2',quantity:'1'},{returnItemId:'return-1-item',basisLineId:'basis',quantity:'1'}]};
        const result=await db!.$transaction(tx=>postReturnCreditInTransaction(tx,input,actor));
        expect(result.status).toBe('POSTED');
        expect(await db!.salesReturnCreditAllocation.count()).toBe(2);
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('111');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice-2'}})).creditedAmount.toString()).toBe('111');
        expect((await db!.$transaction(tx=>postReturnCreditInTransaction(tx,input,actor))).id).toBe(result.id);
        expect(await db!.payment.count()).toBe(0);
    });
    it('serializes double-submit and returns the same committed result',async()=>{
        const results=await Promise.all([post(),post()]);
        expect(results[0].id).toBe(results[1].id);
        expect(await db!.salesReturnCreditAllocation.count()).toBe(1);
        expect(await db!.journalEntry.count({where:{referenceType:'SALES_RETURN'}})).toBe(1);
    });
    it('routes paid or excessive credit to review without credit/journal/Payment',async()=>{
        await db!.invoice.update({where:{id:'invoice'},data:{paidAmount:1000,status:'PARTIAL'}});
        expect((await post()).status).toBe('REVIEW_REQUIRED');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
        expect(await db!.salesReturnCreditAllocation.count()).toBe(0);
        expect(await db!.journalEntry.count({where:{referenceType:'SALES_RETURN'}})).toBe(0);
    });
    it('rolls back all writes when the caller transaction fails',async()=>{
        await expect(db!.$transaction(async tx=>{await postReturnCreditInTransaction(tx,{returnId:'return-1',invoiceId:'invoice',postingDate:date,lines:[{returnItemId:'return-1-item',basisLineId:'basis'}]},actor); throw new Error('injected failure');})).rejects.toThrow('injected failure');
        expect(await db!.salesReturnCredit.count()).toBe(0);
        expect(await db!.auditLog.count()).toBe(0);
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
    });
    it('does not credit a draft return',async()=>{
        await db!.salesReturn.update({where:{id:'return-1'},data:{status:'DRAFT'}});
        await expect(post()).rejects.toThrow();
        expect(await db!.salesReturnCredit.count()).toBe(0);
    });
    it('blocks legacy journals and missing original basis without reposting',async()=>{
        await db!.invoice.update({where:{id:'invoice'},data:{status:'DRAFT'}});
        await db!.invoiceReturnBasisLine.deleteMany();
        await db!.invoice.update({where:{id:'invoice'},data:{status:'UNPAID'}});
        expect((await post()).status).toBe('REVIEW_REQUIRED');
        expect(await db!.journalEntry.count()).toBe(1);
    });
    it('serializes two returns sharing an invoice and rejects over-allocation',async()=>{
        await resetReturnFixture(db!,true,6);
        await createReturn(db!,'return-2',6);
        const results=await Promise.allSettled([post(),post('return-2')]);
        expect(results.filter(r=>r.status==='fulfilled'&&r.value.status==='POSTED')).toHaveLength(1);
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('666');
    });
    it('blocks closed accounting periods with no side effects',async()=>{
        await db!.fiscalPeriod.updateMany({data:{status:'CLOSED'}});
        await expect(post()).rejects.toThrow();
        expect(await db!.salesReturnCredit.count()).toBe(0);
    });
    it('rejects foreign customer/order invoice and nonfinite input',async()=>{
        await db!.salesOrder.create({data:{id:'other-order',orderNumber:'OTHER',customerId:'customer'}});
        await db!.invoice.create({data:{id:'other',invoiceNumber:'OTHER',salesOrderId:'other-order',totalAmount:1110}});
        await expect(post('return-1','other')).rejects.toThrow();
        await expect(post('absent')).rejects.toThrow();
        expect(await db!.salesReturnCredit.count()).toBe(0);
    });
    it('rejects a changed replay allocation instead of silently accepting it',async()=>{
        await post();
        await expect(post('return-1','invoice','other-basis')).rejects.toThrow('alokasi berbeda');
        expect(await db!.salesReturnCreditAllocation.count()).toBe(1);
    });
    it('does not post again when a legacy return journal exists',async()=>{
        await db!.journalEntry.create({data:{id:'legacy',entryNumber:'LEGACY-RETURN',entryDate:date,description:'Synthetic legacy return',referenceType:'SALES_RETURN',referenceId:'return-1',status:'POSTED',isAutoGenerated:true}});
        expect((await post()).status).toBe('REVIEW_REQUIRED');
        expect(await db!.journalEntry.count({where:{referenceType:'SALES_RETURN'}})).toBe(1);
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
    });
    it('requires exact complete item allocation and matching product',async()=>{
        await expect(db!.$transaction(tx=>postReturnCreditInTransaction(tx,{returnId:'return-1',invoiceId:'invoice',postingDate:date,lines:[{returnItemId:'unknown',basisLineId:'basis'}]},actor))).rejects.toThrow('tepat satu kali');
        expect(await db!.salesReturnCredit.count()).toBe(0);
    });
    it('requires original issuance provenance, not just matching totals',async()=>{
        await db!.invoice.update({where:{id:'invoice'},data:{status:'DRAFT'}});
        await db!.invoiceReturnBasisLine.update({where:{id:'basis'},data:{sourceEvidence:{}}});
        await db!.invoice.update({where:{id:'invoice'},data:{status:'UNPAID'}});
        expect((await post()).status).toBe('REVIEW_REQUIRED');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
    });
    it('rejects cancelled invoice even if it has remaining balance',async()=>{
        await db!.invoice.update({where:{id:'invoice'},data:{status:'CANCELLED'}});
        await expect(post()).rejects.toThrow();
        expect(await db!.salesReturnCredit.count()).toBe(0);
    });
    it('rejects posting before the original invoice date and future business dates',async()=>{
        for (const postingDate of [new Date('2026-09-01T00:00:00+07:00'),new Date('2099-09-18T00:00:00+07:00')]) {
            await expect(db!.$transaction(tx=>postReturnCreditInTransaction(tx,{returnId:'return-1',invoiceId:'invoice',postingDate,lines:[{returnItemId:'return-1-item',basisLineId:'basis'}]},actor))).rejects.toThrow();
        }
        expect(await db!.salesReturnCredit.count()).toBe(0);
    });
    it('refuses snapshots exceeding the original invoice total',async()=>{
        await db!.invoice.update({where:{id:'invoice'},data:{status:'DRAFT'}});
        await db!.invoiceReturnBasisLine.update({where:{id:'basis'},data:{netAmount:5000}});
        await db!.invoice.update({where:{id:'invoice'},data:{status:'UNPAID'}});
        expect((await post()).status).toBe('REVIEW_REQUIRED');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
    });
    it('allows exact final settlement',async()=>{
        await resetReturnFixture(db!,true,10);
        expect((await post()).status).toBe('POSTED');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).status).toBe('PAID');
    });
    it('rolls back financial writes when audit insertion fails',async()=>{
        await db!.$executeRawUnsafe(`CREATE FUNCTION reject_return_test_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic audit unavailable'; END $$`);
        await db!.$executeRawUnsafe(`CREATE TRIGGER reject_return_test_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION reject_return_test_audit()`);
        try {
            await expect(post()).rejects.toThrow('synthetic audit unavailable');
            expect(await db!.salesReturnCredit.count()).toBe(0);
            expect(await db!.journalEntry.count({where:{referenceType:'SALES_RETURN'}})).toBe(0);
            expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
        } finally {
            await db!.$executeRawUnsafe(`DROP TRIGGER reject_return_test_audit ON "AuditLog"`);
            await db!.$executeRawUnsafe('DROP FUNCTION reject_return_test_audit()');
        }
    });
    it('routes concurrent tenant contexts to independent databases without main fallback',async()=>{
        const otherUrl=new URL(url!); otherUrl.pathname='/polyflow_return_credit_tenant_test';
        const other=returnTestClient(otherUrl.toString());
        try {
            await resetReturnFixture(other);
            await other.salesReturn.update({where:{id:'return-1'},data:{status:'DRAFT'}});
            const input={returnId:'return-1',invoiceId:'invoice',postingDate:date,lines:[{returnItemId:'return-1-item',basisLineId:'basis'}]};
            const results=await Promise.allSettled([
                tenantContext.run(db!,()=>postReturnCredit(input,actor)),
                tenantContext.run(other,()=>postReturnCredit(input,actor)),
            ]);
            if (results[0].status === 'rejected') throw results[0].reason;
            expect(results[0].status).toBe('fulfilled');
            expect(results[1].status).toBe('rejected');
            expect((await other.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
            expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('222');
            expect(await other.salesReturnCredit.count()).toBe(0);
        } finally { await other.$disconnect(); }
    });
    it('rejects mutation without tenant context before touching any database',async()=>{
        await expect(postReturnCredit({},actor)).rejects.toThrow('Konteks tenant wajib');
    });
    it('rejects payment above net balance and settles the exact remainder after return credit',async()=>{
        await db!.account.create({data:{id:'cash',code:'11100',name:'Synthetic Cash',type:'ASSET',category:'CURRENT_ASSET',isCashAccount:true}});
        await post();
        const pay=(amount:number,number:string)=>db!.$transaction(tx=>recordCustomerPaymentInTransaction(tx,{invoiceId:'invoice',amount,paymentDate:date,method:'Cash'},number,actor));
        await expect(pay(889,'PAY-OVER')).rejects.toThrow('sisa tagihan');
        await pay(888,'PAY-EXACT');
        const invoice=await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}});
        expect(invoice.status).toBe('PAID');
        expect(invoice.paidAmount.toString()).toBe('888');
        expect(invoice.creditedAmount.toString()).toBe('222');
        expect(await db!.payment.count()).toBe(1);
        const balance=await db!.journalLine.aggregate({where:{accountId:'ar',journalEntry:{status:'POSTED'}},_sum:{debit:true,credit:true}});
        expect(balance._sum.debit!.minus(balance._sum.credit!).toString()).toBe('0');
    });
    it('serializes payment competing with return credit without over-settlement',async()=>{
        await db!.account.create({data:{id:'cash',code:'11100',name:'Synthetic Cash',type:'ASSET',category:'CURRENT_ASSET',isCashAccount:true}});
        const outcomes=await Promise.allSettled([post(),db!.$transaction(tx=>recordCustomerPaymentInTransaction(tx,{invoiceId:'invoice',amount:1000,paymentDate:date,method:'Cash'},'PAY-RACE',actor))]);
        expect(outcomes.some(o=>o.status==='fulfilled')).toBe(true);
        const invoice=await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}});
        expect(invoice.paidAmount.plus(invoice.creditedAmount).lte(invoice.totalAmount)).toBe(true);
    });
    it('deletes customer payment without deleting credit and recalculates net status atomically',async()=>{
        await db!.account.create({data:{id:'cash',code:'11100',name:'Synthetic Cash',type:'ASSET',category:'CURRENT_ASSET',isCashAccount:true}});
        await post();
        const payment=await db!.$transaction(tx=>recordCustomerPaymentInTransaction(tx,{invoiceId:'invoice',amount:888,paymentDate:date,method:'Cash'},'PAY-DELETE',actor));
        await db!.$transaction(tx=>deleteCustomerPaymentInTransaction(tx,payment.id,actor));
        const invoice=await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}});
        expect(invoice.paidAmount.toString()).toBe('0');
        expect(invoice.creditedAmount.toString()).toBe('222');
        expect(invoice.status).toBe('PARTIAL');
        expect(await db!.payment.count()).toBe(0);
        expect(await db!.journalEntry.count({where:{referenceType:'SALES_RETURN'}})).toBe(1);
        expect(await db!.journalEntry.count({where:{referenceType:'SALES_PAYMENT'}})).toBe(0);
        expect(await db!.auditLog.count({where:{action:'DELETE_PAYMENT'}})).toBe(1);
    });
    it('concurrent delete attempts cannot subtract the same payment twice',async()=>{
        await db!.account.create({data:{id:'cash',code:'11100',name:'Synthetic Cash',type:'ASSET',category:'CURRENT_ASSET',isCashAccount:true}});
        const payment=await db!.$transaction(tx=>recordCustomerPaymentInTransaction(tx,{invoiceId:'invoice',amount:100,paymentDate:date,method:'Cash'},'PAY-DELETE-RACE',actor));
        const outcomes=await Promise.allSettled([db!.$transaction(tx=>deleteCustomerPaymentInTransaction(tx,payment.id,actor)),db!.$transaction(tx=>deleteCustomerPaymentInTransaction(tx,payment.id,actor))]);
        expect(outcomes.filter(r=>r.status==='fulfilled')).toHaveLength(1);
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).paidAmount.toString()).toBe('0');
    });
    it('rolls back payment deletion when audit insertion fails, preserving credit and cash journal',async()=>{
        await db!.account.create({data:{id:'cash',code:'11100',name:'Synthetic Cash',type:'ASSET',category:'CURRENT_ASSET',isCashAccount:true}});
        await post();
        const payment=await db!.$transaction(tx=>recordCustomerPaymentInTransaction(tx,{invoiceId:'invoice',amount:100,paymentDate:date,method:'Cash'},'PAY-AUDIT',actor));
        await db!.$executeRawUnsafe(`CREATE FUNCTION reject_delete_test_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic delete audit unavailable'; END $$`);
        await db!.$executeRawUnsafe(`CREATE TRIGGER reject_delete_test_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION reject_delete_test_audit()`);
        try {
            await expect(db!.$transaction(tx=>deleteCustomerPaymentInTransaction(tx,payment.id,actor))).rejects.toThrow('synthetic delete audit unavailable');
            expect(await db!.payment.count()).toBe(1);
            expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).paidAmount.toString()).toBe('100');
            expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('222');
            expect(await db!.journalEntry.count({where:{referenceType:'SALES_PAYMENT'}})).toBe(1);
        } finally {
            await db!.$executeRawUnsafe(`DROP TRIGGER reject_delete_test_audit ON "AuditLog"`);
            await db!.$executeRawUnsafe('DROP FUNCTION reject_delete_test_audit()');
        }
    });
    it('does not delete payments already reconciled to the bank',async()=>{
        await db!.account.create({data:{id:'cash',code:'11100',name:'Synthetic Cash',type:'ASSET',category:'CURRENT_ASSET',isCashAccount:true}});
        const payment=await db!.$transaction(tx=>recordCustomerPaymentInTransaction(tx,{invoiceId:'invoice',amount:100,paymentDate:date,method:'Cash'},'PAY-RECONCILED',actor));
        await db!.journalLine.updateMany({where:{journalEntry:{referenceId:payment.id,referenceType:'SALES_PAYMENT'}},data:{reconciledAt:new Date()}});
        await expect(db!.$transaction(tx=>deleteCustomerPaymentInTransaction(tx,payment.id,actor))).rejects.toThrow('direkonsiliasi');
        expect(await db!.payment.count()).toBe(1);
    });
    it('cannot cancel an invoice behind posted return credit',async()=>{
        await post();
        await expect(db!.$transaction(tx=>updateInvoiceStatus({id:'invoice',status:'CANCELLED'},actor,tx))).rejects.toThrow('kredit retur');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).status).toBe('PARTIAL');
        expect((await db!.journalEntry.findUniqueOrThrow({where:{id:'source-journal'}})).status).toBe('POSTED');
    });
    it('compensates a posted credit exactly once without deleting history or issuing money',async()=>{
        const posted=await post();
        const reverse=()=>db!.$transaction(tx=>reverseReturnCreditInTransaction(tx,{returnId:'return-1',reversalDate:date,reason:'Synthetic correction'},actor));
        const results=await Promise.all([reverse(),reverse()]);
        expect(results[0].id).toBe(results[1].id);
        expect(results[0].status).toBe('REVERSED');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
        expect(await db!.salesReturnCreditAllocation.count()).toBe(1);
        expect((await db!.journalEntry.findUniqueOrThrow({where:{id:posted.journalId!}})).status).toBe('POSTED');
        expect(await db!.journalEntry.count({where:{referenceId:posted.id}})).toBe(1);
        expect(await db!.payment.count()).toBe(0);
        await expect(post()).rejects.toThrow('dibalik');
    });
    it('rejects unauthorized direct ledger/cache/history mutations',async()=>{
        const posted=await post();
        await expect(db!.invoice.update({where:{id:'invoice'},data:{creditedAmount:0}})).rejects.toThrow('ledger');
        await expect(db!.salesReturnCredit.delete({where:{id:posted.id}})).rejects.toThrow('history');
        await expect(db!.salesReturnCreditAllocation.updateMany({data:{netAmount:0}})).rejects.toThrow('immutable');
        await expect(db!.invoiceReturnBasisLine.update({where:{id:'basis'},data:{quantity:11}})).rejects.toThrow('immutable');
        await expect(db!.journalEntry.update({where:{id:posted.journalId!},data:{status:'VOIDED'}})).rejects.toThrow('immutable');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('222');
    });
    it('rejects reversal in a closed period and rolls back without touching credit',async()=>{
        await post();
        await db!.fiscalPeriod.updateMany({data:{status:'CLOSED'}});
        await expect(db!.$transaction(tx=>reverseReturnCreditInTransaction(tx,{returnId:'return-1',reversalDate:date,reason:'Synthetic correction'},actor))).rejects.toThrow('Periode');
        expect((await db!.salesReturnCredit.findFirstOrThrow()).status).toBe('POSTED');
    });
    it('generated net balance filters fully credited stale-status invoices before count/limit',async()=>{
        await resetReturnFixture(db!,true,10);
        await post();
        await db!.invoice.update({where:{id:'invoice'},data:{status:'PARTIAL'}});
        await db!.invoice.create({data:{id:'open-invoice',invoiceNumber:'OPEN',salesOrderId:'order',totalAmount:10,status:'UNPAID',invoiceDate:date}});
        const where=positiveSalesReceivableWhere();
        expect(await db!.invoice.count({where})).toBe(1);
        expect((await db!.invoice.findMany({where,take:1}))[0].id).toBe('open-invoice');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).remainingAmount.toString()).toBe('0');
    });
    it('serializes credit against barter and compensation against void/payment deletion',async()=>{
        await db!.supplier.create({data:{id:'supplier',name:'Synthetic Partner'}});
        await db!.barterPartner.create({data:{id:'partner',customerId:'customer',supplierId:'supplier',isActive:true,createdById:actor,updatedById:actor}});
        await db!.account.create({data:{id:'ap',code:'21100',name:'AP',type:'LIABILITY',category:'CURRENT_LIABILITY'}});
        await db!.purchaseOrder.create({data:{id:'purchase',orderNumber:'PO-TEST',supplierId:'supplier',totalAmount:1110}});
        await db!.purchaseInvoice.create({data:{id:'payable',invoiceNumber:'AP-TEST',purchaseOrderId:'purchase',totalAmount:1110,status:'UNPAID',invoiceDate:date}});
        await db!.journalEntry.create({data:{id:'ap-source',entryNumber:'AP-SOURCE',entryDate:date,description:'Synthetic AP',referenceType:'PURCHASE_INVOICE',referenceId:'payable',status:'POSTED',isAutoGenerated:true,lines:{create:[{accountId:'inventory',debit:1110,credit:0},{accountId:'ap',debit:0,credit:1110}]}}});
        const barter=()=>tenantContext.run(db!,()=>BarterSettlementService.create({invoiceId:'invoice',purchaseInvoiceId:'payable',barterAmount:'888',barterDate:date,includeCashPayment:false,cashAmount:'0',notes:'Synthetic',idempotencyKey:'return-barter-race-key'},actor));
        const outcomes=await Promise.all([post(),barter()]);
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).remainingAmount.toString()).toBe('0');
        await Promise.all([
            db!.$transaction(tx=>reverseReturnCreditInTransaction(tx,{returnId:'return-1',reversalDate:date,reason:'Synthetic correction'},actor)),
            tenantContext.run(db!,()=>BarterSettlementService.void({settlementId:outcomes[1].id,reason:'Synthetic void'},actor)),
        ]);
        const invoice=await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}});
        expect(invoice.paidAmount.toString()).toBe('0');expect(invoice.creditedAmount.toString()).toBe('0');expect(invoice.remainingAmount.toString()).toBe('1110');
        expect(await db!.salesReturnCreditAllocation.count()).toBe(1);
    });
    it('rolls back compensation when audit fails and exposes validation failure before callback returns',async()=>{
        await post();
        await db!.$executeRawUnsafe(`CREATE FUNCTION reject_reversal_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='REVERSE_SALES_RETURN_CREDIT' THEN RAISE EXCEPTION 'synthetic reversal audit unavailable'; END IF; RETURN NEW; END $$`);
        await db!.$executeRawUnsafe(`CREATE TRIGGER reject_reversal_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION reject_reversal_audit()`);
        try {
            await expect(db!.$transaction(tx=>reverseReturnCreditInTransaction(tx,{returnId:'return-1',reversalDate:date,reason:'Synthetic correction'},actor))).rejects.toThrow('audit unavailable');
            expect((await db!.salesReturnCredit.findFirstOrThrow()).status).toBe('POSTED');
            expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('222');
            expect(await db!.journalEntry.count()).toBe(2);
        } finally {
            await db!.$executeRawUnsafe('DROP TRIGGER reject_reversal_audit ON "AuditLog"');
            await db!.$executeRawUnsafe('DROP FUNCTION reject_reversal_audit()');
        }
        await expect(db!.$transaction(async tx=>{
            await tx.$executeRaw`SET CONSTRAINTS invoice_return_credit_ledger DEFERRED`;
            await tx.invoice.update({where:{id:'invoice'},data:{creditedAmount:999}});
            await tx.$executeRaw`SET CONSTRAINTS invoice_return_credit_ledger IMMEDIATE`;
        })).rejects.toThrow('ledger');
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('222');
    });
    it('never credits legacy received status without verifiable receipt evidence',async()=>{
        await resetReturnFixture(db!,false);
        expect((await post()).status).toBe('REVIEW_REQUIRED');
        expect(await db!.salesReturnCreditAllocation.count()).toBe(0);
    });
    it('preserves residual cents after reversing one of several partial credits',async()=>{
        await resetReturnFixture(db!,true,1);
        await db!.invoice.update({where:{id:'invoice'},data:{status:'DRAFT'}});
        await db!.invoice.update({where:{id:'invoice'},data:{totalAmount:0.05}});
        await db!.invoiceReturnBasisLine.update({where:{id:'basis'},data:{quantity:3,netAmount:0.05,taxAmount:0,discountAmount:0}});
        await db!.journalLine.updateMany({where:{journalEntryId:'source-journal',accountId:'ar'},data:{debit:0.05}});
        await db!.journalLine.updateMany({where:{journalEntryId:'source-journal',accountId:'revenue'},data:{credit:0.05}});
        await db!.journalLine.updateMany({where:{journalEntryId:'source-journal',accountId:'vat'},data:{credit:0}});
        await db!.invoice.update({where:{id:'invoice'},data:{status:'UNPAID'}});
        await post();await createReturn(db!,'return-2',1);await post('return-2');
        await db!.$transaction(tx=>reverseReturnCreditInTransaction(tx,{returnId:'return-1',reversalDate:date,reason:'Synthetic rounding correction'},actor));
        await createReturn(db!,'return-3',2);await post('return-3');
        const invoice=await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}});
        expect(invoice.creditedAmount.toString()).toBe('0.05');expect(invoice.remainingAmount.toString()).toBe('0');
    });
    it('waits for a concurrently closing period and rejects without posting',async()=>{
        let release!:()=>void;let ready!:()=>void;
        const held=new Promise<void>(resolve=>{ready=resolve;});const gate=new Promise<void>(resolve=>{release=resolve;});
        let pid=0;
        const closing=db!.$transaction(async tx=>{
            pid=(await tx.$queryRaw<{pid:number}[]>`SELECT pg_backend_pid() pid`)[0].pid;
            await tx.$queryRaw`SELECT id FROM "FiscalPeriod" WHERE year=2026 AND month=9 FOR UPDATE`;
            ready();await gate;await tx.fiscalPeriod.updateMany({data:{status:'CLOSED'}});
        },{timeout:15000});
        await held;const pending=Promise.allSettled([post()]);
        try {
            let blocked=false;
            for(let i=0;i<100;i++){
                blocked=(await db!.$queryRaw<{blocked:boolean}[]>`SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE datname=current_database() AND ${pid}=ANY(pg_blocking_pids(pid))) blocked`)[0].blocked;
                if(blocked)break;await new Promise(resolve=>setTimeout(resolve,20));
            }
            expect(blocked).toBe(true);
        }finally{release();await closing;}
        expect((await pending)[0].status).toBe('rejected');expect(await db!.salesReturnCredit.count()).toBe(0);
    });
    it('serializes credit/payment deletion and compensation/payment deletion without losing balances',async()=>{
        await db!.account.create({data:{id:'cash',code:'11100',name:'Synthetic Cash',type:'ASSET',category:'CURRENT_ASSET',isCashAccount:true}});
        const pay=()=>db!.$transaction(tx=>recordCustomerPaymentInTransaction(tx,{invoiceId:'invoice',amount:100,paymentDate:date,method:'Cash'},'DELETE-CREDIT-RACE',actor));
        const payment=await pay();
        await Promise.all([post(),db!.$transaction(tx=>deleteCustomerPaymentInTransaction(tx,payment.id,actor))]);
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).remainingAmount.toString()).toBe('888');
        const second=await pay();
        await Promise.all([
            db!.$transaction(tx=>deleteCustomerPaymentInTransaction(tx,second.id,actor)),
            db!.$transaction(tx=>reverseReturnCreditInTransaction(tx,{returnId:'return-1',reversalDate:date,reason:'Synthetic concurrent correction'},actor)),
        ]);
        const invoice=await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}});
        expect(invoice.remainingAmount.toString()).toBe('1110');expect(invoice.paidAmount.toString()).toBe('0');expect(invoice.creditedAmount.toString()).toBe('0');
        expect(await db!.payment.count()).toBe(0);expect(await db!.salesReturnCreditAllocation.count()).toBe(1);
    });
    it('routes repeated SKU source lines to review rather than guessing shipment price attribution',async()=>{
        await db!.salesOrderItem.create({data:{id:'ambiguous-source',salesOrderId:'order',productVariantId:'variant',quantity:1,unitPrice:999,subtotal:999}});
        expect((await post()).status).toBe('REVIEW_REQUIRED');
        expect(await db!.salesReturnCreditAllocation.count()).toBe(0);
        expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
    });
    it('database check prevents a negative credited amount',async()=>{
        await expect(db!.invoice.update({where:{id:'invoice'},data:{creditedAmount:new Prisma.Decimal(-1)}})).rejects.toThrow();
    });
});
