import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { actor, createReturn, date, resetReturnFixture, returnTestClient } from './return-credit-postgres-fixture';
vi.mock('@/services/accounting/account-resolver',()=>({resolveAccount:async(role:string)=>({id:role==='accounts-receivable'?'ar':role==='vat-output'?'vat':role==='sales-return'?'return':'cash'})}));
import { receiveReturnInTransaction } from '../sales-return-receipt-service';
import { receiveSalesReturn } from '@/services/sales/return-receiving-service';
import { transitionSalesReturn } from '@/services/sales/return-status-service';
import { postReturnCredit } from '../sales-return-credit-service';
import { recordCustomerPaymentInTransaction } from '../customer-payment-service';
import { tenantContext } from '@/lib/core/prisma';
import { captureInvoiceReturnBasis } from '../invoice-return-basis-capture';
const connection=process.env.RETURN_CREDIT_TEST_DATABASE_URL;
const receiptUrl=connection?new URL(connection):null;
if(receiptUrl)receiptUrl.pathname='/polyflow_return_receipt_scope_test';
const db=receiptUrl?returnTestClient(receiptUrl.toString()):null;
const receive=()=>db!.$transaction(tx=>receiveReturnInTransaction(tx,{returnId:'return-1',receivedAt:date,lines:[{returnItemId:'return-1-item',sourceMovementId:'shipment'}]},actor));
describe.skipIf(!db)('return receiving uses original shipment cost',()=>{
 beforeEach(async()=>{
  await resetReturnFixture(db!,false);
  await db!.stockMovement.delete({where:{id:'credit-source-movement'}});
  await db!.salesReturn.update({where:{id:'return-1'},data:{status:'CONFIRMED'}});
  await db!.stockMovement.create({data:{id:'shipment',createdAt:date,type:'OUT',salesOrderId:'order',productVariantId:'variant',fromLocationId:'location',quantity:10,reference:'Synthetic original shipment'}});
  await db!.journalEntry.create({data:{id:'shipment-journal',entryNumber:'SHIP-JE',entryDate:date,description:'Synthetic cost',referenceType:'MANUAL_ENTRY',referenceId:'shipment',status:'POSTED',isAutoGenerated:true,lines:{create:[{accountId:'cogs',debit:600,credit:0},{accountId:'inventory',debit:0,credit:600}]}}});
 });
 afterAll(async()=>{await db?.$disconnect();});
 it('restocks at original 60/unit instead of 70% of entered 999 selling price',async()=>{
  await receive();
  const receipt=await db!.salesReturnReceiptLine.findUniqueOrThrow({where:{returnItemId:'return-1-item'}});
  expect(receipt.restockValue.toString()).toBe('120');
  expect((await db!.inventory.findFirstOrThrow()).quantity.toString()).toBe('2');
  expect((await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}})).creditedAmount.toString()).toBe('0');
  expect(await db!.journalEntry.count({where:{referenceType:'SALES_RETURN'}})).toBe(0);
 });
 it('preserves historical value in destination weighted-average inventory cost',async()=>{
  await db!.inventory.create({data:{locationId:'location',productVariantId:'variant',quantity:3,averageCost:100}});
  await receive();
  const inventory=await db!.inventory.findFirstOrThrow();
  expect(inventory.quantity.toString()).toBe('5');
  expect(inventory.averageCost?.toString()).toBe('84');
 });
 it('initializes an empty destination with historical cost, not a master fallback',async()=>{
  await db!.productVariant.update({where:{id:'variant'},data:{standardCost:999}});
  await receive();
  expect((await db!.inventory.findFirstOrThrow()).averageCost?.toString()).toBe('60');
 });
 it('rejects unknown valuation of existing stock instead of diluting it to zero',async()=>{
  await db!.inventory.create({data:{locationId:'location',productVariantId:'variant',quantity:3,averageCost:null}});
  await expect(receive()).rejects.toThrow('valuasi');
  expect((await db!.inventory.findFirstOrThrow()).quantity.toString()).toBe('3');
  expect(await db!.salesReturnReceiptLine.count()).toBe(0);
 });
 it('double receive never restocks or posts twice',async()=>{
  await Promise.all([receive(),receive()]);
  expect(await db!.salesReturnReceiptLine.count()).toBe(1);
  expect((await db!.inventory.findFirstOrThrow()).quantity.toString()).toBe('2');
 });
 it('does not add damaged goods to saleable inventory or reverse their COGS',async()=>{
  await db!.salesReturnItem.update({where:{id:'return-1-item'},data:{condition:'DAMAGED'}});
  await receive();
  expect(await db!.inventory.count()).toBe(0);
  expect(await db!.journalEntry.count()).toBe(2);
  expect((await db!.salesReturnReceiptLine.findFirstOrThrow()).restockValue.toString()).toBe('0');
 });
 it('rolls back receipt when historical journal is missing',async()=>{
  await db!.journalEntry.delete({where:{id:'shipment-journal'}});
  await expect(receive()).rejects.toThrow();
  expect(await db!.salesReturnReceiptLine.count()).toBe(0);
  expect(await db!.inventory.count()).toBe(0);
  expect((await db!.salesReturn.findUniqueOrThrow({where:{id:'return-1'}})).status).toBe('CONFIRMED');
 });
 it('rejects reversals using the exact existing shipment-reversal reference convention',async()=>{
  await db!.stockMovement.create({data:{id:'reversed',type:'IN',salesOrderId:'order',productVariantId:'variant',toLocationId:'location',quantity:10,reference:'VOID: Synthetic original shipment [SOURCE:delivery]'}});
  await expect(receive()).rejects.toThrow('dibalik');
  expect(await db!.salesReturnReceiptLine.count()).toBe(0);
 });
 it('serializes cumulative quantities across two returns for the same shipment',async()=>{
  await db!.salesReturnItem.update({where:{id:'return-1-item'},data:{returnedQty:6}});
  await createReturn(db!,'return-2',6,false);
  await db!.salesReturn.update({where:{id:'return-2'},data:{status:'CONFIRMED'}});
  const result=await Promise.allSettled([receive(),db!.$transaction(tx=>receiveReturnInTransaction(tx,{returnId:'return-2',receivedAt:date,lines:[{returnItemId:'return-2-item',sourceMovementId:'shipment'}]},actor))]);
  expect(result.filter(r=>r.status==='fulfilled')).toHaveLength(1);
  expect((await db!.inventory.findFirstOrThrow()).quantity.toString()).toBe('6');
 });
 it('blocks future or pre-document receipt dates',async()=>{
  for(const receivedAt of [new Date('2099-01-01'),new Date('2026-09-01T00:00:00+07:00')]) {
   await expect(db!.$transaction(tx=>receiveReturnInTransaction(tx,{returnId:'return-1',receivedAt,lines:[{returnItemId:'return-1-item',sourceMovementId:'shipment'}]},actor))).rejects.toThrow();
  }
  expect(await db!.inventory.count()).toBe(0);
 });
 it('does not restock legacy received returns without exact receipt evidence',async()=>{
  await db!.salesReturn.update({where:{id:'return-1'},data:{status:'RECEIVED'}});
  await expect(receive()).rejects.toThrow('jangan restock ulang');
 });
 it('rolls back inventory and receipt if a historical account is inactive',async()=>{
  await db!.account.update({where:{id:'inventory'},data:{isActive:false}});
  await expect(receive()).rejects.toThrow('tidak aktif');
  expect(await db!.inventory.count()).toBe(0);
  expect(await db!.salesReturnReceiptLine.count()).toBe(0);
 });
 it('runs receive → complete → Finance credit → cash remainder with matching stock and AR journals',async()=>{
  await db!.account.create({data:{id:'cash',code:'11100',name:'Synthetic Cash',type:'ASSET',category:'CURRENT_ASSET',isCashAccount:true}});
  await db!.invoice.update({where:{id:'invoice'},data:{status:'DRAFT'}});
  await db!.invoiceReturnBasisLine.deleteMany();
  expect(await db!.$transaction(tx=>captureInvoiceReturnBasis(tx,'invoice'))).toBe('CAPTURED');
  await db!.invoice.update({where:{id:'invoice'},data:{status:'UNPAID'}});
  const basis=await db!.invoiceReturnBasisLine.findFirstOrThrow();
  await tenantContext.run(db!,()=>receiveSalesReturn('return-1',actor));
  await tenantContext.run(db!,()=>transitionSalesReturn('return-1',actor,'COMPLETED'));
  // The service records today's receipt; the credit cannot predate that actual receipt.
  const receivedAt=(await db!.salesReturnReceiptLine.findUniqueOrThrow({where:{returnItemId:'return-1-item'}})).receivedAt;
  const result=await tenantContext.run(db!,()=>postReturnCredit({returnId:'return-1',invoiceId:'invoice',postingDate:receivedAt,lines:[{returnItemId:'return-1-item',basisLineId:basis.id}]},actor));
  expect(result.status).toBe('POSTED');
  await db!.$transaction(tx=>recordCustomerPaymentInTransaction(tx,{invoiceId:'invoice',amount:888,paymentDate:date,method:'Cash'},'PAY-LIFECYCLE',actor));
  const invoice=await db!.invoice.findUniqueOrThrow({where:{id:'invoice'}});
  expect(invoice.status).toBe('PAID');
  expect(invoice.creditedAmount.toString()).toBe('222');
  expect(invoice.paidAmount.toString()).toBe('888');
  expect((await db!.inventory.findFirstOrThrow()).quantity.toString()).toBe('2');
  expect((await db!.salesReturnReceiptLine.findFirstOrThrow()).restockValue.toString()).toBe('120');
  const ar=await db!.journalLine.aggregate({where:{accountId:'ar',journalEntry:{status:'POSTED'}},_sum:{debit:true,credit:true}});
  expect(ar._sum.debit!.minus(ar._sum.credit!).toString()).toBe('0');
 });
 it('serializes cancellation against receipt without leaving received stock on a cancelled return',async()=>{
  const outcomes=await Promise.allSettled([
   tenantContext.run(db!,()=>receiveSalesReturn('return-1',actor)),
   tenantContext.run(db!,()=>transitionSalesReturn('return-1',actor,'CANCELLED')),
  ]);
  expect(outcomes.filter(result=>result.status==='fulfilled')).toHaveLength(1);
  const row=await db!.salesReturn.findUniqueOrThrow({where:{id:'return-1'}});
  expect(await db!.salesReturnReceiptLine.count()).toBe(row.status==='RECEIVED'?1:0);
  expect(await db!.inventory.count()).toBe(row.status==='RECEIVED'?1:0);
 });
 it('rolls back quantity, valuation, movement and status if receipt audit fails',async()=>{
  await db!.$executeRawUnsafe(`CREATE FUNCTION reject_receipt_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='RECEIVE_SALES_RETURN' THEN RAISE EXCEPTION 'synthetic receipt audit unavailable'; END IF; RETURN NEW; END $$`);
  await db!.$executeRawUnsafe(`CREATE TRIGGER reject_receipt_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION reject_receipt_audit()`);
  try {
   await expect(receive()).rejects.toThrow('audit unavailable');
   expect(await db!.inventory.count()).toBe(0);expect(await db!.salesReturnReceiptLine.count()).toBe(0);
   expect(await db!.stockMovement.count()).toBe(1);expect(await db!.journalEntry.count()).toBe(2);
   expect((await db!.salesReturn.findUniqueOrThrow({where:{id:'return-1'}})).status).toBe('CONFIRMED');
  }finally{await db!.$executeRawUnsafe('DROP TRIGGER reject_receipt_audit ON "AuditLog"');await db!.$executeRawUnsafe('DROP FUNCTION reject_receipt_audit()');}
 });
 it('rejects a balanced non-COGS journal masquerading as shipment evidence',async()=>{
  await db!.journalLine.updateMany({where:{journalEntryId:'shipment-journal',accountId:'cogs'},data:{accountId:'revenue'}});
  await expect(receive()).rejects.toThrow('HPP historis');
  expect(await db!.inventory.count()).toBe(0);
 });
 it('rejects source shipment belonging to another order',async()=>{
  await db!.stockMovement.update({where:{id:'shipment'},data:{salesOrderId:null}});
  await expect(receive()).rejects.toThrow();
  expect(await db!.salesReturnReceiptLine.count()).toBe(0);
 });
});
