/** Tombol & aksi umum */
export const actionLabels = {
  create: 'Buat',
  save: 'Simpan',
  update: 'Perbarui',
  delete: 'Hapus',
  cancel: 'Batal',
  confirm: 'Konfirmasi',
  approve: 'Setujui',
  reject: 'Tolak',
  submit: 'Kirim',
  export: 'Ekspor',
  import: 'Impor',
  print: 'Cetak',
  search: 'Cari',
  filter: 'Filter',
  reset: 'Reset',
  refresh: 'Segarkan',
  close: 'Tutup',
  back: 'Kembali',
  edit: 'Edit',
  add: 'Tambah',
  view: 'Lihat',
  download: 'Unduh',
} as const;

/** Unit display */
export const unitLabels = {
  kg: 'KG',
  roll: 'Roll',
  bal: 'Bal',
  pcs: 'Pcs',
  zak: 'Zak',
  meter: 'Meter',
  sheet: 'Lembar',
} as const;

/** Form field labels umum */
export const formLabels = {
  name: 'Nama',
  email: 'Email',
  phone: 'Telepon',
  address: 'Alamat',
  notes: 'Catatan',
  description: 'Deskripsi',
  date: 'Tanggal',
  qty: 'Qty',
  jumlah: 'Jumlah',
  kuantitas: 'Kuantitas',
  unit: 'Satuan',
  price: 'Harga',
  total: 'Total',
  grandTotal: 'Total Keseluruhan',
  status: 'Status',
  type: 'Tipe',
  category: 'Kategori',
  product: 'Produk',
  unitPrice: 'Harga Satuan',
  subtotal: 'Subtotal',
  action: 'Aksi',
  actions: 'Aksi',
  createdOn: 'Dibuat pada',
  reference: 'Referensi',
  referenceOrder: 'Referensi Pesanan',
  customerInfo: 'Informasi Customer',
  invoiceItems: 'Item Invoice',
  unknown: 'Tidak Diketahui',
  legacyInternalOrder: 'Pesanan Internal (Legacy)',
  legacyInternalOrderHint: 'Pesanan internal legacy, tidak bisa dibuat invoice baru',
} as const;
