/** Finance / Accounting */
export const financeLabels = {
  finance: 'Finance',
  accounting: 'Akuntansi',
  chartOfAccounts: 'Bagan Akun',
  coa: 'COA',
  journalEntry: 'Jurnal',
  generalLedger: 'Buku Besar',
  gl: 'GL',
  balanceSheet: 'Neraca',
  incomeStatement: 'Laba Rugi',
  cashflow: 'Arus Kas',
  accountsReceivable: 'Piutang',
  ar: 'AR',
  accountsPayable: 'Utang',
  ap: 'AP',
  fiscalPeriod: 'Periode Fiskal',
  fixedAsset: 'Aset Tetap',
  budget: 'Anggaran',
  costing: 'HPP',
  cogm: 'HPP Produksi',
  cogs: 'HPP Penjualan',
  wipValuation: 'Valuasi WIP',
} as const;
