/** Kiosk Operator */
export const kioskLabels = {
  jobList: 'Daftar SPK',
  selectJob: 'Pilih SPK untuk mulai atau kelola produksi',
  startJob: 'Mulai SPK',
  pauseJob: 'Jeda SPK',
  resumeJob: 'Lanjutkan SPK',
  completeJob: 'Selesaikan SPK',
  stopJob: 'Hentikan SPK',
  logOutput: 'Catat Hasil',
  logDowntime: 'Catat Downtime',
  machine: 'Mesin',
  operator: 'Operator',
  shift: 'Shift',
  produced: 'Hasil Bagus',
  target: 'Target',
  scrap: 'Scrap',
  goodQuantity: 'Hasil Bagus',
  scrapQuantity: 'Scrap / Reject',
  materialUsed: 'Bahan Terpakai',
  running: 'Berjalan',
  unassigned: 'Belum Ditentukan',
  confirmStop: 'Hentikan SPK ini?',
  confirmComplete: 'Selesaikan SPK ini?',
  noJobs: 'Belum ada SPK. Buat SPK dari produk dan BOM yang sudah disiapkan.',
  createSpk: 'Buat SPK Produksi',
  searchFilter: 'Filter atau cari SPK...',
  refresh: 'Segarkan',
} as const;
