/** Product type display labels */
export const productTypeLabels = {
  RAW_MATERIAL: 'Bahan Baku',
  FINISHED_GOOD: 'Barang Jadi',
  SCRAP: 'Scrap',
  INTERMEDIATE: 'Intermediate',
  PACKAGING: 'Kemasan',
  WIP: 'Dalam Proses',
  SERVICE: 'Jasa',
} as const;

/** Product type badge abbreviations (compact) */
export const productTypeBadgeLabels = {
  RAW_MATERIAL: 'RM',
  FINISHED_GOOD: 'FG',
  SCRAP: 'Scrap',
  INTERMEDIATE: 'Inter',
  PACKAGING: 'Pack',
  WIP: 'WIP',
  SERVICE: 'Service',
} as const;

/** ProductForm component labels */
export const productFormLabels = {
  generalInfo: 'Informasi Umum',
  productName: 'Nama Produk',
  productType: 'Tipe Produk',
  selectProductType: 'Pilih tipe produk',
  productNamePlaceholder: 'contoh: Plastik HDPE',
  smartModeInfo: 'Mode cerah aktif: Varian akan menggunakan konversi satuan 1:1',
  productVariants: 'Varian Produk',
  addVariant: 'Tambah Varian',
  addFirstVariant: 'Tambah Varian Pertama',
  noVariants: 'Belum ada varian ditambahkan',
  cancel: 'Batal',
  creating: 'Membuat...',
  updating: 'Memperbarui...',
  createProduct: 'Buat Produk',
  updateProduct: 'Perbarui Produk',
} as const;

/** ProductTable component labels */
export const productTableLabels = {
  catalogItem: 'Item Katalog',
  skuCode: 'Kode SKU',
  type: 'Tipe',
  unit: 'Satuan',
  stockLevel: 'Stok',
  stockLevelTooltip: 'Stok fisik saat ini untuk SKU ini',
  currentCost: 'Biaya Saat Ini',
  currentCostTooltip: 'Biaya rata-rata tertimbang dari stok saat ini di semua lokasi.',
  standardCost: 'Biaya Standar',
  standardCostTooltip: 'Biaya satuan dihitung dari Bill of Materials (Resep).',
  buyPrice: 'Harga Beli',
  catalog: 'Katalog',
  actions: 'Aksi',
  emptyTitle: 'Tidak ada produk ditemukan',
  emptyDescription: 'Coba ubah filter Anda atau buat produk pertama untuk memulai.',
  deleteDialogTitle: 'Hapus Item Produk',
  deleteDialogDescription: (name: string, variantName: string, skuCode: string) =>
    `Yakin ingin menghapus ${name}${variantName ? ` (${variantName})` : ''}?\nSKU: ${skuCode}\nAksi ini tidak dapat dibatalkan dan akan gagal jika masih ada stok atau riwayat transaksi.`,
  deleteDialogCancel: 'Batal',
  deleting: 'Menghapus...',
  deleteSku: 'Hapus SKU',
} as const;

/** ProductGlossary component labels */
export const productGlossaryLabels = {
  fieldGuide: 'Panduan Kolom',
  title: 'Master Produk - Panduan Kolom',
  subtitle: 'Referensi cepat untuk semua istilah dan kolom produk',
  productTypes: 'Tipe Produk',
  productTypesDesc: 'Kategori berdasarkan tahap produksi',
  unitsOfMeasurement: 'Satuan Ukur',
  unitsOfMeasurementDesc: 'Satuan yang tersedia untuk pelacakan inventaris',
  skuCodeFormat: 'Format Kode SKU',
  skuCodeFormatDesc: 'Identifikasi produk unik 8 karakter',
  typeLabel: 'TIPE (2)',
  categoryLabel: 'KATEGORI (3)',
  seqLabel: 'SEQ (3)',
  exampleLabel: 'Contoh',
  skuExamplePath: 'Bahan Baku → PE Granul → #001',
  dualUnitSystem: 'Sistem Dual Satuan',
  dualUnitSystemDesc: 'Satuan utama untuk pelacakan internal, satuan penjualan untuk kebutuhan pelanggan',
  priceFields: 'Kolom Harga',
  priceFieldsDesc: 'Berbagai titik harga untuk keperluan berbeda',
  inventoryControls: 'Kontrol Inventaris',
  inventoryControlsDesc: 'Pengaturan untuk manajemen inventaris',
  productAttributes: 'Atribut Produk',
  productAttributesDesc: 'Metadata fleksibel untuk informasi produk tambahan',
  productAttributesDetail: 'Simpan properti kustom seperti warna, ketebalan, grade material, dll.',
  exampleJson: 'Contoh JSON:',
  // Glossary items - Product Types
  rmName: 'Bahan Baku',
  rmDesc: 'Bahan masuk dari pemasok (contoh: PE Granul, Pewarna)',
  rmExample: 'PE Granul Murni, Pewarna Merah Masterbatch',
  inName: 'Intermediate',
  inDesc: 'Hasil dari proses pencampuran/blending, belum produk akhir',
  inExample: 'PE Campuran Merah (PE + Pewarna)',
  pkName: 'Kemasan',
  pkDesc: 'Bahan dan perlengkapan kemasan',
  pkExample: 'Kardus, Label, Palet',
  wipName: 'Dalam Proses (WIP)',
  wipDesc: 'Barang setengah jadi yang sedang dalam produksi',
  wipExample: 'Gulungan Raffia Merah (sebelum dipotong)',
  fgName: 'Barang Jadi',
  fgDesc: 'Produk siap jual',
  fgExample: 'Bale Raffia Merah (5kg, 10kg)',
  scName: 'Scrap',
  scDesc: 'Limbah produksi dan bahan daur ulang',
  scExample: 'Guntingan Tepi, Produk Reject, Regrind',
  // Glossary items - Units
  kgDesc: 'Kilogram - Pengukuran berat, paling umum untuk bahan baku dan granul',
  rollDesc: 'Gulungan - Untuk produk film, raffia, atau pita dalam bentuk gulungan',
  balDesc: 'Bale - Produk terikat/terbungkus (contoh: 1 bale = 5kg atau 10kg)',
  packDesc: 'Piece - Untuk item yang dapat dihitung',
  zakDesc: 'Karung - Untuk unit kemasan curah',
  // Dual unit system
  primaryUnit: 'Satuan Utama',
  primaryUnitDesc: 'Unit pelacakan internal (contoh: KG untuk manajemen inventaris yang presisi)',
  primaryUnitExample: 'Semua pergerakan stok dilacak dalam KG',
  salesUnit: 'Satuan Penjualan',
  salesUnitDesc: 'Unit untuk pelanggan (contoh: BAL untuk pesanan penjualan)',
  salesUnitExample: 'Jual dalam Bale, lacak secara internal dalam KG',
  conversionFactor: 'Faktor Konversi',
  conversionFactorDesc: 'Berapa banyak satuan utama = 1 satuan penjualan',
  conversionFactorExample: '1 BAL = 5 KG → Faktor Konversi = 5.0',
  dualUnitTip: 'Untuk bahan baku dan scrap, kedua satuan biasanya sama (contoh: KG/KG dengan faktor 1.0)',
  // Pricing
  price: 'Harga',
  priceDesc: 'Harga dasar/standar untuk referensi umum',
  priceExample: 'Rp 15.000 per KG',
  buyPriceName: 'Harga Beli',
  buyPriceDesc: 'Biaya pembelian dari pemasok (untuk perhitungan biaya dan margin)',
  buyPriceExample: 'Rp 14.500 per KG (harga beli)',
  sellPrice: 'Harga Jual',
  sellPriceDesc: 'Harga penjualan ke pelanggan (untuk faktur dan penawaran)',
  sellPriceExample: 'Rp 16.000 per KG (harga jual pelanggan)',
  marginCalc: 'Perhitungan Margin:',
  marginFormula: '(Harga Jual - Harga Beli) / Harga Beli × 100%',
  // Inventory
  minStockAlert: 'Peringatan Stok Minimum',
  minStockAlertDesc: 'Batas kuantitas - sistem akan memberi peringatan jika total stok di semua lokasi di bawah angka ini',
  minStockAlertExample: 'Atur ke 100 KG → Peringatan jika total stok < 100 KG',
  bestPractice: 'Praktik Terbaik:',
  bestPracticeFormula: 'Atur stok minimum = (Penggunaan Rata-rata Harian × Hari Lead Time) + Stok Cadangan',
} as const;

/** VariantFields component labels */
export const variantFieldLabels = {
  variantLabel: (index: number) => `Varian #${index + 1}`,
  deletePermanently: 'Hapus',
  deleteConfirmMessage: 'Hapus varian ini secara permanen? Tindakan ini tidak dapat dibatalkan.',
  variantName: 'Nama Varian',
  variantNamePlaceholder: 'contoh: Bal Isi 10',
  skuCode: 'Kode SKU',
  skuPlaceholder: 'contoh: RMPPK001',
  auto: 'Auto',
  primaryUnit: 'Satuan Utama',
  selectPrimaryUnit: 'Pilih satuan utama',
  salesUnit: 'Satuan Penjualan',
  selectSalesUnit: 'Pilih satuan penjualan',
  conversionFactor: 'Faktor Konversi',
  referencePrice: 'Harga Referensi',
  minStockAlert: 'Peringatan Stok Minimum (Opsional)',
  simpleUnitMode: 'Mode satuan sederhana (konversi 1:1)',
} as const;

/** ProductCombobox component labels */
export const productComboboxLabels = {
  selectProduct: 'Pilih produk...',
  noProductsFound: 'Tidak ada produk ditemukan.',
  searchPlaceholder: 'Cari produk...',
  suggestions: 'Saran',
  allMaterials: 'Semua Bahan',
} as const;
