/** Produksi / SPK */
export const productionLabels = {
  workOrder: 'SPK Produksi',
  productionOrder: 'SPK Produksi',
  bom: 'BOM / Formula',
  billOfMaterials: 'BOM / Formula',
  materialIssue: 'Ambil Bahan',
  materialReturn: 'Retur Bahan',
  productionOutput: 'Hasil Produksi',
  output: 'Hasil',
  scrap: 'Scrap / Reject',
  rework: 'Rework',
  batch: 'Batch',
  machine: 'Mesin',
  downtime: 'Downtime',
  yield: 'Yield',
  finishedGood: 'Barang Jadi',
  wip: 'WIP / Barang Dalam Proses',
  planMaterial: 'Bahan Rencana',
  actualMaterial: 'Bahan Aktual',
  goodQuantity: 'Hasil Bagus',
  scrapQuantity: 'Scrap / Reject',
  orderStatus: 'Status SPK',
  productionHistory: 'Riwayat Produksi',
  startJob: 'Mulai SPK',
  pauseJob: 'Jeda SPK',
  resumeJob: 'Lanjutkan SPK',
  completeJob: 'Selesaikan SPK',
  reportDowntime: 'Catat Downtime',
  materialUsed: 'Bahan Terpakai',
  orderNumber: 'No. SPK',
} as const;
