/** Purchasing / Pembelian */
export const purchasingLabels = {
  purchasing: "Pembelian",
  supplier: "Supplier",
  purchaseRequest: "Permintaan Pembelian",
  pr: "PR",
  purchaseOrder: "Purchase Order",
  po: "PO",
  goodsReceipt: "Penerimaan Barang",
  purchaseInvoice: "Invoice Pembelian",
  purchaseReturn: "Retur Pembelian",
  unitPrice: "Harga Satuan",
  leadTime: "Lead Time",
  receivedQty: "Qty Diterima",
  orderedQty: "Qty Pesanan",

  // Document identifiers
  prNumber: "No. PR",
  prDate: "Tanggal PR",
  poNumber: "No. PO",
  poDate: "Tanggal PO",
  grNumber: "No. Penerimaan",
  grDate: "Tanggal Penerimaan",
  invoiceNumber: "No. Invoice",
  invoiceDate: "Tanggal Invoice",
  returnNumber: "No. Retur",
  returnDate: "Tanggal Retur",

  // Custom metadata / labels
  requestedBy: "Diminta Oleh",
  source: "Sumber",
  itemsCount: "Jumlah Item",
  destinationWarehouse: "Gudang Tujuan",
  sourceWarehouse: "Gudang Sumber",
  condition: "Kondisi",
  reason: "Alasan",
  supplierCode: "Kode Supplier",
  supplierName: "Nama Supplier",
  taxId: "NPWP",
  paymentTermDays: "Termin Pembayaran",
  shippingCost: "Ongkos Kirim",
  bankName: "Nama Bank",
  bankAccount: "Rekening Bank",
  preferredSupplier: "Supplier Pilihan",
  minOrderQty: "Min. Order Qty",
  productsSupplied: "Produk yang Disuplai",

  // Empty states
  emptyRequests: "Tidak ada permintaan pembelian.",
  emptyOrders: "Tidak ada order pembelian.",
  emptyReceipts: "Tidak ada penerimaan barang.",
  emptyInvoices: "Tidak ada invoice pembelian.",
  emptyReturns: "Tidak ada retur pembelian.",
  emptySuppliers: "Tidak ada supplier.",
} as const;
