/** Finance reports labels */
export const reportLabels = {
  // Reports hub
  financialReports: 'Laporan Keuangan',
  comprehensiveReports: 'Pernyataan akuntansi dan analisa komprehensif.',
  balanceSheet: 'Neraca',
  balanceSheetDesc: 'Ringkasan aset, liabilitas, dan ekuitas pada titik waktu tertentu.',
  incomeStatement: 'Laba Rugi',
  incomeStatementDesc: 'Pernyataan laba rugi yang menunjukkan pendapatan dan beban selama periode.',
  trialBalance: 'Neraca Saldo',
  trialBalanceDesc: 'Daftar seluruh akun buku besar dan saldo saat ini.',
  budgetVariance: 'Varians Anggaran',
  budgetVarianceDesc: 'Perbandingan performa aktual terhadap target anggaran.',
  cashFlowStatement: 'Arus Kas',
  cashFlowStatementDesc: 'Pernyataan arus kas masuk dan keluar (Operasi, Investasi, Pendanaan).',
  taxReport: 'Laporan Pajak',
  taxReportDesc: 'Laporan pajak terintegrasi bulanan (PPN & PPh).',
  maklonProfitability: 'Profitabilitas Maklon',
  maklonProfitabilityDesc: 'Analisa pendapatan layanan vs biaya konversi internal untuk toll manufacturing.',
  viewReport: 'Lihat Laporan',
  customAnalysis: 'Analisa Kustom',
  customAnalysisDesc: 'Butuh laporan khusus atau ekspor data kustom?',
  openReportBuilder: 'Buka Report Builder',
  downloadRawData: 'Unduh Data Mentah (CSV)',
  accountingReport: 'Laporan Akuntansi',
  plStatement: 'P&L Statement',

  // Balance Sheet
  financialPosition: 'Posisi Keuangan per',
  pickDate: 'Pilih tanggal',
  summary: 'Ringkas',
  hideZeroBalances: 'Sembunyikan Saldo Nol',
  neracaRingkas: 'Neraca (Ringkas)',
  neracaDetail: 'Neraca (Detail)',
  akun: 'Akun',
  kode: 'Kode',
  jumlah: 'Jumlah',
  loading: 'Memuat...',
  noData: 'Tidak ada data',
  totalAset: 'TOTAL ASET',
  totalKewajiban: 'TOTAL KEWAJIBAN',
  totalEkuitas: 'TOTAL EKUITAS',
  totalKewajibanEkuitas: 'TOTAL KEWAJIBAN & EKUITAS',
  labaPeriodeBerjalan: 'Laba Periode Berjalan (Belum Diclose)',

  // Income Statement
  laporanLabaRugi: 'Laporan Laba Rugi',
  analisaProfitabilitas: 'Analisis profitabilitas bertahap untuk periode yang dipilih.',
  bulanIni: 'Bulan Ini',
  hideZero: 'Sembunyikan Saldo Nol',
  totalPendapatan: 'Total Pendapatan',
  labaKotor: 'Laba Kotor',
  labaOperasional: 'Laba Operasional',
  labaBersih: 'Laba Bersih',
  statementOfProfitOrLoss: 'Laporan Laba Rugi',
  multiStepManufacturing: 'Laporan laba rugi manufaktur bertahap',
  keteranganAkun: 'Keterangan Akun',
  jumlahIDR: 'Jumlah (IDR)',
  memuatData: 'Memuat data...',
  tidakAdaDataPeriode: 'Tidak ada data untuk periode ini',
  directMaterialsUsed: 'Bahan Baku Langsung',
  directLabor: 'Tenaga Kerja Langsung',
  factoryOverhead: 'Overhead Pabrik',
  totalBiayaProduksi: 'Total Biaya Produksi',
  totalHPP: 'Total HPP',
  labaKotorGP: 'LABA KOTOR (GROSS PROFIT)',
  bebanOperasional: 'Beban Operasional',
  sellingMarketingExpenses: 'Beban Penjualan & Pemasaran',
  generalAdminExpenses: 'Beban Umum & Administrasi',
  totalBebanOperasional: 'Total Beban Operasional',
  labaOperasionalEBIT: 'LABA OPERASIONAL (EBIT)',
  pendapatanBebanLainnya: 'Pendapatan/Beban Lainnya',
  labaBersihNI: 'LABA BERSIH (NET INCOME)',
  beban: 'Beban',
  grossMargin: 'Gross Margin',
  operatingMargin: 'Operating Margin',
  netProfitMargin: 'Net Profit Margin',
  efisiensiProduksi: 'Efisiensi produksi',
  efisiensiOperasional: 'Efisiensi operasional',
  profitabilitasAkhir: 'Profitabilitas akhir',

  // Trial Balance
  neracaSaldoTitle: 'Neraca Saldo',
  neracaSaldoDesc: 'Daftar seluruh akun buku besar dengan saldo debet dan kredit.',
  debit: 'Debet',
  kredit: 'Kredit',
  totalDebit: 'Total Debet',
  totalKredit: 'Total Kredit',
  balance: 'Saldo',

  // Budget Variance
  variansAnggaran: 'Varians Anggaran',
  variansAnggaranDesc: 'Perbandingan performa aktual terhadap target anggaran per periode.',
  anggaran: 'Anggaran',
  aktual: 'Aktual',
  varians: 'Varians',
  persentaseCapaian: '% Capaian',
  bulan: 'Bulan',

  // Cash Flow
  arusKas: 'Laporan Arus Kas',
  arusKasDesc: 'Pernyataan arus kas masuk dan keluar dari aktivitas operasi, investasi, dan pendanaan.',
  arusKasOperasi: 'Arus Kas dari Operasi',
  arusKasInvestasi: 'Arus Kas dari Investasi',
  arusKasPendanaan: 'Arus Kas dari Pendanaan',
  kenaikanBersihKas: 'Kenaikan Bersih Kas',
  kasAwal: 'Kas Awal',
  kasAkhir: 'Kas Akhir',

  // Tax
  laporanPajak: 'Laporan Pajak',
  laporanPajakDesc: 'Ringkasan PPN masuk, PPN keluar, dan PPh terutang.',
  ppnMasuk: 'PPN Masuk',
  ppnKeluar: 'PPN Keluar',
  ppnTerutang: 'PPN Terutang',
  pphTerutang: 'PPh Terutang',

  // Maklon
  maklonProfitTitle: 'Profitabilitas Maklon',
  maklonProfitDesc: 'Analisa pendapatan layanan maklon vs biaya konversi internal.',
  pendapatanLayanan: 'Pendapatan Layanan',
  biayaKonversi: 'Biaya Konversi',
  labaMaklon: 'Laba Maklon',
  marginMaklon: 'Margin Maklon',

  // General Ledger / Buku Besar
  generalLedger: 'Buku Besar',
  generalLedgerDesc: 'Daftar seluruh transaksi akun buku besar dengan saldo berjalan per akun.',
  namaAkun: 'Nama Akun / Tanggal',
  tanggal: 'Tanggal',
  nomor: 'Nomor',
  keterangan: 'Keterangan',
  saldo: 'Saldo',
  saldoAkhir: 'Saldo Akhir',
  dalamIDR: '(dalam IDR)',
} as const;
