/** Sales / Penjualan */
export const salesLabels = {
  sales: 'Penjualan',
  customer: 'Customer',
  quotation: 'Penawaran Penjualan',
  salesOrder: 'Sales Order',
  so: 'SO',
  deliveryOrder: 'Surat Jalan',
  do: 'DO',
  invoice: 'Invoice',
  faktur: 'Faktur',
  salesReturn: 'Retur Penjualan',
  payment: 'Pembayaran',
  dueDate: 'Jatuh Tempo',
  outstanding: 'Belum Dibayar',
  paid: 'Lunas',
  overdue: 'Lewat Jatuh Tempo',
  quotationNumber: 'No. Penawaran',
  quotationDate: 'Tanggal Penawaran',
  validUntil: 'Masa Berlaku',
  orderNumber: 'No. Pesanan',
  orderDate: 'Tanggal Pesanan',
  expectedDate: 'Estimasi Pengiriman',
  orderType: 'Tipe Pesanan',
  location: 'Lokasi',
  sourceWarehouse: 'Gudang Sumber',
  customerWarehouse: 'Gudang Customer',
  deliveryDate: 'Tanggal Pengiriman',
  carrier: 'Ekspedisi / Kurir',
  trackingNumber: 'No. Resi',
  invoiceNumber: 'No. Invoice',
  invoiceDate: 'Tanggal Invoice',
  paidAmount: 'Jumlah Dibayar',
  remainingAmount: 'Sisa Tagihan',
  returnNumber: 'No. Retur',
  returnDate: 'Tanggal Retur',
  returnLocation: 'Lokasi Retur',
  reason: 'Alasan',
  condition: 'Kondisi',
  items: 'Item',
  emptyQuotations: 'Tidak ada penawaran penjualan.',
  emptyOrders: 'Tidak ada sales order.',
  emptyDeliveries: 'Tidak ada surat jalan.',
  emptyInvoices: 'Tidak ada invoice.',
  emptyReturns: 'Tidak ada retur penjualan.',
} as const;
