/** Sales / Penjualan */
export const salesLabels = {
  sales: 'Penjualan',
  customer: 'Customer',
  quotation: 'Penawaran Penjualan',
  salesOrder: 'Sales Order',
  so: 'SO',
  deliveryOrder: 'Surat Jalan',
  do: 'DO',
  invoice: 'Invoice',
  faktur: 'Faktur',
  salesReturn: 'Retur Penjualan',
  payment: 'Pembayaran',
  dueDate: 'Jatuh Tempo',
  outstanding: 'Belum Dibayar',
  paid: 'Lunas',
  overdue: 'Lewat Jatuh Tempo',
  quotationNumber: 'No. Penawaran',
  quotationDate: 'Tanggal Penawaran',
  validUntil: 'Masa Berlaku',
  orderNumber: 'No. Pesanan',
  orderDate: 'Tanggal Pesanan',
  expectedDate: 'Estimasi Pengiriman',
  orderType: 'Tipe Pesanan',
  location: 'Lokasi',
  sourceWarehouse: 'Gudang Sumber',
  customerWarehouse: 'Gudang Customer',
  deliveryDate: 'Tanggal Pengiriman',
  carrier: 'Ekspedisi / Kurir',
  trackingNumber: 'No. Resi',
  invoiceNumber: 'No. Invoice',
  invoiceDate: 'Tanggal Invoice',
  paidAmount: 'Jumlah Dibayar',
  remainingAmount: 'Sisa Tagihan',
  returnNumber: 'No. Retur',
  returnDate: 'Tanggal Retur',
  returnLocation: 'Lokasi Retur',
  reason: 'Alasan',
  condition: 'Kondisi',
  items: 'Item',
  emptyQuotations: 'Tidak ada penawaran penjualan.',
  emptyOrders: 'Tidak ada sales order.',
  emptyDeliveries: 'Tidak ada surat jalan.',
  emptyInvoices: 'Tidak ada invoice.',
  emptyReturns: 'Tidak ada retur penjualan.',
  allReturns: 'Semua Retur',

  // Sales Dashboard
  salesDashboard: 'Dashboard Penjualan',
  salesDashboardDesc: 'Ringkasan performa penjualan.',
  totalRevenuePeriod: 'Total Pendapatan (Periode)',
  basedOnPeriod: 'Berdasarkan periode terpilih',
  noData: 'Tidak ada data',
  activeOrders: 'Pesanan Aktif',
  ordersInProgress: 'Pesanan sedang diproses',
  pendingDeliveries: 'Pengiriman Tertunda',
  readyToShip: 'Siap dikirim',
  activeCustomers: 'Customer Aktif',
  totalActiveBase: 'Total customer aktif',
  recentSalesOrders: 'Pesanan Penjualan Terbaru',

  // Sales Orders
  salesOrders: 'Sales Orders',
  salesOrdersDesc: 'Kelola pesanan customer, produksi, dan layanan maklon.',
  newSalesOrder: 'Pesanan Baru',
  totalOrders: 'Total Pesanan',
  activePending: 'Aktif / Tertunda',
  completed: 'Selesai',
  cancelled: 'Dibatalkan',
  allOrders: 'Semua Pesanan',
  customerDemand: 'Pesanan Customer',
  legacyInternal: 'Legacy Internal',
  mtsBelumLunas: 'MTS Belum Lunas',

  // Sales Quotations
  salesQuotations: 'Penawaran Penjualan',
  salesQuotationsDesc: 'Kelola penawaran dan proposal penjualan.',
  newQuotation: 'Penawaran Baru',
  recentQuotations: 'Penawaran Terbaru',

  // Deliveries
  deliveryOrders: 'Surat Jalan',
  deliveryOrdersDesc: 'Kelola pengiriman keluar dan status pengiriman.',
  allDeliveries: 'Semua Pengiriman',
  allDeliveriesDesc: 'Daftar semua surat jalan dan status saat ini.',

  // Invoices
  salesInvoices: 'Invoice Penjualan',
  salesInvoicesDesc: 'Kelola invoice dan lacak pembayaran.',
  outstandingAmount: 'Jumlah Belum Dibayar',
  unpaidPartial: 'Invoice belum lunas atau sebagian',
  overdueInvoices: 'Invoice Lewat Tempo',
  requiresImmediateAttention: 'Perlu perhatian segera',
  allInvoices: 'Semua Invoice',
  allInvoicesDesc: 'Daftar semua invoice penjualan yang dibuat.',

  // Returns
  salesReturns: 'Retur Penjualan',
  salesReturnsDesc: 'Kelola retur customer dan pengiriman masuk.',
  newSalesReturn: 'Retur Baru',
  totalReturns: 'Total Retur',

  // Customers
  customers: 'Customer',
  customersDesc: 'Kelola customer dan saluran penjualan.',
  allCustomers: 'Semua Customer',
  allCustomersDesc: 'Daftar customer aktif dalam sistem.',
  addCustomer: 'Tambah Customer',
  code: 'Kode',
  name: 'Nama',
  phone: 'Telepon',
  billingAddress: 'Alamat Penagihan',
  status: 'Status',
  actions: 'Aksi',
  active: 'Aktif',
  inactive: 'Non-aktif',
  noCustomersFound: 'Tidak ada pelanggan ditemukan.',
  startByCreating: 'Mulai dengan membuat pelanggan baru.',
} as const;
