/** Gudang / Warehouse */
export const warehouseLabels = {
  warehouse: 'Gudang',
  inventory: 'Stok',
  stock: 'Stok',
  stockMovement: 'Mutasi Stok',
  transferStock: 'Transfer Stok',
  stockAdjustment: 'Penyesuaian Stok',
  stockOpname: 'Stock Opname',
  goodsReceipt: 'Penerimaan Barang',
  incoming: 'Barang Masuk',
  incomingOperational: 'Lihat antrean & catat barang masuk dari supplier.',
  incomingHistory: 'Riwayat Penerimaan',
  receiveFromPo: 'Terima dari PO',
  receiveFromNota: 'Terima dari Nota',
  waitingReceive: 'Menunggu Diterima',
  receivedToday: 'Diterima Hari Ini',
  walkInBadge: 'Dari Nota',
  outgoing: 'Antrian Muat',
  outgoingHistory: 'Riwayat Kirim',
  sourceLocation: 'Lokasi Asal',
  destinationLocation: 'Lokasi Tujuan',
  availableStock: 'Stok Tersedia',
  reservedStock: 'Stok Terpesan',
  lowStock: 'Stok Menipis',

  // Dual-path material ownership (Path A = gudang RM/FG)
  pathATitle: 'Jalur Gudang (bahan baku & barang jadi)',
  pathAHelp:
    'Gudang mengeluarkan RM ke Mixing, catat pelembab/additive ad-hoc dari gudang RM, serta kelola FG & kirim. Pergerakan WIP antar mesin (Mixing→Extru→Packing) dikerjakan produksi di lantai, bukan pengajuan gudang RM.',
  warehouseActions: 'Aksi gudang',
  openActiveSpkQueue: 'Antrean SPK aktif',
  filterAll: 'Semua',
  filterRm: 'Butuh RM (gudang)',
  filterWip: 'WIP lantai',
  filterEmptyRm: 'Tidak ada SPK yang butuh pengeluaran bahan baku saat ini.',
  filterEmptyWip: 'Tidak ada SPK WIP lantai (Extrusi/Packing) di antrean.',
  filterEmptyAll: 'Tidak ada SPK aktif.',
  badgeRm: 'RM',
  badgeWip: 'WIP',
  pathBadgeRmHelp: 'Bahan baku — prioritas gudang',
  pathBadgeWipHelp: 'WIP lantai — staging/transfer produksi; gudang bisa bantu ad-hoc',
} as const;
