-- Price adjustments are separate signed financial documents; preserve original invoice/cash/return ledger.
-- Rebuild the generated balance and its index atomically; never expose a partial schema.
BEGIN;
ALTER TABLE "Invoice" ADD COLUMN "priceAdjustmentAmount" DECIMAL(15,2) NOT NULL DEFAULT 0;
DROP INDEX "Invoice_positive_receivable_due_idx";
ALTER TABLE "Invoice" DROP COLUMN "remainingAmount";
ALTER TABLE "Invoice" ADD COLUMN "remainingAmount" DECIMAL(15,2) NOT NULL GENERATED ALWAYS AS ("totalAmount" + "priceAdjustmentAmount" - "paidAmount" - "creditedAmount") STORED;
CREATE INDEX "Invoice_positive_receivable_due_idx" ON "Invoice" ("dueDate",id) WHERE "remainingAmount">0 AND status IN ('UNPAID','PARTIAL','OVERDUE');
CREATE TYPE "InvoicePriceAdjustmentStatus" AS ENUM ('POSTED','REVERSED');
CREATE TABLE "InvoicePriceAdjustment" (
  id TEXT PRIMARY KEY,
  "invoiceId" TEXT NOT NULL REFERENCES "Invoice"(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  "sourceItemId" TEXT NOT NULL,
  "sourceJournalId" TEXT NOT NULL REFERENCES "JournalEntry"(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  quantity DECIMAL(15,4) NOT NULL CHECK (quantity>0),
  "oldNetUnitPrice" DECIMAL(20,6) NOT NULL CHECK ("oldNetUnitPrice">=0),
  "newNetUnitPrice" DECIMAL(20,6) NOT NULL CHECK ("newNetUnitPrice">=0),
  "netAmount" DECIMAL(15,2) NOT NULL,
  "taxAmount" DECIMAL(15,2) NOT NULL,
  "totalAmount" DECIMAL(15,2) NOT NULL CHECK ("totalAmount"<>0 AND "totalAmount"="netAmount"+"taxAmount"),
  status "InvoicePriceAdjustmentStatus" NOT NULL DEFAULT 'POSTED',
  "postingDate" TIMESTAMP(3) NOT NULL,
  reason TEXT NOT NULL CHECK (length(trim(reason)) BETWEEN 5 AND 1000),
  "sourceEvidence" JSONB NOT NULL,
  "idempotencyKey" TEXT NOT NULL,
  "requestSignature" TEXT NOT NULL,
  "journalId" TEXT NOT NULL REFERENCES "JournalEntry"(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  "createdById" TEXT NOT NULL REFERENCES "User"(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "reversedAt" TIMESTAMP(3),
  "reversedById" TEXT REFERENCES "User"(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  "reversalReason" TEXT,
  "reversalJournalId" TEXT REFERENCES "JournalEntry"(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CHECK ((status='POSTED' AND "reversedAt" IS NULL AND "reversedById" IS NULL AND "reversalReason" IS NULL AND "reversalJournalId" IS NULL) OR
    (status='REVERSED' AND "reversedAt" IS NOT NULL AND "reversedAt">="postingDate" AND "reversedById" IS NOT NULL AND "reversalJournalId" IS NOT NULL AND "reversalReason" IS NOT NULL AND length(trim("reversalReason"))>=5)),
  CHECK (("netAmount">0 AND "taxAmount">=0) OR ("netAmount"<0 AND "taxAmount"<=0))
);
CREATE UNIQUE INDEX "InvoicePriceAdjustment_idempotencyKey_key" ON "InvoicePriceAdjustment"("idempotencyKey");
CREATE UNIQUE INDEX "InvoicePriceAdjustment_journalId_key" ON "InvoicePriceAdjustment"("journalId");
CREATE UNIQUE INDEX "InvoicePriceAdjustment_reversalJournalId_key" ON "InvoicePriceAdjustment"("reversalJournalId");
CREATE INDEX "InvoicePriceAdjustment_invoiceId_postingDate_idx" ON "InvoicePriceAdjustment"("invoiceId","postingDate");
CREATE INDEX "InvoicePriceAdjustment_sourceJournalId_idx" ON "InvoicePriceAdjustment"("sourceJournalId");
CREATE UNIQUE INDEX "InvoicePriceAdjustment_active_source_key" ON "InvoicePriceAdjustment"("invoiceId","sourceItemId") WHERE status='POSTED';

CREATE FUNCTION check_invoice_price_adjustments() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE invoice_id text; journal_id text; a "InvoicePriceAdjustment"%ROWTYPE;
BEGIN
  IF TG_TABLE_NAME='Invoice' THEN invoice_id:=NEW.id; ELSE invoice_id:=NEW."invoiceId"; END IF;
  IF EXISTS (SELECT 1 FROM "Invoice" i WHERE i.id=invoice_id AND i."priceAdjustmentAmount"<>COALESCE((SELECT SUM("totalAmount") FROM "InvoicePriceAdjustment" WHERE "invoiceId"=i.id AND status='POSTED'),0)) THEN
    RAISE EXCEPTION 'Invoice price adjustment cache must equal active ledger';
  END IF;
  IF TG_TABLE_NAME='InvoicePriceAdjustment' THEN
    SELECT * INTO a FROM "InvoicePriceAdjustment" WHERE id=NEW.id;
    IF NOT EXISTS (SELECT 1 FROM "Invoice" i JOIN "SalesOrderItem" si ON si.id=a."sourceItemId" AND si."salesOrderId"=i."salesOrderId" JOIN "JournalEntry" j ON j.id=a."sourceJournalId" WHERE i.id=a."invoiceId" AND j."referenceType"='SALES_INVOICE' AND j."referenceId"=i.id AND j.status='POSTED' AND j."isAutoGenerated") THEN RAISE EXCEPTION 'Price adjustment source mismatch'; END IF;
    FOREACH journal_id IN ARRAY ARRAY[a."journalId",a."reversalJournalId"] LOOP
      IF journal_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "JournalEntry" j JOIN "JournalLine" l ON l."journalEntryId"=j.id WHERE j.id=journal_id AND j.status='POSTED' AND j."isAutoGenerated" GROUP BY j.id HAVING SUM(l.debit)=abs(a."totalAmount") AND SUM(l.credit)=abs(a."totalAmount")) THEN RAISE EXCEPTION 'Price adjustment journal must balance to amount'; END IF;
    END LOOP;
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER invoice_price_ledger AFTER INSERT OR UPDATE ON "Invoice" DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION check_invoice_price_adjustments();
CREATE CONSTRAINT TRIGGER price_adjustment_ledger AFTER INSERT OR UPDATE ON "InvoicePriceAdjustment" DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION check_invoice_price_adjustments();

CREATE FUNCTION guard_invoice_price_history() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE source_id text;
BEGIN
  IF TG_TABLE_NAME='InvoicePriceAdjustment' THEN
    IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Posted price adjustment cannot be deleted'; END IF;
    IF NOT (OLD.status='POSTED' AND NEW.status='REVERSED' AND
      (to_jsonb(NEW)-ARRAY['status','reversedAt','reversedById','reversalReason','reversalJournalId'])=(to_jsonb(OLD)-ARRAY['status','reversedAt','reversedById','reversalReason','reversalJournalId'])) THEN RAISE EXCEPTION 'Price adjustment is immutable; use compensation'; END IF;
  ELSIF TG_TABLE_NAME='Invoice' THEN
    IF EXISTS (SELECT 1 FROM "InvoicePriceAdjustment" WHERE "invoiceId"=OLD.id) THEN
      IF (NEW."totalAmount",NEW."salesOrderId",NEW."invoiceDate",NEW."roundingAmount") IS DISTINCT FROM (OLD."totalAmount",OLD."salesOrderId",OLD."invoiceDate",OLD."roundingAmount") OR NEW.status IN ('DRAFT','CANCELLED') THEN RAISE EXCEPTION 'Adjusted invoice history cannot be rewritten'; END IF;
    END IF;
  ELSIF TG_TABLE_NAME='SalesOrderItem' THEN
    IF EXISTS (SELECT 1 FROM "InvoicePriceAdjustment" WHERE "sourceItemId"=OLD.id) THEN
      IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Adjusted source item cannot be deleted'; END IF;
      IF (NEW.id,NEW."salesOrderId",NEW."productVariantId") IS DISTINCT FROM (OLD.id,OLD."salesOrderId",OLD."productVariantId") THEN RAISE EXCEPTION 'Adjusted source item identity is immutable'; END IF;
    END IF;
  ELSIF TG_TABLE_NAME='SalesOrder' THEN
    IF NEW."customerId" IS DISTINCT FROM OLD."customerId" AND EXISTS (SELECT 1 FROM "InvoicePriceAdjustment" a JOIN "Invoice" i ON i.id=a."invoiceId" WHERE i."salesOrderId"=OLD.id) THEN RAISE EXCEPTION 'Adjusted customer history cannot be rewritten'; END IF;
  ELSE
    IF TG_TABLE_NAME='JournalLine' THEN
      source_id:=CASE WHEN TG_OP='INSERT' THEN NEW."journalEntryId" ELSE OLD."journalEntryId" END;
      PERFORM id FROM "JournalEntry" WHERE id=source_id FOR UPDATE;
      IF TG_OP='UPDATE' THEN
        IF NEW."journalEntryId"<>OLD."journalEntryId" AND EXISTS (SELECT 1 FROM "InvoicePriceAdjustment" WHERE NEW."journalEntryId" IN ("sourceJournalId","journalId","reversalJournalId")) THEN RAISE EXCEPTION 'Cannot move line into price history'; END IF;
      END IF;
    ELSE source_id:=OLD.id; END IF;
    IF EXISTS (SELECT 1 FROM "InvoicePriceAdjustment" WHERE source_id IN ("sourceJournalId","journalId","reversalJournalId")) THEN RAISE EXCEPTION 'Price adjustment journal history is immutable'; END IF;
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;
CREATE TRIGGER price_history BEFORE UPDATE OR DELETE ON "InvoicePriceAdjustment" FOR EACH ROW EXECUTE FUNCTION guard_invoice_price_history();
CREATE TRIGGER price_invoice_history BEFORE UPDATE ON "Invoice" FOR EACH ROW EXECUTE FUNCTION guard_invoice_price_history();
CREATE TRIGGER price_item_history BEFORE UPDATE OR DELETE ON "SalesOrderItem" FOR EACH ROW EXECUTE FUNCTION guard_invoice_price_history();
CREATE TRIGGER price_order_history BEFORE UPDATE ON "SalesOrder" FOR EACH ROW EXECUTE FUNCTION guard_invoice_price_history();
CREATE TRIGGER price_journal_history BEFORE UPDATE OR DELETE ON "JournalEntry" FOR EACH ROW EXECUTE FUNCTION guard_invoice_price_history();
CREATE TRIGGER price_journal_line_history BEFORE INSERT OR UPDATE OR DELETE ON "JournalLine" FOR EACH ROW EXECUTE FUNCTION guard_invoice_price_history();
COMMIT;
