import { expect, it, vi } from 'vitest';
import type { Prisma } from '@prisma/client';
const { isOpen } = vi.hoisted(() => ({ isOpen: vi.fn().mockResolvedValue(false) }));
vi.mock('@/lib/core/prisma', () => ({ prisma: {} }));
vi.mock('../periods-service', () => ({ isPeriodOpen: isOpen }));
import { createJournalEntry } from '../journal-posting';
it('checks fiscal period on the supplied transaction before a journal write', async () => {
    const tx = {} as Prisma.TransactionClient;
    const date = new Date('2026-08-01T00:00:00Z');
    await expect(createJournalEntry({ entryDate: date, description: 'Receipt', reference: 'PAY-TEST', referenceType: 'SALES_PAYMENT', isAutoGenerated: true, lines: [] }, tx)).rejects.toMatchObject({ code: 'FISCAL_PERIOD_CLOSED' });
    expect(isOpen).toHaveBeenCalledWith(date, tx);
});
