import { beforeEach, describe, expect, it, vi } from 'vitest';
import { Prisma, type StockMovement } from '@prisma/client';
import { recordShipmentReversal } from '../shipment-reversal-journal';
import { generateEntryNumber } from '../journal-posting';
import { requireOpenJournalPeriod } from '@/services/finance/sales-recognition-service';
import { logActivity } from '@/lib/tools/audit';

vi.mock('../journal-posting', () => ({ generateEntryNumber: vi.fn() }));
vi.mock('@/services/finance/sales-recognition-service', () => ({ requireOpenJournalPeriod: vi.fn() }));
vi.mock('@/lib/tools/audit', () => ({ logActivity: vi.fn() }));

const date = new Date('2026-08-18T08:00:00Z');
const decimal = (n: Prisma.Decimal.Value) => new Prisma.Decimal(n);
function movement(overrides: Partial<StockMovement> = {}): StockMovement {
    return {
        id: 'original-move', type: 'OUT', productVariantId: 'variant',
        fromLocationId: 'warehouse', toLocationId: null, quantity: decimal('37.5'),
        cost: null, reference: 'Shipment for SO-FIXTURE via DO-FIXTURE',
        createdAt: date, createdById: 'actor', salesOrderId: 'order',
        goodsReceiptId: null, productionOrderId: null, batchId: null, ...overrides,
    };
}
function reversal(overrides: Partial<StockMovement> = {}): StockMovement {
    return movement({ id: 'return-move', type: 'IN', fromLocationId: null,
        toLocationId: 'warehouse', reference: 'VOID: Shipment for SO-FIXTURE via DO-FIXTURE [SOURCE:delivery]', ...overrides });
}
function source() {
    return {
        id: 'source-journal', entryNumber: 'JE-SOURCE', status: 'POSTED',
        isAutoGenerated: true, referenceType: 'MANUAL_ENTRY', referenceId: 'original-move',
        lines: [
            { id: 'debit', accountId: 'original-cogs', debit: decimal('420.45'), credit: decimal(0), description: 'COGS', currency: 'IDR', exchangeRate: decimal(1) },
            { id: 'credit', accountId: 'original-stock', debit: decimal(0), credit: decimal('420.45'), description: 'Shipment', currency: 'IDR', exchangeRate: decimal(1) },
        ],
    };
}
const db = {
    $queryRaw: vi.fn(),
    journalEntry: { findMany: vi.fn(), findFirst: vi.fn(), create: vi.fn() },
};
const tx = db as unknown as Prisma.TransactionClient;
const run = (original = movement(), returned = reversal(), offBalanceSheet = false) =>
    recordShipmentReversal(original, returned, 'actor', tx, { offBalanceSheet });

describe('recordShipmentReversal', () => {
    beforeEach(() => {
        vi.resetAllMocks();
        db.$queryRaw.mockResolvedValue([]);
        db.journalEntry.findMany.mockResolvedValue([source()]);
        db.journalEntry.findFirst.mockResolvedValue(null);
        db.journalEntry.create.mockResolvedValue({ id: 'new-journal' });
        vi.mocked(generateEntryNumber).mockResolvedValue('JE-NEW');
        vi.mocked(requireOpenJournalPeriod).mockResolvedValue(undefined);
        vi.mocked(logActivity).mockResolvedValue(undefined);
    });

    it('uses exact original accounts and Decimal values when movement cost is NULL', async () => {
        const original = source();
        await run();
        expect(db.journalEntry.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({
            entryNumber: 'JE-NEW', referenceId: 'return-move', status: 'POSTED', isAutoGenerated: true,
            lines: { create: original.lines.map(l => ({
                accountId: l.accountId, debit: l.credit, credit: l.debit,
                currency: l.currency, exchangeRate: l.exchangeRate,
                description: `Reversal JE-SOURCE: ${l.description}`,
            })) },
        }) }));
        expect(generateEntryNumber).toHaveBeenCalledWith(date, tx);
        expect(logActivity).toHaveBeenCalledWith(expect.objectContaining({
            userId: 'actor', entityId: 'new-journal', action: 'REVERSE_SHIPMENT_JOURNAL', tx,
            changes: expect.objectContaining({ originalJournalId: 'source-journal', originalMovementId: 'original-move', reversalMovementId: 'return-move' }),
        }));
    });

    it('ignores a different persisted cost instead of revaluing the posted shipment', async () => {
        await run(movement({ cost: decimal('99999') }));
        const args = db.journalEntry.create.mock.calls[0][0];
        expect(args.data.lines.create[0].credit.toString()).toBe('420.45');
    });

    it('preserves currency, exchange rate and cents without converting through Number', async () => {
        const journal = source();
        db.journalEntry.findMany.mockResolvedValue([{ ...journal, lines: journal.lines.map(l => ({
            ...l, description: null, currency: 'USD', exchangeRate: decimal('16234.567891'),
            debit: l.debit.isZero() ? decimal(0) : decimal('9999999999999.99'),
            credit: l.credit.isZero() ? decimal(0) : decimal('9999999999999.99'),
        })) }]);
        await run();
        const line = db.journalEntry.create.mock.calls[0][0].data.lines.create[0];
        expect(line.credit.toString()).toBe('9999999999999.99');
        expect(line.exchangeRate.toString()).toBe('16234.567891');
        expect(line.currency).toBe('USD');
    });

    it('rejects ambiguous active journals instead of selecting an arbitrary first row', async () => {
        db.journalEntry.findMany.mockResolvedValue([source(), { ...source(), id: 'second' }]);
        await expect(run()).rejects.toThrow(/jurnal.*asli|original.*journal/i);
        expect(db.journalEntry.create).not.toHaveBeenCalled();
    });

    it.each(['DRAFT', 'VOIDED'])('rejects a %s source returned by the database', async status => {
        db.journalEntry.findMany.mockResolvedValue([{ ...source(), status }]);
        await expect(run()).rejects.toThrow(/jurnal.*asli|original.*journal/i);
    });

    it('rejects nonautomatic source journals', async () => {
        db.journalEntry.findMany.mockResolvedValue([{ ...source(), isAutoGenerated: false }]);
        await expect(run()).rejects.toThrow(/jurnal.*asli|original.*journal/i);
    });

    it('rejects a different source reference type', async () => {
        db.journalEntry.findMany.mockResolvedValue([{ ...source(), referenceType: 'PURCHASE_INVOICE' }]);
        await expect(run()).rejects.toThrow(/jurnal.*asli|original.*journal/i);
    });

    it('rejects a missing NULL-cost source rather than guessing historical valuation', async () => {
        db.journalEntry.findMany.mockResolvedValue([]);
        await expect(run()).rejects.toThrow(/jurnal.*asli|original.*journal/i);
        expect(db.journalEntry.create).not.toHaveBeenCalled();
    });

    it.each([false, true])('allows only evidenced unvalued shipments (off balance %s)', async offBalance => {
        db.journalEntry.findMany.mockResolvedValue([]);
        await run(movement({ cost: offBalance ? null : decimal(0) }), reversal(), offBalance);
        expect(db.journalEntry.create).not.toHaveBeenCalled();
        expect(logActivity).not.toHaveBeenCalled();
    });

    it('still reverses a posted journal even when caller declares off-balance', async () => {
        await run(movement(), reversal(), true);
        expect(db.journalEntry.create).toHaveBeenCalledOnce();
    });

    it('rejects an existing active reversal journal', async () => {
        db.journalEntry.findFirst.mockResolvedValue({ id: 'already' });
        await expect(run()).rejects.toThrow(/sudah|already/i);
        expect(db.journalEntry.create).not.toHaveBeenCalled();
    });

    it('rejects a closed reversal period', async () => {
        vi.mocked(requireOpenJournalPeriod).mockRejectedValue(new Error('Periode CLOSED'));
        await expect(run()).rejects.toThrow(/periode|period/i);
        expect(db.journalEntry.create).not.toHaveBeenCalled();
    });

    it.each([
        { type: 'OUT' }, { salesOrderId: 'different' }, { productVariantId: 'different' },
        { toLocationId: 'different' }, { fromLocationId: 'warehouse' },
        { quantity: decimal(0) }, { quantity: decimal(38) }, { id: 'original-move' },
    ] satisfies Partial<StockMovement>[])('rejects an invalid source/reversal pair: %j', async override => {
        await expect(run(movement(), reversal(override))).rejects.toThrow(/mutasi|movement/i);
        expect(db.journalEntry.create).not.toHaveBeenCalled();
    });

    it('rejects an original without a sales order', async () => {
        await expect(run(movement({ salesOrderId: null }))).rejects.toThrow(/mutasi|movement/i);
    });

    it('rejects nested VOID sources', async () => {
        await expect(run(movement({ reference: 'VOID: prior shipment' }))).rejects.toThrow(/mutasi|movement/i);
    });

    it.each(['empty', 'unbalanced', 'negative', 'nan', 'rate', 'currency'])('rejects invalid source lines: %s', async kind => {
        const journal = source();
        const changed = kind === 'empty' ? [] : journal.lines.map((l, i) => i !== 0 ? l : ({
            ...l,
            ...(kind === 'unbalanced' ? { debit: decimal(421) } : {}),
            ...(kind === 'negative' ? { debit: decimal(-1) } : {}),
            ...(kind === 'nan' ? { debit: decimal(NaN) } : {}),
            ...(kind === 'rate' ? { exchangeRate: decimal(0) } : {}),
            ...(kind === 'currency' ? { currency: '' } : {}),
        }));
        db.journalEntry.findMany.mockResolvedValue([{ ...journal, lines: changed }]);
        await expect(run()).rejects.toThrow(/jurnal|journal/i);
        expect(db.journalEntry.create).not.toHaveBeenCalled();
    });

    it('propagates audit failures to the owning transaction', async () => {
        vi.mocked(logActivity).mockRejectedValue(new Error('audit unavailable'));
        await expect(run()).rejects.toThrow('audit unavailable');
        expect(logActivity).toHaveBeenCalledWith(expect.objectContaining({ tx }));
    });
});
