import {
    JournalStatus,
    Prisma,
    ReferenceType,
    type PurchaseInvoiceStatus,
} from '@prisma/client';

import { BusinessRuleError, NotFoundError } from '@/lib/errors/errors';
import { logActivity } from '@/lib/tools/audit';
import { AccountingService } from '@/services/accounting/accounting-service';
import { resolveAccount } from '@/services/accounting/account-resolver';
import { requireOpenJournalPeriod } from '@/services/finance/sales-recognition-service';

const CENT = new Prisma.Decimal('0.01');

export type PurchaseBillJournalAccounts = {
    grClearingAccountId: string;
    vatInputAccountId: string;
    accountsPayableAccountId: string;
};

export async function resolvePurchaseBillJournalAccounts(): Promise<PurchaseBillJournalAccounts> {
    const [grClearing, vatInput, accountsPayable] = await Promise.all([
        resolveAccount('gr-clearing'),
        resolveAccount('vat-input'),
        resolveAccount('accounts-payable'),
    ]);
    return {
        grClearingAccountId: grClearing.id,
        vatInputAccountId: vatInput.id,
        accountsPayableAccountId: accountsPayable.id,
    };
}

type SyncPurchaseBillInput = {
    invoiceId: string;
    targetTotal: Prisma.Decimal;
    poTotal: Prisma.Decimal;
    poTax: Prisma.Decimal;
    userId: string;
    accounts: PurchaseBillJournalAccounts;
};

type LockedInvoice = {
    id: string;
    invoiceNumber: string;
    invoiceDate: Date;
    totalAmount: Prisma.Decimal;
    paidAmount: Prisma.Decimal;
    status: PurchaseInvoiceStatus;
};

type ActiveJournal = {
    id: string;
    status: JournalStatus;
    entryDate: Date;
    isAutoGenerated: boolean;
    lines: Array<{
        accountId: string;
        debit: Prisma.Decimal;
        credit: Prisma.Decimal;
    }>;
};

type JournalAmounts = {
    total: number;
    subtotal: number;
    tax: number;
};

type JournalLineInput = {
    accountId: string;
    debit: number;
    credit: number;
    description: string;
};

function assertDistinctAccountRoles(
    accounts: PurchaseBillJournalAccounts,
): void {
    const accountIds = [
        accounts.grClearingAccountId,
        accounts.vatInputAccountId,
        accounts.accountsPayableAccountId,
    ];
    if (
        accountIds.some((accountId) => !accountId) ||
        new Set(accountIds).size !== accountIds.length
    ) {
        throw new BusinessRuleError(
            'Akun GR/IR, PPN masukan, dan hutang harus berbeda.',
            { accountIds },
            'PURCHASE_JOURNAL_ACCOUNT_CONFLICT',
        );
    }
}

function roundMoney(value: number): number {
    return new Prisma.Decimal(value).toDecimalPlaces(2).toNumber();
}

export function calculatePurchaseJournalAmounts(
    totalValue: Prisma.Decimal.Value,
    poTotalValue: Prisma.Decimal.Value,
    poTaxValue: Prisma.Decimal.Value,
): JournalAmounts {
    const total = new Prisma.Decimal(totalValue);
    const poTotal = new Prisma.Decimal(poTotalValue);
    const poTax = new Prisma.Decimal(poTaxValue);
    if ([total, poTotal, poTax].some(value => !value.isFinite() || value.isNegative() || value.decimalPlaces() > 2 || value.gt('9999999999999.99')) ||
        (poTax.gt(0) && poTotal.lte(poTax))) {
        throw new BusinessRuleError('Nominal bill atau PPN tidak valid.', undefined, 'PURCHASE_JOURNAL_INVALID_AMOUNT');
    }
    // Equivalent to the creation handler's proportional VAT, without float loss.
    const tax = poTax.gt(0)
        ? total.mul(poTax).div(poTotal).toDecimalPlaces(2)
        : new Prisma.Decimal(0);
    return { total: total.toNumber(), subtotal: total.minus(tax).toNumber(), tax: tax.toNumber() };
}

function fullJournalLines(
    amounts: JournalAmounts,
    invoiceNumber: string,
    accounts: PurchaseBillJournalAccounts,
): JournalLineInput[] {
    if (amounts.total === 0) return [];

    return [
        {
            accountId: accounts.grClearingAccountId,
            debit: amounts.subtotal,
            credit: 0,
            description: `GR/IR: ${invoiceNumber}`,
        },
        ...(amounts.tax > 0
            ? [
                  {
                      accountId: accounts.vatInputAccountId,
                      debit: amounts.tax,
                      credit: 0,
                      description: `VAT Input for ${invoiceNumber}`,
                  },
              ]
            : []),
        {
            accountId: accounts.accountsPayableAccountId,
            debit: 0,
            credit: amounts.total,
            description: `AP for ${invoiceNumber}`,
        },
    ];
}

function assertKnownJournalShape(
    journals: ActiveJournal[],
    accounts: PurchaseBillJournalAccounts,
    poTotal: Prisma.Decimal,
    poTax: Prisma.Decimal,
): JournalAmounts {
    const draftCount = journals.filter(
        (journal) => journal.status === JournalStatus.DRAFT,
    ).length;
    const postedCount = journals.filter(
        (journal) => journal.status === JournalStatus.POSTED,
    ).length;

    if (draftCount > 1 || (draftCount > 0 && postedCount > 0)) {
        throw new BusinessRuleError(
            'Ditemukan kombinasi jurnal pembelian aktif yang ambigu. Rekonsiliasi jurnal terlebih dahulu.',
            { journalIds: journals.map((journal) => journal.id) },
            'PURCHASE_JOURNAL_AMBIGUOUS',
        );
    }

    const allowedAccounts = new Set([
        accounts.grClearingAccountId,
        accounts.vatInputAccountId,
        accounts.accountsPayableAccountId,
    ]);
    let grNetDebit = new Prisma.Decimal(0);
    let vatNetDebit = new Prisma.Decimal(0);
    let apNetCredit = new Prisma.Decimal(0);

    for (const journal of journals) {
        let debit = new Prisma.Decimal(0);
        let credit = new Prisma.Decimal(0);
        if (
            !journal.isAutoGenerated ||
            (journal.lines.length === 0 &&
                journal.status !== JournalStatus.DRAFT)
        ) {
            throw new BusinessRuleError(
                'Jurnal pembelian lama tidak dikenali sebagai jurnal otomatis yang aman untuk disinkronkan.',
                { journalId: journal.id },
                'PURCHASE_JOURNAL_MISMATCH',
            );
        }

        for (const journalLine of journal.lines) {
            const invalidAmount =
                !journalLine.debit.isFinite() ||
                !journalLine.credit.isFinite() ||
                journalLine.debit.isNegative() ||
                journalLine.credit.isNegative() ||
                (journalLine.debit.gt(0) && journalLine.credit.gt(0));
            if (!allowedAccounts.has(journalLine.accountId) || invalidAmount) {
                throw new BusinessRuleError(
                    'Pemetaan atau nominal jurnal pembelian lama tidak cocok. Rekonsiliasi jurnal terlebih dahulu.',
                    { journalId: journal.id, accountId: journalLine.accountId },
                    'PURCHASE_JOURNAL_MISMATCH',
                );
            }

            debit = debit.plus(journalLine.debit);
            credit = credit.plus(journalLine.credit);
            const netDebit = journalLine.debit.minus(journalLine.credit);
            if (journalLine.accountId === accounts.grClearingAccountId) {
                grNetDebit = grNetDebit.plus(netDebit);
            } else if (journalLine.accountId === accounts.vatInputAccountId) {
                vatNetDebit = vatNetDebit.plus(netDebit);
            } else {
                apNetCredit = apNetCredit.plus(
                    journalLine.credit.minus(journalLine.debit),
                );
            }
        }

        if (debit.minus(credit).abs().gte(CENT)) {
            throw new BusinessRuleError(
                'Jurnal pembelian lama tidak seimbang. Rekonsiliasi jurnal terlebih dahulu.',
                { journalId: journal.id },
                'PURCHASE_JOURNAL_MISMATCH',
            );
        }
    }

    if (journals.length > 0 && apNetCredit.isNegative()) {
        throw new BusinessRuleError(
            'Saldo jurnal hutang pembelian lama tidak valid. Rekonsiliasi jurnal terlebih dahulu.',
            undefined,
            'PURCHASE_JOURNAL_MISMATCH',
        );
    }

    const existing = calculatePurchaseJournalAmounts(
        apNetCredit,
        poTotal,
        poTax,
    );
    if (
        grNetDebit.minus(existing.subtotal).abs().gte(CENT) ||
        vatNetDebit.minus(existing.tax).abs().gte(CENT)
    ) {
        throw new BusinessRuleError(
            'Komposisi GR/IR, PPN, dan hutang pada jurnal lama tidak cocok. Rekonsiliasi jurnal terlebih dahulu.',
            undefined,
            'PURCHASE_JOURNAL_MISMATCH',
        );
    }

    return existing;
}

function deltaJournalLines(
    desired: JournalAmounts,
    existing: JournalAmounts,
    invoiceNumber: string,
    accounts: PurchaseBillJournalAccounts,
): JournalLineInput[] {
    const lines: JournalLineInput[] = [];
    const grDelta = roundMoney(desired.subtotal - existing.subtotal);
    const taxDelta = roundMoney(desired.tax - existing.tax);
    const apDelta = roundMoney(desired.total - existing.total);

    if (Math.abs(grDelta) > 0) {
        lines.push({
            accountId: accounts.grClearingAccountId,
            debit: grDelta > 0 ? grDelta : 0,
            credit: grDelta < 0 ? -grDelta : 0,
            description: `GR/IR adjustment: ${invoiceNumber}`,
        });
    }
    if (Math.abs(taxDelta) > 0) {
        lines.push({
            accountId: accounts.vatInputAccountId,
            debit: taxDelta > 0 ? taxDelta : 0,
            credit: taxDelta < 0 ? -taxDelta : 0,
            description: `VAT Input adjustment for ${invoiceNumber}`,
        });
    }
    if (Math.abs(apDelta) > 0) {
        lines.push({
            accountId: accounts.accountsPayableAccountId,
            debit: apDelta < 0 ? -apDelta : 0,
            credit: apDelta > 0 ? apDelta : 0,
            description: `AP adjustment for ${invoiceNumber}`,
        });
    }

    return lines;
}

/**
 * Caller owns the transaction. The invoice row is locked before paid-state is
 * checked, and all invoice, journal, and audit writes use the same client.
 */
export async function syncPurchaseBillAndJournal(
    tx: Prisma.TransactionClient,
    input: SyncPurchaseBillInput,
): Promise<{
    action: 'noop' | 'protected' | 'updated';
    invoice: LockedInvoice;
}> {
    assertDistinctAccountRoles(input.accounts);

    await tx.$queryRaw`SELECT id FROM "PurchaseInvoice" WHERE id = ${input.invoiceId} FOR UPDATE`;
    const invoice = (await tx.purchaseInvoice.findUnique({
        where: { id: input.invoiceId },
    })) as LockedInvoice | null;
    if (!invoice) throw new NotFoundError('Purchase Invoice', input.invoiceId);

    const paidAmount = new Prisma.Decimal(invoice.paidAmount);
    const maySync =
        invoice.status === 'DRAFT' ||
        (invoice.status === 'UNPAID' && paidAmount.isZero());
    if (!maySync) return { action: 'protected', invoice };

    await tx.$queryRaw`SELECT id FROM "JournalEntry" WHERE "referenceType" = 'PURCHASE_INVOICE' AND "referenceId" = ${input.invoiceId} AND status <> 'VOIDED' FOR UPDATE`;
    const journals = (await tx.journalEntry.findMany({
        where: {
            referenceType: ReferenceType.PURCHASE_INVOICE,
            referenceId: input.invoiceId,
            status: { not: JournalStatus.VOIDED },
        },
        include: { lines: true },
        orderBy: { createdAt: 'asc' },
    })) as ActiveJournal[];

    const desired = calculatePurchaseJournalAmounts(
        input.targetTotal,
        input.poTotal,
        input.poTax,
    );
    const existing = assertKnownJournalShape(
        journals,
        input.accounts,
        input.poTotal,
        input.poTax,
    );
    const draftJournal = journals.find(
        (journal) => journal.status === JournalStatus.DRAFT,
    );
    if (
        journals.some((journal) => journal.status === JournalStatus.POSTED) &&
        invoice.status === 'DRAFT'
    ) {
        throw new BusinessRuleError(
            'Bill DRAFT tidak boleh memiliki jurnal POSTED. Rekonsiliasi terlebih dahulu.',
            { invoiceId: invoice.id },
            'PURCHASE_JOURNAL_MISMATCH',
        );
    }
    if (
        journals.length > 0 &&
        !new Prisma.Decimal(existing.total).equals(invoice.totalAmount)
    ) {
        throw new BusinessRuleError(
            'Total jurnal aktif tidak cocok dengan total bill sebelum perubahan. Rekonsiliasi terlebih dahulu.',
            { invoiceId: invoice.id },
            'PURCHASE_JOURNAL_MISMATCH',
        );
    }
    const invoiceChanged = new Prisma.Decimal(invoice.totalAmount)
        .minus(input.targetTotal)
        .abs()
        .gte(CENT);
    const postedDeltaLines = draftJournal
        ? []
        : deltaJournalLines(
              desired,
              existing,
              invoice.invoiceNumber,
              input.accounts,
          );
    const missingJournalNeedsCreation =
        journals.length === 0 && desired.total > 0;
    const draftNeedsRefresh = Boolean(
        draftJournal &&
            (invoiceChanged ||
                roundMoney(existing.total - desired.total) !== 0 ||
                invoice.status !== 'DRAFT'),
    );
    const journalNeedsMutation =
        missingJournalNeedsCreation ||
        draftNeedsRefresh ||
        postedDeltaLines.length > 0;

    if (!invoiceChanged && !journalNeedsMutation) {
        return { action: 'noop', invoice };
    }

    await requireOpenJournalPeriod(tx, invoice.invoiceDate);
    if (draftJournal) await requireOpenJournalPeriod(tx, draftJournal.entryDate);

    const updatedInvoice = invoiceChanged
        ? ((await tx.purchaseInvoice.update({
              where: { id: invoice.id },
              data: { totalAmount: input.targetTotal },
          })) as LockedInvoice)
        : invoice;

    const desiredStatus =
        invoice.status === 'DRAFT' ? JournalStatus.DRAFT : JournalStatus.POSTED;
    if (draftJournal) {
        await tx.journalEntry.update({
            where: { id: draftJournal.id },
            data: {
                entryDate: invoice.invoiceDate,
                description: `Purchase Invoice #${invoice.invoiceNumber}`,
                reference: invoice.invoiceNumber,
                status: desiredStatus,
                lines: {
                    deleteMany: {},
                    create: fullJournalLines(
                        desired,
                        invoice.invoiceNumber,
                        input.accounts,
                    ),
                },
            },
        });
    } else if (missingJournalNeedsCreation) {
        await AccountingService.createJournalEntry(
            {
                entryDate: invoice.invoiceDate,
                description: `Purchase Invoice #${invoice.invoiceNumber}`,
                reference: invoice.invoiceNumber,
                referenceType: ReferenceType.PURCHASE_INVOICE,
                referenceId: invoice.id,
                isAutoGenerated: true,
                status: desiredStatus,
                lines: fullJournalLines(
                    desired,
                    invoice.invoiceNumber,
                    input.accounts,
                ),
            },
            tx,
        );
    } else if (postedDeltaLines.length > 0) {
        await AccountingService.createJournalEntry(
            {
                entryDate: invoice.invoiceDate,
                description: `Purchase Invoice adjustment #${invoice.invoiceNumber}`,
                reference: invoice.invoiceNumber,
                referenceType: ReferenceType.PURCHASE_INVOICE,
                referenceId: invoice.id,
                isAutoGenerated: true,
                status: JournalStatus.POSTED,
                lines: postedDeltaLines,
            },
            tx,
        );
    }

    await logActivity({
        userId: input.userId,
        action: 'SYNC_BILL_FROM_GR',
        entityType: 'PurchaseInvoice',
        entityId: invoice.id,
        details: `Bill ${invoice.invoiceNumber} synchronized from ${new Prisma.Decimal(invoice.totalAmount).toFixed(2)} to ${input.targetTotal.toFixed(2)} based on GR received quantities`,
        changes: {
            totalAmount: {
                from: new Prisma.Decimal(invoice.totalAmount).toFixed(2),
                to: input.targetTotal.toFixed(2),
            },
            journal: draftJournal
                ? 'refreshed'
                : missingJournalNeedsCreation
                  ? 'created'
                  : postedDeltaLines.length > 0
                    ? 'delta_appended'
                    : 'unchanged',
        },
        tx,
    });

    return { action: 'updated', invoice: updatedInvoice };
}
