BEGIN;

WITH je AS (
  INSERT INTO "JournalEntry" (
    id, "entryNumber", "entryDate", description, reference, "status", "isAutoGenerated", "createdAt", "updatedAt"
  ) VALUES (
    gen_random_uuid()::text,
    'OB-MEL-2026-0001',
    '2026-05-31 23:59:59'::timestamp,
    'Opening Balance Melindo - Journal Only + Module Bridge',
    'OPENING_BALANCE',
    'DRAFT'::"JournalStatus",
    false,
    NOW(),
    NOW()
  )
  RETURNING id
)
INSERT INTO "JournalLine" (
  id, "journalEntryId", "accountId", description, debit, credit, currency, "exchangeRate", "createdAt"
)
SELECT gen_random_uuid()::text, je.id, '7e3c7308-616a-4c9c-bd7c-0473775a9ecd', '1-111 Kas Besar', 0.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, 'a5ad4ec8-e2eb-4265-8c21-af3aeb1884ad', '1-112 Kas Kecil', 22692765.60, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '8d6380a6-321e-42cc-99dd-20e7227437ae', '1-113 MANDIRI', 9169510.98, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, 'fc006d9d-73c5-4695-b483-03255f578854', '1-114 BCA', 635383.70, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, 'eb68e9a7-91d7-40f4-8b53-20159acb9f9f', '1-116 Pajak Dibayar Dimuka', 647584521.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '6d72e42d-bee1-4519-8457-875db8de8770', '1-117 Piutang Karyawan', 15040000.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '8f8a8395-8591-4f14-a114-68fa6778fe85', '1-121 Konstruksi dalam Pengerjaan', 8165000.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '959cdb01-544e-4f0a-856f-0dc12a2e8331', '1-122 Asuransi Dibayar Dimuka', 0.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '6f83c45b-64cc-4d0b-b6ee-bd813c24e619', '1-123 Sewa Dibayar Dimuka', 51502003.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '6f83c45b-64cc-4d0b-b6ee-bd813c24e619', '1-125 Persediaan Bahan Penolong', 3650431.74, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, 'cbaf0019-3593-4827-8a22-53bd57adc4f9', '1-133 Uang Muka ke Supplier', 60917215.54, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '5e6b3dad-5992-498f-81c2-48a72a05abca', '2-120 PPN Keluaran', 0.00, 667916028.48, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '8aedd857-30f8-4416-9a5a-8ffc685966b6', '2-130 PPN Masukan', 0.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '14569e73-225c-4dbb-8c7d-dd3143fbc801', '2-131 Hutang Pajak', 0.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '0d476bb6-3929-49bc-b8e7-27a93eae7fdc', '2-140 Hutang Lancar Lainnya', 0.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, 'ffa6f2e8-2946-46fb-ba9f-2c1ad5f947d2', '2-210 Hutang Jangka Panjang', 0.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '71bc1bd3-becf-4ba4-988e-29ef9c0883f4', '2-390 Hutang ke Nugroho Pramono', 0.00, 681000000.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, 'dc7bd96c-8fe4-4a99-9dc2-429b418fcb42', '3-100b Modal Saham', 0.00, 0.00, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '19015a77-fdba-4590-95bb-7c3fbfa20639', '3-201b Laba Tahun Berjalan', 0.00, 172978343.45, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '19015a77-fdba-4590-95bb-7c3fbfa20639', '3-200b Laba Ditahan', 0.00, 355473088.24, 'IDR', 1, NOW() FROM je
UNION ALL SELECT gen_random_uuid()::text, je.id, '8f8a8395-8591-4f14-a114-68fa6778fe85', 'MODULE-BRIDGE Opening Balance Module Bridge', 1058010628.61, 0.00, 'IDR', 1, NOW() FROM je;

COMMIT;
