SELECT current_database() AS db;

SELECT 'Customer existing exact-name matches' AS check_name, COUNT(*) AS count
FROM "Customer" c
WHERE EXISTS (
  SELECT 1 FROM (
    SELECT 'AEPUDIN' AS name
UNION ALL
    SELECT 'AGAPE JAYA PRATAMA, CV' AS name
UNION ALL
    SELECT 'AGIL' AS name
UNION ALL
    SELECT 'AGUS' AS name
UNION ALL
    SELECT 'AGUS (KOH BILLY TJIO)' AS name
UNION ALL
    SELECT 'AGUS DWI' AS name
UNION ALL
    SELECT 'AGUS HD' AS name
UNION ALL
    SELECT 'AGUS PONOROGO' AS name
UNION ALL
    SELECT 'ALENG SUSANTO (TOKO DEDEK)' AS name
UNION ALL
    SELECT 'ALI' AS name
UNION ALL
    SELECT 'AMAR' AS name
UNION ALL
    SELECT 'ANDI' AS name
UNION ALL
    SELECT 'ANDRI' AS name
UNION ALL
    SELECT 'ANJAR' AS name
UNION ALL
    SELECT 'ANUGERAH LESTARI SEJAHTERA, CV' AS name
UNION ALL
    SELECT 'ARI' AS name
UNION ALL
    SELECT 'ARIF' AS name
UNION ALL
    SELECT 'AROMA' AS name
UNION ALL
    SELECT 'ARYA' AS name
UNION ALL
    SELECT 'BAROKAH PLASTIK' AS name
UNION ALL
    SELECT 'BATANG SUKSES MAKMUR, PT' AS name
UNION ALL
    SELECT 'BERDI JAYA' AS name
UNION ALL
    SELECT 'BRIGI' AS name
UNION ALL
    SELECT 'BU DEWI' AS name
UNION ALL
    SELECT 'BU IRMA' AS name
UNION ALL
    SELECT 'BU NARSO' AS name
UNION ALL
    SELECT 'CHERRY' AS name
UNION ALL
    SELECT 'CIPTA PLASTIK NUSANTARA, PT' AS name
UNION ALL
    SELECT 'DANIEL' AS name
UNION ALL
    SELECT 'DARKIN' AS name
UNION ALL
    SELECT 'DENNY' AS name
UNION ALL
    SELECT 'DEVI' AS name
UNION ALL
    SELECT 'DIDI' AS name
UNION ALL
    SELECT 'DNT' AS name
UNION ALL
    SELECT 'EKO' AS name
UNION ALL
    SELECT 'ERLIN MEILANI WIDYAWATI' AS name
UNION ALL
    SELECT 'FADILLA' AS name
UNION ALL
    SELECT 'FAJAR' AS name
UNION ALL
    SELECT 'FEBI' AS name
UNION ALL
    SELECT 'FIMA PLASTIK' AS name
UNION ALL
    SELECT 'GANDA GUNA BOX' AS name
UNION ALL
    SELECT 'GEMILANG FOAM INDONESIA' AS name
UNION ALL
    SELECT 'HARAPAN MAJU, CV' AS name
UNION ALL
    SELECT 'HARI ABDURAKHMAN' AS name
UNION ALL
    SELECT 'HARTONO LISTIYONO' AS name
UNION ALL
    SELECT 'HERI' AS name
UNION ALL
    SELECT 'HILAL GEMILANG KHAIR, PT' AS name
UNION ALL
    SELECT 'ISIS PRATITNO' AS name
UNION ALL
    SELECT 'ISMANTO+' AS name
UNION ALL
    SELECT 'ISWANTO' AS name
UNION ALL
    SELECT 'JANTAN, TOKO' AS name
UNION ALL
    SELECT 'JOGJA INDAH BOJONEGORO, CV' AS name
UNION ALL
    SELECT 'JOKO' AS name
UNION ALL
    SELECT 'JOY PLASTIK' AS name
UNION ALL
    SELECT 'KASTALONI' AS name
UNION ALL
    SELECT 'KELIK' AS name
UNION ALL
    SELECT 'KIS' AS name
UNION ALL
    SELECT 'KISWANTO' AS name
UNION ALL
    SELECT 'KOMPAS TOP, CV' AS name
UNION ALL
    SELECT 'LAMINDO AGENG MANDIRI, PT' AS name
UNION ALL
    SELECT 'LARNO' AS name
UNION ALL
    SELECT 'LIANTO' AS name
UNION ALL
    SELECT 'LIDYA' AS name
UNION ALL
    SELECT 'MAHFUD' AS name
UNION ALL
    SELECT 'MAHKOTA' AS name
UNION ALL
    SELECT 'MARSONO' AS name
UNION ALL
    SELECT 'MEKAR JAYA DAKOCAN' AS name
UNION ALL
    SELECT 'MELISA' AS name
UNION ALL
    SELECT 'MITRA BOGA SUKSES, CV' AS name
UNION ALL
    SELECT 'MUHTADI' AS name
UNION ALL
    SELECT 'MUSTAKIM' AS name
UNION ALL
    SELECT 'NYOTO PLASTIK' AS name
UNION ALL
    SELECT 'PAK BILLY' AS name
UNION ALL
    SELECT 'PAK DONI' AS name
UNION ALL
    SELECT 'PAK PRAS' AS name
UNION ALL
    SELECT 'PANDA' AS name
UNION ALL
    SELECT 'PELANGI PLASTIK' AS name
UNION ALL
    SELECT 'PELITA TOMANGMAS, PT' AS name
UNION ALL
    SELECT 'PLASTIK SAMUDRA' AS name
UNION ALL
    SELECT 'PT SONLY PRATAMA SEJAHTERA' AS name
UNION ALL
    SELECT 'PT SUPERPLAST ADIPERKASA' AS name
UNION ALL
    SELECT 'PURWANTO' AS name
UNION ALL
    SELECT 'PUTRI' AS name
UNION ALL
    SELECT 'RIBUT SNACK' AS name
UNION ALL
    SELECT 'RIKO' AS name
UNION ALL
    SELECT 'RINI' AS name
UNION ALL
    SELECT 'RISKA' AS name
UNION ALL
    SELECT 'ROBERT ADRIAN HILLEBRANDT' AS name
UNION ALL
    SELECT 'ROHMAT' AS name
UNION ALL
    SELECT 'RUDI' AS name
UNION ALL
    SELECT 'RUDI HERNAWAN' AS name
UNION ALL
    SELECT 'RUKUN JAYA' AS name
UNION ALL
    SELECT 'RUKUN SEJAHTERA, CV' AS name
UNION ALL
    SELECT 'SAHABAT ABADI' AS name
UNION ALL
    SELECT 'SAHABAT ABADI, CV' AS name
UNION ALL
    SELECT 'SANDIKAN' AS name
UNION ALL
    SELECT 'SANTOSO JAYA PLASTIK, PT' AS name
UNION ALL
    SELECT 'SARI BOGA' AS name
UNION ALL
    SELECT 'Saryanto' AS name
UNION ALL
    SELECT 'SAUDIN' AS name
UNION ALL
    SELECT 'SAYUTI NASUTION' AS name
UNION ALL
    SELECT 'SEMAR' AS name
UNION ALL
    SELECT 'SETIA JAYA PLASTIK' AS name
UNION ALL
    SELECT 'SETYO RAHARJO' AS name
UNION ALL
    SELECT 'SINUK' AS name
UNION ALL
    SELECT 'SODIK' AS name
UNION ALL
    SELECT 'SOLO MULTIPACKING, PT' AS name
UNION ALL
    SELECT 'SPD JAYA' AS name
UNION ALL
    SELECT 'SPPG Sawahan' AS name
UNION ALL
    SELECT 'STARFARM, CV' AS name
UNION ALL
    SELECT 'SUGENG SANTOSO' AS name
UNION ALL
    SELECT 'SUHAR' AS name
UNION ALL
    SELECT 'SUMARNI' AS name
UNION ALL
    SELECT 'SUMBER WANGI' AS name
UNION ALL
    SELECT 'SUPERPLAST ADIPERKASA INDONESIA, PT' AS name
UNION ALL
    SELECT 'TAKUL' AS name
UNION ALL
    SELECT 'TJIN LIANG' AS name
UNION ALL
    SELECT 'TOKO 234 RIZKI' AS name
UNION ALL
    SELECT 'Toko Kala Jaya Plastik' AS name
UNION ALL
    SELECT 'TOKO LKS' AS name
UNION ALL
    SELECT 'TOKO PARASUT' AS name
UNION ALL
    SELECT 'TOKO PLASTIK JAYASHREE (DYANA PARAMITA)' AS name
UNION ALL
    SELECT 'TOKO PLASTIK JEMPOL' AS name
UNION ALL
    SELECT 'TOKO PLASTIK UTAMA' AS name
UNION ALL
    SELECT 'TOKO REJEKI' AS name
UNION ALL
    SELECT 'Toko Sepeda Santoso' AS name
UNION ALL
    SELECT 'TOKO SIGIT' AS name
UNION ALL
    SELECT 'TOKO SUMBER JAYA PLASTIK (SJP)' AS name
UNION ALL
    SELECT 'TOP ASLI, CV' AS name
UNION ALL
    SELECT 'Triyanto' AS name
UNION ALL
    SELECT 'UDIN' AS name
UNION ALL
    SELECT 'WAHYU' AS name
UNION ALL
    SELECT 'WAHYU PURNO WIDODO' AS name
UNION ALL
    SELECT 'WARASTANTO' AS name
UNION ALL
    SELECT 'WIDODO' AS name
UNION ALL
    SELECT 'WIDOKO' AS name
UNION ALL
    SELECT 'WIDYA TOKO' AS name
UNION ALL
    SELECT 'WIJIYANTO' AS name
UNION ALL
    SELECT 'WINDOKO' AS name
UNION ALL
    SELECT 'WIRATAMA PLASINDO' AS name
UNION ALL
    SELECT 'YONATHAN TJIOOK TJIE HONG' AS name
UNION ALL
    SELECT 'YONO' AS name
UNION ALL
    SELECT 'YOPI' AS name
UNION ALL
    SELECT 'YUDI' AS name
UNION ALL
    SELECT 'YUSUF' AS name
UNION ALL
    SELECT 'ZULFIAR' AS name
  ) staging WHERE staging.name = c.name
)
UNION ALL
SELECT 'Supplier existing exact-name matches', COUNT(*)
FROM "Supplier" s
WHERE EXISTS (
  SELECT 1 FROM (
    SELECT 'AGUNG JAYA' AS name
UNION ALL
    SELECT 'AGUS SUPRIYANTO' AS name
UNION ALL
    SELECT 'AMAN' AS name
UNION ALL
    SELECT 'AMANAA CONSULTING' AS name
UNION ALL
    SELECT 'ASURANSI MITRA PELINDUNGI MUSTIKA, PT' AS name
UNION ALL
    SELECT 'BAHANA BUANABOX, PT' AS name
UNION ALL
    SELECT 'BARUARA RAYA MANDIRI, PT' AS name
UNION ALL
    SELECT 'CIPTA PLASTIK NUSANTARA, PT' AS name
UNION ALL
    SELECT 'CIPTA SURYA PLASTINDO, PT' AS name
UNION ALL
    SELECT 'CITRA MANDIRI AMANAH' AS name
UNION ALL
    SELECT 'CV CAHAYA CEMERLANG ISTIMEWA' AS name
UNION ALL
    SELECT 'DNM' AS name
UNION ALL
    SELECT 'FADILA' AS name
UNION ALL
    SELECT 'FAJAR' AS name
UNION ALL
    SELECT 'HS. MULYO / NARTO BENGKEL MOBIL' AS name
UNION ALL
    SELECT 'INDOPOLY SWAKARSA INDUSTRY, TBK' AS name
UNION ALL
    SELECT 'INTERA LESTARI POLIMER, PT' AS name
UNION ALL
    SELECT 'JANTAN, TOKO' AS name
UNION ALL
    SELECT 'JOGLOSEMARCCTV' AS name
UNION ALL
    SELECT 'KARYA INDAH MESINDO, PT' AS name
UNION ALL
    SELECT 'KEISHA CHEMICLAS, CV' AS name
UNION ALL
    SELECT 'MARGINI' AS name
UNION ALL
    SELECT 'NAGA PRINT' AS name
UNION ALL
    SELECT 'PANCA BUDI PRATAMA' AS name
UNION ALL
    SELECT 'PANCA BUDI PRATAMA, PT' AS name
UNION ALL
    SELECT 'PAPYRUSS' AS name
UNION ALL
    SELECT 'PELANGI PLASTIC' AS name
UNION ALL
    SELECT 'PODOMORO' AS name
UNION ALL
    SELECT 'PT GUWATIRTA SEJAHTERA' AS name
UNION ALL
    SELECT 'PT KARYA INDAH MESINDO' AS name
UNION ALL
    SELECT 'PT SOLO MULTIPACK' AS name
UNION ALL
    SELECT 'RINALDI EDO' AS name
UNION ALL
    SELECT 'RIZKY PLASTIK' AS name
UNION ALL
    SELECT 'RUKUN SEJAHTERA, CV' AS name
UNION ALL
    SELECT 'SAHABAT ABADI, CV' AS name
UNION ALL
    SELECT 'SANTOSA FIRE PROTECTION' AS name
UNION ALL
    SELECT 'SANTOSO JAYA PLASTIK, PT' AS name
UNION ALL
    SELECT 'SAUDIN' AS name
UNION ALL
    SELECT 'SB' AS name
UNION ALL
    SELECT 'SB PLAST / CHANDRA' AS name
UNION ALL
    SELECT 'SETYO RAHARJO' AS name
UNION ALL
    SELECT 'SINAR MAS PLASINDO' AS name
UNION ALL
    SELECT 'SISKA RISMIYATI' AS name
UNION ALL
    SELECT 'SOLINDO GRAPIKA, PT' AS name
UNION ALL
    SELECT 'SOLO MULTIPACKING, PT' AS name
UNION ALL
    SELECT 'SUMBER MAKMUR SENTOSA, CV' AS name
UNION ALL
    SELECT 'SURYA OFFSET' AS name
UNION ALL
    SELECT 'TOKO KITA' AS name
UNION ALL
    SELECT 'TOP ASLI, CV' AS name
UNION ALL
    SELECT 'TRI KUNCORO PUTRA' AS name
UNION ALL
    SELECT 'UMAR' AS name
UNION ALL
    SELECT 'WIDYA TOKO' AS name
UNION ALL
    SELECT 'YONATHAN TJIOOK TJIE HONG' AS name
  ) staging WHERE staging.name = s.name
);
