import{beforeEach,describe,expect,it,vi}from'vitest';
const m=vi.hoisted(()=>({guard:vi.fn(),context:vi.fn(),user:vi.fn(),grants:vi.fn(),entitled:vi.fn(),post:vi.fn(),reverse:vi.fn(),revalidate:vi.fn()}));
vi.mock('@/lib/core/tenant',()=>({withTenant:(f:unknown)=>f}));vi.mock('@/lib/core/prisma',()=>({getTenantDbFromContext:m.context}));vi.mock('@/lib/auth/finance-access',()=>({requireFinanceAccess:m.guard,requireFinanceApprover:m.guard}));vi.mock('@/lib/auth/access-policy',async original=>({...await original<object>(),hasWorkspaceEntitlement:m.entitled}));vi.mock('@/services/finance/invoice-price-adjustment-service',()=>({postInvoicePriceAdjustment:m.post,reverseInvoicePriceAdjustment:m.reverse}));vi.mock('next/cache',()=>({revalidatePath:m.revalidate}));
import{postFinanceInvoicePriceAdjustment,reverseFinanceInvoicePriceAdjustment}from'../invoice-price-adjustment';
describe('price adjustment approval authorization',()=>{
 beforeEach(()=>{vi.clearAllMocks();m.guard.mockResolvedValue({user:{id:'actor'}});m.context.mockReturnValue({user:{findUnique:m.user},rolePermission:{findMany:m.grants}});m.user.mockResolvedValue({isActive:true,role:'FINANCE',roles:[]});m.grants.mockResolvedValue([{resource:'/finance/invoices/sales'}]);m.entitled.mockReturnValue(true);m.post.mockResolvedValue({invoiceId:'invoice'});m.reverse.mockResolvedValue({invoiceId:'invoice'});});
 it.each([postFinanceInvoicePriceAdjustment,reverseFinanceInvoicePriceAdjustment])('accepts authorized Finance, derives actor and revalidates only success',async action=>{expect((await action({createdById:'forged'})).success).toBe(true);expect(m.revalidate).toHaveBeenCalledWith('/finance/invoices/sales/invoice');expect(m.post.mock.calls[0]?.[1]??m.reverse.mock.calls[0]?.[1]).toBe('actor');});
 it.each(['missing-tenant','inactive','sales','permission','entitlement','superadmin'])('rejects %s before service mutation',async kind=>{if(kind==='missing-tenant')m.context.mockReturnValue(undefined);if(kind==='inactive')m.user.mockResolvedValue({isActive:false});if(kind==='sales')m.user.mockResolvedValue({isActive:true,role:'SALES',roles:[]});if(kind==='permission')m.grants.mockResolvedValue([{resource:'/sales'}]);if(kind==='entitlement')m.entitled.mockReturnValue(false);if(kind==='superadmin')m.guard.mockResolvedValue({user:{id:'actor',isSuperAdmin:true}});expect((await postFinanceInvoicePriceAdjustment({})).success).toBe(false);expect(m.post).not.toHaveBeenCalled();expect(m.revalidate).not.toHaveBeenCalled();});
 it('preserves rollback failures without false success or refresh',async()=>{m.post.mockRejectedValue(Error('rollback'));expect((await postFinanceInvoicePriceAdjustment({})).success).toBe(false);expect(m.revalidate).not.toHaveBeenCalled();});
});
