import { JournalStatus, ReferenceType } from '@prisma/client';

import { prisma } from '@/lib/core/prisma';
import { AccountingService } from '../accounting/accounting-service';

import { getAccountByCode } from './auto-journal-shared';

export async function handleSalesInvoiceCreated(invoiceId: string) {
    const invoice = await prisma.invoice.findUnique({
        where: { id: invoiceId },
        include: { salesOrder: true }
    });

    if (!invoice) throw new Error(`Invoice ${invoiceId} not found`);

    const arAccount = await getAccountByCode('11210');
    const revenueAccount = await getAccountByCode('41100');
    const vatAccount = await getAccountByCode('21310');

    const totalAmount = Number(invoice.totalAmount);
    const soTotal = Number(invoice.salesOrder.totalAmount || 0);
    const soTax = Number(invoice.salesOrder.taxAmount || 0);

    let taxAmount = 0;
    if (soTotal > 0 && soTax > 0) {
        const taxRate = soTax / (soTotal - soTax);
        const netAmount = totalAmount / (1 + taxRate);
        taxAmount = totalAmount - netAmount;
    }

    const subtotal = totalAmount - taxAmount;
    const journalStatus = invoice.status === 'DRAFT' ? JournalStatus.DRAFT : JournalStatus.POSTED;

    await AccountingService.createJournalEntry({
        entryDate: invoice.invoiceDate,
        description: `Sales Invoice #${invoice.invoiceNumber}`,
        reference: invoice.invoiceNumber,
        referenceType: ReferenceType.SALES_INVOICE,
        referenceId: invoice.id,
        isAutoGenerated: true,
        status: journalStatus,
        lines: [
            { accountId: arAccount.id, debit: totalAmount, credit: 0, description: `AR for ${invoice.invoiceNumber}` },
            { accountId: revenueAccount.id, debit: 0, credit: subtotal, description: `Revenue for ${invoice.invoiceNumber}` },
            { accountId: vatAccount.id, debit: 0, credit: taxAmount, description: `VAT Output for ${invoice.invoiceNumber}` }
        ]
    });
}

export async function handlePurchaseInvoiceCreated() {
    return;
}