import { JournalStatus, ReferenceType } from "@prisma/client";

import { prisma } from "@/lib/core/prisma";
import { AccountingService } from "../accounting/accounting-service";

import { getAccountByRole } from "./auto-journal-shared";

export async function handleSalesInvoiceCreated(invoiceId: string) {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: { salesOrder: true },
  });

  if (!invoice) throw new Error(`Invoice ${invoiceId} not found`);

  const arAccount = await getAccountByRole("accounts-receivable");
  const revenueAccount = await getAccountByRole("sales-revenue");
  const vatAccount = await getAccountByRole("vat-output");

  const totalAmount = Number(invoice.totalAmount);
  const soTotal = Number(invoice.salesOrder.totalAmount || 0);
  const soTax = Number(invoice.salesOrder.taxAmount || 0);

  let taxAmount = 0;
  // FIX: Guard against division by zero (soTotal === soTax)
  if (soTotal > 0 && soTax > 0 && soTotal > soTax) {
    const taxRate = soTax / (soTotal - soTax);
    const netAmount = totalAmount / (1 + taxRate);
    taxAmount = totalAmount - netAmount;
  }
  // else: taxAmount stays 0 (no tax info, or edge case where soTotal === soTax)

  const subtotal = totalAmount - taxAmount;
  const journalStatus =
    invoice.status === "DRAFT" ? JournalStatus.DRAFT : JournalStatus.POSTED;

  await AccountingService.createJournalEntry({
    entryDate: invoice.invoiceDate,
    description: `Sales Invoice #${invoice.invoiceNumber}`,
    reference: invoice.invoiceNumber,
    referenceType: ReferenceType.SALES_INVOICE,
    referenceId: invoice.id,
    isAutoGenerated: true,
    status: journalStatus,
    lines: [
      {
        accountId: arAccount.id,
        debit: totalAmount,
        credit: 0,
        description: `AR for ${invoice.invoiceNumber}`,
      },
      {
        accountId: revenueAccount.id,
        debit: 0,
        credit: subtotal,
        description: `Revenue for ${invoice.invoiceNumber}`,
      },
      {
        accountId: vatAccount.id,
        debit: 0,
        credit: taxAmount,
        description: `VAT Output for ${invoice.invoiceNumber}`,
      },
    ],
  });
}

export async function handlePurchaseInvoiceCreated(invoiceId: string) {
  const invoice = await prisma.purchaseInvoice.findUnique({
    where: { id: invoiceId },
    include: { purchaseOrder: true },
  });

  if (!invoice) throw new Error(`Purchase Invoice ${invoiceId} not found`);

  const totalAmount = Number(invoice.totalAmount);
  const poTotal = Number(invoice.purchaseOrder.totalAmount || 0);
  const poTax = Number(invoice.purchaseOrder.taxAmount || 0);

  let taxAmount = 0;
  if (poTotal > 0 && poTax > 0 && poTotal > poTax) {
    const taxRate = poTax / (poTotal - poTax);
    const netAmount = totalAmount / (1 + taxRate);
    taxAmount = totalAmount - netAmount;
  }

  if (taxAmount <= 0) return;

  const vatInputAccount = await getAccountByRole("vat-input");
  const apAccount = await getAccountByRole("accounts-payable");

  const journalStatus =
    invoice.status === "DRAFT" ? JournalStatus.DRAFT : JournalStatus.POSTED;

  await AccountingService.createJournalEntry({
    entryDate: invoice.invoiceDate,
    description: `Purchase Invoice #${invoice.invoiceNumber} - PPN Masukan`,
    reference: invoice.invoiceNumber,
    referenceType: ReferenceType.PURCHASE_INVOICE,
    referenceId: invoice.id,
    isAutoGenerated: true,
    status: journalStatus,
    lines: [
      {
        accountId: vatInputAccount.id,
        debit: taxAmount,
        credit: 0,
        description: `VAT Input for ${invoice.invoiceNumber}`,
      },
      {
        accountId: apAccount.id,
        debit: 0,
        credit: taxAmount,
        description: `AP for ${invoice.invoiceNumber} PPN`,
      },
    ],
  });
}
