import { JournalStatus, ReferenceType } from '@prisma/client';

import { prisma } from '@/lib/core/prisma';
import { AccountingService } from '../accounting/accounting-service';

import { getAccountByCode, getAccountCodeByMethod } from './auto-journal-shared';

export async function handleSalesPayment(paymentId: string, amount: number, method: string = 'Bank Transfer') {
    const payment = await prisma.payment.findUnique({
        where: { id: paymentId },
        include: { invoice: true }
    });
    const invoice = payment?.invoice;
    if (!payment || !invoice) return;

    const paymentAcc = await getAccountByCode(getAccountCodeByMethod(method));
    const arAcc = await getAccountByCode('11210');

    await AccountingService.createJournalEntry({
        entryDate: payment.paymentDate,
        description: `Payment Receipt (${method}) for ${invoice.invoiceNumber}`,
        reference: payment.paymentNumber || `PAY-${invoice.invoiceNumber}`,
        referenceType: ReferenceType.SALES_PAYMENT,
        referenceId: payment.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        lines: [
            { accountId: paymentAcc.id, debit: amount, credit: 0, description: 'Payment In' },
            { accountId: arAcc.id, debit: 0, credit: amount, description: 'AR Payment' }
        ]
    });
}

export async function handlePurchasePayment(paymentId: string, amount: number, method: string = 'Bank Transfer') {
    const payment = await prisma.payment.findUnique({
        where: { id: paymentId },
        include: { purchaseInvoice: true }
    });
    const invoice = payment?.purchaseInvoice;
    if (!payment || !invoice) return;

    const paymentAcc = await getAccountByCode(getAccountCodeByMethod(method));
    const apAcc = await getAccountByCode('21110');

    await AccountingService.createJournalEntry({
        entryDate: payment.paymentDate,
        description: `Payment (${method}) for Purchase Invoice ${invoice.invoiceNumber}`,
        reference: payment.paymentNumber || `PAY-${invoice.invoiceNumber}`,
        referenceType: ReferenceType.PURCHASE_PAYMENT,
        referenceId: payment.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        lines: [
            { accountId: apAcc.id, debit: amount, credit: 0, description: 'AP Payment' },
            { accountId: paymentAcc.id, debit: 0, credit: amount, description: 'Payment Out' }
        ]
    });
}