import { JournalStatus, ReferenceType } from '@prisma/client';

import { prisma } from '@/lib/core/prisma';
import { BusinessRuleError } from '@/lib/errors/errors';
import { AccountingService } from '../accounting/accounting-service';

import { getAccountByRole } from './auto-journal-shared';

/** @deprecated Physical receiving never posts AR. Use the authenticated Finance credit action. */
export async function handleSalesReturnReceived(_returnId: string): Promise<void> {
    throw new BusinessRuleError('Posting retur otomatis dinonaktifkan. Gunakan alokasi kredit Finance berdasarkan invoice dan pengiriman asal.');
}

export async function handlePurchaseReturnShipped(returnId: string) {
    const purchaseReturn = await prisma.purchaseReturn.findUnique({
        where: { id: returnId },
        include: { items: true, supplier: true },
    });
    if (!purchaseReturn || !purchaseReturn.totalAmount) return;

    const apAcc = await getAccountByRole('accounts-payable');
    const invAcc = await getAccountByRole('raw-material');

    await AccountingService.createJournalEntry({
        entryDate: purchaseReturn.returnDate,
        description: `Purchase Return Debit Note ${purchaseReturn.returnNumber}`,
        reference: purchaseReturn.returnNumber,
        referenceType: ReferenceType.PURCHASE_RETURN,
        referenceId: purchaseReturn.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        lines: [
            {
                accountId: apAcc.id,
                debit: Number(purchaseReturn.totalAmount),
                credit: 0,
                description: 'AP Reversal / Debit Note',
            },
            {
                accountId: invAcc.id,
                debit: 0,
                credit: Number(purchaseReturn.totalAmount),
                description: 'Inventory Reduction',
            },
        ],
    });
}
