import { JournalStatus, ReferenceType } from '@prisma/client';

import { prisma } from '@/lib/core/prisma';
import { AccountingService } from '../accounting/accounting-service';

import { getAccountByRole } from './auto-journal-shared';

// Configurable restock valuation rate for returned goods in GOOD condition.
// 0.7 = 70% of original price (conservative estimate for resellable returns).
const RESTOCK_VALUATION_RATE = 0.7;

export async function handleSalesReturnReceived(returnId: string) {
    const salesReturn = await prisma.salesReturn.findUnique({
        where: { id: returnId },
        include: { items: true, customer: true }
    });
    if (!salesReturn || !salesReturn.totalAmount) return;

    const returnAcc = await getAccountByRole('sales-return');
    const arAcc = await getAccountByRole('accounts-receivable');

    const lines = [
        { accountId: returnAcc.id, debit: Number(salesReturn.totalAmount), credit: 0, description: 'Sales Return' },
        { accountId: arAcc.id, debit: 0, credit: Number(salesReturn.totalAmount), description: 'AR Reversal' }
    ];

    let restockValue = 0;
    for (const item of salesReturn.items) {
        if (item.condition === 'GOOD') {
            restockValue += Number(item.returnedQty) * Number(item.unitPrice) * RESTOCK_VALUATION_RATE;
        }
    }

    if (restockValue > 0) {
        const invAcc = await getAccountByRole('raw-material');
        const cogsAcc = await getAccountByRole('cogs');
        lines.push(
            { accountId: invAcc.id, debit: restockValue, credit: 0, description: 'Inventory Restock' },
            { accountId: cogsAcc.id, debit: 0, credit: restockValue, description: 'COGS Reversal' }
        );
    }

    await AccountingService.createJournalEntry({
        entryDate: salesReturn.returnDate,
        description: `Sales Return Credit Note ${salesReturn.returnNumber}`,
        reference: salesReturn.returnNumber,
        referenceType: ReferenceType.SALES_RETURN,
        referenceId: salesReturn.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        lines
    });
}

export async function handlePurchaseReturnShipped(returnId: string) {
    const purchaseReturn = await prisma.purchaseReturn.findUnique({
        where: { id: returnId },
        include: { items: true, supplier: true }
    });
    if (!purchaseReturn || !purchaseReturn.totalAmount) return;

    const apAcc = await getAccountByRole('accounts-payable');
    const invAcc = await getAccountByRole('raw-material');

    await AccountingService.createJournalEntry({
        entryDate: purchaseReturn.returnDate,
        description: `Purchase Return Debit Note ${purchaseReturn.returnNumber}`,
        reference: purchaseReturn.returnNumber,
        referenceType: ReferenceType.PURCHASE_RETURN,
        referenceId: purchaseReturn.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        lines: [
            { accountId: apAcc.id, debit: Number(purchaseReturn.totalAmount), credit: 0, description: 'AP Reversal / Debit Note' },
            { accountId: invAcc.id, debit: 0, credit: Number(purchaseReturn.totalAmount), description: 'Inventory Reduction' }
        ]
    });
}
