import { JournalStatus, ReferenceType } from '@prisma/client';

import { prisma } from '@/lib/core/prisma';
import { AccountingService } from '../accounting/accounting-service';

import {
    getAccountByRole,
    resolvePaymentBankAccount,
} from './auto-journal-shared';

export async function handleSalesPayment(
    paymentId: string,
    amount: number,
    method: string = 'Bank Transfer',
    // Tanggal buku jurnal. Default: payment.paymentDate (jalur direct-entry, finance input
    // sendiri saat itu). Jalur verifikasi remittance mengirim tanggal verifikasi finance —
    // sama dengan paymentDate-nya, jadi jurnal dan payment selalu jatuh di hari yang sama.
    journalDate?: Date,
) {
    // Validate amount
    if (!amount || amount <= 0 || !isFinite(amount)) {
        console.warn(
            `[AutoJournal] Invalid payment amount: ${amount} for paymentId=${paymentId}`,
        );
        return;
    }

    const payment = await prisma.payment.findUnique({
        where: { id: paymentId },
        include: { invoice: true },
    });
    const invoice = payment?.invoice;
    if (!payment || !invoice) {
        console.warn(
            `[AutoJournal] Payment or invoice not found for paymentId=${paymentId}`,
        );
        return;
    }

    const paymentMethod = payment.method || method;
    const paymentAcc = await resolvePaymentBankAccount(
        paymentMethod,
        payment.destinationBank,
    );
    const arAcc = await getAccountByRole('accounts-receivable');

    await AccountingService.createJournalEntry({
        entryDate: journalDate ?? payment.paymentDate,
        description: `Payment Receipt (${paymentMethod}) for ${invoice.invoiceNumber}`,
        reference: payment.paymentNumber || `PAY-${invoice.invoiceNumber}`,
        referenceType: ReferenceType.SALES_PAYMENT,
        referenceId: payment.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        lines: [
            {
                accountId: paymentAcc.id,
                debit: amount,
                credit: 0,
                description: 'Payment In',
            },
            {
                accountId: arAcc.id,
                debit: 0,
                credit: amount,
                description: 'AR Payment',
            },
        ],
    });
}

export async function handlePurchasePayment(
    paymentId: string,
    amount: number,
    method: string = 'Bank Transfer',
    journalDate?: Date,
) {
    // Validate amount
    if (!amount || amount <= 0 || !isFinite(amount)) {
        console.warn(
            `[AutoJournal] Invalid payment amount: ${amount} for paymentId=${paymentId}`,
        );
        return;
    }

    const payment = await prisma.payment.findUnique({
        where: { id: paymentId },
        include: { purchaseInvoice: true },
    });
    const invoice = payment?.purchaseInvoice;
    if (!payment || !invoice) {
        console.warn(
            `[AutoJournal] Purchase payment or invoice not found for paymentId=${paymentId}`,
        );
        return;
    }

    const paymentMethod = payment.method || method;
    const paymentAcc = await resolvePaymentBankAccount(
        paymentMethod,
        payment.destinationBank,
    );
    const apAcc = await getAccountByRole('accounts-payable');

    await AccountingService.createJournalEntry({
        entryDate: journalDate ?? payment.paymentDate,
        description: `Payment (${paymentMethod}) for Purchase Invoice ${invoice.invoiceNumber}`,
        reference: payment.paymentNumber || `PAY-${invoice.invoiceNumber}`,
        referenceType: ReferenceType.PURCHASE_PAYMENT,
        referenceId: payment.id,
        isAutoGenerated: true,
        status: JournalStatus.POSTED,
        lines: [
            {
                accountId: apAcc.id,
                debit: amount,
                credit: 0,
                description: 'AP Payment',
            },
            {
                accountId: paymentAcc.id,
                debit: 0,
                credit: amount,
                description: 'Payment Out',
            },
        ],
    });
}
