import {
    JournalStatus,
    Prisma,
    ReferenceType,
    type Account,
} from '@prisma/client';

import { BusinessRuleError } from '@/lib/errors/errors';
import { AccountingService } from '@/services/accounting/accounting-service';

export type BarterJournalAccounts = {
    receivable: Pick<Account, 'id' | 'type' | 'isActive' | 'isCashAccount'>;
    payable: Pick<Account, 'id' | 'type' | 'isActive' | 'isCashAccount'>;
    cash?: Pick<Account, 'id' | 'type' | 'isActive' | 'isCashAccount'>;
};

function validateAccounts(
    accounts: BarterJournalAccounts,
    requiresCash: boolean,
) {
    if (
        !accounts.receivable.isActive ||
        !accounts.payable.isActive ||
        accounts.receivable.isCashAccount ||
        accounts.payable.isCashAccount ||
        accounts.receivable.type !== 'ASSET' ||
        accounts.payable.type !== 'LIABILITY'
    ) {
        throw new BusinessRuleError(
            'Mapping akun piutang/hutang barter tidak valid atau tidak aktif.',
            undefined,
            'BARTER_CONTROL_ACCOUNT_INVALID',
        );
    }
    if (
        requiresCash &&
        (!accounts.cash?.isActive || !accounts.cash.isCashAccount)
    ) {
        throw new BusinessRuleError(
            'Akun kas/bank pembayaran tambahan tidak valid atau tidak aktif.',
            undefined,
            'BARTER_CASH_ACCOUNT_INVALID',
        );
    }
}

export class BarterJournalService {
    static async validatePurchaseInvoiceJournal(
        tx: Prisma.TransactionClient,
        purchaseInvoiceId: string,
        totalAmount: Prisma.Decimal,
        payableAccountId: string,
    ) {
        await tx.$queryRaw`SELECT id FROM "JournalEntry" WHERE "referenceType" = 'PURCHASE_INVOICE' AND "referenceId" = ${purchaseInvoiceId} AND status <> 'VOIDED' FOR UPDATE`;
        const journals = await tx.journalEntry.findMany({
            where: {
                referenceType: ReferenceType.PURCHASE_INVOICE,
                referenceId: purchaseInvoiceId,
                status: { not: JournalStatus.VOIDED },
            },
            include: { lines: true },
        });
        if (
            journals.length !== 1 ||
            journals[0].status !== JournalStatus.POSTED
        ) {
            throw new BusinessRuleError(
                'Jurnal invoice pembelian belum tersedia atau belum POSTED. Selesaikan workflow invoice sebelum barter.',
                { purchaseInvoiceId },
                'BARTER_PURCHASE_JOURNAL_INVALID',
            );
        }
        const debit = journals[0].lines.reduce(
            (sum, line) => sum.plus(line.debit),
            new Prisma.Decimal(0),
        );
        const credit = journals[0].lines.reduce(
            (sum, line) => sum.plus(line.credit),
            new Prisma.Decimal(0),
        );
        const payableCredit = journals[0].lines
            .filter((line) => line.accountId === payableAccountId)
            .reduce(
                (sum, line) => sum.plus(line.credit).minus(line.debit),
                new Prisma.Decimal(0),
            );
        if (
            journals[0].lines.length === 0 ||
            journals[0].lines.some(
                (line) => line.debit.lt(0) || line.credit.lt(0),
            ) ||
            debit.minus(credit).abs().gt('0.01') ||
            payableCredit.minus(totalAmount).abs().gt('0.01')
        ) {
            throw new BusinessRuleError(
                'Nilai hutang pada jurnal invoice pembelian tidak cocok dengan total invoice.',
                { purchaseInvoiceId },
                'BARTER_PURCHASE_JOURNAL_AMOUNT_MISMATCH',
            );
        }
    }

    static async postOffset(
        tx: Prisma.TransactionClient,
        input: {
            settlementId: string;
            settlementNumber: string;
            amount: Prisma.Decimal;
            entryDate: Date;
            userId: string;
            salesInvoiceNumber: string;
            purchaseInvoiceNumber: string;
            accounts: BarterJournalAccounts;
        },
    ) {
        validateAccounts(input.accounts, false);
        const existing = await tx.journalEntry.findFirst({
            where: {
                referenceType: ReferenceType.BARTER_SETTLEMENT,
                referenceId: input.settlementId,
                status: { not: JournalStatus.VOIDED },
            },
        });
        if (existing) return existing;

        return AccountingService.createJournalEntry(
            {
                entryDate: input.entryDate,
                description: `Barter ${input.salesInvoiceNumber} dengan ${input.purchaseInvoiceNumber}`,
                reference: input.settlementNumber,
                referenceType: ReferenceType.BARTER_SETTLEMENT,
                referenceId: input.settlementId,
                status: JournalStatus.POSTED,
                isAutoGenerated: true,
                createdById: input.userId,
                lines: [
                    {
                        accountId: input.accounts.payable.id,
                        debit: input.amount.toNumber(),
                        credit: 0,
                        description: 'Potong hutang dagang',
                    },
                    {
                        accountId: input.accounts.receivable.id,
                        debit: 0,
                        credit: input.amount.toNumber(),
                        description: 'Potong piutang dagang',
                    },
                ],
            },
            tx,
        );
    }

    static async postCashPayment(
        tx: Prisma.TransactionClient,
        input: {
            paymentId: string;
            paymentNumber: string;
            amount: Prisma.Decimal;
            entryDate: Date;
            method: string;
            destinationBank: string | null;
            purchaseInvoiceNumber: string;
            userId: string;
            accounts: BarterJournalAccounts;
        },
    ) {
        validateAccounts(input.accounts, true);
        const existing = await tx.journalEntry.findFirst({
            where: {
                referenceType: ReferenceType.PURCHASE_PAYMENT,
                referenceId: input.paymentId,
                status: { not: JournalStatus.VOIDED },
            },
        });
        if (existing) return existing;

        return AccountingService.createJournalEntry(
            {
                entryDate: input.entryDate,
                description: `Pembayaran tambahan barter (${input.method}) untuk ${input.purchaseInvoiceNumber}`,
                reference: input.paymentNumber,
                referenceType: ReferenceType.PURCHASE_PAYMENT,
                referenceId: input.paymentId,
                status: JournalStatus.POSTED,
                isAutoGenerated: true,
                createdById: input.userId,
                lines: [
                    {
                        accountId: input.accounts.payable.id,
                        debit: input.amount.toNumber(),
                        credit: 0,
                        description: 'Pelunasan hutang dagang',
                    },
                    {
                        accountId: input.accounts.cash!.id,
                        debit: 0,
                        credit: input.amount.toNumber(),
                        description: input.destinationBank
                            ? `Uang keluar ${input.destinationBank}`
                            : 'Uang keluar',
                    },
                ],
            },
            tx,
        );
    }
}
