import { Prisma } from '@prisma/client';
import { getTenantDbFromContext } from '@/lib/core/prisma';
import { BusinessRuleError } from '@/lib/errors/errors';
import { generateEntryNumber } from '@/services/accounting/journal-posting';
import { requireOpenJournalPeriod } from './sales-recognition-service';

export const zero = () => new Prisma.Decimal(0);
export function customerCreditDb() {
    const db = getTenantDbFromContext();
    if (!db)
        throw new BusinessRuleError(
            'Konteks tenant wajib untuk saldo kredit pelanggan.',
        );
    return db;
}
export async function creditJournal(
    tx: Prisma.TransactionClient,
    input: {
        id: string;
        date: Date;
        reference: string;
        description: string;
        userId: string;
        lines: {
            accountId: string;
            debit: Prisma.Decimal;
            credit: Prisma.Decimal;
        }[];
    },
) {
    await requireOpenJournalPeriod(tx, input.date);
    const accountIds = [...new Set(input.lines.map((l) => l.accountId))];
    if (
        (await tx.account.count({
            where: { id: { in: accountIds }, isActive: true },
        })) !== accountIds.length
    )
        throw new BusinessRuleError(
            'Akun kredit pelanggan tidak aktif. Periksa pemetaan akun.',
        );
    if (
        !input.lines
            .reduce((s, l) => s.plus(l.debit).minus(l.credit), zero())
            .isZero()
    )
        throw new BusinessRuleError('Jurnal kredit pelanggan tidak seimbang.');
    return tx.journalEntry.create({
        data: {
            entryNumber: await generateEntryNumber(input.date, tx),
            entryDate: input.date,
            description: input.description,
            reference: input.reference,
            referenceType: 'MANUAL_ENTRY',
            referenceId: input.id,
            status: 'POSTED',
            isAutoGenerated: true,
            createdById: input.userId,
            approvedById: input.userId,
            approvedAt: new Date(),
            lines: { create: input.lines },
        },
    });
}
export async function reverseCreditJournal(
    tx: Prisma.TransactionClient,
    input: {
        journalId: string;
        id: string;
        date: Date;
        reason: string;
        userId: string;
    },
) {
    await tx.$queryRaw`SELECT id FROM "JournalEntry" WHERE id=${input.journalId} FOR UPDATE`;
    const original = await tx.journalEntry.findUniqueOrThrow({
        where: { id: input.journalId },
        include: { lines: true },
    });
    if (original.status !== 'POSTED' || !original.isAutoGenerated)
        throw new BusinessRuleError('Jurnal kredit asal tidak valid.');
    return creditJournal(tx, {
        ...input,
        reference: `CUSTOMER_CREDIT_REVERSAL:${input.id}`,
        description: `Pembalikan saldo kredit: ${input.reason}`,
        lines: original.lines.map((l) => ({
            accountId: l.accountId,
            debit: l.credit,
            credit: l.debit,
        })),
    });
}
export async function lockCreditInvoice(
    tx: Prisma.TransactionClient,
    invoiceId: string,
) {
    const row = await tx.invoice.findUniqueOrThrow({
        where: { id: invoiceId },
        select: { salesOrderId: true },
    });
    await tx.$queryRaw`SELECT id FROM "SalesOrder" WHERE id=${row.salesOrderId} FOR SHARE`;
    await tx.$queryRaw`SELECT id FROM "Invoice" WHERE id=${invoiceId} FOR UPDATE`;
    return tx.invoice.findUniqueOrThrow({
        where: { id: invoiceId },
        include: { salesOrder: { select: { customerId: true } } },
    });
}
