
import { prisma } from '@/lib/prisma';
import { AccountingService } from '../accounting-service';
import { ReferenceType } from '@prisma/client';

export class FixedAssetService {

    /**
     * Get Assets
     */
    static async getAssets() {
        return await prisma.fixedAsset.findMany({
            include: { location: true },
            orderBy: { purchaseDate: 'desc' }
        });
    }

    /**
     * Create Fixed Asset
     */
    static async createAsset(data: {
        assetCode: string;
        name: string;
        category: string;
        purchaseDate: Date;
        purchaseValue: number;
        scrapValue?: number;
        usefulLifeMonths: number;
        assetAccountId: string;
        depreciationAccountId: string;
        accumulatedDepreciationAccountId: string;
        locationId?: string;
    }) {
        return await prisma.fixedAsset.create({
            data: {
                ...data,
                purchaseValue: Number(data.purchaseValue),
                scrapValue: Number(data.scrapValue || 0),
                usefulLifeMonths: data.usefulLifeMonths
            }
        });
    }

    /**
     * Run Monthly Depreciation for ALL active assets
     * For a specific Year and Month
     */
    static async runDepreciation(year: number, month: number, userId: string) {
        const assets = await prisma.fixedAsset.findMany({
            where: {
                status: 'ACTIVE',
                purchaseDate: { lte: new Date(year, month, 0) } // Purchase date on or before month end
            }
        });

        const results = [];

        for (const asset of assets) {
            // Check if already depreciated for this month
            if (asset.lastDepreciationDate) {
                const last = new Date(asset.lastDepreciationDate);
                if (last.getFullYear() === year && last.getMonth() + 1 === month) {
                    continue; // Skip
                }
            }

            // Straight Line Logic: (Value - Scrap) / Useful Life
            const monthlyDepr = (Number(asset.purchaseValue) - Number(asset.scrapValue)) / asset.usefulLifeMonths;

            if (monthlyDepr <= 0) continue;

            // Generate Journal
            await AccountingService.createJournalEntry({
                entryDate: new Date(year, month - 1, 28), // Usually end of month
                description: `Depreciation of ${asset.name} (${asset.assetCode}) - ${month}/${year}`,
                reference: asset.assetCode,
                referenceType: ReferenceType.MANUAL_ENTRY, // Or custom DEPRECIATION type
                createdById: userId,
                isAutoGenerated: true,
                lines: [
                    {
                        accountId: asset.depreciationAccountId,
                        debit: monthlyDepr,
                        credit: 0,
                        description: 'Depreciation Expense'
                    },
                    {
                        accountId: asset.accumulatedDepreciationAccountId,
                        debit: 0,
                        credit: monthlyDepr,
                        description: 'Accumulated Depreciation'
                    }
                ]
            });

            // Update Asset
            await prisma.fixedAsset.update({
                where: { id: asset.id },
                data: {
                    lastDepreciationDate: new Date(year, month - 1, 28)
                }
            });

            results.push({ assetId: asset.id, amount: monthlyDepr });
        }

        return results;
    }
}
