import { createHash } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { BusinessRuleError, NotFoundError } from '@/lib/errors/errors';
import { resolveAccount } from '@/services/accounting/account-resolver';
import { calculateReturnProposal } from './return-credit-proposal';
const zero = () => new Prisma.Decimal(0);
export async function getPriceAdjustmentSource(
    tx: Prisma.TransactionClient,
    invoiceId: string,
) {
    const invoice = await tx.invoice.findUnique({
        where: { id: invoiceId },
        include: {
            salesOrder: {
                include: {
                    items: {
                        orderBy: { id: 'asc' },
                        include: {
                            productVariant: {
                                select: { name: true, primaryUnit: true },
                            },
                        },
                    },
                    deliveryOrders: {
                        where: { status: { in: ['SHIPPED', 'DELIVERED'] } },
                        select: { totalCharge: true },
                    },
                },
            },
            returnBasisLines: { orderBy: { id: 'asc' } },
        },
    });
    if (!invoice) throw new NotFoundError('Invoice');
    if (!['UNPAID', 'PARTIAL', 'OVERDUE', 'PAID'].includes(invoice.status))
        throw new BusinessRuleError(
            'Penyesuaian hanya untuk invoice yang sudah diakui. Revisi draft melalui dokumen penjualan.',
        );
    if (!invoice.salesOrder.customerId)
        throw new BusinessRuleError('Customer invoice belum lengkap.');
    const [ar, vat, revenue] = await Promise.all([
        resolveAccount('accounts-receivable'),
        resolveAccount('vat-output'),
        resolveAccount('sales-revenue'),
    ]);
    const journals = await tx.journalEntry.findMany({
        where: {
            referenceType: 'SALES_INVOICE',
            referenceId: invoiceId,
            status: { not: 'VOIDED' },
        },
        include: { lines: { orderBy: { id: 'asc' } } },
        take: 2,
    });
    if (
        journals.length !== 1 ||
        journals[0].status !== 'POSTED' ||
        !journals[0].isAutoGenerated
    )
        throw new BusinessRuleError(
            'Jurnal invoice harus terverifikasi sebelum penyesuaian.',
        );
    const journal = journals[0];
    const arAmount = journal.lines
        .filter((l) => l.accountId === ar.id)
        .reduce((s, l) => s.plus(l.debit).minus(l.credit), zero());
    const tax = journal.lines
        .filter((l) => l.accountId === vat.id)
        .reduce((s, l) => s.plus(l.credit).minus(l.debit), zero());
    if (
        tax.lt(0) ||
        tax.gt(invoice.totalAmount) ||
        !journal.lines.some(
            (l) => l.accountId === revenue.id && l.credit.gt(l.debit),
        ) ||
        !arAmount.equals(invoice.totalAmount) ||
        !journal.lines
            .reduce((s, l) => s.plus(l.debit).minus(l.credit), zero())
            .isZero() ||
        journal.lines.some(
            (l) =>
                l.currency !== 'IDR' ||
                !l.exchangeRate.equals(1) ||
                l.debit.lt(0) ||
                l.credit.lt(0),
        )
    )
        throw new BusinessRuleError(
            'Jurnal invoice tidak cocok dengan nilai asli. Rekonsiliasi dahulu.',
        );
    if (
        (await tx.account.count({
            where: { id: { in: [ar.id, vat.id, revenue.id] }, isActive: true },
        })) !== 3
    )
        throw new BusinessRuleError('Akun penyesuaian belum valid/aktif.');
    const existing = await tx.invoicePriceAdjustment.findMany({
        where: { invoiceId },
        orderBy: { id: 'asc' },
    });
    // Retain an original, audited basis after previous adjustments; never use new SO prices.
    let lines: {
        sourceItemId: string;
        productVariantId: string;
        quantity: string;
        netAmount: string;
        taxAmount: string;
    }[];
    let sourceLabel: string;
    if (invoice.returnBasisLines.length) {
        if (
            invoice.returnBasisLines.some(
                (l) =>
                    l.sourceJournalId !== journal.id ||
                    (l.sourceEvidence as Prisma.JsonObject)?.version !== 1 ||
                    (l.sourceEvidence as Prisma.JsonObject)
                        ?.capturedAtInvoiceCreation !== true,
            )
        )
            throw new BusinessRuleError('Bukti invoice asal belum valid.');
        lines = invoice.returnBasisLines.map((l) => ({
            sourceItemId: l.sourceItemId,
            productVariantId: l.productVariantId,
            quantity: l.quantity.toString(),
            netAmount: l.netAmount.toFixed(2),
            taxAmount: l.taxAmount.toFixed(2),
        }));
        sourceLabel = 'Snapshot invoice asal';
    } else if (existing.length) {
        // A reversed adjustment still proves the original reviewed source. Do not
        // rebase subsequent adjustments on a SO edited after the first approval.
        const reviewed = existing[0].sourceEvidence as Prisma.JsonObject;
        const original = reviewed.originalLines;
        if (!Array.isArray(original))
            throw new BusinessRuleError(
                'Bukti harga asli tidak lengkap. Rekonsiliasi diperlukan.',
            );
        lines = original.map((value) => {
            const line = value as Prisma.JsonObject;
            if (
                !line ||
                [
                    'sourceItemId',
                    'productVariantId',
                    'quantity',
                    'netAmount',
                    'taxAmount',
                ].some((k) => typeof line[k] !== 'string')
            )
                throw new BusinessRuleError('Bukti harga asli tidak valid.');
            return {
                sourceItemId: line.sourceItemId as string,
                productVariantId: line.productVariantId as string,
                quantity: line.quantity as string,
                netAmount: line.netAmount as string,
                taxAmount: line.taxAmount as string,
            };
        });
        sourceLabel =
            'Bukti harga asli pada persetujuan penyesuaian sebelumnya';
    } else {
        if (
            (await tx.invoice.count({
                where: {
                    salesOrderId: invoice.salesOrderId,
                    status: { not: 'CANCELLED' },
                },
            })) !== 1
        )
            throw new BusinessRuleError(
                'Invoice historis berulang pada SO memerlukan pemeriksaan sumber, bukan perkiraan harga.',
            );
        const hasDelivery = invoice.salesOrder.items.some((i) =>
            i.deliveredQty.gt(0),
        );
        const shipping = invoice.salesOrder.deliveryOrders.length
            ? invoice.salesOrder.deliveryOrders.reduce(
                  (s, d) => s.plus(d.totalCharge ?? 0),
                  zero(),
              )
            : new Prisma.Decimal(invoice.salesOrder.shippingCost ?? 0);
        lines = invoice.salesOrder.items
            .filter((i) => (hasDelivery ? i.deliveredQty : i.quantity).gt(0))
            .map((i) => {
                const quantity = hasDelivery ? i.deliveredQty : i.quantity;
                const v = calculateReturnProposal({
                    totalAmount: invoice.totalAmount,
                    roundingAmount: new Prisma.Decimal(
                        invoice.roundingAmount ?? 0,
                    ),
                    shippingAmount: shipping,
                    journalTax: tax,
                    items: invoice.salesOrder.items,
                    returned: [
                        {
                            productVariantId: i.productVariantId,
                            returnedQty: quantity,
                        },
                    ],
                    basis: [],
                });
                return {
                    sourceItemId: i.id,
                    productVariantId: i.productVariantId,
                    quantity: quantity.toString(),
                    netAmount: new Prisma.Decimal(v.totalAmount)
                        .minus(v.taxAmount)
                        .toFixed(2),
                    taxAmount: v.taxAmount,
                };
            });
        sourceLabel =
            'Rincian SO saat ini dicocokkan ke invoice/jurnal — wajib diperiksa Finance';
    }
    if (
        !lines.length ||
        new Set(lines.map((l) => l.productVariantId)).size !== lines.length
    )
        throw new BusinessRuleError('Atribusi item invoice kosong/ambigu.');
    if (
        lines
            .reduce((s, l) => s.plus(l.netAmount).plus(l.taxAmount), zero())
            .gt(invoice.totalAmount) ||
        !lines.reduce((s, l) => s.plus(l.taxAmount), zero()).equals(tax)
    )
        throw new BusinessRuleError(
            'Nilai sumber item/pajak tidak cocok dengan invoice asli.',
        );
    const credits = await tx.salesReturnCreditAllocation.findMany({
        where: { invoiceId, credit: { status: 'POSTED' } },
        include: { basisLine: true },
        orderBy: { id: 'asc' },
    });
    if (credits.some((c) => !c.basisLine || !c.quantity))
        throw new BusinessRuleError(
            'Invoice mempunyai kredit retur manual tanpa alokasi kuantitas. Rekonsiliasi sumber sebelum penyesuaian harga.',
        );
    const items = lines.map((line) => {
        const used = credits
            .filter((c) => c.basisLine?.sourceItemId === line.sourceItemId)
            .reduce((s, c) => s.plus(c.quantity!), zero());
        const active = existing.some(
            (a) =>
                a.sourceItemId === line.sourceItemId && a.status === 'POSTED',
        );
        const sourceItem = invoice.salesOrder.items.find(
            (i) =>
                i.id === line.sourceItemId &&
                i.productVariantId === line.productVariantId,
        );
        if (!sourceItem)
            throw new BusinessRuleError(
                'Sumber item invoice tidak cocok dengan SO.',
            );
        return {
            ...line,
            name: sourceItem.productVariant.name,
            unit: sourceItem.productVariant.primaryUnit,
            availableQuantity: active
                ? '0'
                : new Prisma.Decimal(line.quantity).minus(used).toString(),
            activeAdjustment: active,
            netUnitPrice: new Prisma.Decimal(line.netAmount)
                .div(line.quantity)
                .toFixed(6),
        };
    });
    const fingerprint = createHash('sha256')
        .update(
            JSON.stringify({
                invoice: {
                    id: invoice.id,
                    total: invoice.totalAmount,
                    paid: invoice.paidAmount,
                    credited: invoice.creditedAmount,
                    adjustment: invoice.priceAdjustmentAmount,
                    status: invoice.status,
                    customer: invoice.salesOrder.customerId,
                },
                journal,
                items,
                credits,
                existing,
            }),
        )
        .digest('hex');
    return {
        invoice,
        sourceJournalId: journal.id,
        items,
        originalLines: lines,
        sourceLabel,
        fingerprint,
        accounts: { ar: ar.id, vat: vat.id, revenue: revenue.id },
        journalTax: tax,
    };
}
