import { createHash } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { getTenantDbFromContext } from '@/lib/core/prisma';
import {
    BusinessRuleError,
    NotFoundError,
    ValidationError,
} from '@/lib/errors/errors';
import { getSalesInvoiceBalance } from '@/lib/finance/sales-return-allocation';
import { toBusinessDateString } from '@/lib/utils/timezone';
import { resolveAccount } from '@/services/accounting/account-resolver';
import { calculateReturnProposal } from './return-credit-proposal';
import { postManualReturnCreditInTransaction } from './manual-return-credit-service';

export type ReturnCreditProposal =
    | {
          ready: true;
          invoiceId: string;
          invoiceNumber: string;
          orderNumber: string;
          totalAmount: string;
          taxAmount: string;
          remaining: string;
          remainingAfter: string;
          source: 'SNAPSHOT' | 'SO_REVIEW';
          fingerprint: string;
          evidence: string;
      }
    | { ready: false; reason: string };
const id = z.string().trim().min(1).max(100);
const approvedReason =
    'Finance menyetujui nominal usulan dokumen retur dan invoice terkait.';
const zero = () => new Prisma.Decimal(0);

/** Read-only proposal. The submission regenerates it under source locks before posting. */
export async function prepareReturnCreditProposal(
    tx: Prisma.TransactionClient,
    returnId: string,
): Promise<ReturnCreditProposal> {
    const returned = await tx.salesReturn.findUnique({
        where: { id: id.parse(returnId) },
        include: {
            items: { orderBy: { id: 'asc' } },
            credit: true,
            salesOrder: {
                include: {
                    items: { orderBy: { id: 'asc' } },
                    deliveryOrders: {
                        where: { status: { in: ['SHIPPED', 'DELIVERED'] } },
                        orderBy: { id: 'asc' },
                        select: { totalCharge: true },
                    },
                },
            },
        },
    });
    if (!returned) throw new NotFoundError('Retur');
    const blocked = (reason: string): ReturnCreditProposal => ({
        ready: false,
        reason,
    });
    if (!['RECEIVED', 'COMPLETED'].includes(returned.status))
        return blocked('Menunggu penerimaan barang.');
    if (returned.credit && returned.credit.status !== 'REVIEW_REQUIRED')
        return blocked(
            'Retur sudah memiliki riwayat kredit. Jangan posting ulang.',
        );
    if (
        await tx.journalEntry.findFirst({
            where: { referenceType: 'SALES_RETURN', referenceId: returnId },
        })
    )
        return blocked(
            'Jurnal retur lama ditemukan. Rekonsiliasi diperlukan; jangan memotong dua kali.',
        );
    const invoices = await tx.invoice.findMany({
        where: {
            salesOrderId: returned.salesOrderId,
            status: { not: 'CANCELLED' },
        },
        include: { returnBasisLines: { orderBy: { id: 'asc' } } },
        orderBy: { id: 'asc' },
        take: 2,
    });
    if (invoices.length !== 1)
        return blocked(
            'SO tidak memiliki tepat satu invoice tujuan. Pilih dan periksa alokasi manual.',
        );
    const invoice = invoices[0];
    // Earlier credits have already consumed portions/rounding; keep this shortcut
    // for the first full-return allocation and retain the detailed/manual path otherwise.
    if (
        await tx.salesReturnCreditAllocation.count({
            where: {
                invoiceId: invoice.id,
                credit: { status: { in: ['POSTED', 'REVERSED'] } },
            },
        })
    )
        return blocked(
            'Invoice sudah mempunyai riwayat kredit retur. Periksa sisa alokasi melalui opsi lanjutan/manual.',
        );
    if (
        !['UNPAID', 'PARTIAL', 'OVERDUE'].includes(invoice.status) ||
        getSalesInvoiceBalance(invoice).lte(0)
    )
        return blocked(
            'Invoice belum diakui atau sudah lunas. Periksa Finance.',
        );
    if (
        !returned.customerId ||
        returned.customerId !== returned.salesOrder.customerId
    )
        return blocked('Customer retur dan SO tidak cocok.');
    const journals = await tx.journalEntry.findMany({
        where: {
            referenceType: 'SALES_INVOICE',
            referenceId: invoice.id,
            status: { not: 'VOIDED' },
        },
        include: { lines: { orderBy: { id: 'asc' } } },
        orderBy: { id: 'asc' },
        take: 2,
    });
    if (
        journals.length !== 1 ||
        journals[0].status !== 'POSTED' ||
        !journals[0].isAutoGenerated
    )
        return blocked(
            'Jurnal invoice belum terverifikasi. Pemeriksaan Finance diperlukan.',
        );
    const [ar, vat] = await Promise.all([
        resolveAccount('accounts-receivable'),
        resolveAccount('vat-output'),
    ]);
    const journal = journals[0];
    const journalTax = journal.lines
        .filter((line) => line.accountId === vat.id)
        .reduce((sum, line) => sum.plus(line.credit).minus(line.debit), zero());
    const journalAr = journal.lines
        .filter((line) => line.accountId === ar.id)
        .reduce((sum, line) => sum.plus(line.debit).minus(line.credit), zero());
    if (
        !journalAr.equals(invoice.totalAmount) ||
        !journal.lines
            .reduce(
                (sum, line) => sum.plus(line.debit).minus(line.credit),
                zero(),
            )
            .isZero() ||
        journal.lines.some(
            (line) =>
                line.currency !== 'IDR' ||
                !line.exchangeRate.equals(1) ||
                line.debit.lt(0) ||
                line.credit.lt(0),
        )
    )
        return blocked('Nominal atau mata uang jurnal invoice tidak cocok.');
    let shipping = returned.salesOrder.deliveryOrders.length
        ? returned.salesOrder.deliveryOrders.reduce(
              (sum, delivery) => sum.plus(delivery.totalCharge ?? 0),
              zero(),
          )
        : new Prisma.Decimal(returned.salesOrder.shippingCost ?? 0);
    if (invoice.returnBasisLines.length) {
        if (
            invoice.returnBasisLines.some(
                (line) => line.sourceJournalId !== journal.id,
            )
        )
            return blocked(
                'Snapshot tidak mengacu ke jurnal invoice yang aktif. Periksa Finance.',
            );
        const evidence = invoice.returnBasisLines[0]
            .sourceEvidence as Prisma.JsonObject;
        shipping =
            typeof evidence?.shippingAmount === 'string' &&
            /^\d+(\.\d{1,2})?$/.test(evidence.shippingAmount)
                ? new Prisma.Decimal(evidence.shippingAmount)
                : zero();
    }
    try {
        const value = calculateReturnProposal({
            totalAmount: invoice.totalAmount,
            roundingAmount: new Prisma.Decimal(invoice.roundingAmount ?? 0),
            shippingAmount: shipping,
            journalTax,
            items: returned.salesOrder.items,
            returned: returned.items,
            basis: invoice.returnBasisLines,
        });
        const remaining = getSalesInvoiceBalance(invoice);
        if (new Prisma.Decimal(value.totalAmount).gt(remaining))
            return blocked(
                'Nilai retur melebihi sisa piutang. Periksa nominal manual; tidak ada refund otomatis.',
            );
        const active = await tx.salesReturnCreditAllocation.aggregate({
            where: { invoiceId: invoice.id, credit: { status: 'POSTED' } },
            _sum: { netAmount: true, taxAmount: true },
        });
        if (
            new Prisma.Decimal(value.taxAmount)
                .plus(active._sum.taxAmount ?? 0)
                .gt(journalTax) ||
            new Prisma.Decimal(value.totalAmount)
                .minus(value.taxAmount)
                .plus(active._sum.netAmount ?? 0)
                .gt(invoice.totalAmount.minus(journalTax))
        )
            return blocked(
                'Sisa netto/pajak invoice tidak cukup untuk usulan retur.',
            );
        const fingerprint = createHash('sha256')
            .update(
                JSON.stringify({
                    returnId,
                    status: returned.status,
                    returnDate: returned.returnDate,
                    items: returned.items,
                    so: returned.salesOrder,
                    invoice,
                    journal,
                    active,
                    value,
                }),
            )
            .digest('hex');
        return {
            ready: true,
            invoiceId: invoice.id,
            invoiceNumber: invoice.invoiceNumber,
            orderNumber: returned.salesOrder.orderNumber,
            ...value,
            remaining: remaining.toFixed(2),
            remainingAfter: remaining.minus(value.totalAmount).toFixed(2),
            fingerprint,
            evidence: `Usulan ${fingerprint}; retur ${returnId}; SO ${returned.salesOrderId}; invoice ${invoice.id}; sumber ${value.source}.`,
        };
    } catch (error) {
        if (
            error instanceof BusinessRuleError ||
            error instanceof ValidationError
        )
            return blocked(error.message);
        throw error;
    }
}

const schema = z.object({
    returnId: id,
    fingerprint: z.string().regex(/^[a-f0-9]{64}$/),
    postingDate: z.coerce.date(),
    confirmed: z.literal(true),
});
export async function postProposedReturnCredit(input: unknown, userId: string) {
    const data = schema.parse(input);
    const db = getTenantDbFromContext();
    if (!db)
        throw new BusinessRuleError(
            'Konteks tenant wajib untuk posting retur.',
        );
    return db.$transaction(async (tx) => {
        await tx.$queryRaw`SELECT id FROM "SalesReturn" WHERE id=${data.returnId} FOR UPDATE`;
        const returned = await tx.salesReturn.findUnique({
            where: { id: data.returnId },
            include: { credit: true },
        });
        if (!returned) throw new NotFoundError('Retur');
        if (
            returned.credit?.status === 'POSTED' &&
            returned.credit.mode === 'MANUAL' &&
            returned.credit.approvalReason === approvedReason &&
            returned.credit.evidenceReference?.startsWith(
                `Usulan ${data.fingerprint};`,
            ) &&
            toBusinessDateString(returned.credit.postedAt!) ===
                toBusinessDateString(data.postingDate)
        )
            return returned.credit;
        await tx.$queryRaw`SELECT id FROM "SalesOrder" WHERE id=${returned.salesOrderId} FOR UPDATE`;
        await tx.$queryRaw`SELECT id FROM "SalesOrderItem" WHERE "salesOrderId"=${returned.salesOrderId} ORDER BY id FOR SHARE`;
        await tx.$queryRaw`SELECT id FROM "Invoice" WHERE "salesOrderId"=${returned.salesOrderId} ORDER BY id FOR UPDATE`;
        await tx.$queryRaw`SELECT j.id FROM "JournalEntry" j JOIN "Invoice" i ON i.id=j."referenceId" WHERE i."salesOrderId"=${returned.salesOrderId} AND j."referenceType"='SALES_INVOICE' ORDER BY j.id FOR UPDATE OF j`;
        await tx.$queryRaw`SELECT id FROM "DeliveryOrder" WHERE "salesOrderId"=${returned.salesOrderId} ORDER BY id FOR SHARE`;
        const proposal = await prepareReturnCreditProposal(tx, data.returnId);
        if (!proposal.ready) throw new BusinessRuleError(proposal.reason);
        if (proposal.fingerprint !== data.fingerprint)
            throw new BusinessRuleError(
                'Sumber atau saldo berubah. Muat ulang dan periksa usulan terbaru sebelum posting.',
            );
        return postManualReturnCreditInTransaction(
            tx,
            {
                returnId: data.returnId,
                invoiceId: proposal.invoiceId,
                totalAmount: proposal.totalAmount,
                taxAmount: proposal.taxAmount,
                expectedRemaining: proposal.remaining,
                postingDate: data.postingDate,
                confirmed: true,
                reason: approvedReason,
                evidence: proposal.evidence,
            },
            userId,
        );
    });
}
