import { Prisma } from '@prisma/client';
import { getTenantDbFromContext } from '@/lib/core/prisma';
import { z } from 'zod';
import { BusinessRuleError, NotFoundError } from '@/lib/errors/errors';
import {
    allocateReturnValue,
    classifyReturnCredit,
    getSalesInvoiceBalance,
    getSalesInvoiceSettlementStatus,
} from '@/lib/finance/sales-return-allocation';
import { logActivity } from '@/lib/tools/audit';
import { toBusinessDateString } from '@/lib/utils/timezone';
import { resolveAccount } from '@/services/accounting/account-resolver';
import { generateEntryNumber } from '@/services/accounting/journal-posting';
import {
    lockSalesInvoice,
    requireOpenJournalPeriod,
} from './sales-recognition-service';

const id = z.string().min(1).max(100);
const inputSchema = z.object({
    returnId: id,
    // Compatibility for transaction callers using one explicit invoice. New UI uses basis + quantity.
    invoiceId: id.optional(),
    postingDate: z.coerce.date(),
    lines: z
        .array(
            z.object({
                returnItemId: id,
                basisLineId: id,
                quantity: z.union([z.string(), z.number()]).optional(),
            }),
        )
        .min(1)
        .max(200),
});

type LockedInvoice = Awaited<ReturnType<typeof lockSalesInvoice>>;
type Basis = Prisma.InvoiceReturnBasisLineGetPayload<object>;
const zero = () => new Prisma.Decimal(0);
const postingDayBeforeReceipt = (postingDate: Date, receivedAt: Date) =>
    toBusinessDateString(postingDate) < toBusinessDateString(receivedAt);

/** Explicit tenant client; authorization belongs to the Finance action, never the browser. */
export async function postReturnCredit(input: unknown, userId: string) {
    const db = getTenantDbFromContext();
    if (!db)
        throw new BusinessRuleError('Konteks tenant wajib untuk kredit retur.');
    return db.$transaction((tx) =>
        postReturnCreditInTransaction(tx, input, userId),
    );
}

async function validateSourceJournal(
    tx: Prisma.TransactionClient,
    invoice: LockedInvoice,
    basis: Basis[],
    arId: string,
    vatId: string,
) {
    const sourceIds = [...new Set(basis.map((line) => line.sourceJournalId))];
    if (sourceIds.length !== 1) return false;
    await tx.$queryRaw`SELECT id FROM "JournalEntry" WHERE "referenceType" = 'SALES_INVOICE' AND "referenceId" = ${invoice.id} ORDER BY id FOR UPDATE`;
    const sources = await tx.journalEntry.findMany({
        where: {
            referenceType: 'SALES_INVOICE',
            referenceId: invoice.id,
            status: { not: 'VOIDED' },
        },
        include: { lines: true },
    });
    if (sources.length !== 1) return false;
    const source = sources[0];
    const debit = source.lines.reduce(
        (sum, line) => sum.plus(line.debit),
        zero(),
    );
    const credit = source.lines.reduce(
        (sum, line) => sum.plus(line.credit),
        zero(),
    );
    const ar = source.lines
        .filter((line) => line.accountId === arId)
        .reduce((sum, line) => sum.plus(line.debit).minus(line.credit), zero());
    const vat = source.lines
        .filter((line) => line.accountId === vatId)
        .reduce((sum, line) => sum.plus(line.credit).minus(line.debit), zero());
    return (
        source.id === sourceIds[0] &&
        source.status === 'POSTED' &&
        source.isAutoGenerated &&
        debit.equals(credit) &&
        ar.equals(invoice.totalAmount) &&
        basis
            .reduce((sum, line) => sum.plus(line.taxAmount), zero())
            .lte(vat) &&
        basis
            .reduce(
                (sum, line) => sum.plus(line.netAmount).plus(line.taxAmount),
                zero(),
            )
            .lte(invoice.totalAmount.minus(invoice.roundingAmount ?? 0)) &&
        !source.lines.some(
            (line) =>
                line.currency !== 'IDR' ||
                !line.exchangeRate.equals(1) ||
                line.debit.lt(0) ||
                line.credit.lt(0),
        )
    );
}

/** Transaction-owned posting. No payment, refund, stock write or historical repricing. */
export async function postReturnCreditInTransaction(
    tx: Prisma.TransactionClient,
    input: unknown,
    userId: string,
) {
    const data = inputSchema.parse(input);
    await tx.$queryRaw`SELECT id FROM "SalesReturn" WHERE id = ${data.returnId} FOR UPDATE`;
    const returned = await tx.salesReturn.findUnique({
        where: { id: data.returnId },
        include: {
            items: {
                include: { receipt: { include: { sourceMovement: true } } },
            },
            credit: { include: { allocations: true } },
            salesOrder: { select: { customerId: true } },
        },
    });
    if (!returned) throw new NotFoundError('Sales Return');
    if (!['RECEIVED', 'COMPLETED'].includes(returned.status))
        throw new BusinessRuleError(
            'Barang retur harus diterima sebelum kredit diterapkan.',
        );
    if (returned.credit?.status === 'REVERSED')
        throw new BusinessRuleError(
            'Kredit sudah dibalik. Pemeriksaan Finance diperlukan; riwayat tidak boleh diposting ulang.',
        );
    const lines = data.lines.map((line) => {
        const item = returned.items.find(
            (candidate) => candidate.id === line.returnItemId,
        );
        if (!item)
            throw new BusinessRuleError(
                'Alokasi harus mencakup setiap item retur tepat satu kali secara penuh.',
            );
        if (line.quantity === undefined && !data.invoiceId)
            throw new BusinessRuleError(
                'Kuantitas alokasi invoice wajib dipilih secara eksplisit.',
            );
        const quantity = new Prisma.Decimal(line.quantity ?? item.returnedQty);
        if (
            !quantity.isFinite() ||
            quantity.lte(0) ||
            quantity.decimalPlaces() > 4
        )
            throw new BusinessRuleError('Kuantitas alokasi tidak valid.');
        return { ...line, quantity, item };
    });
    if (
        new Set(lines.map((line) => `${line.returnItemId}:${line.basisLineId}`))
            .size !== lines.length ||
        returned.items.some(
            (item) =>
                !lines
                    .filter((line) => line.returnItemId === item.id)
                    .reduce((sum, line) => sum.plus(line.quantity), zero())
                    .equals(item.returnedQty),
        )
    ) {
        throw new BusinessRuleError(
            'Alokasi harus mencakup setiap item retur tepat satu kali secara penuh.',
        );
    }
    const signature = (
        values: {
            returnItemId: string;
            basisLineId: string;
            quantity: Prisma.Decimal;
        }[],
    ) =>
        JSON.stringify(
            values
                .map(
                    (line) =>
                        `${line.returnItemId}:${line.basisLineId}:${line.quantity.toString()}`,
                )
                .sort(),
        );
    if (returned.credit?.status === 'POSTED') {
        if (
            signature(returned.credit.allocations) !== signature(lines) ||
            (data.invoiceId &&
                returned.credit.allocations.some(
                    (line) => line.invoiceId !== data.invoiceId,
                )) ||
            toBusinessDateString(returned.credit.postedAt!) !==
                toBusinessDateString(data.postingDate)
        )
            throw new BusinessRuleError(
                'Retur sudah dikreditkan dengan alokasi berbeda.',
            );
        return returned.credit;
    }
    const review = async (reason: string) => {
        const result = await tx.salesReturnCredit.upsert({
            where: { salesReturnId: returned.id },
            create: {
                salesReturnId: returned.id,
                createdById: userId,
                reviewReason: reason,
            },
            update: { reviewReason: reason },
        });
        await logActivity({
            userId,
            action: 'REVIEW_SALES_RETURN_CREDIT',
            entityType: 'SalesReturn',
            entityId: returned.id,
            details: reason,
            tx,
        });
        return result;
    };
    if (
        await tx.journalEntry.findFirst({
            where: { referenceType: 'SALES_RETURN', referenceId: returned.id },
        })
    )
        return review(
            'Jurnal retur lama ditemukan. Rekonsiliasi sebelum alokasi kredit; jangan posting ulang.',
        );
    if (
        returned.items.some(
            (item) =>
                !item.receipt ||
                !item.receipt.quantity.equals(item.returnedQty) ||
                item.receipt.sourceMovement.salesOrderId !==
                    returned.salesOrderId ||
                item.receipt.sourceMovement.productVariantId !==
                    item.productVariantId ||
                item.receipt.sourceMovement.type !== 'OUT',
        )
    )
        return review(
            'Bukti penerimaan dan sumber pengiriman belum terverifikasi. Periksa Finance; jangan menerapkan kredit otomatis.',
        );
    if (
        returned.items.some((item) =>
            postingDayBeforeReceipt(data.postingDate, item.receipt!.receivedAt),
        )
    )
        throw new BusinessRuleError(
            'Tanggal posting tidak boleh mendahului penerimaan barang.',
        );
    const requestedBasis = await tx.invoiceReturnBasisLine.findMany({
        where: { id: { in: lines.map((line) => line.basisLineId) } },
    });
    const invoiceIds = [
        ...new Set([
            ...requestedBasis.map((line) => line.invoiceId),
            ...(data.invoiceId ? [data.invoiceId] : []),
        ]),
    ].sort();
    const invoices = new Map<string, LockedInvoice>();
    const postingDay = toBusinessDateString(data.postingDate);
    if (
        postingDay < toBusinessDateString(returned.returnDate) ||
        postingDay > toBusinessDateString(new Date())
    )
        throw new BusinessRuleError(
            'Tanggal posting harus sesudah dokumen sumber dan tidak di masa depan.',
        );
    for (const invoiceId of invoiceIds) {
        const invoice = await lockSalesInvoice(tx, invoiceId);
        if (
            invoice.salesOrderId !== returned.salesOrderId ||
            !returned.customerId ||
            returned.customerId !== returned.salesOrder.customerId ||
            (data.invoiceId && invoice.id !== data.invoiceId)
        )
            throw new BusinessRuleError(
                'Invoice dan retur harus berasal dari SO dan customer yang sama.',
            );
        if (invoice.status === 'DRAFT')
            throw new BusinessRuleError(
                'Invoice draft belum dapat menerima kredit retur.',
            );
        if (postingDay < toBusinessDateString(invoice.invoiceDate))
            throw new BusinessRuleError(
                'Tanggal posting harus sesudah dokumen sumber.',
            );
        invoices.set(invoice.id, invoice);
    }
    // Read again under invoice locks: draft refresh cannot race validation/consumption.
    const basis = await tx.invoiceReturnBasisLine.findMany({
        where: { invoiceId: { in: invoiceIds } },
    });
    if (
        !basis.length ||
        lines.some(
            (line) =>
                !basis.some((original) => original.id === line.basisLineId),
        )
    )
        return review(
            'Snapshot nilai invoice asal belum tersedia. Perlu pemeriksaan Finance.',
        );
    if (
        basis.some((line) => {
            const evidence = line.sourceEvidence;
            return (
                !evidence ||
                typeof evidence !== 'object' ||
                Array.isArray(evidence) ||
                evidence.version !== 1 ||
                evidence.capturedAtInvoiceCreation !== true
            );
        })
    )
        return review(
            'Bukti snapshot saat penerbitan invoice tidak tersedia. Pemeriksaan Finance diperlukan.',
        );
    const [ar, vat, returnAccount] = await Promise.all([
        resolveAccount('accounts-receivable'),
        resolveAccount('vat-output'),
        resolveAccount('sales-return'),
    ]);
    if (
        (await tx.account.count({
            where: {
                id: { in: [ar.id, vat.id, returnAccount.id] },
                isActive: true,
            },
        })) !== 3
    )
        throw new BusinessRuleError(
            'Akun jurnal retur belum valid atau tidak aktif.',
        );
    for (const invoice of invoices.values()) {
        if (
            !(await validateSourceJournal(
                tx,
                invoice,
                basis.filter((line) => line.invoiceId === invoice.id),
                ar.id,
                vat.id,
            ))
        )
            return review(
                'Jurnal invoice asal tidak sesuai snapshot/akun/pajak. Rekonsiliasi sebelum kredit.',
            );
    }
    const allocations: Prisma.SalesReturnCreditAllocationCreateWithoutCreditInput[] =
        [];
    const byInvoice = new Map<string, Prisma.Decimal>();
    // Deterministic cumulative rounding independent of client line order.
    for (const requested of [...lines].sort(
        (a, b) =>
            a.basisLineId.localeCompare(b.basisLineId) ||
            a.returnItemId.localeCompare(b.returnItemId),
    )) {
        const original = basis.find(
            (line) => line.id === requested.basisLineId,
        )!;
        const sourceItem = await tx.salesOrderItem.findUnique({
            where: { id: original.sourceItemId },
            select: { salesOrderId: true, productVariantId: true },
        });
        if (
            original.productVariantId !== requested.item.productVariantId ||
            sourceItem?.salesOrderId !== returned.salesOrderId ||
            sourceItem.productVariantId !== original.productVariantId
        )
            return review(
                'Item invoice asal tidak tersedia atau tidak cocok dengan retur.',
            );
        // Movements identify SKU, not SO line. Repeated SKU lines cannot prove which
        // historical price was shipped; do not let a selection invent that attribution.
        if (
            (await tx.salesOrderItem.count({
                where: {
                    salesOrderId: returned.salesOrderId,
                    productVariantId: original.productVariantId,
                },
            })) !== 1
        )
            return review(
                'Beberapa baris SO memakai produk yang sama; atribusi pengiriman ke item invoice perlu pemeriksaan Finance.',
            );
        const previous = await tx.salesReturnCreditAllocation.aggregate({
            where: { basisLineId: original.id, credit: { status: 'POSTED' } },
            _sum: {
                quantity: true,
                netAmount: true,
                taxAmount: true,
                discountAmount: true,
            },
        });
        const earlier = allocations.filter(
            (line) => line.basisLine.connect?.id === original.id,
        );
        const inRequest = earlier.reduce(
            (sum, line) => sum.plus(String(line.quantity)),
            zero(),
        );
        const cumulativeQuantity = (previous._sum.quantity ?? zero())
            .plus(inRequest)
            .plus(requested.quantity);
        const cumulativeValue = allocateReturnValue(
            original,
            0,
            cumulativeQuantity,
        );
        // A reversal may remove a different rounding slice. Subtract actual active ledger
        // amounts, not a recomputed previous proportion, so final cents remain conserved.
        const residual = (key: 'netAmount' | 'taxAmount' | 'discountAmount') =>
            cumulativeValue[key]
                .minus(previous._sum[key] ?? zero())
                .minus(
                    earlier.reduce(
                        (sum, line) => sum.plus(String(line[key])),
                        zero(),
                    ),
                );
        const netAmount = residual('netAmount');
        const taxAmount = residual('taxAmount');
        const discountAmount = residual('discountAmount');
        if (
            [netAmount, taxAmount, discountAmount].some((amount) =>
                amount.lt(0),
            )
        )
            return review('Sisa pembulatan alokasi perlu diperiksa Finance.');
        const value = {
            netAmount,
            taxAmount,
            discountAmount,
            totalAmount: netAmount.plus(taxAmount),
        };
        allocations.push({
            invoice: { connect: { id: original.invoiceId } },
            basisLine: { connect: { id: original.id } },
            returnItem: { connect: { id: requested.item.id } },
            quantity: requested.quantity,
            ...value,
        });
        byInvoice.set(
            original.invoiceId,
            (byInvoice.get(original.invoiceId) ?? zero()).plus(
                value.totalAmount,
            ),
        );
    }
    for (const [invoiceId, amount] of byInvoice) {
        if (amount.lte(0))
            return review(
                'Nilai kredit setelah pembulatan belum positif. Periksa alokasi Finance; tidak membuat kredit nol.',
            );
        if (
            classifyReturnCredit(
                amount,
                getSalesInvoiceBalance(invoices.get(invoiceId)!),
            ) === 'REVIEW_REQUIRED'
        )
            return review(
                'Invoice lunas atau nilai retur melebihi sisa tagihan. Periksa Finance; tidak ada refund otomatis.',
            );
    }
    const netAmount = allocations.reduce(
        (sum, line) => sum.plus(String(line.netAmount)),
        zero(),
    );
    const taxAmount = allocations.reduce(
        (sum, line) => sum.plus(String(line.taxAmount)),
        zero(),
    );
    const totalAmount = netAmount.plus(taxAmount);
    await requireOpenJournalPeriod(tx, data.postingDate);
    const journal = await tx.journalEntry.create({
        data: {
            entryNumber: await generateEntryNumber(data.postingDate, tx),
            entryDate: data.postingDate,
            description: `Kredit retur ${returned.returnNumber}`,
            reference: returned.returnNumber,
            referenceType: 'SALES_RETURN',
            referenceId: returned.id,
            status: 'POSTED',
            isAutoGenerated: true,
            createdById: userId,
            approvedById: userId,
            approvedAt: new Date(),
            lines: {
                create: [
                    { accountId: ar.id, debit: zero(), credit: totalAmount },
                    ...(netAmount.gt(0)
                        ? [
                              {
                                  accountId: returnAccount.id,
                                  debit: netAmount,
                                  credit: zero(),
                              },
                          ]
                        : []),
                    ...(taxAmount.gt(0)
                        ? [
                              {
                                  accountId: vat.id,
                                  debit: taxAmount,
                                  credit: zero(),
                              },
                          ]
                        : []),
                ],
            },
        },
    });
    await tx.$executeRaw`SET CONSTRAINTS invoice_return_credit_ledger, return_credit_ledger, return_allocation_ledger DEFERRED`;
    const values = {
        status: 'POSTED' as const,
        reviewReason: null,
        postedAt: data.postingDate,
        netAmount,
        taxAmount,
        totalAmount,
        journalId: journal.id,
        allocations: { create: allocations },
    };
    const result = await tx.salesReturnCredit.upsert({
        where: { salesReturnId: returned.id },
        create: { salesReturnId: returned.id, createdById: userId, ...values },
        update: values,
    });
    for (const [invoiceId, amount] of byInvoice) {
        const invoice = invoices.get(invoiceId)!;
        const creditedAmount = invoice.creditedAmount.plus(amount);
        await tx.invoice.update({
            where: { id: invoiceId },
            data: {
                creditedAmount,
                status: getSalesInvoiceSettlementStatus({
                    ...invoice,
                    creditedAmount,
                }),
            },
        });
    }
    await logActivity({
        userId,
        action: 'POST_SALES_RETURN_CREDIT',
        entityType: 'SalesReturn',
        entityId: returned.id,
        details: `Kredit ${totalAmount.toFixed(2)}; jurnal ${journal.entryNumber}`,
        changes: { invoiceIds, creditId: result.id, journalId: journal.id },
        tx,
    });
    // Prisma 5 may swallow a deferred COMMIT error. Force validation inside the callback.
    await tx.$executeRaw`SET CONSTRAINTS invoice_return_credit_ledger, return_credit_ledger, return_allocation_ledger IMMEDIATE`;
    return result;
}
