import { Prisma } from '@prisma/client';
import { BusinessRuleError } from '@/lib/errors/errors';
import { allocateReturnValue } from '@/lib/finance/sales-return-allocation';

type HistoricalLine = {
    accountId: string;
    debit: Prisma.Decimal;
    credit: Prisma.Decimal;
    currency: string;
    exchangeRate: Prisma.Decimal;
};
type HistoricalCostSource = {
    movement: {
        id: string;
        type: string;
        salesOrderId: string | null;
        productVariantId: string;
        quantity: Prisma.Decimal;
    };
    journal: {
        id: string;
        status: string;
        referenceType: string | null;
        referenceId: string | null;
        isAutoGenerated: boolean;
        lines: HistoricalLine[];
    } | null;
};

/** Historical journal vector, never current product cost or a percentage of selling price. */
export function allocateHistoricalReturnCost(
    source: HistoricalCostSource,
    alreadyRestocked: string,
    quantity: string,
    condition: 'GOOD' | 'DAMAGED',
) {
    const { movement, journal } = source;
    if (movement.type !== 'OUT' || !movement.salesOrderId)
        throw new BusinessRuleError(
            'Sumber HPP harus mutasi pengiriman penjualan.',
        );
    // Validate quantity even when damaged goods have no inventory value to reverse.
    allocateReturnValue(
        {
            quantity: movement.quantity,
            netAmount: 0,
            taxAmount: 0,
            discountAmount: 0,
        },
        alreadyRestocked,
        quantity,
    );
    if (condition === 'DAMAGED')
        return {
            amount: new Prisma.Decimal(0),
            lines: [] as HistoricalLine[],
            restock: false,
        };
    if (
        !journal ||
        journal.status !== 'POSTED' ||
        !journal.isAutoGenerated ||
        journal.referenceType !== 'MANUAL_ENTRY' ||
        journal.referenceId !== movement.id ||
        journal.lines.length !== 2 ||
        journal.lines.some(
            (line) =>
                line.currency !== 'IDR' ||
                !line.exchangeRate.equals(1) ||
                !line.debit.isFinite() ||
                !line.credit.isFinite() ||
                line.debit.lt(0) ||
                line.credit.lt(0),
        )
    ) {
        throw new BusinessRuleError(
            'Jurnal HPP pengiriman asal hilang atau tidak valid. Perlu pemeriksaan Finance.',
        );
    }
    const debit = journal.lines.reduce(
        (sum, line) => sum.plus(line.debit),
        new Prisma.Decimal(0),
    );
    const credit = journal.lines.reduce(
        (sum, line) => sum.plus(line.credit),
        new Prisma.Decimal(0),
    );
    if (
        !debit.gt(0) ||
        !debit.equals(credit) ||
        journal.lines.some((line) => line.debit.gt(0) && line.credit.gt(0))
    ) {
        throw new BusinessRuleError(
            'Jurnal HPP pengiriman asal tidak seimbang.',
        );
    }
    const portion = (amount: Prisma.Decimal) =>
        allocateReturnValue(
            {
                quantity: movement.quantity,
                netAmount: amount,
                taxAmount: 0,
                discountAmount: 0,
            },
            alreadyRestocked,
            quantity,
        ).netAmount;
    return {
        amount: portion(debit),
        restock: true,
        lines: journal.lines.map((line) => ({
            accountId: line.accountId,
            currency: line.currency,
            exchangeRate: line.exchangeRate,
            debit: portion(line.credit),
            credit: portion(line.debit),
        })),
    };
}
