import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { getTenantDbFromContext } from '@/lib/core/prisma';
import { BusinessRuleError, NotFoundError } from '@/lib/errors/errors';
import { getSalesInvoiceSettlementStatus } from '@/lib/finance/sales-return-allocation';
import { logActivity } from '@/lib/tools/audit';
import { toBusinessDateString } from '@/lib/utils/timezone';
import { generateEntryNumber } from '@/services/accounting/journal-posting';
import {
    lockSalesInvoice,
    requireOpenJournalPeriod,
} from './sales-recognition-service';

const schema = z.object({
    returnId: z.string().min(1).max(100),
    reversalDate: z.coerce.date(),
    reason: z.string().trim().min(5).max(1000),
});

export async function reverseReturnCredit(input: unknown, userId: string) {
    const db = getTenantDbFromContext();
    if (!db)
        throw new BusinessRuleError(
            'Konteks tenant wajib untuk pembalikan kredit retur.',
        );
    return db.$transaction((tx) =>
        reverseReturnCreditInTransaction(tx, input, userId),
    );
}

/** Compensation only: original journal, allocations and physical receipt are never edited/deleted. */
export async function reverseReturnCreditInTransaction(
    tx: Prisma.TransactionClient,
    input: unknown,
    userId: string,
) {
    const data = schema.parse(input);
    await tx.$queryRaw`SELECT id FROM "SalesReturn" WHERE id = ${data.returnId} FOR UPDATE`;
    const credit = await tx.salesReturnCredit.findUnique({
        where: { salesReturnId: data.returnId },
        include: { allocations: true },
    });
    if (!credit) throw new NotFoundError('Kredit retur');
    if (credit.status === 'REVERSED') {
        if (
            credit.reversalReason !== data.reason ||
            toBusinessDateString(credit.reversedAt!) !==
                toBusinessDateString(data.reversalDate)
        )
            throw new BusinessRuleError(
                'Kredit sudah dibalik dengan instruksi berbeda.',
            );
        return credit;
    }
    if (credit.status !== 'POSTED' || !credit.postedAt || !credit.journalId)
        throw new BusinessRuleError(
            'Hanya kredit terposting yang dapat dibalik.',
        );
    const day = toBusinessDateString(data.reversalDate);
    if (
        day < toBusinessDateString(credit.postedAt) ||
        day > toBusinessDateString(new Date())
    )
        throw new BusinessRuleError(
            'Tanggal pembalikan harus sesudah posting dan tidak di masa depan.',
        );
    const invoices = [];
    for (const invoiceId of [
        ...new Set(credit.allocations.map((line) => line.invoiceId)),
    ].sort())
        invoices.push(await lockSalesInvoice(tx, invoiceId));
    await requireOpenJournalPeriod(tx, data.reversalDate);
    await tx.$queryRaw`SELECT id FROM "JournalEntry" WHERE id = ${credit.journalId} FOR UPDATE`;
    const journal = await tx.journalEntry.findUnique({
        where: { id: credit.journalId },
        include: { lines: true },
    });
    if (
        !journal ||
        journal.status !== 'POSTED' ||
        journal.referenceType !== 'SALES_RETURN' ||
        journal.referenceId !== data.returnId ||
        !journal.isAutoGenerated ||
        !journal.lines
            .reduce((sum, line) => sum.plus(line.debit), new Prisma.Decimal(0))
            .equals(credit.totalAmount) ||
        !journal.lines
            .reduce((sum, line) => sum.plus(line.credit), new Prisma.Decimal(0))
            .equals(credit.totalAmount)
    )
        throw new BusinessRuleError(
            'Jurnal kredit tidak sesuai. Rekonsiliasi sebelum pembalikan.',
        );
    const accountIds = [
        ...new Set(journal.lines.map((line) => line.accountId)),
    ];
    if (
        (await tx.account.count({
            where: { id: { in: accountIds }, isActive: true },
        })) !== accountIds.length
    )
        throw new BusinessRuleError('Akun jurnal pembalikan tidak aktif.');
    const reversal = await tx.journalEntry.create({
        data: {
            entryNumber: await generateEntryNumber(data.reversalDate, tx),
            entryDate: data.reversalDate,
            description: `Pembalikan kredit retur: ${data.reason}`,
            reference: `RETURN_CREDIT_REVERSAL:${credit.id}`,
            referenceType: 'MANUAL_ENTRY',
            referenceId: credit.id,
            status: 'POSTED',
            isAutoGenerated: true,
            createdById: userId,
            approvedById: userId,
            approvedAt: new Date(),
            lines: {
                create: journal.lines.map((line) => ({
                    accountId: line.accountId,
                    debit: line.credit,
                    credit: line.debit,
                    currency: line.currency,
                    exchangeRate: line.exchangeRate,
                })),
            },
        },
    });
    await tx.$executeRaw`SET CONSTRAINTS invoice_return_credit_ledger, return_credit_ledger, return_allocation_ledger DEFERRED`;
    const result = await tx.salesReturnCredit.update({
        where: { id: credit.id },
        data: {
            status: 'REVERSED',
            reversedAt: data.reversalDate,
            reversedById: userId,
            reversalReason: data.reason,
            reversalJournalId: reversal.id,
        },
    });
    for (const invoice of invoices) {
        const amount = credit.allocations
            .filter((line) => line.invoiceId === invoice.id)
            .reduce(
                (sum, line) => sum.plus(line.totalAmount),
                new Prisma.Decimal(0),
            );
        const creditedAmount = invoice.creditedAmount.minus(amount);
        if (creditedAmount.lt(0))
            throw new BusinessRuleError(
                'Saldo kredit tidak sesuai ledger. Rekonsiliasi terlebih dahulu.',
            );
        await tx.invoice.update({
            where: { id: invoice.id },
            data: {
                creditedAmount,
                status: getSalesInvoiceSettlementStatus({
                    ...invoice,
                    creditedAmount,
                }),
            },
        });
    }
    await logActivity({
        userId,
        action: 'REVERSE_SALES_RETURN_CREDIT',
        entityType: 'SalesReturn',
        entityId: data.returnId,
        details: data.reason,
        changes: {
            creditId: credit.id,
            originalJournalId: journal.id,
            reversalJournalId: reversal.id,
        },
        tx,
    });
    await tx.$executeRaw`SET CONSTRAINTS invoice_return_credit_ledger, return_credit_ledger, return_allocation_ledger IMMEDIATE`;
    return result;
}
