/**
 * scripts/apply-all-fixes.ts
 * ============================================================
 * Master script — jalankan SATU INI setelah sync dari production.
 * Script ini IDEMPOTENT: aman dijalankan berkali-kali.
 *
 * Urutan:
 *   1. Fix product inventoryAccountId
 *   2. Reklasifikasi saldo akun 12xxx → 113xx
 *   3. Update nama akun 11330 & 11340
 *   4. Sync standardCost dari buyPrice
 *   5. Sync inventory.averageCost dari standardCost
 *   6. Reklasifikasi jurnal PACKAGING dari 11310 → 11340
 *   7. Final GL check
 * ============================================================
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function nextJENumber() {
    // Find the highest JE number across any format (JE-000001 or JE - 2026 -00001)
    const allJEs = await prisma.journalEntry.findMany({
        select: { entryNumber: true },
        orderBy: { id: 'desc' },
        take: 1
    });
    // Just use a timestamp-based unique number to avoid collisions
    const ts = Date.now();
    return `JE-FIX-${ts}`;
}

// ─── Step 1 ─────────────────────────────────────────────────────────────────
async function step1() {
    console.log('\n=== Step 1: Fix Product inventoryAccountId ===');
    const get = async (code: string) => (await prisma.account.findUnique({ where: { code } }))?.id;

    const id11310 = await get('11310');
    const id11340 = await get('11340');
    const id11320 = await get('11320');
    const id11350 = await get('11350');
    const id12400acc = (await prisma.account.findUnique({ where: { code: '12400' } }))?.id;

    if (id11340) {
        const pkg = await prisma.product.updateMany({
            where: { productType: 'PACKAGING', inventoryAccountId: id11310 },
            data: { inventoryAccountId: id11340 }
        });
        if (pkg.count) console.log(`  ✅ ${pkg.count} PACKAGING products → 11340`);
    }
    if (id12400acc && id11320) {
        const wip = await prisma.product.updateMany({
            where: { inventoryAccountId: id12400acc },
            data: { inventoryAccountId: id11320 }
        });
        if (wip.count) console.log(`  ✅ ${wip.count} WIP products → 11320`);
    }
    if (id11350) {
        const scrap = await prisma.product.updateMany({
            where: { productType: 'SCRAP', inventoryAccountId: null },
            data: { inventoryAccountId: id11350 }
        });
        if (scrap.count) console.log(`  ✅ ${scrap.count} SCRAP products → 11350`);
    }
    console.log('  ✅ Step 1 selesai');
}

// ─── Step 2 ─────────────────────────────────────────────────────────────────
async function step2() {
    console.log('\n=== Step 2: Reklasifikasi 12xxx → 113xx ===');
    const reclassMap = [
        { from: '12500', to: '11330', ref: 'RECLASS-12500-TO-11330' },
        { from: '12310', to: '11310', ref: 'RECLASS-12310-TO-11310' },
        { from: '12400', to: '11320', ref: 'RECLASS-12400-TO-11320' },
    ];

    for (const { from, to, ref } of reclassMap) {
        const alreadyDone = await prisma.journalEntry.findFirst({ where: { reference: ref, status: 'POSTED' } });
        if (alreadyDone) { console.log(`  ℹ️  ${from}→${to}: sudah dikerjakan (${alreadyDone.entryNumber})`); continue; }

        const accFrom = await prisma.account.findUnique({
            where: { code: from },
            include: { journalLines: { where: { journalEntry: { status: 'POSTED' } } } }
        });
        if (!accFrom) continue;
        const balance = accFrom.journalLines.reduce((s, l) => s + Number(l.debit) - Number(l.credit), 0);
        if (balance <= 0) { console.log(`  ⏭  ${from}: saldo 0, skip`); continue; }

        const toAcc = await prisma.account.findUniqueOrThrow({ where: { code: to } });
        const entryNum = await nextJENumber();
        await prisma.journalEntry.create({
            data: {
                entryNumber: entryNum, entryDate: new Date('2026-02-19'),
                description: `Reklasifikasi ${from} → ${to}`,
                reference: ref, referenceType: 'MANUAL_ENTRY',
                isAutoGenerated: false, status: 'POSTED',
                lines: {
                    create: [
                        { accountId: toAcc.id, debit: balance, credit: 0, description: `Reclass masuk dari ${from}` },
                        { accountId: accFrom.id, debit: 0, credit: balance, description: `Reclass keluar ke ${to}` }
                    ]
                }
            }
        });
        console.log(`  ✅ ${entryNum}: Rp ${balance.toLocaleString()} ${from} → ${to}`);
    }

    // Nonaktifkan akun 12xxx
    const deactivate = ['12130', '12210', '12220', '12310', '12400', '12500', '12600', '12610', '12620'];
    let n = 0;
    for (const code of deactivate) {
        const a = await prisma.account.findUnique({ where: { code } });
        if (a?.isActive) { await prisma.account.update({ where: { code }, data: { isActive: false } }); n++; }
    }
    if (n) console.log(`  ✅ Deactivated ${n} akun 12xxx`);
    console.log('  ✅ Step 2 selesai');
}

// ─── Step 3: Update nama akun ────────────────────────────────────────────────
async function step3() {
    console.log('\n=== Step 3: Update nama akun ===');
    await prisma.account.update({ where: { code: '11330' }, data: { name: 'Barang Jadi - Roll/Gulungan' } });
    await prisma.account.update({ where: { code: '11340' }, data: { name: 'Barang Jadi - Pack/Kresek' } });
    console.log('  ✅ 11330 → Barang Jadi - Roll/Gulungan');
    console.log('  ✅ 11340 → Barang Jadi - Pack/Kresek');
}

// ─── Step 4: Sync standardCost ───────────────────────────────────────────────
async function step4() {
    console.log('\n=== Step 4: Sync standardCost dari buyPrice ===');
    const variants = await prisma.productVariant.findMany({
        where: {
            product: { productType: { in: ['RAW_MATERIAL', 'INTERMEDIATE', 'FINISHED_GOOD', 'PACKAGING'] } },
            OR: [{ standardCost: null }, { standardCost: { equals: 0 } }]
        },
        select: { id: true, buyPrice: true }
    });
    let count = 0;
    for (const v of variants) {
        const bp = Number(v.buyPrice ?? 0);
        if (bp > 0) { await prisma.productVariant.update({ where: { id: v.id }, data: { standardCost: bp } }); count++; }
    }
    console.log(`  ✅ Updated standardCost: ${count} variants`);
}

// ─── Step 5: Sync averageCost ────────────────────────────────────────────────
async function step5() {
    console.log('\n=== Step 5: Sync inventory.averageCost ===');
    const items = await prisma.inventory.findMany({
        where: { OR: [{ averageCost: null }, { averageCost: { equals: 0 } }], quantity: { gt: 0 } },
        select: { id: true, productVariant: { select: { standardCost: true, buyPrice: true } } }
    });
    let count = 0;
    for (const inv of items) {
        const cost = Number(inv.productVariant.standardCost ?? 0) || Number(inv.productVariant.buyPrice ?? 0);
        if (cost > 0) { await prisma.inventory.update({ where: { id: inv.id }, data: { averageCost: cost } }); count++; }
    }
    console.log(`  ✅ Synced averageCost: ${count} inventory records`);
}

// ─── Step 6: Reklasifikasi PACKAGING 11310 → 11340 ──────────────────────────
async function step6() {
    console.log('\n=== Step 6: Reklasifikasi PACKAGING 11310 → 11340 ===');
    const REF = 'RECLASSIFY-PKG-11340';
    const exists = await prisma.journalEntry.findFirst({ where: { reference: REF, status: 'POSTED' } });
    if (exists) { console.log(`  ℹ️  Sudah dilakukan (${exists.entryNumber}), skip`); return; }

    const acc11310 = await prisma.account.findUniqueOrThrow({ where: { code: '11310' } });
    const acc11340 = await prisma.account.findUniqueOrThrow({ where: { code: '11340' } });

    const pkgIds = (await prisma.productVariant.findMany({
        where: { product: { productType: 'PACKAGING' } }, select: { id: true }
    })).map(v => v.id);

    const movIds = (await prisma.stockMovement.findMany({
        where: { productVariantId: { in: pkgIds } }, select: { id: true }
    })).map(m => m.id);

    const lines = await prisma.journalLine.findMany({
        where: {
            accountId: acc11310.id, debit: { gt: 0 },
            journalEntry: { status: 'POSTED', referenceId: { in: movIds } }
        },
        select: { debit: true }
    });
    const total = lines.reduce((s, l) => s + Number(l.debit), 0);

    if (total > 0) {
        const entryNum = await nextJENumber();
        await prisma.journalEntry.create({
            data: {
                entryNumber: entryNum, entryDate: new Date('2026-02-19'),
                description: 'Reklasifikasi: PACKAGING dari 11310 ke 11340',
                reference: REF, referenceType: 'MANUAL_ENTRY',
                isAutoGenerated: false, status: 'POSTED',
                lines: {
                    create: [
                        { accountId: acc11340.id, debit: total, credit: 0, description: 'Reklasifikasi masuk: Barang Jadi Pack/Kresek' },
                        { accountId: acc11310.id, debit: 0, credit: total, description: 'Reklasifikasi keluar dari Raw Materials' }
                    ]
                }
            }
        });
        console.log(`  ✅ ${entryNum}: Rp ${total.toLocaleString()} dari 11310 → 11340`);
    } else {
        console.log('  ℹ️  Tidak ada PACKAGING journal di 11310');
    }
}

// ─── Step 7: Final GL check ──────────────────────────────────────────────────
async function step7() {
    console.log('\n=== Final GL Balance ===');
    let total = 0;
    for (const code of ['11310', '11320', '11330', '11340', '11350']) {
        const acc = await prisma.account.findUnique({
            where: { code },
            include: { journalLines: { where: { journalEntry: { status: 'POSTED' } } } }
        });
        if (acc) {
            const bal = acc.journalLines.reduce((s, l) => s + Number(l.debit) - Number(l.credit), 0);
            total += bal;
            console.log(`  ${code} (${acc.name}): Rp ${Math.round(bal).toLocaleString()}`);
        }
    }
    console.log(`\n  TOTAL INVENTORY GL: Rp ${Math.round(total).toLocaleString()}`);
}

// ─── Main ────────────────────────────────────────────────────────────────────
async function main() {
    console.log('╔══════════════════════════════════════════════════╗');
    console.log('║   Polyflow — Apply All Inventory Fixes           ║');
    console.log('╚══════════════════════════════════════════════════╝');
    await step1();
    await step2();
    await step3();
    await step4();
    await step5();
    await step6();
    await step7();
    console.log('\n✅ SELESAI — semua koreksi berhasil diterapkan\n');
}

main().catch(console.error).finally(() => prisma.$disconnect());
