
import { recordCustomerPayment } from '../src/actions/finance';
import { prisma } from '../src/lib/prisma';

async function run() {
    const invoiceId = 'b5d8fb4f-3a2f-4dda-aa0b-65e88f5c5aeb'; // TAG-023
    console.log(`💰 Creating test payment for Invoice ID: ${invoiceId} (Direct Prisma)...`);

    try {
        const invoice = await prisma.invoice.findUnique({ where: { id: invoiceId } });
        if (!invoice) throw new Error("Invoice not found");

        const paymentNumber = 'TEST-PAY-001';
        const amount = 1000000;

        await prisma.$transaction(async (tx) => {
            // 1. Create Payment
            const payment = await tx.payment.create({
                data: {
                    paymentNumber,
                    paymentDate: new Date(),
                    amount,
                    method: 'Bank Transfer',
                    invoiceId
                }
            });

            // 2. Update Invoice
            await tx.invoice.update({
                where: { id: invoiceId },
                data: {
                    paidAmount: Number(invoice.paidAmount) + amount,
                    status: 'PARTIAL'
                }
            });

            // 3. Create Journal Entries
            const journal = await tx.journalEntry.create({
                data: {
                    entryNumber: 'TEST-JE-001',
                    entryDate: new Date(),
                    description: `Payment for ${invoice.invoiceNumber}`,
                    reference: paymentNumber,
                    referenceId: payment.id,
                    referenceType: 'SALES_PAYMENT',
                    status: 'POSTED',
                    isAutoGenerated: true,
                    lines: {
                        create: [
                            { accountId: (await tx.account.findFirst({ where: { code: '11120' } }))!.id, debit: amount, credit: 0, description: 'Bank' },
                            { accountId: (await tx.account.findFirst({ where: { code: '11210' } }))!.id, debit: 0, credit: amount, description: 'AR' }
                        ]
                    }
                }
            });
            console.log(`✅ Created Payment ID: ${payment.id} with Journal ID: ${journal.id}`);
        });

    } catch (error) {
        console.error('Error:', error);
    } finally {
        await prisma.$disconnect();
    }
}

run();
