
import { PrismaClient, ReferenceType, JournalStatus } from '@prisma/client';
import { createJournalEntry } from '../src/services/accounting/journals-service';

const prisma = new PrismaClient();

async function testManualJournal() {
    console.log("🔍 Verifying manual journal entry for account 11512...");

    const account = await prisma.account.findUnique({ where: { code: '11512' } });
    if (!account) {
        throw new Error("Account 11512 (Piutang Fadilla) not found after migration");
    }

    const cashAccount = await prisma.account.findUnique({ where: { code: '11110' } });
    if (!cashAccount) {
        throw new Error("Cash account 11110 not found");
    }

    const userId = await prisma.user.findFirst().then(u => u?.id);
    if (!userId) {
        throw new Error("No user found in database to use as creator");
    }

    try {
        console.log("Attempting to create manual journal entry...");
        const entry = await createJournalEntry({
            entryDate: new Date(),
            description: "Test Manual Journal for Piutang Fadilla",
            reference: "TEST-FADILLA-001",
            referenceType: 'MANUAL_ENTRY' as ReferenceType,
            status: 'DRAFT' as JournalStatus,
            isAutoGenerated: false,
            createdById: userId,
            lines: [
                { accountId: account.id, debit: 100000, credit: 0, description: "Pinjaman Karyawan" },
                { accountId: cashAccount.id, debit: 0, credit: 100000, description: "Kas Keluar" }
            ]
        });

        console.log("✅ SUCCESS: Manual journal entry created for account 11512!");
        console.log("Entry ID:", entry.id);

        // Cleanup
        console.log("Cleaning up test entry...");
        await prisma.journalLine.deleteMany({ where: { journalEntryId: entry.id } });
        await prisma.journalEntry.delete({ where: { id: entry.id } });
        console.log("Done.");

    } catch (error) {
        console.error("❌ FAILED: Still unable to create manual journal entry.");
        console.error(error);
        process.exit(1);
    }
}

testManualJournal()
    .finally(async () => {
        await prisma.$disconnect();
    });
