// @vitest-environment jsdom
import {fireEvent,render,screen} from '@testing-library/react';import {beforeEach,describe,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({list:vi.fn(),toast:vi.fn()}));vi.mock('@/actions/purchasing/purchase-remittance',()=>({listPurchaseRemittancesAction:m.list}));vi.mock('@/components/purchasing/CreatePurchaseRemittanceDialog',()=>({CreatePurchaseRemittanceDialog:()=>null}));vi.mock('sonner',()=>({toast:{error:m.toast}}));
import {PurchaseRemittanceEntryPoint} from '../PurchaseRemittanceEntryPoint';
const invoice={id:'inv',invoiceNumber:'INV-1',totalAmount:100,paidAmount:0,purchaseOrder:{orderNumber:'PO-1',supplier:{name:'Supplier'}}};const bank={key:'BCA',name:'BCA',holder:'Synthetic',account:'000'};
describe('PurchaseRemittanceEntryPoint honest states',()=>{beforeEach(()=>vi.clearAllMocks());
 it('disables CTA and explains auxiliary service errors',()=>{render(<PurchaseRemittanceEntryPoint invoices={[invoice]} paymentBanks={[bank]} canCreate auxiliaryState={{outstanding:'error',remittances:'error',paymentBanks:'error'}}/>);expect(screen.getByRole('alert').textContent).toContain('dinonaktifkan');expect(screen.queryByRole('button',{name:'Ajukan Pembayaran Supplier'})).toBeNull();});
 it('distinguishes missing banks, no eligible invoices, and no history',()=>{render(<PurchaseRemittanceEntryPoint invoices={[]} canCreate auxiliaryState={{outstanding:'empty',remittances:'empty',paymentBanks:'missing'}}/>);expect(screen.getByText(/Rekening pembayaran belum dikonfigurasi/)).toBeTruthy();expect(screen.getByText(/Tidak ada invoice yang memenuhi syarat/)).toBeTruthy();expect(screen.getByText(/Belum ada pengajuan/)).toBeTruthy();});
 it('shows CTA only when capability, eligibility, and prerequisites are ready',()=>{const {rerender}=render(<PurchaseRemittanceEntryPoint invoices={[invoice]} paymentBanks={[bank]} canCreate={false} auxiliaryState={{outstanding:'ready',remittances:'empty',paymentBanks:'ready'}}/>);expect(screen.queryByRole('button',{name:'Ajukan Pembayaran Supplier'})).toBeNull();rerender(<PurchaseRemittanceEntryPoint invoices={[invoice]} paymentBanks={[bank]} canCreate auxiliaryState={{outstanding:'ready',remittances:'empty',paymentBanks:'ready'}}/>);expect(screen.getByRole('button',{name:'Ajukan Pembayaran Supplier'})).toBeTruthy();});
 it('reports a failed retry instead of treating it as no history',async()=>{m.list.mockResolvedValue({success:false,error:'retry gagal'});render(<PurchaseRemittanceEntryPoint invoices={[invoice]} paymentBanks={[bank]} canCreate auxiliaryState={{outstanding:'ready',remittances:'error',paymentBanks:'ready'}}/>);fireEvent.click(screen.getByRole('button',{name:/Coba muat/}));await vi.waitFor(()=>expect(m.toast).toHaveBeenCalledWith('retry gagal'));});
});
