'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger
} from "@/components/ui/alert-dialog";
import { postJournal, voidJournal, reverseJournal } from '@/actions/finance/journal';
import { toast } from 'sonner';
import { Loader2, CheckCircle, Ban, RotateCcw, Pencil } from 'lucide-react';
import Link from 'next/link';

interface JournalActionsProps {
    id: string;
    status: 'DRAFT' | 'POSTED' | 'VOIDED';
    isAutoGenerated?: boolean;
}

export function JournalActions({ id, status, isAutoGenerated }: JournalActionsProps) {
    const [loading, setLoading] = useState(false);

    const handleAction = async (action: 'post' | 'void' | 'reverse') => {
        setLoading(true);
        try {
            let result;
            if (action === 'post') result = await postJournal(id);
            if (action === 'void') result = await voidJournal(id);
            if (action === 'reverse') result = await reverseJournal(id);

            if (result?.success) {
                toast.success(`Journal berhasil di-${action}.`);
            } else {
                toast.error(result?.error || 'Aksi gagal');
            }
        } catch (_error) {
            toast.error("Gagal memproses jurnal. Silakan coba lagi.")
        } finally {
            setLoading(false);
        }
    };

    if (status === 'VOIDED') {
        return <Button variant="outline" disabled>Voided</Button>;
    }

    return (
        <div className="flex gap-2">
            {status === 'DRAFT' && (
                <>
                    {!isAutoGenerated && (
                        <Link href={`/finance/journals/${id}/edit`}>
                            <Button variant="outline" disabled={loading}>
                                <Pencil className="mr-2 h-4 w-4" /> Edit
                            </Button>
                        </Link>
                    )}
                    <AlertDialog>
                        <AlertDialogTrigger asChild>
                            <Button disabled={loading}>
                                {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <CheckCircle className="mr-2 h-4 w-4" />}
                                Post Journal
                            </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                            <AlertDialogHeader>
                                <AlertDialogTitle>Posting Entri Jurnal?</AlertDialogTitle>
                                <AlertDialogDescription>
                                    Ini akan memfinalisasi entri jurnal dan memperbarui saldo akun. Setelah itu tidak bisa diedit, hanya bisa di-void atau dibalik.
                                </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                                <AlertDialogCancel>Batal</AlertDialogCancel>
                                <AlertDialogAction onClick={() => handleAction('post')}>Konfirmasi Posting</AlertDialogAction>
                            </AlertDialogFooter>
                        </AlertDialogContent>
                    </AlertDialog>
                </>
            )}

            {status === 'POSTED' && (
                <>
                    <AlertDialog>
                        <AlertDialogTrigger asChild>
                            <span title={isAutoGenerated ? "Cannot directly reverse an auto-generated journal. Please reverse the source document in Inventory/Production instead." : ""}>
                                <Button variant="outline" disabled={loading || isAutoGenerated}>
                                    <RotateCcw className="mr-2 h-4 w-4" /> Reverse
                                </Button>
                            </span>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                            <AlertDialogHeader>
                                <AlertDialogTitle>Balik Entri Jurnal?</AlertDialogTitle>
                                <AlertDialogDescription>
                                    Ini akan membuat entri jurnal baru dengan baris debit/kredit yang dibalik untuk meng-offset entri ini.
                                </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                                <AlertDialogCancel>Batal</AlertDialogCancel>
                                <AlertDialogAction onClick={() => handleAction('reverse')}>Konfirmasi Pembalikan</AlertDialogAction>
                            </AlertDialogFooter>
                        </AlertDialogContent>
                    </AlertDialog>

                    <AlertDialog>
                        <AlertDialogTrigger asChild>
                            <span title={isAutoGenerated ? "Cannot directly void an auto-generated journal. Please void the source document in Inventory/Production instead." : ""}>
                                <Button variant="destructive" disabled={loading || isAutoGenerated}>
                                    <Ban className="mr-2 h-4 w-4" /> Void
                                </Button>
                            </span>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                            <AlertDialogHeader>
                                <AlertDialogTitle>Void Entri Jurnal?</AlertDialogTitle>
                                <AlertDialogDescription>
                                    Yakin ingin VOID jurnal ini? Tindakan ini akan membatalkan transaksi secara penuh.
                                </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                                <AlertDialogCancel>Batal</AlertDialogCancel>
                                <AlertDialogAction onClick={() => handleAction('void')} className="bg-destructive hover:bg-destructive/90">
                                    Konfirmasi Void
                                </AlertDialogAction>
                            </AlertDialogFooter>
                        </AlertDialogContent>
                    </AlertDialog>
                </>
            )}
        </div>
    );
}
