'use server';

import { withTenant } from "@/lib/core/tenant";
import { prisma } from "@/lib/core/prisma";
import { transactionWizardSchema, TransactionWizardValues } from "@/lib/schemas/transaction-wizard";
import { TRANSACTION_TYPES } from "@/lib/config/transaction-types";
import { AccountingService } from "@/services/accounting/accounting-service";
import { FixedAssetService } from "@/services/finance/fixed-asset-service";
import { ReferenceType, JournalStatus } from "@prisma/client";
import { requireAuth } from "@/lib/tools/auth-checks";
import { revalidatePath } from "next/cache";
import { recordCustomerPayment, recordSupplierPayment } from "../finance/finance";
import { logger } from "@/lib/config/logger";
import { safeAction, BusinessRuleError } from "@/lib/errors/errors";

export const createWizardTransaction = withTenant(
async function createWizardTransaction(data: TransactionWizardValues) {
    return safeAction(async () => {
        const session = await requireAuth();

        const validation = transactionWizardSchema.safeParse(data);
        if (!validation.success) {
            throw new BusinessRuleError(validation.error.issues[0].message);
        }

        const config = TRANSACTION_TYPES.find(t => t.id === data.transactionTypeId);
        if (!config) {
            throw new BusinessRuleError("Invalid transaction type");
        }

        try {
            if (config.requiresInvoice && data.invoiceId) {
                const targetAccountId = config.requiresInvoice === 'SALES' ? data.customDebitAccountId : data.customCreditAccountId;

                let bankAcc;
                if (targetAccountId) {
                    bankAcc = await prisma.account.findUnique({ where: { id: targetAccountId } });
                } else {
                    bankAcc = await prisma.account.findUnique({ where: { code: config.requiresInvoice === 'SALES' ? config.debitAccountCode : config.creditAccountCode } });
                }

                const method = bankAcc?.code === '11110' ? 'Cash' : 'Bank Transfer';

                if (config.requiresInvoice === 'SALES') {
                    const result = await recordCustomerPayment({
                        invoiceId: data.invoiceId,
                        amount: data.amount,
                        paymentDate: data.entryDate,
                        method,
                        notes: data.description
                    });
                    if (!result.success) throw new BusinessRuleError(result.error);
                    return { id: 'payment' };
                } else {
                    const result = await recordSupplierPayment({
                        invoiceId: data.invoiceId,
                        amount: data.amount,
                        paymentDate: data.entryDate,
                        method,
                        notes: data.description
                    });
                    if (!result.success) throw new BusinessRuleError(result.error);
                    return { id: 'payment' };
                }
            }

            const debitAccountId = data.customDebitAccountId || (await getAccountIdByCode(config.debitAccountCode));
            const creditAccountId = data.customCreditAccountId || (await getAccountIdByCode(config.creditAccountCode));

            let referenceType = ReferenceType.MANUAL_ENTRY as ReferenceType;
            if (config.category === 'ASSET') referenceType = ReferenceType.GOODS_RECEIPT as ReferenceType;
            if (config.category === 'SALES') referenceType = ReferenceType.SALES_INVOICE as ReferenceType;

            const result = await AccountingService.createJournalEntry({
                entryDate: data.entryDate,
                description: data.description,
                reference: data.reference ?? "",
                referenceType,
                createdById: session.user.id,
                isAutoGenerated: false,
                status: JournalStatus.POSTED,
                lines: [
                    {
                        accountId: debitAccountId,
                        debit: data.amount,
                        credit: 0,
                        description: data.description
                    },
                    {
                        accountId: creditAccountId,
                        debit: 0,
                        credit: data.amount,
                        description: data.description
                    }
                ]
            });

            if (config.category === 'ASSET' && data.assetCode) {
                await FixedAssetService.createAsset({
                    assetCode: data.assetCode,
                    name: data.description,
                    category: config.label,
                    purchaseDate: data.entryDate,
                    purchaseValue: data.amount,
                    usefulLifeMonths: data.usefulLifeMonths || 48,
                    assetAccountId: debitAccountId,
                    depreciationAccountId: data.depreciationAccountId || "",
                    accumulatedDepreciationAccountId: data.accumulatedDepreciationAccountId || ""
                });
                revalidatePath('/finance/assets');
            }

            revalidatePath('/finance/journals');
            revalidatePath('/finance/reports/balance-sheet');
            revalidatePath('/finance/reports/trial-balance');
            revalidatePath('/finance');

            return { id: result.id };
        } catch (error) {
            if (error instanceof BusinessRuleError) throw error;
            logger.error("Wizard Transaction Error", { error, data, module: 'TransactionWizard' });
            throw new BusinessRuleError("Failed to record transaction");
        }
    });
}
);

const accountCache = new Map<string, string>();

async function getAccountIdByCode(code: string): Promise<string> {
    if (accountCache.has(code)) return accountCache.get(code)!;

    const acc = await prisma.account.findUnique({ where: { code } });
    if (!acc) throw new Error(`GL Account code ${code} not found. Please contact Administrator to fix COA.`);

    accountCache.set(code, acc.id);
    return acc.id;
}
